### ISSUE TITLE
PMD_MagIC.py Only measurments and samples tables 

### ISSUE THREAD

**Issue by greadown** [PmagPy/PmagPy#106]
Only got measurement data and two tables demag GUI delayed launch

**Comment by Caoimhinmg** [comment]
Hey @greadown. So I added the export of a Sites level table and a Specimens level table using what information I could and added a box to Pmag GUI which has fields for Site lat and lon so you don't have to input it manually if you want VGPs or something. I do not have any PMD files to test this with though so if you run into any further issues feel free to report them as they happen and I'll do my best to fix them asap. Note if you're not running off of the Github repo directly you won't see these changes until the next release. Cheers.
