### ISSUE TITLE
import orientation file no longer an option in pmag_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#107]
we need to be able to import orientation.txt files with orientation_magic.py 
also this should be upgraded to 3.0

**Comment by moonshoes87** [comment]
This option is now available as step 2 in Pmag GUI.  I believe it is upgraded to work in 3.0, but that should be tested.  @ltauxe, let me know if this seems to work!

**Comment by moonshoes87** [comment]
I am working on some more updates to how orientation magic works in Pmag GUI, but in the meantime I am closing this issue.
