### ISSUE TITLE
Some column names need to be removed from 3.0 upload files

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#119]
Some columns are added into tables where they don't belong.  For example, the specimens table might have 'site' and 'location'.  Those should be removed prior to upload.  This will be a function for new_builder (a method of Contribution).

**Comment by moonshoes87** [comment]
I've now implemented functionality that does this: 641847bcd

The way this currently works is that all headers that aren't in the 3.0 data model are removed from all MagIC tables prior to upload.  The problem with this approach is that if someone has a slightly incorrect MagIC column, this will be deleted as well. With Rupert's new interface, it's pretty easy to fix a misspelled column name, but a user won't have the option to do that if I chuck that column before the upload.  

Some options:

- We could warn users about the columns that are being auto-deleted.
- We could blacklist instead of whitelisting (drop certain known nuisance columns, but leave ambiguous/potentially misspelled columns in the upload)

Misspelled columns aren't too likely to be a problem for people who are using PmagPy the whole way through their process, since we are pretty consistent.  But if they're mixing and matching with their process, maybe doing some editing by hand, the problem could come up.

@ltauxe, any thoughts about this?

**Comment by moonshoes87** [comment]
From meeting:  Add a warning, and an are you sure?

**Comment by njarboe** [comment]
My two cents worth is that when creating a MagIC file for upload the
columns that are used internally in the PmagPy programs, but not found in
the data model, should be dropped without a warning. Columns added by the
user, but not in the data model, should be kept with a warning. The user,
as you said, can link an unknown column to the correct one in the data
model when uploading. I'm generally against correcting spelling
automatically and instead like just pointing out the possible problem.

**Comment by moonshoes87** [comment]
@njarboe, thanks for your input.  I've implemented a solution that does more or less what you suggest, although the problem with blacklisting PmagPy columns is that I suspect I don't have a complete list of what should be dropped.  I will keep trying to add those (in ipmag.upload_magic3, to RmKeys and extra_RmKeys) as I find them.  Everyone else should feel free to do the same, or let me know what they find.
