### ISSUE TITLE
move gauss coefficients from pmag.py

### ISSUE THREAD

**Issue by lfairchild** [PmagPy/PmagPy#121]
There needs to be separate storage for the gauss coefficients of the IGRF model (they can just be moved to a separate file). I think that storing these coefficients in pmag.py makes the pmag file really difficult to open and slow to work with in a text editor.

**Comment by ltauxe** [comment]
I put the coefficients in coefficients.py which is only imported when pmag.doigrf() is called.

**Comment by Swanson-Hysell** [comment]
Hooray! There is now syntax highlights of pmag.py in my favorite text editor.
