### ISSUE TITLE
pmag.dokent args were changed and some programs will break

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#131]
The pmag.dokent function was changed to take only a single parameter which will break eqarea_magic, eqarea_magic3.0, eqarea_ell, and plotdi_e (which all use do_kent with providing 2 parameters).

**Comment by moonshoes87** [comment]
I would suggest in a situation like this using grep to find all places were the changed function was called.  This will be easy to fix but did temporarily break stuff.

**Comment by Swanson-Hysell** [comment]
My bad on the change and not propagating it through to everywhere it is called. Nice suggesting on grep. I have now gone through and replaced everywhere it is called within the programs.

**Comment by ltauxe** [comment]
Oops - I just remembered what the NN was for - it is used for normalizing the MEANS instead of regular data - Gored gored recipes have to roll that one back to the way it was - Nick can you do that?
Lisa

**Comment by Swanson-Hysell** [comment]
Ok. That makes sense. I will revert those changes.

**Comment by Swanson-Hysell** [comment]
Code has been reverted to previous syntax.
