### ISSUE TITLE
pmag_gui under data model 3.0

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#134]
The "Add MagIC metadata" is not creating a specimen file with all the specimens measured.  So when I try to create an upload file, some specimens (without interpretations) are missing.  All specimens measured should be in the specimens table.

**Comment by moonshoes87** [comment]
@ltauxe, I think I need more detail to recreate this problem.  As far as I can tell, when I import a measurement file and then translate to 2.5, all specimens that were in the measurement file are put into the specimen table.  Can you give me more specifics about how you ran into this problem?
