### ISSUE TITLE
Rewrite Conversion Scripts in 3.0 Data Model

### ISSUE THREAD

**Issue by Caoimhinmg** [PmagPy/PmagPy#135]
To improve the work flow of Pmag GUI and overall make contributing measurement level data to the MagIC database, I am planning on rewriting as many of the magnetometer conversion scripts and insuring their integration with Pmag GUI is fully functioning. Though help would not be amiss if anyone wants to assist with their own data formats.

**Comment by moonshoes87** [comment]
In our MagIC meeting today @ltauxe pointed out that one way of doing this is to simply move the conversion step from Pmag GUI into the import scripts themselves.  This would mean that the import scripts still read in to 2.5, but makes the conversion to 3.0 entirely behind the scenes and writes out to 3.0 without the user ever knowing that 2.5 was involved.  This would be a faster way to implement this change.  Are there significant advantages to rewriting the import scripts from the bottom up?  

If we decide to just move the conversion from being a step in Pmag GUI to incorporated into 2.5 import scripts, I should help with that.  Thoughts?

**Comment by Swanson-Hysell** [comment]
I think that it makes sense to take a two-prong strategy here. First, to get the conversion step into the import scripts as a stop gap so there isn't that added layer. Second, to get at least some scripts writing directly to data model 3.0. One advantage to rewriting import scripts is that some of them are not writing all of the necessary tables. And as you said in the MagIC meeting, minimizing how many times we are converting back and forth makes sense from the stand-point of limiting the number of places the conversion could cause problems.

**Comment by Swanson-Hysell** [comment]
A related question, is it going to cause a problem in the GUIs that the new data model doesn't have the sample and site column in measurements.txt?

**Comment by Caoimhinmg** [comment]
I agree that the conversion behind the scenes is the easier method (heck that's how CIT_magic3 works), and in the short term that is probably the best solution. However, the differences between the data models makes this strange as evidenced by the missing locations.txt issue we had at the Workshop, which I think will simply escalate as many of the scripts in their current form only output a er_samples and magic_measurements. This lack of a one to one relationship between tables in the two data models makes direct translation as it exists currently in PmagPy incomplete. Also simply code accessibility eventually when nearly everything is running 3.0 going back through and figuring out how everything works becomes more and more complicated as we retain old bloat from previous data formats, this might be unavoidable for the large hard to convert things but not for short scripts particularly those so instrumental to being able to contribute to the database. Thus I see that the easiest way to get rid of all these problems, reduce bugs, and make contributing easier is through the rewriting of the scripts.

**Comment by Caoimhinmg** [comment]
@Swanson-Hysell because the GUIs are converting from 3.0 to 2.5 I have Demag GUI at least search for the site, sample and etc. in the other tables and propagate through to measurements. Which I think I remembered to remove before writing back to measurements.txt.........well correct me if I forgot. I'm going to focus on fixing cit_magic3 first.

**Comment by Swanson-Hysell** [comment]
@njarboe, Are there example data files from the Santa Cruz lab in PmagPy>data_files>Measurement_Import? Can you point those out to @Caoimhinmg and @moonshoes87?

It makes sense to prioritize the conversion for that lab as Nick will be going there at the end of next week to work with Rob Coe and data conversion. @njarboe, am I right in thinking you will want to use the GUI to convert the measurements files?

**Comment by ltauxe** [comment]
Well, here are the two ways: 
1) make all the import scripts put out 3.0 instead of 2.5
2) make them put out 2.5 which then gets converted to 3.0 in the combining all the *.magic => magic_measurements step.

the latter is simpler and already happens in the 1b step anyway.  The problem is that some of the import scripts produce stuff in other tables besides the .magic one (sample locations, orientations, volumes, weights, etc.) so those all have to be brought along.   

Also there is the issue that there are many studies already underway that were started under 2.5 with new data being added.  forcing a conversion to 3.0 might be a show stopper for some.  

I guess I’m leaning toward option 2 above…..   
lisa

**Comment by njarboe** [comment]
@Swanson-Hysell The workflow for recent Santa Cruz paleomag is to create a large file with the magnetometer control software with data for each stratigraphic section (the "location" in MagIC parlance) in one large .scz file. We should be able to extract all the information to fill out the location, site, sample, specimen, and measurement data from this xml file. The interpretations for each sample is saved in a .pmm file, one for each lava flow (site). Then another .pmm file is used to determine location level interpretations. We also have .pmd files for analyzing measurement data in the Enkin program, but we don't need those if the .scz is not corrupted or lost. For uploading past studies, I think that running a script on the command line to put together the information in the .scz file withe a multiple of .pmm files would be great. Going into the future I imagine importing the .scz file into pmag_gui for people to do their interpretations. Pmag_gui is better than the old enkin program we used, is an active project, and is being improved. 

@Caoimhinmg @moonshoes87 I have some time to work on writing the Santa Cruz converter before I go down there on the 8th. Having the ability to make quick changes to the code as issues arise on-site is crucial to success. I want to have it in the native 3.0 data model, but many functions would have to be re-written such as pmag.magic_write. Should functions be added with similar names like magic_write3 or are there problems with the old workflow that could be addressed at this time?

I'll add a directory for .scz data files and put some associated .pmm in there as well. Pete Lippert's lab may also be able to use this converter program to get in measurement data.

**Comment by Caoimhinmg** [comment]
So @njarboe there already is something similar to magic_write implemented in the 3.0 data model in PmagPy. However, as during the 3.0 conversion things have gone more OOP it is in the MagicDataFrame object that @moonshoes87 created which is generally accessed wrapped in a Contribution object (also @moonshoes87's work) which has a number of methods for propagating data between tables and such. So you would theoretically in a full 3.0 converter you would:

1. create a Pandas DataFrame for each table
2. fill each table
3. instantiate a Contribution object with the correct tables (i.e. con = Contribution(stuff))
4. insert your filled DataFrames in the MagicDataFrames contained in the Contribution tables (i.e. con.tables['measurements'].df = meas_df)
5. finally you can call MagicDataFrame.write_magic_file (con.tables['measurements'].write_magic_file())

The other pmag.py functions that handle say sample name to site name conversion and such should all still work as they are data model independent. If you want to see the code and try creating this 3.0 native converter these objects are defined in new_builder.py.

**Comment by moonshoes87** [comment]
To answer a few questions that have popped up:

The workshop issue where the locations table wasn't created is now addressed in the convert 2.5 --> 3 step.  (Fixed here: https://github.com/PmagPy/PmagPy/commit/56bcd5ffc4e1ebb11493896ea691ba7e641e6aeb)

In response to @Swanson-Hysell's other question: A related question, is it going to cause a problem in the GUIs that the new data model doesn't have the sample and site column in measurements.txt?

That shouldn't be a problem.  @Caoimhinmg, you don't need to remove those columns. They are added in if needed in the Contribution, but stripped out in ipmag.upload_magic along with any other non 3.0 columns:  https://github.com/PmagPy/PmagPy/commit/641847bcd63d980abd4c006111bb73f54fad80e8.  So you can leave sample, site, etc. in the specimens table until upload.

**Comment by moonshoes87** [comment]
@njarboe, you can see examples of how I tried to re-write some programs exclusively in 3.0.  Any of the plotting programs with 3 in the title use Contributions/dataframes throughout.  None of those build a Contribution from scratch (they read in 3.0 files), but you can definitely get an idea of what working in 3.0 could look like. 

Also, the notebooks in PmagPy/data_files/notebooks/Intro to MagIC Contributions.ipynb and Intro to MagicDataFrames.ipynb have some useful examples, including how you might build up a MagicDataFrame from scratch.  

<img width="1051" alt="screen shot 2017-02-02 at 12 04 43 pm" src="https://cloud.githubusercontent.com/assets/1836578/22566187/cfc2c49c-e93f-11e6-93bf-4fa597436c5b.png">

@njarboe, if you want additional help from me just let me know if I can assist.

**Comment by Caoimhinmg** [comment]
So I've finished converting the iodp_srm_magic script and the iodp_dscr_magic script to native 3.0, fixed them up, and expanded them a bit, but the testing was a little funny. Foremost, the old scripts wouldn't run on the test data. When I got the new scripts running I noticed in the original mag file that there was only one (occasionally two) measurements per specimen, but okay fair enough at least it worked. Finally there just wasn't any test data I could find for the iodp_dscr_magic script (checked by running the old iodp_dscr_magic script on all logical mag files under data_files/Measurement_Import/). So figured I'd just shout out here to see if anyone has or can obtain a test dataset which has iodp discrete sample files for testing and perhaps a less buggy iodp srm file?

**Comment by moonshoes87** [comment]
I don’t have anything.  @ltauxe might?

**Comment by Swanson-Hysell** [comment]
Katerina Petronotis <petronotis@iodp.tamu.edu> (Expedition Project Manager/Staff Scientist for IODP) would be a person to be in touch with. She was planning to get IODP software developers work on this conversion so getting files and info from her would be helpful.

**Comment by ltauxe** [comment]
I do, but I am in Cambodia right now and can’t dig this stuff out this week.  will do as soon as i can.
lisa

**Comment by Caoimhinmg** [comment]
Okay a few more questions for the group at large. I noticed a while back there are 4 JR6 conversion scripts so I was saving it for a full day. However, Pmag GUI only uses 3 of them jr6_txt_magic.py, jr6_jr6_magic.py, and iodp_jr6_magic.py. My plan is thus to convert these 3 only and leave jr6_magic.py as is. Is there some reason to do this another way? If not what is the purpose of this jr6_magic.py considering that the other scripts cover every jr6 example file in data_files as far as I can tell and it's not used by Pmag GUI? I remember something about JR6 file conversion at the workshop and don't want to mess with anything so I'll just work on the iodp_jr6 in the mean time because it is different enough I'm sure it is necessary.

On the note of the iodp_jr6 example data. Does anyone have more? The example data currently in the repo is just a single measurement, one NRM. If not, no problem, I'm going to email Katerina Petronotis today to see about all the iodp data formats. Just thought I'd see if anyone had some handy.

Thanks everyone.

**Comment by moonshoes87** [comment]
I think jr6_magic may have worked on an older non-current format, but I think it’s safe to skip it.

**Comment by ltauxe** [comment]
i have tons of iodp_jr6 data - they are painful because of the limited specimen names so i used the IODP cryptic ID which then must be matched with a more sensible name containing exp-hole-core-sec-cm info.  I can send it along if you like. 
lisa

**Comment by Caoimhinmg** [comment]
Yeah the specimen name in the one iodp_jr6 file in the repo is just a string of numbers that as far as I can tell doesn't explain anything. I'm thinking of just making flags for the exp-hole-core-sec-cm names and then doing what I did in IODP srm and constructing specimen, sample, site, and location names from them then just drop this string of numbers in alternate names. Any thoughts on that? Of course I'm basing this plan on a single NRM record and one specimen so probably not the most thought out of ideas yet. So yes I'd find the additional IODP srm, discrete sample, and jr6 data very useful, either attached here or uploaded to the repo when you have a chance. Thanks.

**Comment by Caoimhinmg** [comment]
Well thought I was done, but guess I missed one. Showed up the moment I tried working on a new local pmag_basic_dialogs file. Anyway there's something funny about this last script, huji_magic.py, because there is also a huji_magic_new.py. One for the huji magic new format and one for the old format, but I translated huji_magic_new and it ran on every single test file and output data that ran in Demag GUI flawlessly. I couldn't cross check the data as there are no common specimens between the clearly marked old vs. new datasets, but I looked at the input files and checked to see if that was getting mapped correctly to the output files and as far as I could tell it was. So I guess I'm asking these questions:

- Is this a file that we no longer need, just like jr6_magic?
- If so is there any objection to me removing them from the repo? They'll live on in git history but if they are unnecessary there is no reason to have them take up space and the programs directory is cluttered enough as is.
- finally Pmag GUI has huji_magic and huji_magic_new used in the HUJI conversion dialog, will people freak out if I remove the old vs. new format option there because they're in one script now?

**Comment by moonshoes87** [comment]
You might want to check in with @ronshaar  about this format and making sure it works correctly.  He might be able to provide you with better test data files if that would help.

I agree that if the updated HUJI_magic script deals with old and new files correctly that we should go ahead and simplify by having only one script and eliminating the option for old/new in Pmag GUI.  To be conservative, we could put a note in the Pmag GUI import window that says "Works for both old and new HUJI formats", but it doesn't seem strictly necessary.

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87, so as the last commit message points out I made an altered pmag_basic_dialogs (pmag_basic_dialogs_native3) that uses the new conversion scripts and a has more detailed interface because there are more fields for input now. Also uses the new 3.0 combine_magic I just made to remove duplicate fields. I've tested every single data format on every dataset I have (except for the CIT format as I have like 100 datasets in CIT format). So I guess I'm paging you now to talk about how we might go about integrating these into Pmag GUI proper? I just replaced the import statement in Pmag GUI for pmag_basic_dialogs when testing and that worked fine, but I think a clearer distinction might be better, especially as we don't want to completely remove 2.5 support yet. At least in part because this is still probably going to be a pretty buggy transition. Cheers.

**Comment by moonshoes87** [comment]
Great!  I think we can then just go to importing the 3.0 dialogs when -DM 3 and the 2.5 dialogs when -DM 2.5.  We can import both and then select the correct one to use for all dialogs when the data model is picked (which can either be immediate in the instantiation of the program or slightly later with the 'choose your data model' dialog).  

We can still leave the 'convert to 3.0' step in case people are upgrading legacy data, but it will be unnecessary if someone just wants to start in 3.0.  I think I may move the 'upgrade' button somewhere else, in that case, so that it isn't in the expected workflow order of the import --> analysis steps.

Does that all sound good?

**Comment by Caoimhinmg** [comment]
Sounds perfect @moonshoes87, I like the idea of moving the upgrade function to a menu function or something so it's not in the workflow. My plan for the imports would be to import both pmag_basic_dialogs at the top of Pmag GUI under two names then just assign one to the name used in the rest of Pmag GUI during the point when Pmag GUI picks data model to keep imports at the top of the file.

In other news, I plan to leave the conversion scripts in their sub-directory of programs as I think it cleans up the programs directory (which is kinda colossal) and prevents name collisions, unless you have a reason not to do this.

I was also looking at some of the other programs in the programs directory and there are quite a few which rely on 2.5 formatted data files. I'm thinking we might want to start a dialogue on what's going to happen to these things as the 3.0 model becomes the primary form of data. Any thoughts @ltauxe or @Swanson-Hysell?

Finally one of the ideas brought up to me at the workshop was to make a more generic conversion dialog that reads in a delimited text file and allows the user to provide the mapping to magic, as this covers most of the data files out there. Something basically that uses pandas read_csv function then has the user provide a mapping in the dialog which feeds into pandas.DataFrame.rename and from there just outputs to file. Obviously a low priority project, but thought I'd toss it out there to see what you all thought before I forgot.

**Comment by moonshoes87** [comment]
Ok, I just pushed a commit that moves "the convert to 3.0" button da61e93 to the right side of the GUI.  I want it to be a little more prominent than hidden in the menu.  Let me know if anyone thinks it belongs somewhere else.  

I think leaving the conversion scripts in their subdirectory is fine, but I will need to fix the pip install script to look for them if so.

@Caoimhinmg, do you want to switch the Pmag GUI 3.0 to using the native 3.0 scripts, or did you want me to do that?

**Comment by moonshoes87** [comment]
I would like to re-do the Pmag GUI tutorial in the Cookbook to reflect the 3.0 workflow and have corresponding images.  The example data files (imported by generic_magic) should be fine as they are, but I want to make sure the 3.0 workflow is correct and somewhat stable first.  

I added a milestone for this task, which I will do as soon as we've figured out the issues from my comment above!

**Comment by ltauxe** [comment]
yes.  and i also have to add a bit about my new program plot_magmap.py.  

I can check thellier_gui with some old and new data.  I sure hope it works.  
lisa

**Comment by Caoimhinmg** [comment]
@moonshoes87 I'd be happy to switch the Pmag GUI 3.0 interface to the 3.0 scripts. I won't be able to do it for a bit though as I'm busy this week. I'll push a commit to this issue when I get it done.

**Comment by moonshoes87** [comment]
Ok, great, I will test and release for pip shortly and we can wait a bit longer on the standalones.

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87 I just pushed a commit that makes Pmag GUI use the correct dialogs depending on data model. Also changed the button size on the 3.0 GUI as the difference in the unpack contribution and convert 3.0 buttons looked a bit wonky on my distro. So I think we might finally have managed this task. (Also sorry I forgot to tag the commit to this issue)

Moving forward, I'm going to close this thread with this comment and any further bugs with these scripts should be opened in their own issues. If there are any data formats I'm missing please reopen this issue and either tell me the format name and provide examples in the comment or create a milestone referencing examples in the repo. Thanks.
