### ISSUE TITLE
demag_gui breaks with older data sets

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#139]
Using demag_gui on an elderly data set (from a few years ago) from Costa Rica (Cromwell et al., 2013 - doi: 10.1002/ggge.20199), it breaks with this error message: 
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/demag_gui.py", line 2312, in read_criteria_file
    try: acceptance_criteria=pmag.read_criteria_from_file(os.path.join(self.WD, criteria_file_name), acceptance_criteria)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/pmag.py", line 9075, in read_criteria_from_file
    rec[crit]=rec[crit].strip('\n')
KeyError: 'specimen_aniso_ftest_flag'

Kevin?

**Comment by Caoimhinmg** [comment]
Hey @ltauxe, so it looks like it's something in pmag.py read_criteria_from_file. There is a section where the criteria anisotropy_ftest_flag is changed to specimen_aniso_ftest_flag with the comment "convert legacy criterion to 2.5". As far as I can tell this flag isn't in the criteria data so it's causing a break, I just added a check for the original flag in the criteria data hoping that would catch it without creating further problems. However, I couldn't find the Cromwell et al., 2013 contribution in the MagIC database by searching "Cromwell 2013" or by searching the DOI you provided, so I haven't tested this. If you could link to the data or send it to me I could debug more accurately.

**Comment by Caoimhinmg** [comment]
@ltauxe I haven't heard anything on this for a while. Is this still a open issue (I am still incapable of recreating it)? If not I plan to close it in a few days.

**Comment by ltauxe** [comment]
it seems to be working now…

**Comment by Caoimhinmg** [comment]
Okay I'll close this out then.
