### ISSUE TITLE
Contribution.__init__ argument to suppress import of vocabularies and methods

### ISSUE THREAD

**Issue by Caoimhinmg** [PmagPy/PmagPy#141]
@moonshoes87 would the creation of a boolean argument to the __init__ of the Contribution object which suppresses the import of vocabularies and methods be possible? I don't know if there is hard coded portions of the Contribution object which would shatter into a million pieces if this happened or what, but this change would allow for giant increases in runtime for the GUIs that don't need these vocabularies and simply use the Contribution object to read and write tables. It would also help with the magnetometer file conversion to magic files as I wouldn't need to import these things when writing to disk. I could work around this in the case of conversion scripts by using just the MagicDataFrame object, but that wouldn't fix the delay this feature has in the GUIs. Obviously this is a low priority objective, but right now the runtime of the GUIs in 3.0 is significantly slower than in 2.5 even running tests takes 2-3 times longer just because starting is so much slower. I'd be happy to help work on making this happen when we both have a break in the current set of more pressing issues, but I thought I'd first ask if this is even a feasible objective.

**Comment by moonshoes87** [comment]
This is actually a result of your changes a while back.  I used to not download either vocabularies or data model by default.  

See #93 

However, we should only be importing from earthref once per session, because DataModel and Vocabulary classes both set that data as a class constant.  Are you saying this is happening more often, or just that the start up time is annoying?  

That said, I see a few ways of dealing with this.

1. Boolean argument for Contribution could work in situations where you know you won't need vocabulary/data model.  The only problem with this approach is that you then need to be SURE you don't need vocabulary or data model, since I took out all of the places where I check for it (again, see #93 )

2. Never download from earthref -- rely on cached versions of data model and vocabularies, method codes, etc.  This is a lot faster, but potentially less up to date.

**Comment by Caoimhinmg** [comment]
Yeah fair enough, I did make it start up and import by default so as to reduce duplicate imports which was slowing the GUIs down even more. I'm just asking if we can eliminate this overhead entirely except where necessary.

I like the idea number 1 better simply because there are times where I'm sure I don't need the model, vocabularies, or method codes and we can remove any import slow down. For instance the GUIs basically just use the Contribution object to read in DataFrames, hold onto the DataFrames, and write to disk. Which unless I'm missing some hidden functionality doesn't require checking vocabulary or anything because the user can't put method codes in or change lithology or other controlled fields that's all done by the GUI already and checked by PmagGUI before upload. Same more or less goes for the conversion tools.

**Comment by moonshoes87** [comment]
Controlled vocabularies and data model are used in Pmag GUI and MagIC GUI, so I'm guessing you mean that you don't need them in Demag/Thellier GUIs.  

In that case, if you are running Demag/Thellier GUI by themselves, or running conversion scripts on the command line, those would be the times when you shouldn't need vocabularies/data model, correct?  

We would then also need to add a no data-model flag for MagicDataFrames, which also grabs the data model by default.  Contribution.remove_non_magic_cols would break, along with some of the ways of instantiating MagicDataFrames -- currently you can create MagicDataFrames with default required columns or building up the column names by providing column group names.  This wouldn't necessarily be a big deal if you aren't using any of those options, but I'm a little afraid of this sneakily breaking things down the road when a Contribution or MagicDataFrame object is missing these things.  

I think I have prevented all (or almost all) redundant calls to Earthref, which means that the slowness should occur only in the beginning.  However, it can be significant depending on your internet connection, which is definitely annoying.  

As I think it through, I lean a little more towards the caching option, honestly.  Another unrelated argument for caching exclusively is to prevent issues like the one you caught earlier today #140.  Caching means we would still be reading in data_model/vocabularies at times when we don't strictly need them, but it's pretty fast to do so.  

Does that seem like a reasonable solution for now?

**Comment by Caoimhinmg** [comment]
It solves the problem simply and more quickly. Though I do like the idea of just having the data model on the internet and grabbing it caching is perhaps the best solution. This is more than enough to solve the GUI slowdown when testing Thellier and Demag GUI (which was most annoying part as tests were taking 15-20 min to run). Though this is still a significant slowdown on the conversion scripts, because they were so fast in the first place, it's not unreasonable. I'll close the issue for now.
