### ISSUE TITLE
problem saving file names with colons 

### ISSUE THREAD

**Issue by jbowles100** [PmagPy/PmagPy#143]
I don't see this reported elsewhere, but my students working on PCs are unable to use the -sav switches in many PmagPy programs because the output files all have colons in them which is not permitted by the Windows operating system.  For example, dayplot_magic.py or eqarea_magic.py.

**Comment by Swanson-Hysell** [comment]
Interesting. It seems like this should be a pretty straight-forward fix. @ltauxe, any issue with getting rid of the colons in these output file names from your perspective?

**Comment by moonshoes87** [comment]
It should be an easy fix but we need to make sure we don’t break things for Rupert’s use on the server.  I believe we just need to use the isServer flag.  This is something we discussed a bit before the workshop, but couldn't get to.  I can take this one.

**Comment by jbowles100** [comment]
Thank you!!

Julie

**Comment by moonshoes87** [comment]
I just released pmagpy/pmagpy-cli 3.8.7.  The colons will now be replaced with underscores, so the auto-generated filenames should no longer be illegal in Windows.  I am not closing this issue yet because I want to go through the programs and output a more sensible, readable name for each file, but for now this should prevent things from breaking.  

Thanks for reporting this issue, @jbowles100!

**Comment by ltauxe** [comment]
no problem at all.  Rupert wanted them, but they are not essential. 
lisa

**Comment by jbowles100** [comment]
Thank you for fixing this so quickly!

Julie

_______________________________

Julie A Bowles
Assistant Professor
Department of Geosciences
University of Wisconsin - Milwaukee
PO Box 413, Lapham Hall 366
Milwaukee, WI  53201
bowlesj@uwm.edu<mailto:bowlesj@uwm.edu>
414-229-6110
http://people.uwm.edu/bowlesj/
_______________________________





On Feb 14, 2017, at 6:02 PM, moonshoes87 <notifications@github.com<mailto:notifications@github.com>> wrote:


I just released pmagpy/pmagpy-cli 3.8.7. The colons will now be replaced with underscores, so the auto-generated filenames should no longer be illegal in Windows. I am not closing this issue yet because I want to go through the programs and output a more sensible, readable name for each file, but for now this should prevent things from breaking.

Thanks for reporting this issue, @jbowles100<https://github.com/jbowles100>!

**Comment by moonshoes87** [comment]
No problem!  

@ltauxe, I am preserving the old style of naming for on the server, so this shouldn’t affect Rupert at all.

**Comment by moonshoes87** [comment]
The following commits make more readable plot names when not used on the server: 95bbf0995069b2c5ee15647550648ec966121ba4, dca344068dee9db4392f5eb45c0e21f23348cdcf,  167d8d7955eb6445b3f6762abe355ee82a472143.
