### ISSUE TITLE
IODP changed LIMS format 

### ISSUE THREAD

**Issue by sms0832** [PmagPy/PmagPy#145]
IODP has changed their format for srm data. (argh)

Example of new data format:

http://iodp.tamu.edu/LORE/?reportName=srmsection&appl=LORE&action=show&filters=[%22x_expedition%20in%20%28%27318%27%29%22,%22x_site%20in%20%28%27U1361%27%29%22]&postretrieve={%22scale_id%22:%2211331%22}

Pre Expedition 362 format:
http://iodp.tamu.edu/LORE/?reportName=srmsectionold&appl=LORE&action=show&filters=[%22x_expedition%20in%20%28%27318%27%29%22,%22x_site%20in%20%28%27U1361%27,%27U1361%27%29%22]&postretrieve={%22scale_id%22:%2211331%22}

**Comment by ltauxe** [comment]
of COURSE they did!  seems to happen every year or two. very annoying. 
lisa

**Comment by Caoimhinmg** [comment]
Yeah I got some of the new data, I'm working on patching the new native 3.0 IODP_srm_magic script so it works on all the IODP SRM data. Will close issue when I'm done. Thanks for the tip off and links, @sms0832.
