### ISSUE TITLE
problem reading in orientation data from SUFAR4

### ISSUE THREAD

**Issue by jbowles100** [PmagPy/PmagPy#146]
There seems to be an issue with how the orientation data are read in in the SUFAR4_asc_magic program in ipmag.py.  The program assumes (I believe) that the azi/dip are actually azimuth and hade field measurements in the SIO convention.  SUFAR4 allows for a more generic approach to orientation and uses four orientation parameters (P1, P2, P3, P4) to describe what azimuth and dip actually mean.  The following modifications generalize the orientations and at least work for the system we are using,
where P1 = 12, P2 = 90, P3 = 12, P4 = 90.  A diagram of the orientation parameters is attached below.

Sorry -- I haven't figured out the whole push request thing yet...

Within:  def SUFAR4_magic...  (ipmag.py)

        if 'Azi' in words and isspec=='0':
            #SampRec['sample_azimuth']=words[1]
            #labaz=float(words[1])
            az = float(words[1])
            P1 = float(words[4])
            P2 = float(words[5]) 
            P3 = float(words[6]) 
            P4 = float(words[7])  # P4 relates to a fabric or bedding measurement -- not dealt with here
            az = az+P1*360./12. - P3*360./12.
            if az>=360:
            	az=az-360
            elif az<=-360:
            	az=az+360
            labaz = az
            SampRec['sample_azimuth']=str(round(az,1))
                            
        if 'Dip' in words:            
            #SampRec['sample_dip']='%7.1f'%(-float(words[1]))
            #labdip=float(words[1])
            SpecRec['specimen_vol']='%8.3e'%(float(words[10])*1e-6) # convert actual volume to m^3 from cm^3
            dip=float(words[1])        
            if P2==90:
        	    dip=dip-90.
            labdip=dip
            SampRec['sample_dip']=str(round(dip,1))

![agico_orientation](https://cloud.githubusercontent.com/assets/25388016/23106850/5b607216-f6b9-11e6-8486-9f3a4e11c421.png)

**Comment by Swanson-Hysell** [comment]
I went ahead and implemented you edit to that function and committed it. I will close the issue for a moment, but let me know if it works after testing as I haven't tested it.

These Github guide articles could be helpful for how to put in a pull request:
https://guides.github.com/activities/hello-world/#pr
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by ltauxe** [comment]
right - that was for the IODP instrument and I just hard wired it.  it needs to be more flexible.  thanks nick and julie

**Comment by jbowles100** [comment]
Hi Nick,

It works if we download and do a developer install, but it doesn’t work on the PIP install.

Julie

**Comment by Swanson-Hysell** [comment]
Hi Julie,

There is currently discussion of doing a new PIP release: #74. The last release doesn't have this code edit in it.

**Comment by jbowles100** [comment]
Hi Nick,

Thanks for the update.  You guys should certainly schedule the PIP releases however makes sense to you all.  I had initially assumed that it was just automatically updated, but it makes sense that it requires an extra step.  I’m working off the developer install, and I have one master’s student who needed the bug fix immediately — I got the developer install working for him.  For the larger classroom setting it’s a bit of a hassle, but it can be done — or we can just work around it.

Julie

**Comment by Swanson-Hysell** [comment]
You using the code for a class seems like a good reason to do a PIP release now. You think you could go ahead and put together the release @moonshoes87?

**Comment by ltauxe** [comment]
one tiny problem just popped up.  Rupert is about to change the aniso_mean stuff in 3.0 and I need to fix thellier_gui to match.  I suppose that’s ok but we really need to finalize thellier_gui 3.0 
I suggest we go ahead with a pip release now and maybe do another one at the end of the week.  
lisa

**Comment by moonshoes87** [comment]
Ok, I will make a pip release later today, then we can do another plus a release of standalones next week with Pmag GUI and Thellier GUI 3.0 adjustments.
