### ISSUE TITLE
Demag GUI help

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#148]
The Demag GUI help message isn't super useful for someone trying to run Demag GUI on the command line.  Maybe we should point them to the Cookbook, or provide information about the command line options?

**Comment by Caoimhinmg** [comment]
Fair enough I've focused so much on the in context help I kinda forgot this was a thing; I'll update the doc string tomorrow or Monday so it's more standardized, informative, and includes links to further sources.

**Comment by Swanson-Hysell** [comment]
Make sure to tag this commit for the docathon (https://bids.github.io/docathon/):

> Any documentation commits should include the words "doc", "documentation", or "docathon" in the commit message. During the week, we'll be keeping track of stats on who's contributed. This will be displayed on our lovely stats page. Below are the current leaders in both projects and users. We'll update these plots a few times each day so that we can congratulate those that have made contributions. You can also click a plot to go to a summary page.

**Comment by Caoimhinmg** [comment]
Hey @ltauxe and @ronshaar in my update of the Demag GUI documentation I want to include a script style docstring which describes how to run from command line and should go where the "Log Header" is currently. For now I'm just going to move the Log Header down and put in the docstring, but this Log Header is defiantly out of date, seems redundant considering we use github now, and uses up a decent bit of space in the script. So I would like your opinions on removing this Log Header from the top of Demag GUI and possibly Thellier GUI and instead just including a list of authors at the bottom of the docstring. Thanks.

**Comment by moonshoes87** [comment]
The new help looks good to me!

**Comment by Caoimhinmg** [comment]
K, I'm going to close this for now then so it's not cluttering the issues page.
