### ISSUE TITLE
Pmag GUI inventing columns during Add MagIC metadata for uploading step

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#153]
Pmag GUI makes many phantom columns when it opens the data files - result_type,  geologic_type and so on.  Also some of these columns have "Edit All" under the name.

**Comment by moonshoes87** [comment]
The Edit ALL part is a bug which I will fix.

The other additions, though, are required column names that are put in automatically because they are required by the data model.  Do you think it is better to add columns automatically, or to simply alert the user that they are missing those required columns later in validations?  I thought the former would be less frustrating, which is why I made it that way initially.

**Comment by ltauxe** [comment]
well, they weren’t there originally but i inserted them in thellier_gui because it was an annoying extra step to put them in in pmag_gui.  i’m not sure I filled them in correctly in thellier_gui - they should all be ‘i’ for all of the calculations made in thellier_gui.  maybe you can check that part out.  but the bottom line is, pmag_gui should first check if they are there and then put them in.  the smoothest sequence is for the user to have to think the least - so thellier_gui and demag gui should just fill in those columns ‘I’.  same for result_quality, which should be ‘g’ unless it fails something in criteria.  
did that make sense?  
lisa

**Comment by Caoimhinmg** [comment]
Opps, when did quality change to result_quality for most of the tables?!? Demag GUI did not expect this. Will patch this name change in a couple minutes.

**Comment by Caoimhinmg** [comment]
Never mind apparently someone already fixed this. Heck could have been me, I'm not sure I remember some of what I've patched at this point.

**Comment by moonshoes87** [comment]
@ltauxe, I am hopeful that I may have indirectly fixed your problem with the columns (I also fixed the validation issue you mentioned in email).  You can see more explanation about what I changed in #155. If you don't mind giving it another go (from the release branch), let me know if there are still sticking points.

@Caoimhinmg, I think we may be ready to re-do the releases.  I did some structural changes to how Demag GUI/Thellier GUI are called from Pmag GUI, and I've played around with them and everything seems to be working smoothly.  It would be great if you could do some poking around as well and let me know if you find any trouble.  I'll give it another poke or two tomorrow, and if all seems well I will re-release my side of it.

**Comment by moonshoes87** [comment]
@ltauxe, let me know if this is still a problem
