### ISSUE TITLE
i'm in a world of hurt

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#157]
I was working on "master" but y'all have been working in "release".  so when i tried git checkout release i created a bunch of conflicts.  
CONTRIBUTING.md: needs merge
command_line_setup.py: needs merge
data_files/di_rot/fishrot.out: needs merge
data_files/notebooks/_PmagPy.ipynb: needs merge
data_files/notebooks/_PmagPy_3.0.ipynb: needs merge
data_files/notebooks/data_model_conversion.ipynb: needs merge
data_files/tk03/tk03.out: needs merge
data_files/uniform/uniform.out: needs merge
pmagpy/ipmag.py: needs merge
pmagpy/mapping/map_magic.py: needs merge
pmagpy/new_builder.py: needs merge
pmagpy/pmag.py: needs merge
pmagpy/validate_upload3.py: needs merge
programs/demag_gui.py: needs merge
programs/generic_magic.py: needs merge
programs/thellier_gui.py: needs merge
setup.py: needs merge

what do i do now?????

**Comment by moonshoes87** [comment]
It is hard to tell. I will merge the release stuff into master tonight or tomorrow morning, so maybe it would be easiest if you can wait until then.

**Comment by moonshoes87** [comment]
Release is now merged into master
