### ISSUE TITLE
propagating values between tables

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#165]
Currently, there is functionality in Contributions to propagate values geologic_types, geologic_classes, lithologies from sites or samples down into samples/specimens.  

1.  Should any other columns automatically propagate down in this way?

2.  Should those columns propagate up into the sites table if present in samples, but not in sites?

**Comment by ltauxe** [comment]
I think all required columns should propogate up and down if they do not yet exist in the tables.

**Comment by moonshoes87** [comment]
what do you mean by all required columns?

This is how I find all of the columns that are straight up required (not conditionally required, but required in all cases):

<img width="2000" alt="screen shot 2017-03-17 at 2 26 54 pm" src="https://cloud.githubusercontent.com/assets/1836578/24061661/ed6b5234-0b1d-11e7-9717-bc7498c32985.png">

Not all of them make sense to propagate between tables, right?  Like citations, result_quality, method_codes etc.  Also, some that are *not* required we currently propagate, like lithologies etc. into the specimen table.

**Comment by ltauxe** [comment]
in particular the geological_classes, lithologies and geologic_types.  
lisa

**Comment by moonshoes87** [comment]
Ok, currently we do propagate those three [geologic_types, geologic_classes, and lithologies] down.  This happens automatically in Pmag GUI step 3, but it is just a single method on the Contribution object so it can be implemented anywhere else you want it.

 I can implement functionality to propagate up -- what that will look like is:

if a site doesn't have a lithologies value, create a colon-delimited list for each value belonging to one of its samples and assign that value to it.

I will go ahead and work on that.

Anything else I should add, or stick to propagating just those three columns?

**Comment by ltauxe** [comment]
these are the main ones.  but i am still interested in somehow propogating age info from where-ever to the sites table.  
lisa

**Comment by ltauxe** [comment]
so now the types and classes get propagated but not lithologies.  this would be handy.

**Comment by moonshoes87** [comment]
lithologies are propagating as expected for me.  I did decide to treat "Not Specified" as a null value, though.  In other words, if a specimen has "Not Specified" as a value in lithologies, and its parent sample has "Basalt", the specimen will end up with the value "Basalt".  Also, I don't yet have functionality to propagate values up (i.e., from samples to sites).

So here I assign lithology values in the sites table:

<img width="1170" alt="screen shot 2017-03-21 at 3 13 14 pm" src="https://cloud.githubusercontent.com/assets/1836578/24171163/f5823540-0e48-11e7-92a8-e7fd4fcb34e5.png">

the samples table starts out with no lithologies values, then I run the propagation function, and the appropriate lithologies propagate through:

<img width="1009" alt="screen shot 2017-03-21 at 3 13 51 pm" src="https://cloud.githubusercontent.com/assets/1836578/24171179/078f54ac-0e49-11e7-8042-dbe9285666a8.png">

and to the specimens table as well:

<img width="1089" alt="screen shot 2017-03-21 at 3 16 15 pm" src="https://cloud.githubusercontent.com/assets/1836578/24171271/5e6d4ed2-0e49-11e7-8860-581ce39f6572.png">


So if lithologies aren't propagating through for you, I'm not sure why that is.  Can you give me more details about where/how this is failing for you?

**Comment by ltauxe** [comment]
ahh.  that’s what did it.   these were lithology “Not Specified”.  could you not treat it as a null value?  
lisa

**Comment by moonshoes87** [comment]
Yep.  I’ll change that.

**Comment by moonshoes87** [comment]
Let me know if this gives you any more problems.  And when we meet (next week, I hope?) we can discuss the ages propagation.

**Comment by ltauxe** [comment]
ok   i’ll give it a go.
