### ISSUE TITLE
test_new_builder.test_init_empty failing because of written locations.txt

### ISSUE THREAD

**Issue by Caoimhinmg** [PmagPy/PmagPy#166]
So I was running all tests to try and fix any random bugs that our new release and change to the conversion scripts might have introduced and I found that this test was failing because somehow it is writing a locations.txt before running it. This all happens inside this suite of tests because running it on its own still causes the problem. That said I have been through the tests and can't find where this is anywhere. Perhaps you have some ideas @moonshoes87?

**Comment by moonshoes87** [comment]
Yes, that is a random non-bug bug that I have been meaning to track down.  It isn’t actually a problem with the failing test (it works if you run it alone), but some other test that is leaving a file or two hanging around in the PmagPy directory.  I’ll track this down when I have time!

**Comment by Caoimhinmg** [comment]
Yeah it's not a rush as it affects nothing. I've been experiencing a lot of test failures around 19 of 337 (some of which no doubt because of my platform). Thought I'd finally track them all down and raise those I couldn't solve here.

**Comment by moonshoes87** [comment]
Ok, great.  test_init_empty is the only test failure I have at present (excepting those Demag GUI tests that crash on my platform that I routinely skip).

**Comment by Caoimhinmg** [comment]
Okay this is now the only test I have failing so it looks like everything is pretty stable. I'm still not sure what to do about those Demag GUI tests on mac as far as I can tell skipping them is still the only solution.
