### ISSUE TITLE
SCAT box no longer drawn in Thellier GUI 3.0

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#167]
1. SCAT statistic is only displayed if present in criteria file

2. SCAT box is no longer drawn

**Comment by moonshoes87** [comment]
It looks like SCAT box IS drawn normally, but I am getting insane SCAT values for the contribution you've been working on, @ltauxe.  The bounding lines are coming out enormous:

    pars['specimen_scat_bounding_line_low'][1] -3007.94535983
    pars['specimen_scat_bounding_line_low'][0] 2553.15786798
    pars['specimen_scat_bounding_line_high'][1] 3004.59224261
    pars['specimen_scat_bounding_line_high'][0] -2550.4575756

I'm trying to figure out why this would be, since the SCAT calculation seems to perform normally for other contributions.

**Comment by moonshoes87** [comment]
Aha!  beta_threshold was getting set to -999, which made all the values crazy.  I will prevent that.

**Comment by ltauxe** [comment]
yes i was going to mention that it depends on beta.  so if SCAT is set to TRUE, beta has to be set to some reasonable default - say 0.1. 
lisa
