### ISSUE TITLE
pmag_criteria => criteria conversion

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#168]
somewhere in pmag.convert_criteria_file_2_to_3,  samples.int_n_samples is generated and it should be samples.int_n_specimens.

**Comment by moonshoes87** [comment]
I fixed this locally for PmagPy, but I presume this should be changed in the data model as well (this is what is currently in the data model json):

<img width="708" alt="screen shot 2017-03-21 at 2 54 58 pm" src="https://cloud.githubusercontent.com/assets/1836578/24170488/a0b23206-0e46-11e7-90f7-0ffd82a2dc69.png">

**Comment by ltauxe** [comment]
ahh.  yes that must be changed in the data model. rupert?  
lisa

**Comment by rminnett** [comment]
I updated the data model on the website. 2.5 criterion **sample_int_n** now maps to 3.0 column **samples.int_n_specimens**.
