### ISSUE TITLE
thellier_gui error with site_int_n

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#169]
When I try to set the site_int_n parameter to something, i get this on saving: 

  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/thellier_gui.py", line 2391, in On_close_criteria_box
    if not dia.set_site_int_n.GetValue():
AttributeError: 'Criteria_Dialog' object has no attribute 'set_site_int_n'

**Comment by ltauxe** [comment]
this happens with both 2.5 and 3.0.

**Comment by moonshoes87** [comment]
I pushed a fix for the dialog name problem, but not sure about the bigger picture.

**Comment by ltauxe** [comment]
Now it does this correctly, BUT thellier_gui now saves all the criteria with the 'ACCEPT' criterion instead of the IE-SPEC, etc. criteria.  This is a new bug.

**Comment by moonshoes87** [comment]
@ltauxe, are you still having the 'ACCEPT' criterion problem?
