### ISSUE TITLE
Flipped map in Demag_GUI VGP viewer

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#171]
The basemap of the demag_gui vgp viewer is reflected. While this results in an interesting new perspective on the world, in should be fixed:
<img width="985" alt="screen shot 2017-03-27 at 9 51 13 am" src="https://cloud.githubusercontent.com/assets/4332322/24367872/17f44fd0-12d3-11e7-9fdb-9c9e9b92e70a.png">

**Comment by Caoimhinmg** [comment]
Yeah guess this happened kind of intentionally, I had originally set the map to center on the average of the longitudes so it gives the easiest view between spread data. Did not count on how dumb this would look with all the points in one spot and 180 degrees off of normal map view. Set the center to 0 now so it should look more normal. Also made it so you could save the plot with ctrl-s.
