### ISSUE TITLE
clarify windows dev_setup instructions

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#176]
@Caoimhinmg, when Windows users are providing their path-to-python during for dev_setup, should they include the terminal python.exe, or does it matter?

I.e., should it be:

`dev_setup.py install -p C:\Users\USERNAME\AppData\Local\Continuum\Anaconda2`
or
`dev_setup.py install -p C:\Users\USERNAME\AppData\Local\Continuum\Anaconda2\python.exe`
or either one?

Either seemed to work on my Windows VM, but I wanted to make sure that was correct.

I am starting to work on some Cookbook updates and clarifications, so I want to make sure this is well-described.

**Comment by Caoimhinmg** [comment]
Looking at the code it seems I had the full path with python.exe in mind. I can add a check for that though easy enough and push the change when I'm done with the merge of my fork. Think it would be better if it didn't matter which you use.

**Comment by moonshoes87** [comment]
Yeah, that seems best.  Thanks!

**Comment by Caoimhinmg** [comment]
Alright just did this, and it should work now. Reopen if there are problems.
