### ISSUE TITLE
random.jumpahead functionality not in Python 3...

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#180]
scalc.py and scalc_magic.py both use the method random.jumpahead, however it is deprecated in Python 3:

    >>> random.jumpahead.__doc__
    Change the internal state to one that is likely far away
        from the current state.  This method will not be in Py3.x,
        so it is better to simply reseed.

Looking at the code in scalc.py, I'm not really sure how to go about fixing this.  Here's the code snippet:

      for i in range(nb): # now do bootstrap                                                                    
        BVgps=[]
        for k in range(len(Vgps)):
            ind=random.randint(0,len(Vgps)-1)
            random.jumpahead(int(ind*1000))
            BVgps.append(Vgps[ind])
        SBs.append(pmag.get_Sb(BVgps))

Does someone with more insight into the math, or knowledge about the random module, want to take a whack at this?  @Swanson-Hysell, @Caoimhinmg, @ltauxe?

**Comment by Swanson-Hysell** [comment]
I think what could be done is to change the code so that it resets the seed each time before random.randint() it called. random.seed() initializes the random number generator. 

```
 for i in range(nb): # now do bootstrap                                                                    
    BVgps=[]
    for k in range(len(Vgps)):
        random.seed()
        ind=random.randint(0,len(Vgps)-1)
        BVgps.append(Vgps[ind])
    SBs.append(pmag.get_Sb(BVgps))
```

**Comment by Caoimhinmg** [comment]
This is the most sensible solution I could think of, also the method I would have thought of in the first place. That said I implemented it and tested it on a couple of datasets over here, results were reasonable. @Swanson-Hysell if you could give it a spin on some of your own data and make sure I'm not just reading this wrong or completely crazy.
