### ISSUE TITLE
"number" is still being used as a column name in the measurement table

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#182]
When I run cit_magic it creates a "number" column in the measurement table. This should now be "treat_step_num". This is in the current data model on the MagIC website, but maybe when I run the program the data model is not being updated. I get the message that it is using a cashed 3.0 data model. How does it decide to update the model? And where does it cache it?

Thanks

~/git/pmagpy/PmagPy/programs/conversion_scripts/cit_magic.py -f bl9-1.sam -sn BL9001 -usr Hagstrum -loc 'Boring volcanic field' -A -mcd FS-FD:LT-AF-Z:SO-SM
/Users/njarboe/anaconda/lib/python3.6/site-packages/matplotlib/font_manager.py:280: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '
Boring Lava collection 2009

-I- Using cached 3.0 data model
-I- Using cached method codes
-I- Using cached vocabularies
-I- Importing suggested vocabularies from https://earthref.org
-I- Using cached suggested vocabularies
-I- Using cached 3.0 data model
-I- overwriting /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/2009/bl9/bl9-1/specimens.txt
-I- overwriting /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/2009/bl9/bl9-1/samples.txt
-I- overwriting /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/2009/bl9/bl9-1/sites.txt
-I- overwriting /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/2009/bl9/bl9-1/locations.txt
-I- overwriting /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/2009/bl9/bl9-1/measurements.txt

**Comment by moonshoes87** [comment]
I still need to update the cache.  I should be able to do that today.  Sorry for the delay!  I will let you know when it is done.

**Comment by njarboe** [comment]
Is the cache a file in the PmagPy git repository? Is it hard to create. I tend to be the one to add to the model so maybe I should be able to propagate the info from the google doc to the PmagPy cache so that, when working with the community, I can get things working quickly.

**Comment by moonshoes87** [comment]
Yes, it is a document that lives in pmagpy/data_model/data_model.json.  It is simple to re-cache, I haven’t automated it but I just have to download the data model json from Earthref and rename the file.  Updating controlled vocabularies etc. is a bit more of a pain, but I hope to streamline that soon.

I’m not set up to easily put changes into the data_model.json file from the google doc, though.  Would that be helpful?  

With this particular change, we also have to fix a bunch of spots in the conversion scripts that use “number”.  I’m working on that now...

**Comment by moonshoes87** [comment]
Ok, the replacement should be complete now.  Let me know if cit_magic now works as expected.

**Comment by njarboe** [comment]
Working.
