### ISSUE TITLE
deprecated axisbg 

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#184]
59b36e8

Removing axisbg breaks for people who have matplotlib < 2.0.

    AttributeError: Unknown property facecolor

I think it would be better to leave axisbg for now, since that doesn't break anything.  @Caoimhinmg?

**Comment by Caoimhinmg** [comment]
Oops sorry about that just saw that it was depreciated didn't realize it would break everything for people with older matplotlibs.

**Comment by moonshoes87** [comment]
I only know because I tried the same thing ;)
