### ISSUE TITLE
Demag GUI without measurement-level data

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#185]
I have a location table with one entry and I get this error when I run demag_gui from pmag_gui:
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/pmag_gui.py", line 518, in on_run_demag_gui
    evt_quit=DemagGuiExitEvent)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 225, in __init__
    self.locations.sort()# get list of sites
TypeError: '<' not supported between instances of 'float' and 'str'

Line 225 is the second line here:
        self.locations=list(self.Data_hierarchy['locations'].keys())# get list of sites
        self.locations.sort()# get list of sites
The comments on these lines, I'm guessing, should have sites replaced with locations, but I'm not sure what is causing the error.
Here is a zip of the various files that I have pmag_gui running off of.
[Archive.zip](https://github.com/PmagPy/PmagPy/files/972238/Archive.zip)

**Comment by moonshoes87** [comment]
Somehow, this line:

    self.locations=list(self.Data_hierarchy['locations'].keys())# get list of sites

was getting some string values and some np.nan values.  We should figure out why Data_hierarchy is getting any np.nan values, but I've pushed a fix that removes any non-null values.

**Comment by njarboe** [comment]
This fix works. Should I close this issue or leave it open until you find out "why Data_hierarchy is getting any np.nan values"?

**Comment by Caoimhinmg** [comment]
@njarboe, do you think I could see the data file causing this error? I for the life of me can't recreate it by messing up locations.txt. Once I know what caused it, I'll try another fix that might fit slightly better in the framework of the GUI (I have a few ideas) then I'll close the issue.

**Comment by moonshoes87** [comment]
Yes, please leave it open.  Nick included an example above, Archive.zip.  Do you want to look into this, or should I?

**Comment by Caoimhinmg** [comment]
Oops, can't believe I missed that archive. I'll handle this one.

**Comment by Caoimhinmg** [comment]
So this is an interesting error, it seems to be caused because the sites you have listed in the sites.txt table don't match up with the sites in the samples.txt table so when propagating down from locations.txt to measurements.txt it hits a data gap. I have patched this by simply removing any data for which this problem exists. Problem is that is most of your dataset @njarboe. 

The ultimate solution then is to insure that data like this never gets generated again as it has no simple fix besides removing it. So how was this data generated @njarboe?

**Comment by moonshoes87** [comment]
Producing files with continuity between locations/sites/samples/specimens is obviously important.  But I am curious about these lines more generally:

            # do some filtering
            if 'location' in meas_data3_0.columns:
                meas_data3_0 = meas_data3_0[meas_data3_0['location'].notnull()]
             if 'site' in meas_data3_0.columns:
                 meas_data3_0 = meas_data3_0[meas_data3_0['site'].notnull()]

Do we really want to ignore measurements that don't have a location or site provided?  Maybe I'm misunderstanding something, but it seems like location shouldn't *have* to be provided in order to analyze measurements in Demag GUI, even if some measurements have location data and others don't.  Thoughts?

**Comment by Caoimhinmg** [comment]
Well it doesn't need a location interpretation, but it does need a name of some kind. It has to group the data that's the idea of the GUI and data model so it needs a group name. I could give a default name to data with this issue, like "unknown". So it'd be more like:

```python
if 'location' in meas_data3_0.columns:
    meas_data3_0.replace({'location':float('nan')},'unknown',inplace=True)
if 'site' in meas_data3_0.columns:
    meas_data3_0.replace({'site':float('nan')},'unknown',inplace=True)
if 'sample' in meas_data3_0.columns:
    meas_data3_0.replace({'sample':float('nan')},'unknown',inplace=True)
if 'specimen' in meas_data3_0.columns:
     meas_data3_0.replace({'specimen':float('nan')},'unknown',inplace=True)
```

**Comment by moonshoes87** [comment]
Interesting.  It just seems like if we don't exclude measurements without location data as long as *none* of them have location data, we shouldn't exclude measurements without location data if only *some* of them are missing it.  

I don't know the details of how all this is implemented in Demag GUI, so you probably understand the challenges better than I do.  It seems like your strategy above could be a reasonable way to deal with this...

**Comment by Caoimhinmg** [comment]
Okay I applied the fix suggested above. The basic problem @moonshoes87 is that there has to be a location you can say the samples or specimens belong to in the GUI. It's too ingrained to move around even when there is nothing but measurement data the GUI invents the 'unknown' location for the dataset. This is simply the logical extension of that so if there is partially unaccounted for data it goes in unknown now too  not just if the whole dataset doesn't have a location.

**Comment by njarboe** [comment]
This data set is from the USGS with the measurement data for all the specimens collected over decades (long projects at the USGS sometimes). So in this case they converted over to the Cal Tech system around 2005. We have the data files from those, but before that they are either on paper or some dos floppies. We may try and get those eventually, but I wanted to get the partial set of data available. This will happen a lot I think for people not using PmagPy for analysis (everyone but Berkeley and SIO for now I think). Showing how PmagPy and MagIC can be used on people's own data is a better way to convince them to use PmagPy for their analysis and easy upload into MagIC. 

Also, there are studies where people take set of samples from a lava flow and a site mean was determined. Later during the same study, another lava is sampled far away, a set of samples are taken, and another site mean determined. Eventually using the paleomagnetic directions and geochemistry of some of the sites are determined to have erupted from the same volcanic eruption and are combined in an average. This is also called a site. Thinking about it now, the result_type should be set to 'a' (for average) for this type of averaged site instead of usual 'i' (individual) for the other sites. I will modify my sites table to have an 'a' for the averages sites.

In the sites.txt file I gave you the 'i' sites have alphanumeric names like BL8097 while the averages sites (which I need to change to 'a') have names the are used for the whole eruption that can cover thousands of square kilometers (eg. Basalt of Barnes Road).

There should not be any samples and/or specimens that do not have a parent site and location in the sites.txt and location.txt files for this data set. I did not check for this closely, so I may have missed where my scripts were not set up right. Is it a problem for pmag_gui to have sites that have no sample/specimens? For the case where a researcher has not grouped some measurements and specimens into sites and locations, putting them all in a default called 'unknown' and printing a warning seems like a good solution.

If ignoring sites that have no specimen data is a pain to fix, I am not sure what to do. Many MagIC data sets will be like this and it would be nice if people can use demag_gui to look at the data downloaded from MagIC. Not sure the best way to deal with this.

**Comment by moonshoes87** [comment]
@njarboe  -- I'm going back through old issues.  Is this resolved?  As far as I can tell, it isn't a problem to have sites without samples/specimens in Pmag GUI.

**Comment by njarboe** [comment]
@moonshoes87 I unpacked this MagIC file that has four locations and many sites, but no measurements, and tried to look at the site level data using demag_gui through pmag_gui. I get an error that no measurement file was found and the site level data is not displayed. Also the samples in this data file are only a sub-set of all the samples used to determine the site level data. The only samples included are ones with ages determine for them.
[magic_contribution_12463.txt](https://github.com/PmagPy/PmagPy/files/1472554/magic_contribution_12463.txt)
![screen shot 2017-11-14 at 1 09 15 pm](https://user-images.githubusercontent.com/1278789/32805458-59641e2e-c93e-11e7-9fe8-d336ff98e4e3.png)

It would be great to be able to look at this study in demag_gui (and many others in MagIC like this) but maybe that is beyond the scope of demag_gui at the moment?

**Comment by ltauxe** [comment]
Nick - you demag gui only works on measurement data - it just plots zijderveld diagrams, etc.  
lisa

**Comment by njarboe** [comment]
That is what I thought. OK. People will have to play with site and sample level data downloaded from MagIC in some other way then. I was hoping to let Hagstrum do some interpretations on his data that I uploaded but, since he does not have measurement level data for all of his sites, I guess this won't work. If he opens up his data in demag_gui, he can see the specimens and sites with measurement data but sites and samples without measurement data would be lost when creating a file for MagIC upload.

**Comment by ltauxe** [comment]
this would be what those notebooks would be for.

**Comment by Swanson-Hysell** [comment]
As Lisa says, we haven't built demag_gui with this use case in mind as the goal with it is to facilitate the analysis of measurement level data. My go to for looking at site level data would be to use pmagpy functions in a notebook as Lisa writes. The notebooks in this repository are a good place for people to get started: https://github.com/PmagPy/2016_Tauxe-et-al_PmagPy_Notebooks

**Comment by njarboe** [comment]
Ok. Maybe we can build some online tools to look at and interact with data
on the MagIC website with the next MagIC grant.

**Comment by Swanson-Hysell** [comment]
The ability to deal with sample and site level data (sans measurements) could be integrated into demag_gui with additional development.

**Comment by ltauxe** [comment]
maybe a different GUI?  something like dir_gui ?  which would plot directions, poles, do study level calculations?  or do we want a notebook template for that?  
lisa

**Comment by moonshoes87** [comment]
I am working on cleaning up our issues list -- this hasn't been touched in two years.  Is this still worth considering, or is the functionality unnecessary and/or provided in a notebook?

**Comment by Swanson-Hysell** [comment]
Demag_GUI is about the measurements and there are tools to do other things with site level data within the notebooks. So I think this issue is good to close.
