### ISSUE TITLE
Thellier GUI plot paleointensity curve

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#190]
I don't think the "plot paleointensity curve" was fully updated for MagIC 3.  I've been able to run this, but I always get an empty plot.  

@ronshaar, @ltauxe, has this plotting worked for you?  Should I add it to my to do list?

**Comment by ltauxe** [comment]
oh yeah - i forgot about that.  sure!  if you can handle this that would be great.  It has to do with where to put the ages - they aren’t supposed to be in ages.txt which is where thellier_gui was looking (er_ages.txt in the old model). They belong in sites.txt now.  
lisa

**Comment by ronshaar** [comment]
Lori,
please leave this bug open and I will close it.
Ron.

**Comment by moonshoes87** [comment]
Great, I will leave this alone!  Thanks!

**Comment by moonshoes87** [comment]
This functionality is still missing for Thellier GUI with MagIC 3.  I can try to convert it, or at least remove the menu option so that users aren't trying and failing to use this.  

I'm happy to try to update this to MagIC 3,  but I don't want to step on your toes @ronshaar.

**Comment by ltauxe** [comment]
Lori why don’t you have a stab at it.  I think Ron is too busy?

**Comment by moonshoes87** [comment]
I think this is working now -- @ltauxe, want to give it a test and let me know if anything is functioning differently than you expect?

**Comment by ltauxe** [comment]
This works for me.  I'm closing this issue.
