### ISSUE TITLE
aarm_magic.py & atrm_magic.py

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#191]
aarm_magic.py is not updated to use MagIC data model 3.0.  It still works fine with MagIC data model 2.5.  

Changes needed: Currently aarm_magic.py outputs to rmag_anisotropy.txt and rmag_results.txt.  Presumably these results should be written to specimens.txt instead.  Also, headers need to be switched from 2.5 to 3.0.  

atrm_magic.py has the same issue.

**Comment by ltauxe** [comment]
roger that.  I’ll take a look when I have a moment.  
lisa

**Comment by moonshoes87** [comment]
All data should go into specimens.txt, one line that combines RmagSpecRec and RmagResRec.

**Comment by moonshoes87** [comment]
@ltauxe, aarm_magic and atrm_magic now take the -DM switch (defaulting to MagIC 3).  I've tried them with the example data_files and they seem correct, but If you could have a look as well that would be great.  Also, I didn't have a sample file to check that aarm_magic works with the -crd option, so that would be particularly worth looking at.

Should azdip_magic also be updated to use 3.0?

**Comment by moonshoes87** [comment]
@ltauxe, I've created a separate issue for updating azdip_magic.  If you have the chance to test out aarm_magic and atrm_magic with MagIC 3, and find they work as expected, you can close this issue!
