### ISSUE TITLE
Python 3 orientation_magic bug

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#193]
2) When using “calculate gepgraphic/tilt correction…” from pmag_gui I get:
  File "/Users/ronshaar/PmagPy/dialogs/pmag_basic_dialogs.py", line 3149, in on_m_calc_orient
    ran_successfully, error_message = ipmag.orientation_magic(or_con, dec_correction_con, dec_correction, bed_correction, hours_from_gmt=hours_from_gmt, method_codes=method_codes, average_bedding=average_bedding, orient_file='demag_orient.txt', samp_file=samp_file, site_file=site_file, input_dir_path=self.WD, output_dir_path=self.WD, append=append)
  File "/Users/ronshaar/PmagPy/pmagpy/ipmag.py", line 4493, in orientation_magic
    if var != "":
NameError: name 'var' is not defined

**Comment by ronshaar** [comment]
Fixed. 
In Python 3 we can use exec to assign values to local variables but they need to declared first.

**Comment by moonshoes87** [comment]
@ronshaar, a clarification about being able to assign variables using exec in Python 3:

You actually cannot assign a “local” variable using exec.

>>> def f():
...     a = 1
...     exec("a = 3")
...     print(a)
... 
>>> f()
1
>>> 

So, in that case, declaring the local variable first just means that you end up using that first declared value.  You can still set global variables with exec, though:

>>> a = 1
>>> exec("a = 3")
>>> a
3

Exec also still works for setting things, like wx.SetBackgroundColour, but it’s definitely something to be cautious of.  

So, what was happening in the code fix that you did in c35921c is that the variable was being initialized to ‘’ but couldn’t be re-set by exec.  

Fortunately, exec wasn’t really necessary in this function anyway.  Here’s my update:  b7c514d.  I’ve tested it with a modified version of the example file in data_files/orientation_magic (modified to include some additional headers and make sure we are hitting everything), and it seems to work correctly.  Let me know if you find that this doesn’t work the way you expect!

**Comment by ronshaar** [comment]
Thanks Lori.
You are totally correct about the exec. Im happy you found this bug.  My mistake was that I didn’t understand that   exec behaves differently inside a definition:
>>> a=1;exec("a=3");print (a)
3

 but 

>>> def f():
...     a=1;exec("a=3");print (a)
... 
>>> f()
1

Thanks !!
Ron.
