### ISSUE TITLE
Confusion on the cit_magic.py volume and weight conversion code

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#195]
@Caoimhinmg I am using cit_magic.py to convert some data files from Scott Bogue at Occidental College and I am a bit confused by the weight/vol moment to magnetization conversion code.

First, the help says the volume/weight can be set to gm, kg, cc, or m3, but only cc or m3 are used in the following code (if not cc or m3, defaults to cc). I'll remove the weight options in the help decription for now.

Then there is this code:

```
if vol!=1.0:
            if norm=='cc':units="1"
            if norm=='m3':units="2"
            SpecRec['weight']=""
            if units=="1" or "":
                SpecRec['volume']='%10.3e'%(vol*1e-6)
            else:
                SpecRec['volume']='%10.3e'%(vol)
        else:
            if norm=='cc':units="1"
            if norm=='m3':units="2"
            SpecRec['volume']=""
            if units=="1" or "":
                SpecRec['weight']='%10.3e'%(vol*1e-3)
            else:
                SpecRec['weight']='%10.3e'%(vol)
```

I'm not sure why the "norm" variable is converted to "units" variable, but my main question is why (I'm not familiar with the Berkeley convention), if the vol is set to 1.0, then use normalization by weight instead (but still using the volume info in the conversion).

Also conversion from cc (cm3) to m3 should be a factor of (1/100)^3 = 1e-6.

Bogue uses 1.0 in the volume to indicate volume not given, but I still think in that case he would want the moment converted to some standard (2.5cm^3 would be good) volume.

Enlightenment on this issue would be appreciated. Thanks.

**Comment by Caoimhinmg** [comment]
Hey @njarboe, I have no idea what is going on with this piece of the code, I've just never touched it. It's basically still hanging around from an earlier era. I think part of the challenge is that the field volume/weight is the same in CIT convention and different in MagIC so the handling of this is a bit strange. I'd just rewrite it such that the user specified units either volume or mass and then convert whatever I get to MagIC standard and get it in the right field. Plain and simple I think this is just a bug I never caught as most of my work has been on directional data in Demag GUI. I'll see what I can do to rewrite this whole section this weekend or this week.

**Comment by njarboe** [comment]
Scott Bogue at Occidental, who has the same system, uses 1.0 because he does not care about the magnetization. Jonathan Glen in an email does care about the magnetization and puts in the volume. He explained to situation to me thus:

I believe Scott routinely puts in 1 because if the samples get mixed up its very difficult to fix the files.  Since Magnetizations is very important for my potential field work, I always put the right value in and triple-check the order of my samples to make sure they don't get mixed up.  I am not sure what a typical Cal tech user does.  One other thing you should be aware of is that the .rmg file has a mistake in it.  The column labeled Moment is really Magnetization (you can confirm this by calculating it from the component values of moment).

I think if the user puts 1.0 because the mass/volume is unspecified, we should honor that and only write out the moment, not put in the wrong magnetization with volume or mass 1.0. A cleaner way to do this would be to put an option flag of, say -mo, for moment only and don't calculate and set the magnetization in that case. This could be a check box in the pmag-gui import interface. What do you think. If you could set it up this way, that would be great.

**Comment by moonshoes87** [comment]
@njarboe, @Caoimhinmg, was this issue ever resolved?  I can implement the Pmag GUI portion if so.

**Comment by Swanson-Hysell** [comment]
This issue still needs to be dealt with and relates to different labs dealing with setting up their header files in different ways. At present, the code is dealing with things such that when the value is set to 1.0 it isn't improperly interpreting that as a real value. Instead it is treating it as a dummy value that is disregarded. We are following the same procedure as Scott such that the code is probably assigning things to ```measurement_magn_moment``` with:

```
M='%8.2e'%(float(line[31:39])*vol*1e-3) # convert to Am2
```

and

```
MeasRec['measurement_magn_moment']=M
```
 @njarboe can you send along some of Jon Glen's data for us to look at? We need to see the .sam, sample files and .rmg files to figure out how to better deal with this. I think that a flag to chose whether the measurement is assigned to moment or magnetization makes sense.

@moonshoes87, Can you explain to me what is going on with their being both **conversion_scripts** and **conversion_scripts2** folders?

**Comment by moonshoes87** [comment]
conversion_scripts2 translates magnetometer files into MagIC 2.5, which pretty much no one should be doing at this point.  However, we didn't want to completely remove that functionality in case someone does need it for whatever reason.  conversion_scripts contains all of the scripts that translate magnetometer files into 3.0.

Both dev_setup.py and the pip version of PmagPy still install both the 2.5 and 3.0 versions of the import scripts.

**Comment by njarboe** [comment]
@Swanson-Hysell @Caoimhinmg 
I have queried Jonathan for some example measurement data files and will forward them when I receive them.

Another issue in resolving all of the variations on the Caltech format is the use of mT or Oe. The document we have in the PmagPy github (included below) describing the format says that the AF units are in mT but both the USGS and MIT use Oe. Ben Weiss told me that the "official" Caltech format uses Oe when I told him that we use mT. Do you know where that data format description comes from? Maybe we need a group email between MIT, Caltech, USGS, Berkeley, Occidental, (others?) to hash it out. We could also have a -lab flag that would set defaults based on the lab, if people won't standardize. 

[sample_formats.pdf](https://github.com/PmagPy/PmagPy/files/1533159/sample_formats.pdf)

**Comment by moonshoes87** [comment]
@njarboe, what is the status here?  Do we need to do work on the CIT format conversion, or has this been cleared up?

**Comment by moonshoes87** [comment]
I am closing this for now.
