### ISSUE TITLE
save pmag tables breaks with Demag GUI data model 2, python3

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#199]
Save Pmag tables in Demag GUI data model 2, Python 3:

    demag_gui.py -WD /Users/ronshaar/Dropbox/pmag-users/Nicole/GH-Pmag-Nicole-Python3Test/MagIC
      File "/Users/ronshaar/PmagPy/programs/demag_gui.py", line 5792, in on_menu_make_MagIC_results_tables
        self.On_close_MagIC_dialog(dia)
      File "/Users/ronshaar/PmagPy/programs/demag_gui.py", line 4987, in On_close_MagIC_dialog
        ipmag.specimens_results_magic(coord=coord, vgps_level=vgps_level, DefaultAge=DefaultAge, avg_directions_by_sample=avg_directions_by_sample, avg_by_polarity=avg_by_polarity, use_criteria=use_criteria)
      File "/Users/ronshaar/PmagPy/pmagpy/ipmag.py", line 3905, in specimens_results_magic
        PmagSiteRec = pmag.lnpbykey(siteD, 'site', key)
      File "/Users/ronshaar/PmagPy/pmagpy/pmag.py", line 3805, in lnpbykey
        rec['dec'] = float(rec[key1 + '_dec'])
    TypeError: 'bool' object is not subscriptable

**Comment by moonshoes87** [comment]
Here is the source of this bug in ipmag.specimens_results_magic.  It results from a faulty translation from Python 2 --> Python 3:

    ...
          sd = pmag.get_dictitem(SiteNFO, 'er_site_name', site, 'T')
            if len(sd) > 0:
                sitedat = sd[0]
                if not avg_all_components:  # do component wise averaging
                    for comp in Comps:
                        # get all components comp
                        siteD = pmag.get_dictitem(
                            tmp1, key + '_comp_name', comp, 'T')
                        # remove bad data from means
                        siteD = [
                            x if 'specimen_flag' in x and x['specimen_flag'] == 'g' else True for x in siteD]
                        siteD = [x if 'sample_flag' in x and x['sample_flag']
                                 == 'g' else True for x in siteD]
                        if len(siteD) > 0:  # there are some for this site and component name
                            # get an average for this site
                            PmagSiteRec = pmag.lnpbykey(siteD, 'site', key)

In the course of trying to remove bad records from siteD, you end up with a list that mixes True and dictionaries.  In the original Python 2 code, filter and lambda were used instead of a list comprehension.  


Anyway, I've changed it:

          sd = pmag.get_dictitem(SiteNFO, 'er_site_name', site, 'T')
            if len(sd) > 0:
                sitedat = sd[0]
                if not avg_all_components:  # do component wise averaging
                    for comp in Comps:
                        # get all components comp
                       siteD = pmag.get_dictitem(
                            tmp1, key + '_comp_name', comp, 'T')
                        # remove bad data from means                                                                                 
                        quality_siteD = []
                        # remove any records for which specimen_flag or sample_flag are 'b'                                          
                        # assume 'g' if flag is not provided                                                                         
                        for rec in siteD:
                            spec_quality = rec.get('specimen_flag', 'g')
                            samp_quality = rec.get('sample_flag', 'g')
                            if (spec_quality == 'g') and (samp_quality == 'g'):
                                quality_siteD.append(rec)
                        if len(siteD) > 0:  # there are some for this site and component name    
                           # get an average for this site
                            PmagSiteRec = pmag.lnpbykey(siteD, 'site', key)

**Comment by ltauxe** [comment]
great sleuthing.  thanks
