### ISSUE TITLE
File uploaded to MagIC from the MIT group crashes pmag_gui  in OSX 2.1.1 and developer most recent version

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#201]
Attached is the MagIC text file, but it should be the same as you get for version 3 of the Weiss 2017 contribution on the MagIC homepage (first on the list at this moment). 
[magic_contribution_11943.txt](https://github.com/PmagPy/PmagPy/files/1023011/magic_contribution_11943.txt)
The pmag_gui developer error is:

pmag_gui.py 
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
-I- Fetching output frame
-I- Fetching output frame
-I- Read in any available data from working directory
-I- Using cached 3.0 data model
-I- Using cached method codes
-I- Using cached vocabularies
-I- Importing suggested vocabularies from https://earthref.org
-I- Using cached suggested vocabularies
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Borlina/criteria.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Borlina/ages.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Borlina/images.txt
-I- running python script:
 demag_gui.py -WD /Users/njarboe/Dropbox/MagIC/people/Borlina
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Borlina/criteria.txt
-I- can't find zeq_gui_preferences file, using defualt default
data model: 3.0
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Borlina/criteria.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Borlina/ages.txt
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/pmag_gui.py", line 518, in on_run_demag_gui
    evt_quit=DemagGuiExitEvent)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 222, in __init__
    self.Data,self.Data_hierarchy=self.get_data() # Get data from magic_measurements and rmag_anistropy if exist.
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 3527, in get_data
    dec=float(rec["measurement_dec"])
TypeError: float() argument must be a string or a number, not 'NoneType'

I did not try to debug this error but I don't think "measurement_dec" is in the 3.0 measurement table.

There is a different error when using 2.1.1, but I am hoping we soon update the standalones to 3.0 and am not worrying about that too much except that is the version people are using.

**Comment by moonshoes87** [comment]
Ok, I am debugging (on master branch, Python 3, and data model 3).

**Comment by moonshoes87** [comment]
The problem came because null values can be None, '', or np.nan.  I added a function to new_builder that correctly evaluates all of those values to null.

**Comment by moonshoes87** [comment]
I fixed it in the Python2 branch also.
