### ISSUE TITLE
OS X frozen binary for Python 3

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#202]
We want to make the standalones in Python 3.  I need to figure out if there are any differences with doing this in Python 2 vs. Python 3.  As the master branch has become relatively stable, this is the blocker for creating new OS X standalones.

**Comment by njarboe** [comment]
Looking forward to having the standalones on the main development branch again. Let me know how I can help. I can run the Python 3 standalone pmag_gui on some data I'm familiar with before we release it to the public.

**Comment by moonshoes87** [comment]
py2app *should* be compatible with Python 3.  However, it doesn't seem to work with 3.6.  

So I downgraded to 3.5, which fixed some problems.

Then I ran into a LOT more problems.  

Those are mainly documented [here](https://stackoverflow.com/questions/44169646/py2app-failing-with-anaconda-python-3) and [here](https://stackoverflow.com/questions/44190269/py2app-with-anaconda-python-3-missing-constraints-error).  I don't have solutions yet.

I'm going to try using a non-Anaconda Python 3 and see if I run into fewer (or at least different) obstacles.

**Comment by moonshoes87** [comment]
Using a different Python 3 (Enthought EDM) results in the same 'missing constraints' error.  So this is a more systematic issue.

**Comment by moonshoes87** [comment]
Pyinstaller was able to produce a minimal working wxPython python 3 frozen binary.  So I'm trying with that for now.  

This does require pulling pyinstaller from develop:

https://github.com/pyinstaller/pyinstaller/issues/2434

And I am now stuck for the real GUIs on this issue:

https://github.com/pyinstaller/pyinstaller/issues/2135

**Comment by moonshoes87** [comment]
monkey patch for pyinstaller with EDM:

found:  /Users/***/anaconda/python.app/Contents/Resources/qt_menu.nib

try putting it here:  /Users/**/.edm/envs/py2app-python3/Resources/Python.app/Contents/MacOS/../../../../python.app/Contents/Resources

so it is now:   /Users/***/.edm/envs/py2app-python3/python.app/Contents/Resources/qt_menu.nib/

And it can, apparently, be found.

Now pyinstaller runs without errors.  However, no GUI shows up when I try to open it.

**Comment by moonshoes87** [comment]
Looks like I need Pyside, which is only compatible with Python 3.4.  sigh.

**Comment by moonshoes87** [comment]
pip install PySide.whl (downloaded)

pip install delocate: https://github.com/matthew-brett/delocate

**Comment by moonshoes87** [comment]
Now let's try Anaconda with pyinstaller.

First, install develop version of pyinstaller:  pip install git+https://github.com/pyinstaller/pyinstaller.git

Minimal script non-windowed with matplotlib import --> success

Minimal script windowed with matplotlib --> success

Magic GUI --> pyinstaller runs without substantial errors, but then lots of SandboxViolations in console.  Progress.

**Comment by moonshoes87** [comment]
Something in self.add_fit is breaking things in Demag GUI.  It isn't self.user_warning.  Seems this may be a matplotlib issue?

**Comment by moonshoes87** [comment]
It is a matplotlib issue.  Trying with some different versions of matplotlib:

Newest version (2 something) --> fails

1.5.3 --> still fails

1.5.2 --> not available

**Comment by moonshoes87** [comment]
So, with these specifications, everything works except actually showing a minimal plot:

pyinstaller # latest from develop as of 6/5/17.  must use develop branch or else breaks with wx
python # anaconda 3.5 or 3.6
matplotlib # 2.2, 1.5.3, or 1.5.1

Error output:

    /Users/***/Python/PmagPy/dist/minimal_matplotlib ; exit;
     ~ /Users/***/Python/PmagPy/dist/minimal_matplotlib ; exit;
    /var/folders/qb/3td4bl3s2pz__jc94hp7z2c40000gn/T/_MEIm5bXgl/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
    /var/folders/qb/3td4bl3s2pz__jc94hp7z2c40000gn/T/_MEIm5bXgl/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
    Intel MKL FATAL ERROR: Cannot load libmkl_avx2.dylib or libmkl_mc.dylib.
    logout


https://github.com/scikit-learn/scikit-learn/issues/5046  # info on the Intel MKL error

Looks like there is a MKL library error.  Trying again after `conda install nomkl`:

Minimal matplotlib script works!!!  And so does demag_gui build.  There will likely be a performance hit for calculations (not using MKL), but still.

**Comment by moonshoes87** [comment]
Install anaconda python 3.

To build:  

    pip install git+https://github.com/pyinstaller/pyinstaller.git
    conda instal nomkl

Make the .spec file:

    pyi-makespec --onefile --windowed --icon=.\programs\images\PmagPy.ico  --name=PmagGUI .\programs\pmag_gui.py 

add the following to the resulting pmag_gui.spec file:

    files = [
         ('/Users/***/PmagPy/pmagpy/data_model/*.json', './pmagpy/data_model/')
    ]

    ...
    a = Analysis(['programs/pmag_gui.py'],
        ...
        datas=files,
    ...

Then run:

    pyinstaller pmag_gui.spec

This will create pmag_gui.app in PmagPy/dist.

**Comment by njarboe** [comment]
I have run the pmag_gui that you linked in your dropbox and it runs on my system. I can see data with demag_gui. When I try to create an upload file with these MagIC files:
[HagstrumMagICFiles.zip](https://github.com/PmagPy/PmagPy/files/1053827/HagstrumMagICFiles.zip)
the program hangs. 

I also do not see a console window for looking at the error and warnings. Does the consolw=e exist for you @moonshoes87 ?

**Comment by moonshoes87** [comment]
I just replaced both GUIs on Dropbox with version that do show a console window.  Now I'll have a look at the upload problem.

**Comment by moonshoes87** [comment]
I fixed the upload issue and another problem or two.  An updated Pmag GUI is synching on Dropbox now.  Let me know what else you find!

**Comment by moonshoes87** [comment]
@njarboe, from your testing, do you think the Python 3 OS X standalone is ok to be released?  I technically have one more week of work before going on leave, so I'm trying to wrap up loose ends as much as possible.

**Comment by njarboe** [comment]
@moonshoes87, I have been using the new pmag_gui stand-alone to look at some data. Looks good so far. I just opened a new issue on the gui problems in the demag_gui, but that is probably an on issue and not related to the new code. I am leaving to do some field work tomorrow and won't be back until Sunday/Monday. If you are out for a while starting next week I would say you should push the new standalones to the public site by Friday. Thanks for the hard work.

**Comment by moonshoes87** [comment]
Thanks @njarboe.  I will release OSX standalones by the end of the week.  Please create new issues for anything else weird that comes up!  Enjoy your field work :)
