### ISSUE TITLE
Windows standalones for Python 3

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#203]
As with py2app, this may or may not be significantly different in Python 3.

**Comment by Caoimhinmg** [comment]
This is going to be a bit annoying having to set up a python environment in Windows again, I'll see what I can do this weekend. I'll let you know when it's all up @moonshoes87.

**Comment by moonshoes87** [comment]
Well, it is going very, very slowly for OS X.  So no pressure ; )

**Comment by moonshoes87** [comment]
I made a Windows release, but didn't really have a chance to test it at all.  If someone can check it out, that would be great:  https://github.com/PmagPy/PmagPy-Standalone-Windows/releases/tag/3.0.0

It is off the master branch and using Python 3.  If it is super broken, maybe someone can take it down?
