### ISSUE TITLE
PmagPy translation of 2.5 --> 3.0 needs proper disclaimers, and/or to crunch together some records

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#204]
Note for Lori: with Crowne data

**Comment by moonshoes87** [comment]
@njarboe, we discussed these data a bit in our meeting two weeks ago.  You were suggesting that we shouldn't end up with multiple records for each sample after translating from MagIC 2 to MagIC 3.  However, multiple records are also created when using the MagIC upgrade tool:

PmagPy translation:

![screen shot 2017-06-07 at 11 31 51 am](https://user-images.githubusercontent.com/1836578/26895002-f3aeb6ee-4b74-11e7-8fd9-0ca6a62683c2.png)

MagIC translation:

![screen shot 2017-06-07 at 11 32 24 am](https://user-images.githubusercontent.com/1836578/26895016-05986ea4-4b75-11e7-88af-3f29fa9b61fa.png)

I think most of the differences shouldn't be too important, but I agree that we should encourage users to mostly use the upgrade tool on Earthref.  

In any case, I am planning to close this issue and not try to squash the sample records together.  @njarboe, let me know if you see this differently.

**Comment by moonshoes87** [comment]
I am adding a clarifying warning and an option to go straight to the Earthref upgrade tool, also.

**Comment by njarboe** [comment]
@moonshoes87  Looks like the MagIC translation puts the data together but still has two lines (except for the description) while the PmagPy has different fields filled out in each line. I'm not clear on what we mean when there are two rows for the same sample name as sample name should be unique ( @rminnett may have some idea ).

**Comment by moonshoes87** [comment]
It was my impression that sample name (or any other name level) does not have to be unique in the new data model....

**Comment by rminnett** [comment]
Other than the description, are these two rows identical? If not, that's the reason they won't fit in a single row in the 3.0 data model. If they are, I need to take another look at the upgrade tool and see why they didn't get merged at the end.

**Comment by moonshoes87** [comment]
There are a few different elements.

It looks like row 1 comes from pmag_samples and row 2 comes from pmag_results.

this isn't nicely formatted, but here:

	citations	cooling_rate	criteria	description	        geologic_classes	        geologic_types	int_abs	int_abs_sigma	int_abs_sigma_perc	int_n_specimens	lat	lithologies	lon	method_codes	result_quality	result_type	sample	site	software_packages	specimens
    sample																				
    CP1	This study	4.28e+11	None	paleointensity mean	Archeologic	Ceramic	4.61e-05	8.25e-07	1.79	2	31.7354	Not Specified	35.2039	IE-TT:LP-AN-TRM:LP-PI-ALT-PTRM:LP-PI-BT-IZZI:L...	g	None	CP1	Crowne Plaza VI-VII	thellier_gui.pmagpy-3.9.1-5:pmagpy-3.9.1-5	CP1-A:CP1-B
    CP1	This study	4.28e+11	ACCEPT	Paleointensity;V[A]DM;CP1, Paleointensity; V[A]DM	Archeologic	Ceramic	4.61e-05	8.25e-07	1.79	2	31.7354	Not Specified	35.2039	IE-TT:LP-AN-TRM:LP-PI-ALT-PTRM:LP-PI-BT-IZZI:L...	None	i	CP1	Crowne Plaza VI-VII	thellier_gui.pmagpy-3.9.1-5:pmagpy-3.9.1-5	CP1-A:CP1-B

criteria, result_quality, result_type, and description are different.
