### ISSUE TITLE
core_depthplot.py error

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#207]
core_depthplot error (in _PmagPy.ipynb)

    -W-  <class 'IsADirectoryError'> [Errno 21] Is a directory: './'

**Comment by moonshoes87** [comment]
Looks like core_depthplot hasn't been updated to MagIC 3....

**Comment by moonshoes87** [comment]
I've gotten rid of the IsADirectory error and updated core_depthplot to MagIC 3 (at least so that the example in _PmagPy.ipynb works).  @ltauxe, when you have time, can you test out core_depthplot to see if it works as you expect with MagIC 3?

**Comment by ltauxe** [comment]
also agm_magic

**Comment by moonshoes87** [comment]
@ltauxe, I've created a new issue for agm_magic.  If you get a chance to test out core_depthplot with MagIC 3 files and don't find any problems, you can close this issue!
