### ISSUE TITLE
update agm_magic to MagIC 3

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#213]
also make sure you update the agm_magic example in the cookbook and _PmagPy.ipynb

**Comment by ltauxe** [comment]
I fixed agm_magic but not the cookbook or notebook yet.

**Comment by moonshoes87** [comment]
I just checked this and agm_magic is not currently working.  It has been renamed agm_magic2, and it looks like it was partially but not fully converted to work with MagIC 3.  I am pushing a small fix to make sure it still works with MagIC 2.  @ltauxe,  Do you want to finish converting this to work with MagIC 3, or do you want me to?

**Comment by ltauxe** [comment]
oh - i was using it happily.  i’ll look into it. lisa

**Comment by moonshoes87** [comment]
Taking this on.

**Comment by moonshoes87** [comment]
@ltauxe, agm_magic wasn't properly skipping some of the metadata rows.  It now seems to work on the data you gave me.  Give it a try and then close this issue if it works.

**Comment by ltauxe** [comment]
yes now agm_magic is working EXCEPT that the output files *_specimens.txt, etc. are being put in the directory in which the program is launched and not in the working directory as specified by -F.  and -WD doesn't seem to help.

**Comment by moonshoes87** [comment]
ok I'll fix this

**Comment by moonshoes87** [comment]
Ok, it now works like this:

by default, output files are written to your current directory

if you specify -WD, all output files will be written to that directory

if you specify -F path/to/file.txt, the measurements file will be written to that custom file (and likewise with -Fsp etc.).  

Test it out and let me know if it is as expected.
