### ISSUE TITLE
Download of Mac Standalone is very slow

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#228]
I am downloading the current Mac standalone and it seems quite slow. My connection reads 14 Mbps using fast.com and the download has completed 100 MB in 10 minutes. Do you think there has been new restrictions on bandwidth from github?

**Comment by moonshoes87** [comment]
I just tried downloading it, and I got the whole thing in 3 minutes or less (1.5 - 1.7 MB/sec, according to Safari).  Not sure why yours is going so slowly, if it isn't a bad internet connection....

**Comment by njarboe** [comment]
Tried again and seems better now. Not sure what the problem was.
