### ISSUE TITLE
Geochronology Method (GM) is not an option when adding method codes to the location table. 

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#229]
Geochronology Method (GM) is not an option when adding method codes to the location table. 
![screen shot 2017-06-20 at 1 07 50 pm](https://user-images.githubusercontent.com/1278789/27353757-07b8dc88-55ba-11e7-94ab-e497ab902952.png)

**Comment by moonshoes87** [comment]
Great.  Are geochronology methods needed at any additional levels?

**Comment by moonshoes87** [comment]
@njarboe, I believe this is fixed so I am closing the issue.  Let me know if I have missed something!

**Comment by njarboe** [comment]
Sorry I did not see your previous comment. Geochronology method codes could be at any level, but are required at the site level. Maybe you already added them at all levels, but I'll reopen in case you have not.
