### ISSUE TITLE
Help button does not work in Mac OX standalone

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#230]
![screen shot 2017-06-20 at 1 26 35 pm](https://user-images.githubusercontent.com/1278789/27354364-2be5e41e-55bc-11e7-98b5-755ad0859f29.png)

**Comment by moonshoes87** [comment]
Should just need to update .spec files to be able to find the html.

**Comment by moonshoes87** [comment]
I have fixed this locally, and will be making a new standalone release soon
