### ISSUE TITLE
demag_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#232]
This program fails to produce any plots if sites can not be associated with specimens.  it also seems to treat sample and site names that look like integers as integers and not strings.  

Here is a folder  with data that "should" work but it doesn't.  

[Dubois_MagIC.zip](https://github.com/PmagPy/PmagPy/files/1110628/Dubois_MagIC.zip)

HELP!

**Comment by Caoimhinmg** [comment]
Oops saw the email before the issue, here's a copy of my last message:

Okay I have applied a patch to master. Basically it checks for empty or improperly propagated fields in the necessary meta data of measurements and replaces the stuff that just didn't work out with the 'unknown' place holder. This allows the data to still be viewed but the data hierarchy is obviously not preserved and will make it basically impossible to extract some other data that needs that hierarchy. It seems as if the code was just not ready for meta data that was all numbers it seems to have caused havoc in the data propagation code of the Contribution object as well as in Demag GUI itself.

This is a non-ideal solution as it does mess up some functionality and doesn't really address the problem so much as circumvent it so hopefully it can just be temporary. I'd have done better, but it's 9:42 and I'm tired.

I'm cc-ing Lori now as if this can be fixed anywhere inside the Contribution object is the best spot as it handles the data read in for data model 3 and it seems it is pandas that is causing the files to read in the meta data as float or int objects. If anyone wants to mess with my patch it's lines 3352-3356 of Demag GUI and I commented out 3381-3390 as they don't do anything now.

**Comment by moonshoes87** [comment]
Yes, I should be able to make sure names are read in as strings, which should be easy.  I hope to do this tomorrow.  Baby Eleanor has arrived, though, so no absolute promises :)

**Comment by ltauxe** [comment]
thanks to all for helping track this down.  I thought it was something like the fact that Shelby’s samples are all numbers - of course we could change that, but i don’t think that is unusal and should be possible.  

lisa

**Comment by moonshoes87** [comment]
@Caoimhinmg, @ltauxe, I haven't been able to get to this.  If one of you wants to make sure that names are string-i-fied in the MagicDataFrame object, please go ahead!  We are having lots of busy baby times around here :)
