### ISSUE TITLE
ipmag.combine_magic.py does not work as advertised

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#237]
The output file does not include the directory name as specified either through -F or through -WD.  it is just the file name in the current directory.

**Comment by moonshoes87** [comment]
I will check this out.

**Comment by ltauxe** [comment]
My old combine_magic should work just fine - not sure what happened to it

**Comment by moonshoes87** [comment]
If I remember correctly Combine_magic required some small updates to work with MagIC 3.  I believe I've fixed this issue now with 12c3a3bcd4046c24cef45fd897f8cab4f26190c2
