### ISSUE TITLE
Problem with pandas not being installed in the Windows version of PmagPy

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#240]
Courtney Sprain would like to use PmagPy to analyze her data but is having some problems with the Anaconda and pip install on Windows.  (see info below)

What can I do to help solve this problem? I will update my Windows test system to see if I get the same error, but was wondering if this is a known issue already. 

------
Hi Nick,

I've recently installed pmapy etc. on a new laptop and tried to use bgc_magic and pmag_gui to convert bgc files to magic format. Neither work and I get the same error message in both cases. I've attached the error message below. if you have any idea how to fix, I would be most appreciative.

Thanks,
Courtney

![bgc_magic_error](https://user-images.githubusercontent.com/1278789/30341717-ee28292a-97ab-11e7-9afb-05930effce05.PNG)

[RJ17-1.1a.txt](https://github.com/PmagPy/PmagPy/files/1296985/RJ17-1.1a.txt)

**Comment by moonshoes87** [comment]
I don't think this is a problem with pandas, but most likely with an earlier import failing and causing pandas not to be imported, thus leading to the name pd not being defined.  I'm looking into it.

**Comment by njarboe** [comment]
It works on my recently installed Windows 10. Should I tell her to re-install pmagpy, as per the cookbook?:
To uninstall either, use the command: pip uninstall pmagpy or pip uninstall pmagpy-cli
If you run into trouble, use pip to uninstall both pmagpy and pmagpy-cli, then try again to install first pmagpy and then pmagpy-cli.

**Comment by moonshoes87** [comment]
I couldn't reproduce the problem either.  Uninstalling and reinstalling is a good idea.

**Comment by njarboe** [comment]
I'll let you know how it goes and close this issue if that fixes it.

**Comment by moonshoes87** [comment]
@njarboe, any update on this issue?

**Comment by njarboe** [comment]
She has not yet responded to my email suggesting to try uninstalling and installing pmagpy (six days ago). Just sent her a query on if she got it working.

**Comment by moonshoes87** [comment]
I'm closing this issue for now, since we weren't able to reproduce it and haven't heard back from Courtney Sprain.  @njarboe, please feel free to reopen it!

**Comment by njarboe** [comment]
Sent an inquire to Courtney. Will reopen if she still has the same problem.
