### ISSUE TITLE
Demag GUI plots look weird....

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#241]
These plots look improperly formatted:

<img width="610" alt="screen shot 2017-09-18 at 6 23 00 pm" src="https://user-images.githubusercontent.com/1836578/30571739-8d1bb7a8-9c9e-11e7-88f6-15b11f7c581d.png">
<img width="604" alt="screen shot 2017-09-18 at 6 24 12 pm" src="https://user-images.githubusercontent.com/1836578/30571759-a783b546-9c9e-11e7-88eb-894cc47afad7.png">

This is with the Dubois data, which was previously attached to issue #232 .
[Dubois_MagIC.zip](https://github.com/PmagPy/PmagPy/files/1312764/Dubois_MagIC.zip)

**Comment by njarboe** [comment]
One or two step demag is likely to occur in the Dubois data set, as seen here. The tick marks seem too bunched up. Is this what you mean by "improperly formatted"?

**Comment by Caoimhinmg** [comment]
Ah, yes, my old nemesis. This has been a well documented problem which seems to occur with the default plot settings for some data. I have been stumped about it for a while, but as it is a fringe effect dominantly I never put the time into investigating a fix for it. I can take a look through and see about coming up with a new method of generating tick marks I'll let you know if I come up with something.

**Comment by moonshoes87** [comment]
This doesn't necessarily seem urgent, I just noticed it and thought it looked a bit odd.
