### ISSUE TITLE
pmag_gui doesn't work

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#247]
After following all the instructions on the Cookbook, I get this error error with pmag_gui.py 

-I- Importing Pamg GUI dependencies
-I- Starting Pmag GUI - please be patient
This program nees access to the screen.  Please run with a Framework build of python and only when you are logged in on the main display of your Mac.  

This shouldn't happen....

**Comment by moonshoes87** [comment]
If using Anaconda and installing with pip, you must call pmag_gui_anaconda instead of pmag_gui.py.

**Comment by moonshoes87** [comment]
I am closing this issue, @ltauxe let me know if there is still a problem...
