### ISSUE TITLE
Validation in pmag_gui does not check ages correctly

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#248]
Here is the email I sent describing this problem:

Age low and age high are not clear terms. age_low means age younger and age_high means age older. Need to check and fix all database entries.

Some description on the error:
Age younger and older would have been much better but I think we are stuck with this ambiguous wording. I can change the descriptions to be clear at least, but we have used them inconsistently in the database. For old ages, ie 175-185 Ma, the higher number has been put in the age_high column i.e. 185. This is from GPMDB MagIC contribution 13434.

age_low	age_high	age_unit

175	185	Ma

This is how I understood the meaning also, but I don't work with calendar year dates where it seems funny to say age_high is 1200AD and age_low is 1750AD

I set up the ages in Cromwell's Hawaii data with this age convention and "Create MagIC file for upload" gives the error message on the location table - according to the above convention "Create MagIC file for upload" is checking and rejecting the correct convention.
name	row_number	problem_type	problem_col	error_message
Hawaii	0	value	age_high	1843 (age_high) must be >= 2010 (age_low)
Hawaii	0	value	age_low	2010 (age_low) must be <= 1843 (age_high)

Ron's Shaar 2017 contribution 13949 also has this age inversion problem problem
age_low	age_high	age_unit
1400	1500	Years Cal AD (+/-)

so we were not checking this on Dec 12, 2016

I checked one of Ron's older contributions (Dec 31,2014), 12116, and it also has the incorrect age on the sites, although he is missing ages in the location table.

age	age_low	age_high	age_unit
-918	-930 -913	Years Cal AD (+/-)

so I'm not sure if the was ever checked in the old workbook system.

**Comment by rminnett** [comment]
There are two paths we can take on the website:

1. **Age Low/High are bounds in either order:**
    - Remove the validation requirement in the data model that age_low <= age_high.
    - Relax the summarizing so Elasticsearch will still index (1400 AD to 1500 AD) as (450 BP to 550 BP) and not ignore (550 BP to 450 BP).
    - Re-index existing data.

2. **Age Low (BP) <= Age High (BP):**
    - Implement the validation requirement that age_low (in BP) <= age_high (in BP), which is confusing if the age_unit is Years AD.
    - Fix all of the contributions that don't satisfy this.

I vote for 1. to avoid updating lots of existing contributions and to handle future misinterpretations of age_low/age_high, but I don't know if this causes problems with PmagPy or other software that expect age_low/age_high to be in a certain order?

If I implement 1., validation of the age_low and age_high can be relaxed in PmagPy rather than being corrected.

**Comment by moonshoes87** [comment]
Hmm, yes, it seems like removing this validation might be best... all I would need to do in that case is re-cache the updated data model.

**Comment by rminnett** [comment]
Ok, I'll post an updated one here. Other than validation, does PmagPy expect one to be less than the other anywhere?

**Comment by moonshoes87** [comment]
Possibly.  It looks like age_high/age_low might need to be updated in Demag GUI, but I'm not super familiar with that code so I don't know how exactly the ages are used there.  

It also seem that the pmag.convert_ages function might need to be updated.  (It is used in several programs to convert ages to Ma).  

@ltauxe, does this seem reasonable to update?

**Comment by moonshoes87** [comment]
I still need to re-cache the data model, but it looks like this shouldn't be a problem.
