### ISSUE TITLE
KeyError in Thellier GUI when reading in (some) MagIC files

### ISSUE THREAD

**Issue by lfairchild** [PmagPy/PmagPy#249]
I am getting a KeyError when opening MagIC files in Thellier GUI. All data files have been auto-converted to data model 3. Some open without this error. I have attached two example data files (one that is working for me and one that is not).

```
Traceback (most recent call last):
  File "/Users/lukefairchild765/GitHub_files/PmagPy/programs/pmag_gui.py", line 493, in on_run_thellier_gui
    evt_quit=ThellierGuiExitEvent)
  File "/Users/lukefairchild765/GitHub_files/PmagPy/programs/thellier_gui.py", line 356, in __init__
    self.read_criteria_file(os.path.join(self.WD, self.crit_file))
  File "/Users/lukefairchild765/GitHub_files/PmagPy/programs/thellier_gui.py", line 2739, in read_criteria_file
    crit['criterion_value'])
KeyError: 'measurement_step_max'
```
Example data file that gets this error:
[Tauxe_2006.zip](https://github.com/PmagPy/PmagPy/files/1353772/Tauxe_2006.zip)

Data file that opens successfully in Thellier GUI: 
[Zhu-et-al_2008.zip](https://github.com/PmagPy/PmagPy/files/1353769/Zhu-et-al_2008.zip)

**Comment by moonshoes87** [comment]
Thanks Luke, I will check into this.

**Comment by lfairchild** [comment]
These were downloaded directly from MagIC ([Tauxe, 2006](https://www2.earthref.org/MagIC/12742) and [Zhu et al., 2008](https://www2.earthref.org/MagIC/14775)). Thanks for looking into this Lori.

**Comment by moonshoes87** [comment]
Tauxe 2006 uses 'meas_step_max' in the criteria file.  ('measurement_step_max' in 2.5).  Thellier GUI generates acceptance_criteria by calling pmag.initialize_acceptance_criteria.  'measurement_step_max' is missing from those default criteria, hence the `KeyError`.

Measurement_step_max isn't in the display for Thellier GUI's acceptance criteria, but should it be?

Options:

1. Add a default criteria value for measurement_step_max into pmag.initialize_acceptance_criteria. 

2.  Add a default criteria value for measurement_step_max into thellier GUI's method add_thellier_gui_criteria.

3.  Change thellier GUI's method read_criteria_file to add an entry into self.acceptance_criteria for any unexpected criteria found.

If we do any of the above three options, we would need to change Thellier GUI's display to show measurement_step_max.  Or we could just ignore any unexpected criterion -- like measurement_step_max -- entirely.

@ltauxe, @ronshaar?

**Comment by ltauxe** [comment]
yes measurement_step_max should be in Thellier GUI’s acceptance criteria.  so let’s do options 1 and 2?  if 3 is straightforward, then we can do it.  

until that is done, we should just ignore unexpected criteria, perhaps with a warning.  
lisa

**Comment by moonshoes87** [comment]
Ok, I need some help with the defaults:

category: IE-SPEC
criterion_name: measurement_step_max
value:  ?
threshold type:  'high'
decimal: ?

2.  It should be added to the specimen acceptance criteria, right?

**Comment by moonshoes87** [comment]
@lfairchild, you should be able to at least run Thellier GUI on contributions using unrecognized criteria.   I will need to do a bit more digging to figure out how to deal more elegantly with these kind of criteria.

**Comment by lfairchild** [comment]
Great, thanks. The file now opens successfully with the warning `-W- Your criteria file contains measurement_step_max, which is not currently supported in Thellier GUI`.

**Comment by moonshoes87** [comment]
Adding measurement_step_max into Thellier GUI is a bit awkward.  The rest of the IE-SPEC acceptance criteria are SPD statistics which are re-calculated every time new bounds are selected (except for measurements.experiment, which is just used to select only measurements from a thellier type experiment).  I'm not sure how measurement_step_max should be handled here.  Should it be added to the SPD module?  Or used behind the scenes in Thellier GUI to select available measurements?  It obviously isn't recalculated when you change the bounds....  Whatever the solution, I don't think it can be generalized as a way to handle just *any* unrecognized criterion.  

Also, the description of meas_step_max could be clearer ("Step included in calculation, Higher bound").  @rminnet, should this description specify that we are talking about a max temperature?  Or can it also be microwave power?  Either way, a little additional clarity would be helpful.

**Comment by rminnett** [comment]
Yes, I believe specimens.meas_step_min/max are intended to describe lower and upper limits on the parameter that was swept for the experiment and they don't have to be describing just temperature or microwave power. Perhaps @njarboe could help clarify the descriptions next week?

**Comment by njarboe** [comment]
Here is what I have changed the descriptions to:
meas_step_min: The lower bound for the parameter varied during the experiment
meas_step_max: The upper bound for the parameter varied during the experiment

If there are two experiments on a specimen that both use step_min and step_max, then we will just have separate lines for each? How would one know which experiment it was if the specimens.experiments value includes all experiments?

**Comment by moonshoes87** [comment]
After conversation with @ltauxe, we will ignore this!
