### ISSUE TITLE
demag_gui: specimen equal area plot appears with tick marks

### ISSUE THREAD

**Issue by ronshaar** [PmagPy/PmagPy#25]
When demag gui is first loaded, and there is no previous interpretation for the given specimen the specimen equal area plot appears with tick marks

**Comment by Swanson-Hysell** [comment]
Ron, are you still seeing having this issue on the most recent version of the GUI in master? I don't seem to be having the issue any longer.

**Comment by Swanson-Hysell** [comment]
This tick mark issue seems to have been resolved.
