### ISSUE TITLE
new troubles in thellier_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#254]
When importing files in 2.5, thellier_gui is called sio_magic - not sio_magic2.py - so a version 3.0 file is created, messing everything else up down the line.

**Comment by moonshoes87** [comment]
The import is happening in Pmag GUI with data model 2.5?  Or in Thellier GUI with data model 2.5?

**Comment by moonshoes87** [comment]
@ltauxe, this seems to work correctly for me.  If I run Pmag GUI with data model 2, it uses pmag_basic_dialogs which imports sio_magic2 from conversion_scripts2.  If I run Pmag GUI with data model 3, it uses pmag_basic_dialogs_native3 which imports sio_magic from conversion_scripts.  Is this not what you are looking at?

**Comment by ltauxe** [comment]
It is in Pmag GUI when running in model 2.5 - the file created on importing is a data model 3. But let me mess around a bit more.

**Comment by moonshoes87** [comment]
I tried the same thing, and got a 2.5 .magic file.  So I'm wondering what we're doing differently...

**Comment by moonshoes87** [comment]
@ltauxe, let me know if this is still acting up for you.  If not, feel free to close this issue.

**Comment by moonshoes87** [comment]
I'm closing this issue because it seems to be working correctly for me at present, @ltauxe let me know if you have more troubles along these lines.
