### ISSUE TITLE
pmag_gui.py CIT to magic file conversion always averages replicates

### ISSUE THREAD

**Issue by yuempark** [PmagPy/PmagPy#255]
When converting between CIT and magic using the GUI, replicates are always averaged in the output, regardless of which radio button is selected.

**Comment by Swanson-Hysell** [comment]
This must be a new bug. Could you have a look at old version of the stand-along release of the GUI and see what versions do/don't do this? The version of the GUI on my desktop (v 0.33) doesn't average replicates.

**Comment by moonshoes87** [comment]
This seems to be failing in the current version of Pmag GUI.  I can look into it.

**Comment by yuempark** [comment]
after the 8b1e934 above, the radio buttons are switched (i.e. selecting "import all replicates" averages the replicates, but clicking "average replicates" imports all replicates).

**Comment by moonshoes87** [comment]
Haha, oops.  I will fix this.

**Comment by moonshoes87** [comment]
The variable is 'no average', so I got it backwards.  Should work now, though.
