### ISSUE TITLE
Demag_GUI will not save plots

### ISSUE THREAD

**Issue by CourtneySprain** [PmagPy/PmagPy#268]
Current version of Demag_GUI will not save plots in the PmagPy package or standalone. Receive error message "AttributeError: module 'wx' has no attribute 'SAVE'".

**Comment by moonshoes87** [comment]
This is a wxPython 3 --> 4 problem, fixed elsewhere but apparently missed it here.  I will get this fixed shortly.

**Comment by moonshoes87** [comment]
I still need to re-release for pip and the standalones, which I'll do asap since this is core functionality.  It is working again with the developer install now, and I'll get the other releases up shortly.

**Comment by moonshoes87** [comment]
pip release is done.  @CourtneySprain, let me know if this isn't fixed for you!

**Comment by moonshoes87** [comment]
standalones now updated as well (Windows & OS X)
