### ISSUE TITLE
combine_magic problems

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#270]
Lisa's issue Archaeomag_3

Step 1.3 combine_magic

something_specimens.txt
specimens.txt

Doesn't append nicely.  Stub values.  

When you go back to run step 1 a second or third time, things get weird.  

A row with just specimen, sample can be dropped if there is another row.

**Comment by ltauxe** [comment]
Also, combine_magic.py doesn't seem to work at all on the command line.

**Comment by moonshoes87** [comment]
@ltauxe, here's an update on combine_magic.

First, the bug in Thellier GUI that we thought was due to combine_magic issues actually is from a pandas bug which will be fixed eventually.  In the meantime, I wrote in a workaround to prevent the pandas bug from crashing Thellier GUI.

Second, combine_magic still works on the command line for me.  

<img width="826" alt="screen shot 2017-12-05 at 12 23 26 pm" src="https://user-images.githubusercontent.com/1836578/33628944-3489e898-d9b7-11e7-9e80-2e91459b4bf5.png">

If it isn't working on the command line for you, could you send me the error message that you're seeing?

Last, I've added functionality so that combine_magic drops rows that are probably useless (rows where index is not unique AND no values but name/citations/magic_software are filled out).  This should make it much more reasonable to run and rerun combine_magic.  Try this out and see if the workflow feels more reasonable.
