### ISSUE TITLE
measurements.sequence

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#273]
Since measurements.sequence is now a required field for measurements, the conversion scripts should presumably fill it in.

Our conversion scripts already generate measurements.txt with the records in the correct order.  So, in a measurements table with n rows, can the measurements simply be added to each record starting with 0 and ending with n-1?  (or starting with 1 and ending with n) .  

Does anyone see a problem with implementing this into all MagIC 3 conversion scripts?

**Comment by ltauxe** [comment]
no - i guess we need this one.  lisa

**Comment by njarboe** [comment]
When we have online validation, the plan is that, if the sequence is missing, we will add the sequence by using the order in the upload file. The sequence is a signed float so you can start with 1 or 0. Putting them into the scripts is probably a good idea as validation is not happening right now and having the sequence created closer to the original data files reduces the likely hood for mistakes.

**Comment by moonshoes87** [comment]
Great, this is easy to implement anyway.
