### ISSUE TITLE
thellier_magic problems

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#275]
thellier_magic is running into problems at this line:

            pars, errcode = pmag.PintPars(
                thelblock, araiblock, zijdblock, start, end, accept, version=3)

apparently because start/end haven't been correctly set are are still both empty strings.  I'm having some trouble understanding the code that is supposed to set these parameters.

This is one of the last few obstacles to getting make_magic_plots to work correctly again with Python & MagIC 3.

**Comment by moonshoes87** [comment]
It seems that pmag.PintPars doesn't work without a value for start and end.  In Thellier_magic, using data without previous specimen interpretations, no value is set for start or end, so this fails:

            pars, errcode = pmag.PintPars(
                thelblock, araiblock, zijdblock, start, end, accept, version=3)

I tried making `start = 0` and `end = len(zijdblock) - 1,` but this fails later in the code:

                mpars = pmag.domean(araiblock[1], start, end, 'DE-BFL')

with this error:

      File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 315, in main
        mpars = pmag.domean(araiblock[1], start, end, 'DE-BFL')
      File "/Users/nebula/Python/PmagPy/pmagpy/pmag.py", line 2441, in domean
        if indata[end0] != datablock[end]:
    IndexError: list index out of range

Either thellier_magic needs to correctly set start/end, or it needs to fail gracefully and let users know that they need to have prior interpretations to use thellier_magic.  @ltauxe, which of these should happen?

**Comment by ltauxe** [comment]
it should just skip the pintPars part if there are no interpretations.  
lisa
