### ISSUE TITLE
thellier GUI measurement quality

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#277]
should ignore data points with quality marked 'b' for calculations and plot them as x's as in demag gui.

**Comment by moonshoes87** [comment]
This is what @Caoimhinmg was working on in #170.  It is at least partially set up in the current code.  @Caoimhinmg, would you mind giving an update where you got to with this project and what might still need to be done?  

@ltauxe, you might also want to look again at #170 and make sure the whole approach seems right to you.

**Comment by moonshoes87** [comment]
@ltauxe, I am closing this issue in favor of #170.
