### ISSUE TITLE
download_magic with data model 3

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#278]
Download_magic splits up records into Location_1, Location_2, etc.  The problem is, in data model 3, location name isn't necessarily available at the sample, specimen, and measurement level.  

So this line fails to find any records:

                lrecs = pmag.get_dictitem(recs, 'location', loc_name, 'T')

So Location_* folders often are still created but are only populated with contribution, location, and site files.  

This means that some of make_magic_plots doesn't work correctly.

We can either:

- Ditch the Location_1, Location_2 system (simplifies things, but some other issues)
- Have ipmag.download_magic try to propagate location names down to the measurement level (this should work in most cases with valid contributions, but it won't work if intermediate tables are missing or incomplete and it will slow things down)

@ltauxe?

**Comment by ltauxe** [comment]
let’s ditch the many location folders.  (option 1)

**Comment by moonshoes87** [comment]
Ok, splitting into location folders is now a non-default option.  If a user selects it, I do all the propagating of location name down to the measurement level, so that everything can be portioned out into the right folders.
