### ISSUE TITLE
zeq_magic.py

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#281]
This program calls pmagplotlib.plotZ, which works fine, but somewhere in zeq_magic, the axes are being rescaled so that the zijderveld diagram is in the wrong units.  I can't find where that is happening.  please help!

**Comment by ltauxe** [comment]
found where the scaling problem is  happening - somehow when the best fit direction is supposed to get plotted.  I can fix that, but I still have the weird problem that the data get doubled. this happens when it is read in by nb.Contributions.   Here is an example file.  run with zeq_magic.py -f tmp.txt
[tmp.txt](https://github.com/PmagPy/PmagPy/files/1590120/tmp.txt)

**Comment by moonshoes87** [comment]
I think this problem comes from #196

**Comment by ltauxe** [comment]
all fixed (I hope).  multiple sample orientations are allowed and the priorities are set in pmag.set_priorities() with the preferred type selected by get_orient().  updated get_orient to allow data_model=3.
