### ISSUE TITLE
matplotlib API changes

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#286]
We probably can't support matplotlib < 2 and matplotlib > 2.  We should update everything to 2, and make appropriate warnings for users that they should upgrade their matplotlib.  Also, add matplotlib > 2 as a dependency for pip install.

    /Users/***/anaconda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:3260: 
    MatplotlibDeprecationWarning: The ishold function was deprecated in version 2.0.
    b = ax.ishold()

**Comment by moonshoes87** [comment]
Can't do this yet.  Because #250.  matplotlib 2.1 is not available with canopy, and is not the default download for anaconda.  and matplotlib 2.0 breaks with wxPython wxPhoenix.

**Comment by ltauxe** [comment]
NO - contourf doesn't work in matplotlib >2.  we should use matplotlib 1.5.3  until that gets fixed.  hope that doesn't create other problems.  we should probably make a note of that in the cookbook as plot_magmap breaks with matplotlib >2.

**Comment by moonshoes87** [comment]
vgpmap_magic works with matplotlib 2.1, and it calls pmagplotlib.plotMAP which calls contourf.  So the plot_magmap issue #290 must be something else.

**Comment by moonshoes87** [comment]
All the programs that use basemap/matplotlib that are in _PmagPy.ipynb and _PmagPy_3.0.ipynb work correctly with matplotlib 2.1 and basemap 1.0.7

**Comment by ltauxe** [comment]
the plot_magmap problems were: 1) a nasty warning which actually did nothing and 2) jpg output just doesn’t work - have to use png or other.  
I put in an ‘ignore’ command for the warnings and suppressed the jpg option for saving of plots.  
lisa

**Comment by moonshoes87** [comment]
Correction: basemap must be updated to 1.1.0 to work correctly.

Here is the issue with matplotlib/basemap up to date:

    Traceback (most recent call last):
      File "/Users/nebula/Python/PmagPy/programs/plot_magmap.py", line 133, in <module>
    main()
      File "/Users/nebula/Python/PmagPy/programs/plot_magmap.py", line 110, in main
    cs=m.contourf(x,y,Bs,levels=levels,cmap=cmap)
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 536, in with_transform
    return plotfunc(self,x,y,data,*args,**kwargs)
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 3633, in contourf
    xx = x[x.shape[0]/2,:]
    IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Fixed in the latest version of basemap, which can be installed with this command:

    conda install basemap --channel conda-forge

**Comment by moonshoes87** [comment]
Ok, I'm going to add in a warning that users should update to matplotlib 2.1.  This won't yet cause anything to break, it will just provide a heads up.
