### ISSUE TITLE
aniso_magic not working in _PmagPy.ipynb

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#287]

**Comment by ltauxe** [comment]
there are no aniso data in the mcmurdo specimens table.

**Comment by moonshoes87** [comment]
Hmm, well, this used to generate plots…. 

See: https://github.com/PmagPy/PmagPy/blob/master/data_files/notebooks/_PmagPy_3.0.ipynb

**Comment by ltauxe** [comment]
there ARE aniso_s data in McMurdo, but the method of getting method_codes='AE-' was failing.  Now it just gets aniso_s data directly and it seems to work.
