### ISSUE TITLE
zeq_magic NameError

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#288]
New zeq_magic bug:

<img width="3000" alt="screen shot 2018-01-02 at 9 33 43 am" src="https://user-images.githubusercontent.com/1836578/34493287-360f6090-efb9-11e7-959b-a5cb8853256a.png">

@ltauxe, this is from _PmagPy_3.0.ipynb.  Want to take a look, or should I?

**Comment by ltauxe** [comment]
ok NOW it is fixed.  that should have been beg_pcas.
lisa

**Comment by moonshoes87** [comment]
Great -- I figured this was a simple one, but I didn't want to mess with zeq_magic anymore!
