### ISSUE TITLE
implementing an alternative to basemap

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#292]
As @Caoimhinmg brought up in #286, Basemap is no longer being developed and won't be supported after 2020.  See discussion [here](https://github.com/SciTools/cartopy/issues/920).  There is no huge hurry to stop using it, but in the long run we will probably want to use something else.

It looks like [cartopy](http://scitools.org.uk/cartopy/) is the likely heir to the throne.  We should have a look at cartopy and see how much work it will be to make the switch.

**Comment by ltauxe** [comment]
yeah - the guy who developed it died in 2012 or so.  maybe we should look into plotly?  or something else?

**Comment by moonshoes87** [comment]
It sounds like [cartopy](http://scitools.org.uk/cartopy/) is probably the right package to replace basemap. @ltauxe, do you want to have a look at this?  Here is a good place to look: http://scitools.org.uk/cartopy/docs/latest/matplotlib/intro.html

**Comment by moonshoes87** [comment]
@ltauxe, I'm seeing how it goes to convert plot_magmap to cartopy.  So far, it seems doable.

**Comment by ltauxe** [comment]
yes, cartopy looks like a promising option to replace basemap.    I’m reluctant to switch right now for my class, but it certainly can be added to PmagPy. there are only a few mapping programs anyway.  it shouldn’t be a bit deal for, e.g., basemap_magic, the vgp one and plot_magmap.  i can check for all the ones that call basemap.  

but.  is cartopy actively being developed?    and what will we do about matplotlib in general?  
lisa

**Comment by moonshoes87** [comment]
cartopy is actively being developed, and is intended to be a replacement for Basemap.  cartopy is also mean to play nicely with matplotlib, so it actually works similarly to how Basemap does.

**Comment by moonshoes87** [comment]
And matplotlib itself is still being maintained/developed.

**Comment by ltauxe** [comment]
here is a notebook that implements the examples from the cartopy website.  the only one that doesn’t work requires some data set that I didn’t have lying around…   I like it!

lisa

**Comment by moonshoes87** [comment]
Great!  And I already have plot_magmap partially working with cartopy.

**Comment by moonshoes87** [comment]
I just added cartopy_plot_magmap to the repo (d1f0bbcb8c736bb8354bc1059212aebaa1ad05af).  There are some issues with the projections -- cartopy doesn't have hammer, so things look a little different.  Also, some of the alternative models don't look the same (arch3k is all messed up with cartopy).

Otherwise, things are pretty good.

Cartopy:


![cartopy_igrf1800 0](https://user-images.githubusercontent.com/1836578/34790570-ffd71434-f5f6-11e7-8d9a-95ef5b9c43c7.png)

Basemap:
![igrf1800 0](https://user-images.githubusercontent.com/1836578/34790571-fff4a35a-f5f6-11e7-8d4b-4bfe7d16d93e.png)

**Comment by moonshoes87** [comment]
I'm not sure what's causing the white stripe in the cartopy version, though -- missing data?

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87 and @ltauxe. Paul Wessel just gave a talk here and it looks like the new GMT6 is coming with wrappers to python, julia, and matlab/octave. While they are not fully released yet it may be good to use this in PmagPy as users will be more familiar with GMT than other libraries and because the base code is C it should be quite fast. Here's an explanatory [jupyter notebook](https://hub.mybinder.org/user/genericmappingt--try-gmt-python-uhe8x0qq/notebooks/try-gmt-python.ipynb) and their [github page.](https://github.com/GenericMappingTools/gmt-python)

**Comment by ltauxe** [comment]
I have a whole set of python native stuff that reproduces much of what is in GMT (5) [https://github.com/ltauxe/GMT_Notebooks <https://github.com/ltauxe/GMT_Notebooks>] 
but they use basemap in case anyone finds them useful…  

lisa

**Comment by Swanson-Hysell** [comment]
I have started a cartopy branch and have committed within it changes to:

ipmag.equi()
ipmag.plot_pole()
ipmag.plot_vgp()

and have added a make_orthographic_map() function to ipmag.

Things are working pretty well. For example,

```
vgps = fishrot(dec=200,inc=30)
map_axis = make_orthographic_map(central_longitude=200,central_latitude=30)
plot_vgp(map_axis,vgp_lon=vgp_lon_list,vgp_lat=vgp_lat_list,color='red',markersize=40)
```
<img width="350" alt="screen shot 2018-09-26 at 3 03 44 pm" src="https://user-images.githubusercontent.com/4332322/46111905-83cbd500-c19d-11e8-8f40-6840d969fba2.png">

ipmag.plot_pole() is working ok too as in this example:
```
plon = 210
plat = 60
A95 = 5
map_axis = make_orthographic_map(central_longitude=200,central_latitude=30)
plot_pole(map_axis, plon, plat, A95 ,color='red',markersize=40)
```
<img width="350" alt="screen shot 2018-09-26 at 3 15 06 pm" src="https://user-images.githubusercontent.com/4332322/46112270-fe492480-c19e-11e8-872b-7aa1debff091.png">

The only issue being that there is an outline around the entire map that is the color of the A95 ellipse (not sure how to resolve this issue at present).

**Comment by Swanson-Hysell** [comment]
In the cartopy branch, all of the ipmag functions are now updated to use cartopy rather than basemap. Not as much of a hassle as I thought it would be. 

In pmagplotlib, it looks like the only two functions that use Basemap are:

- plot_mag_map()
- plot_map()

@moonshoes87 or @ltauxe could you commit your implementation of those functions using cartopy to the branch?

And then it lives within a number of the programs as well:

- basemap_magic.py (which says it is deprecated and perhaps it should be removed)
- cont_rot.py (which has a rich set of projections that can be flagged that correspond to those available in Basemap)
- and more...

**Comment by moonshoes87** [comment]
@Swanson-Hysell, thanks!  I do notice that there are a few failing tests (you can see these on https://travis-ci.com/PmagPy/PmagPy/builds).  It looks like there is just a misplaced or forgotten quotation mark.  I usually check travis-ci and then run locally any tests that are failing for non-obvious reasons.

@ltauxe, I think you all of the cartopy functions on your machine -- if you want me to fiddle with or commit them to the branch, just send them to me.

**Comment by Swanson-Hysell** [comment]
I fixed that quotation mark in ipmag.equi() that was causing the test to fail. Nice catch! There is still a unit test failing due to the cartopy import. Where does this need to be addressed?

```
    import cartopy
ImportError: No module named 'cartopy'
```

**Comment by ltauxe** [comment]
looks nice - and i had the same problem in the map_points_cartopy  function in pmagplotlib of the color of the outline - i have no idea why.  perhaps the order of operation?  
lisa

**Comment by moonshoes87** [comment]
.travis.yml is where the testing environment is defined.  I added cartopy, so hopefully tests are passing now!

**Comment by Swanson-Hysell** [comment]
I have raised an issue over at cartopy regarding the map data occurring as a color of the outline issue (https://github.com/SciTools/cartopy/issues/1133). It happens with quite simple plots:

```
x = [-149.99, -143.82, -140.38, -140.40, -143.15, -147.54, -152.45, -156.84, -159.59, -159.61, -156.17, -149.99, -149.99]
y = [64.99, 64.07, 61.74, 58.93, 56.53, 55.17, 55.17, 56.53, 58.93, 61.74, 64.07, 64.99, 64.99]

fig = plt.figure(figsize=(8,8))
map_projection = ccrs.Orthographic(central_longitude=200,central_latitude=30)
ax = plt.axes(projection = map_projection)
plt.plot(x, y, color='red', transform=ccrs.Geodetic())
```
![screen shot 2018-09-27 at 10 46 52 am](https://user-images.githubusercontent.com/4332322/46164672-79fcad00-c243-11e8-9cad-5b4a8ed6aba8.png)

**Comment by Swanson-Hysell** [comment]
Note that I am putting minimal examples of using the cartopy functions within the docstrings. These could be pulled out and used in the pmagpy notebook.

**Comment by Swanson-Hysell** [comment]
For what it is worth, I have noticed that the orthographic projection is quite fast to render while the Mollweide is quite slow.

**Comment by moonshoes87** [comment]
Testing environment issues persist, including: https://github.com/SciTools/cartopy/issues/1035

**Comment by ltauxe** [comment]
because you can do a help(ipmag.WHATEVER) in the notebook, we don’t need additional verbiage.  Also demonstrates the value of doc strings.  
lisa

**Comment by moonshoes87** [comment]
Ok, I finally got the testing environment fixed (and in fact, improved!).  All tests are passing now.  I would encourage, where possible, making tests for the new functions.

**Comment by Swanson-Hysell** [comment]
Perhaps you saw this, but based on feedback in this issue discussion (SciTools/cartopy#1133) I was able to fix the weird plotting issue in cartopy that led to the color of the outline issue with this commit that tweaks the ipmag.equi() function (https://github.com/PmagPy/PmagPy/commit/9413b5fa83313760493ead6a8093c896e64d43ba). The workaround is to reversed the order in which the points are being plotted. So changing the example above to be the following (note ```x[::-1], y[::-1]```) works:

```
x = [-149.99, -143.82, -140.38, -140.40, -143.15, -147.54, -152.45, -156.84, -159.59, -159.61, -156.17, -149.99, -149.99]
y = [64.99, 64.07, 61.74, 58.93, 56.53, 55.17, 55.17, 56.53, 58.93, 61.74, 64.07, 64.99, 64.99]

fig = plt.figure(figsize=(8,8))
map_projection = ccrs.Orthographic(central_longitude=200,central_latitude=30)
ax = plt.axes(projection = map_projection)
plt.plot(x[::-1], y[::-1], color='red', transform=ccrs.Geodetic())
ax.set_global()
```
The ax.set_global() command is important because the cartopy default is to only show as much of the map for which there is data — for our purposes I think we want to plot the whole projection.

**Comment by ltauxe** [comment]
polemap_magic.py works just fine now.

**Comment by Swanson-Hysell** [comment]
It was  @Caoimhinmg who put the plot VGP code into demag GUI (calling on ```draw_map()``` in demag_dialogs.py. I am going ahead and having a look at switching it over.

In the pmag.import_cartopy() function, we should have it import ```import cartopy.crs as ccrs``` as well. What is the best way to do this @moonshoes87?

**Comment by Swanson-Hysell** [comment]
@Caoimhinmg, would you be able to have a quick look at this? To make the change in demag_dialogs this is the class that needs to change over to cartopy:

```class VGP_Dialog(wx.Dialog):```

```
    def draw_map(self):
        #set basemap
        self.map = Basemap(projection='moll',lon_0=0,resolution='c',ax=self.eqarea)
        self.map.drawcoastlines(linewidth=.25)
        self.map.fillcontinents(color='bisque',lake_color='white',zorder=1)
        self.map.drawmapboundary(fill_color='white')
        self.map.drawmeridians(list(range(0,390,30)))
        self.map.drawparallels(list(range(-90,120,30)))
```

should be replaced with something along the lines of:

```ipmag.make_mollweide_map()```

and

```
        for dp in data:
            lat,lon = dp['vgp_lat'],dp['vgp_lon']
            XYM=self.map(float(lon),float(lat))
            FC=dp['color'];EC=dp['color']
            if self.selected_pole==dp['name']+dp['comp_name']: marker='D'
            else: marker='o'
            self.map.scatter([XYM[0]],[XYM[1]],marker=marker,edgecolor=EC, facecolor=FC,s=30,lw=1,clip_on=False,zorder=2)
            self.xdata.append(XYM[0]);self.ydata.append(XYM[1])
```

should be the cartopy syntax like in ```ipmag.plot_vgp```:

```
map_axis.scatter(vgp_lon, vgp_lat, marker=marker,
                    s=markersize, color=color, label=label, zorder=100, transform=ccrs.PlateCarree())
```

I tried to implement this change, but am doing something wrong such that the plot is just coming out as an xy-axis:

<img width="986" alt="screen shot 2018-09-28 at 4 16 54 pm" src="https://user-images.githubusercontent.com/4332322/46237536-f2459a00-c339-11e8-8852-74494aa2ce47.png">

**Comment by ltauxe** [comment]
i enabled the mapping part of thellier_gui as cartopy as well as basemap.  there is no checking for version yet and the projection is kind of weird - also there is no "plot by location" option yet.  but it works.

**Comment by Swanson-Hysell** [comment]
For simplicity, in ipmag.py I overwrote all of the functions that previously used Basemap with functions that use cartopy. I think I prefer this approach in terms of simplicity — although there are clear backward capability issues that arise. Is it ok that we keep it this way or should I put the Basemap functions back into ipmag with the the suffix _basemap on them?

**Comment by ltauxe** [comment]
I prefer if you keep the old ones, but rename them _basemap    
that is what I’m doing in pmagplotlib anyway and for the command line programs.  

lisa

**Comment by ltauxe** [comment]
I'm at my wit's end with cartopy and plot_magmap.  I'm sending a notebook illustrates my problem (or at least the most vexing one).   by rotating the central longitude by 27 degrees or more, the contourf function in cartopy just doesn't work (although the contours are just fine, if you plot them.

**Comment by moonshoes87** [comment]
@Swanson-Hysell 

> In the pmag.import_cartopy() function, we should have it import import cartopy.crs as ccrs as well. What is the best way to do this @moonshoes87?

I could add the ccrs import into import_cartopy.  However, I'm wondering if we would rather just do:

    if has_cartopy:
        import cartopy.crs as ccrs
        from cartopy import config
        from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter

as Lisa has it in Thellier GUI, since different elements will be needed depending on the program.

Just importing a module in one file doesn't put it into the global namespace, so ccrs would have to be returned by the function.

**Comment by moonshoes87** [comment]
@ltauxe, it looks like you already did the basemap/cartopy reasonable checks in Thellier GUI, and plot_magmap.  I made some tiny changes in Thellier GUI.  @ltauxe and @Swanson-Hysell , are there other parts of this transition that you want support on?

**Comment by ltauxe** [comment]
just to make sure the demag gui works…  
lisa

**Comment by moonshoes87** [comment]
Great.  I will give everything a good shakedown before we make a new release!

**Comment by Swanson-Hysell** [comment]
I am still not clear on how I should be using pmag.import_cartopy() or taking other approaches to make cartopy installation optional in ipmag. At present, I just had there be these import statements at the top: ```import cartopy``` ```import cartopy.crs as ccrs```

Currently, it looks like the import is done two different ways in pmagplotlib. 

In ```plot_mag_map()``` it is done this way:
```
    has_cartopy, Cartopy = pmag.import_cartopy()
    if not has_cartopy:
       return
    import cartopy.crs as ccrs
```

In ```plot_map``` it is done this way:

```
    try:
        import cartopy
    except:
        print ('This program requires the installation of cartopy')
        return
    import cartopy.crs as ccrs
    from cartopy import config
    from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
    from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
    from cartopy import feature as cfeature
    from cartopy.feature import NaturalEarthFeature, LAND, COASTLINE, OCEAN, LAKES, BORDERS
```

I would rather not have the import statements be within the functions. This seems burdensome to code development and an unnecessary computational expense to reimport a package every time a function is called upon (I am often call these functions over and over within notebooks). Perhaps we could have code like this with most of the import statements or is the pmag import_cartopy function preferable in this context?:

```
    try:
        import cartopy
        import cartopy.crs as ccrs
    except:
        print ('Some plotting functions require an installation of cartopy which was not imported')
```

**Comment by moonshoes87** [comment]
@Swanson-Hysell, totally, feel free to do it that way.  The reason I added a function for the Basemap import is because there are three different ways the import could fail, and thus different relevant error messages -- reproducing that over and over felt a bit repetitive.  Cartopy is (so far!) a simpler import.

I would just consider `except ImportError` instead of a generic `except`, so that we are not masking other types of errors.

**Comment by moonshoes87** [comment]
Oh, and just to respond to one more point -- Python won't reimport a module that's already been imported unless you use importlib.reload.

**Comment by moonshoes87** [comment]
I do think we want to have at least a transitional period where we don't require cartopy, but simply recommend that users install it.  I agree that we should have imports at the top of the module, not in each individual function.  So, either `try/except ImportError` or pmag.import_cartopy should happen at the beginning of ipmag/pmagplotlib/etc..  Does that seem sensible?

**Comment by ltauxe** [comment]
roger that.

**Comment by Swanson-Hysell** [comment]
Sounds good.

**Comment by Swanson-Hysell** [comment]
All should be good in ipmag with the both the cartopy and basemap plotting functions.

I am still having a bit of a hard time trying to implement a successful solution in demag_gui for the VGP map in cartopy. The issue is that previously the code was setup to create a axis object and then set the basemap to that axis. But the cartopy syntax is rather to create a 'geoaxis' object rather than set to a preexisting axis. There is likely a slick workaround, but I haven't yet come upon it.

The VGP viewer is a pretty minor thing in demag_gui so let's just leave it as the Basemap implementation for now — I don't think we need to have it hold things up. @lfairchild or I will dig into it more down the line.

**Comment by moonshoes87** [comment]
@ltauxe, do you want to update install\_etopo.py to work with cartopy instead?  It looks like it still searches for the basemap data directory.

**Comment by moonshoes87** [comment]
It looks like people are at least poking at the contourf issue in cartopy, so I am optimistic that it will be resolved (eventually): 
https://github.com/SciTools/cartopy/issues/1131

**Comment by ltauxe** [comment]
I thought it just looked in data_files/etopo20   won’t that work?  
lisa

**Comment by moonshoes87** [comment]
instal\l_etopo.py finds the files in data_files/etopo20, but then it tries to put them into the basemap\_datadir.  I guess they no longer need to be moved at all, then?  So install\_etopo.py is only needed if using Basemap?

**Comment by ltauxe** [comment]
Maybe not even for basemap?  but it works fine for me in cartopy version - for pip people too?  
lisa

**Comment by moonshoes87** [comment]
install\_etopo can *only* work if you have Basemap installed, since it tries to import Basemap and then prints out an error message if it can't import Basemap.  If you only have cartopy installed, it won't do anything.  Perhaps I will just update the error message to say that install\_etopo is only helpful if you're using basemap, otherwise don't worry about it?

**Comment by Swanson-Hysell** [comment]
Should we close out this main issue given that cartopy is now integrated throughout much of the code and focus instead on smaller issues that are relevant to specific aspects of the implementation?

**Comment by moonshoes87** [comment]
Yes, I agree.  I've fixed the install\_etopo error message, and I will make a separate issue for adding cartopy into the Demag GUI vgp viewer eventually.
