### ISSUE TITLE
core_depthplot redo

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#295]
And add to make_magic_plots

**Comment by moonshoes87** [comment]
Issue to deal with: what level has the core_depth/composite_depth data.

**Comment by moonshoes87** [comment]
@ltauxe, here are some of the issues with core_depthplot:

- wig_file doesn't currently work
- sum_file doesn't currently work
- ngr_file doesn't currently work (never fully implemented)
- suc_file doesn't currently work (never fully implemented)
- problems with plotting susceptibility:
    + LT-X isn't a valid method code (should be LP-X?  I went ahead and changed this...)
    + SDecs, SIncs, and SInts are never filled in with the current code

**Comment by ltauxe** [comment]
AND this has the same problem as ani_depthplot.py  when called from the notebook with: 
!core_depthplot.py -DM 3 -fsa ./../core_depthplot/samples.txt -LP AF 15 \
    -f ./../core_depthplot/measurements.txt -log \
    -d 50 150 -ts gts12 23 34 -D -fmt png -sav -DM 3

I get this: 
Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/core_depthplot.py", line 4, in <module>
    import wx
ImportError: No module named wx

Why do we need wx for these anyway?

**Comment by moonshoes87** [comment]
wx is being used instead of the tkinter backend.  I implemented this so that core_depthplot and ani_depthplot could go into Pmag GUI and still be used on the command line, since the Tkinter is incompatible with wxPython.

**Comment by ltauxe** [comment]
can we enable it only if called from pmag_gui?  because that is the source of the problems in the notebook - which doens’t use wxPython anyway. 
lisa

**Comment by moonshoes87** [comment]
I do think we have to work out the source of your notebook environment troubles — because that is likely to cause other unpredictable problems.

But let me look into what it would take to partially roll back the code to plot interactively with Tkinter instead of outputting a finished plot.

**Comment by moonshoes87** [comment]
@ltauxe, I am closing this issue.  Core_depthplot still works on the command line, and you have an implementation in the PmagPy Analysis and Plots notebook.  If you still want to work on core_depthpot.py, including making it work in the notebook better, you can re-open.
