### ISSUE TITLE
pyinstaller isn't working on OS X

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#296]
I updated a bunch of packages, and pyinstaller isn't working for pmag/magic GUIs anymore.  It does work with minimal matplotlib example.

**Comment by moonshoes87** [comment]
Also works with a minimal wxPython script.

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87, might be worth [raising this](https://github.com/pyinstaller/pyinstaller/issues) with their dev team. I have contacted them in the past regarding an issue I had getting pyinstaller to run locally, and they responded quickly and didn't seem to mind helping with my strange conflict I was having with a linux based skype instillation blocking pyinstaller.

**Comment by moonshoes87** [comment]
@Caoimhinmg, yeah, definitely.  I want to home in on the problem a bit more first, and I have been called away to other bugs.  But I will definitely report the issue.

**Comment by moonshoes87** [comment]
I thought this might be the problem

    80893 INFO:   Matplotlib backend "WebAgg": ignored
        Traceback (most recent call last):
      File "<string>", line 12, in <module>
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_webagg.py", line 327, in <module>
        class _BackendWebAgg(_Backend):
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_webagg.py", line 329, in _BackendWebAgg
        FigureManager = FigureManagerWebAgg
    NameError: name 'FigureManagerWebAgg' is not defined

but now I'm thinking not.

**Comment by moonshoes87** [comment]
Any import from "dialogs" causes the whole script to fail.

**Comment by Caoimhinmg** [comment]
[Here's](https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) a trouble shooting guide I used when I was having problems. Also [here's](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) the guide for bug reporting follow it to the letter and you'll get a lot more info.

**Comment by moonshoes87** [comment]
Thanks, that's handy!
