### ISSUE TITLE
thellier_gui.py fails when aniso_s is present but other keys are absent in specimens.txt

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#307]
I upgraded data from Selkin et al., 2007 using the online MagIC upgrade tool.  It has anisotropy data in it, with, e.g., aniso_s, but not other parameters, generating this error on line 6580:  
KeyError: "['aniso_ftest' 'aniso_ftest12' 'aniso_ftest23' 'aniso_s_n_measurements'\n 'description'] not in index"

these can be calculated from aniso_s and should be....

**Comment by moonshoes87** [comment]
Is this an issue that should be solved in PmagPy or in the MagIC upgrade tool?

**Comment by ltauxe** [comment]
in thellier_gui

**Comment by moonshoes87** [comment]
As it is done in aniso_magic?  It looks like the missing aniso_s_n_measurements is still a problem for calculating the other parameters...

**Comment by ltauxe** [comment]
yes you are right - this is all happening because rmag_anisotropy is not being translated properly.  maybe i should go back to the source…   
lisa

**Comment by moonshoes87** [comment]
So maybe it is a MagIC upgrade issue after all?  Or is there something else to do on the PmagPy side?

**Comment by moonshoes87** [comment]
@ltauxe, did you resolve this issue?

**Comment by ltauxe** [comment]
nope…   sorry.  could you look into it? 
lisa

**Comment by moonshoes87** [comment]
@ltauxe, this should be good now.
