### ISSUE TITLE
fix where core depth info goes

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#308]
- Add to sites table in relevant programs (i.e., iodp_srm_magic)
- Make sure all plotting programs, etc. that use depth look in sites table
- Remove core depth during upload

**Comment by moonshoes87** [comment]
Maybe this could just happen in upload_magic?  Propagate any core depth info from samples to sites?

**Comment by ltauxe** [comment]
yes

**Comment by moonshoes87** [comment]
Ok, I've implemented this into upload_magic, but ultimately it would be good to re-do all the depth stuff in PmagPy so that it all happen at the site level.
