### ISSUE TITLE
tdt_magic experiment/experiments column

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#309]
tdt_magic generates measurements.experiment (valid MagIC column) and measurements.experiments (not valid MagIC column).  The two values are different, so I'm not sure which is correct.  @Caoimhinmg, I believe you did the conversion of tdt_magic to data model 3, so maybe you could have a quick look at this issue?

You can see the problem in the data from PmagPy/data_files/Measurement_Import/TDT_magic/Krasa_MGH1.tdt 

For example, this measurement:
MGH1:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-BT-MD:LP-PI-ZI

experiment:
MGH1:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-BT-MD:LP-PI-ZI

experiments:
MGH1:LP-PI-TRM:LP-PI-TRM-ZI:LP-PI-ALT:LP-PI-BT-MD:LP-PI-BT

**Comment by moonshoes87** [comment]
This issue exists in other import scripts as well (at least in generic_magic), but in that case the experiment column and the experiments column have the same value.

**Comment by moonshoes87** [comment]
It looks like measurements.experiment is set in pmag.measurements_methods3, and 'experiments' is being set in the import script.  So, I think in the case of generic_magic, just switching 'experiments' to 'experiment' in the script should be fine.  It may be that some of the import scripts are doing redundant work to figure out the experiment column, but that's probably not a big deal.  However, in tdt_magic these two processes are generating significantly different values, so which one should we trust?

**Comment by ltauxe** [comment]
looks like the measurements.experiment is good enough. 
lisa
