### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#313]
when i try to import pmag in a jupyter notebook, i get this error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-94b0f196b214> in <module>()
----> 1 import pmag as pmag
      2 #import ipmag as ipmag
      3 #import ipmagplotlib as ipmagplotlib
      4 import numpy as np
      5 import pandas as pd

ImportError: bad magic number in 'pmag': b'\x03\xf3\r\n'

any ideas?

**Comment by Swanson-Hysell** [comment]
Shouldn't the import be:

```
import pmagpy.pmag as pmag
```

Might that be the problem?

**Comment by ltauxe** [comment]
You are right - but that wasn’t the problem. I had to delete all the .pyc
files for some reason.

**Comment by Swanson-Hysell** [comment]
Interesting. That's a bit odd, but I am glad that fixed the issue.
