### ISSUE TITLE
pmag_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#317]
when importing hysteresis files, this must call agm_magic2 and not agm_magic.py because it is producing an antique format - not even 2.5.

**Comment by ltauxe** [comment]
the problem might be in ipmag.  agm_magic works just fine

**Comment by moonshoes87** [comment]
Thanks!  I will work on this soon (probably tomorrow).

**Comment by ltauxe** [comment]
It seems that lots of ipmag functions are in 2.5. Sigh. Also none of the
3_0 notebook calls work any more - something to do with future imports....
class starting in 2 weeks so I’m panicking

**Comment by moonshoes87** [comment]
Which notebook is failing for you?  

You should already have it installed, but just in case you can run:

conda install future

**Comment by ltauxe** [comment]
The one in the 3_0 notebook folder indata_files

But I think I fixed. The import problem

**Comment by moonshoes87** [comment]
I did some work on this but then saw your latest commit, so I haven't pushed my changes.  Is agm_magic working in Pmag GUI now as expected?  If not, I have it working locally and will push those changes....

**Comment by ltauxe** [comment]
i do have future installed and this problem only happens in the notebooks - not on the command line

**Comment by ltauxe** [comment]
I did fix agm_magic and i think it works now.  
lisa
