### ISSUE TITLE
new? bug in pmag_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#321]
when operating in 2.5, trying to combine magic files I get this error message: 
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/dialogs/pmag_basic_dialogs.py", line 152, in on_nextButton
    combine_dia = combine_magic_dialog(self.WD, self.parent, data_model=2.5)
TypeError: __init__() got an unexpected keyword argument 'data_model'

I don't know where to start....

**Comment by moonshoes87** [comment]
I'll look into it.

**Comment by moonshoes87** [comment]
@ltauxe , reopen if this doesn't fix it for you.
