### ISSUE TITLE
Fix tail check issue in pmag.measurements_methods

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#323]

**Comment by moonshoes87** [comment]
@ltauxe, have you been able to look at this yet?

**Comment by ltauxe** [comment]
not yet

**Comment by moonshoes87** [comment]
@ltauxe, let me know if I can assist on this.  I think it would be good if we can get to the bottom of this.

**Comment by ltauxe** [comment]
I’ll try soon - I’m still swamped here having just given my fourth lecture
(whew) I’ll try to do this tomorrow

**Comment by moonshoes87** [comment]
fixed!
