### ISSUE TITLE
change default color for fit so that second fit is not yellow

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#326]
The current default is to color the second fit made for a sample to be yellow which is hard to read on the equal area plot in particular.

**Comment by Caoimhinmg** [comment]
@Swanson-Hysell I modified this slightly using a color picker. Let me know if you like it or not. For reference here's the [color picker](http://paletton.com/) and the line to modify in Demag GUI is 204 if you want to set it yourself.

**Comment by Swanson-Hysell** [comment]
Great. Much more legible.
