### ISSUE TITLE
feature of demag_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#329]
Having followed the instructions on the cookbook exactly, I would have problems uploaded the example file because of errors in the sites.txt saved by demag_gui.  

name	row_number	problem_type	problem_col	error_message
sr01	0	type	dir_n_samples	"7.0" should be an integer
sr01	0	type	dir_n_specimens_lines	"8.0" should be an integer
sr01	0	type	dir_n_specimens_planes	"0.0" should be an integer
sr01	0	value	criteria	This value: "ACCEPT" is not found in: criterion column in criteria table

This looks like a fairly simple fix -  I'm teaching a short course next week in China and would greatly appreciate an update. :)

**Comment by moonshoes87** [comment]
Fixed this in 74beca5
