### ISSUE TITLE
validations require dir_bfv_dec, dir_bvf_inc if any Directional columns are selected

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#330]
somehow these are now required:  
dir_bfv_dec, dir_bfv_inc
in the specimens table, but not provided by demag_gui.  

I do NOT think these should be required and if they really are necessary, then demag gui should provide them.

**Comment by ltauxe** [comment]
I added in these (unnecessary columns with Pmag GUI), then got these errors:  

-I- specimens file successfully read in
-I- Validating specimens
-W- these rows have problems:
 row: 0, name: sr01a1
row: 1, name: sr01a1
row: 2, name: sr01a1
row: 3, name: sr01a2
row: 4, name: sr01a2  ...
(for full error output see error file)
-W- these columns contain bad values: int_n_measurements, dir_n_comps, dir_n_measurements, int_n_ptrm

Pmag GUI seems to have made these values floats instead of integers. 
[specimens.txt](https://github.com/PmagPy/PmagPy/files/1905679/specimens.txt)

**Comment by Swanson-Hysell** [comment]
These dir_bfv_dec, dir_bfv_inc values certainly shouldn't be required as they are only appropriate for plane fits so will only be in a specimens file every once and a while.

**Comment by ltauxe** [comment]
I fixed these, and successfully got a cheerful message to go to MagIC and upload.  But more problems!

somehow the upload tool added these columns to the sites table:


Column name "dir_n_specimens" is unrecognized in column number 41 for table name "sites".
--
Column name "int_n_ptrm" is unrecognized in column number 42 for table name "sites".
Column name "int_dang" is unrecognized in column number 43 for table name "sites".
Column name "meas_step_max" is unrecognized in column number 44 for table name "sites".
Column name "int_treat_dc_field" is unrecognized in column number 45 for table name "sites".
Column name "int_b_beta" is unrecognized in column number 46 for table name "sites".
Column name "int_n_measurements" is unrecognized in column number 47 for table name "sites".
Column name "int_corr_nlt" is unrecognized in column number 48 for table name "sites".
Column name "int_corr_cooling_rate" is unrecognized in column number 49 for table name "sites".
Column name "meas_step_unit" is unrecognized in column number 50 for table name "sites".
Column name "int_frac" is unrecognized in column number 51 for table name "sites".
Column name "specimen" is unrecognized in column number 52 for table name "sites".
Column name "int_gmax" is unrecognized in column number 53 for table name "sites".
Column name "int_corr_aniso" is unrecognized in column number 54 for table name "sites".
Column name "int_mad_free" is unrecognized in column number 55 for table name "sites".
Column name "int_corr" is unrecognized in column number 56 for table name "sites".
Column name "meas_step_min" is unrecognized in column number 57 for table name "sites".
Column name "int_scat" is unrecognized in column number 58 for table name "sites".
Column name "sample" is unrecognized in column number 59 for table name "sites".
Column name "int_k" is unrecognized in column number 60 for table name "sites".
Column name "dir_comp" is unrecognized in column number 61 for table name "sites".

[sites.txt](https://github.com/PmagPy/PmagPy/files/1905694/sites.txt)

and of course the import fails.

**Comment by moonshoes87** [comment]
I will fix the float/integer issue.  

The validations are generated from the data model.  The reason that those columns (dir_bfv_dec, etc.) are required is because they are governed columns.

For example, for dir_bfv_dec:

Validations: | min(0)max(360), requiredIfGroup("Direction")
-- | --

This means there are other columns present from the Direction group, and that is why dir_bfv_dec is required.  

You can see that in more detail here https://www2.earthref.org/MagIC/data-models/3.0

**Comment by Swanson-Hysell** [comment]
In my view, ```dir_bfv_dec, dir_bfv_inc``` shouldn't have the ```requiredIfGroup("Direction")``` designation as they are values that will only occasionally be present in a dataset.

**Comment by moonshoes87** [comment]
I can remove this requirement in PmagPy right now, if that is helpful.  However, it sounds like we might want to change this in data model 3?

**Comment by ltauxe** [comment]
They are rare and should in any case not be a show stopper. Demag GUI could
just add them to the specimen table behind the scenes or we should bust
make them optional in the data model

**Comment by moonshoes87** [comment]
I’ve removed them in data_model.json, but I guess there will then be a problem when they try to validate/activate on MagIC?

**Comment by moonshoes87** [comment]
That is, I removed the requirement to include those columns, not the vocabulary items themselves.

**Comment by moonshoes87** [comment]
Those requirements are being removed.

**Comment by rminnett** [comment]
The requiredIfGroup() validation has been removed from those two columns:

https://earthref.org/MagIC/data-models/3.0
