### ISSUE TITLE
Pmag GUI tutorial: Thellier GUI creating a pmag_criteria file

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#337]
Sometime during [save MagIC tables], a pmag_criteria.txt file is being created even though we are working in data model 3.  This happens whether or not criteria have been selected (if criteria have been selected, they are added to a valid 3.0 criteria file, and the pmag_criteria.txt file is created anyway).  

I'd like to track this down and figure out what is meant to be happening...

**Comment by ltauxe** [comment]
yes i noticed that.  i don’t know where it is coming from yet.  
lisa

**Comment by moonshoes87** [comment]
That happens around here:

Thellier GUI line 4427

        # make pmag_criteria.txt if it does not exist                                                               
        if not os.path.isfile(os.path.join(self.WD, "pmag_criteria.txt")):
            Fout = open(os.path.join(self.WD, "pmag_criteria.txt"), 'w')
            Fout.write("tab\tpmag_criteria\n")
            Fout.write("er_citation_names\tpmag_criteria_code\n")
            Fout.write("This study\tACCEPT\n")

In the same section, Thellier GUI also makes a magic_methods.txt file.  

I will fix it so that this pmag_criteria/magic_methods files are only created if we're in data model 2, but should a criteria file be created by default in 3.0?

**Comment by ltauxe** [comment]
i think we should only have a criteria file if there are any criteria set.  no?
lisa

**Comment by moonshoes87** [comment]
That does make sense.  I’m not sure why the default is there for 2.5.  I will close this issue, then.
