### ISSUE TITLE
make_magic_plots

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#348]
Get make_magic_plots up and working for @njarboe

**Comment by moonshoes87** [comment]
@njarboe, I haven't been able to look at this yet, but I will soon!

**Comment by moonshoes87** [comment]
I'm finding lots of problems in the 2 --> 3 translation.  A big issue is that some pmag.py functions assume a string, where pandas reads in all kinds of datatypes.

**Comment by moonshoes87** [comment]
I fixed every issue I found.  @njarboe and @ltauxe, let me know if you find additional problems with this program.

**Comment by njarboe** [comment]
This file was created and uploaded with data model 3.0. 
[magic_contribution_16462.txt](https://github.com/PmagPy/PmagPy/files/1981009/magic_contribution_16462.txt)

I can upload it into pmag_gui and one can look at it in the demag_gui tool. It does not have any interpretations so this may be why zeq_magic.py does not work with it. It also does not have any anisotropy measurements but tries to create an anisotropy plot with:
aniso_magic.py -x -B -sav -fmt png -crd s
and then crashes.

Here is the full stack trace when running make_magic_plots.py

kamacite:bogue2017 njarboe$ make_magic_plots.py 
working on:  ./
found sample file samples.txt
using geographic coordinates
working on measurements data
zeq_magic.py -fsp specimens.txt -sav -fmt png -crd g
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/zeq_magic.py", line 550, in <module>
    main()
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/zeq_magic.py", line 297, in main
    or_info,az_type=pmag.get_orient(samp_data,this_sample,data_model=3)
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/pmag.py", line 198, in get_orient
    az_type = SO_methods[SO_methods.index(SO_priorities[0])]
IndexError: list index out of range
result file found sites.txt
number of datapoints:  408 ./
working on site directions
individual number of directions:  0
number of tilt corrected directions:  0
number of geographic  directions:  0
number of sample  directions:  0
number of no coordinates  directions:  0
working on VGP map
working on intensities
magic_select.py  -key int_abs 0. has -F tmp1.txt -f sites.txt
no data matched your criteria
grab_magic_key.py -f tmp1.txt -key int_abs | awk '{print $1*1e6}' >tmp2.txt
LO:__intensities_histogram:_.png
-W- No data found
histplot.py -b 1 -xlab 'Intensity (uT)' -sav -f tmp2.txt -F LO:__intensities_histogram:_.png
working on hysteresis specimens.txt
working on anisotropy specimens.txt
aniso_magic.py -x -B -sav -fmt png -crd s
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/aniso_magic.py", line 621, in <module>
    main()
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/aniso_magic.py", line 144, in main
    spec_df=spec_df.dropna(subset=['aniso_s']).copy()
  File "/Users/njarboe/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 3489, in dropna
    raise KeyError(list(np.compress(check, subset)))
KeyError: ['aniso_s']

**Comment by njarboe** [comment]
Here is another file I am testing with. It has been converted from 2.5 to 3.0 and so has multiple site rows with the same site names. It does produce a plot with all of the directions on it. This is great, but it would also be nice to have plots of the directions for each of the four locations individually. Is this what make_magic_plots.py is already expected to produce.
[magic_contribution_12463.txt]
(https://github.com/PmagPy/PmagPy/files/1981043/magic_contribution_12463.txt)

@moonshoes87 Just saw your new message while working on these examples. Got bogged down in fixing MagIC website bugs while posting the last issue. If you can check these out, that would be great.

**Comment by ltauxe** [comment]
well, download_magic originally split data out into different locations, so make_magic_plots would be run from those separate directories.  it could certainly be modified to go by location (which was in fact the original intent). 
lisa

**Comment by ltauxe** [comment]
thanks!  will do.  
lisa

**Comment by moonshoes87** [comment]
download_magic still can split data into different location folders, but it no longer does so by default.  Unfortunately I don't remember exactly why we made this change.

To have download_magic write out to separate directories:

    download_magic.py -f infile -sep 

or 

    ipmag.download_magic(infile, separate_locs=True)

**Comment by moonshoes87** [comment]
We made the change in download_magic because of this issue:  https://github.com/PmagPy/PmagPy/issues/278.  Basically, it's because location name is no longer automatically available at the specimen and sample levels.

@ltauxe, are you changing make_magic_plots to find different locations, or do you want me to?  Or do we want to leave it as is?

**Comment by moonshoes87** [comment]
Today I will look at: magic_contribution_16462.txt which has the key_error.

**Comment by moonshoes87** [comment]
I've fixed the anisotropy problem.  It looks like another issue is that the method code SO-SUN-SIGHT isn't included in pmag.set_priorities.  If I add a few lines so that SO-SUN-SIGHT is treated like SO-SUN, then everything seems to work.  

@ltauxe and @njarboe, does this seem like an appropriate solution?  Alternatively, I could add SO-SUN-SIGHTS to the list of SO_defaults, presumably after SO-SUN and before SO-SIGHT....

**Comment by ltauxe** [comment]
yes SO-SUN-SIGHT would be before SO-SIGHT and after SO-SUN.  just like SO-SM (which is sun or magnetic_
lsia

**Comment by moonshoes87** [comment]
@njarboe, I have made lots of fixes, including splitting data out by location.  However, I am fairly sure that I've introduced some new bugs.  If you're willing to have another run at it, that would be very helpful.

**Comment by moonshoes87** [comment]
We previously have discussed adding core_depthplot and/or ani_depthplot to make_magic_plots.  Is that still on the agenda?  If so, I'll need some help figuring what the treatment protocol and step are (required arguments).

**Comment by ltauxe** [comment]
oh yeah.  i’ll take a look.  maybe this week-end

**Comment by moonshoes87** [comment]
@njarboe, how's it going with make_magic_plots on the server?  Any issues, or missing plots?

**Comment by njarboe** [comment]
Hello Lori,

I have make magic running on the server and moving the plot files around to
the right places. I have installed Apache to serve up the plots but need to
configure it to let the MagIC website computer access it. I have been
preping for the EarthCube meeting and the IRM summer school and the
EarthCube end today. Hopefully I'll have some time this weekend between
EarthCube and the IRM to work on the server and get it working or at least
to the next stage of needing help.

Thanks for asking about the progress.

Cheers,
Nick

**Comment by moonshoes87** [comment]
That’s good to hear!  Hopefully we have taken care of the big problems already.

-Lori

**Comment by njarboe** [comment]
Pulled PmagPy for the first time in awhile and now I get this error with multiple data files that worked before. Is this the panda problem that hopefully will be fixed soon?
[magic_contribution_16463.txt](https://github.com/PmagPy/PmagPy/files/2160359/magic_contribution_16463.txt)

njarboe$ make_magic_plots.py -F magic_contribution_16463.txt 

Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/new_builder.py", line 53, in __init__
    self.vocab = Contribution.vocab
AttributeError: type object 'Contribution' has no attribute 'vocab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/make_magic_plots.py", line 454, in <module>
    main()
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/make_magic_plots.py", line 96, in main
    con = nb.Contribution()
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/new_builder.py", line 55, in __init__
    Contribution.vocab = cv.Vocabulary(dmodel=self.data_model)
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/controlled_vocabularies3.py", line 41, in __init__
    self.get_all_vocabulary()
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/controlled_vocabularies3.py", line 287, in get_all_vocabulary
    all_codes, code_types = self.get_meth_codes()
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/controlled_vocabularies3.py", line 68, in get_meth_codes
    all_codes = pd.concat([all_codes, df], sort=True)
TypeError: concat() got an unexpected keyword argument 'sort'

**Comment by moonshoes87** [comment]
Ah, I added the ‘sort’ argument in based on a FutureWarning (see PmagPy issue #375).   You can solve it  by upgrading pandas to the latest version.  Or, I could revert it and make the update later.  Eventually we will need that ‘sort’ argument to maintain the correct behavior when the default changes.  What do you think?

**Comment by njarboe** [comment]
I have not done a conda update in awhile. Are you running anaconda as your python management system? And how do you decide when to update? I guess anytime I pull from the PmagPy master, running a conda update would be a good idea?

**Comment by moonshoes87** [comment]
Dealing with versions and updates in a more systematic way has been on my list for a while.  I use conda to update most things (there are a few exceptions, like wxPython, that must be managed with pip).  

It is possible, with pip or conda, to "freeze" a requirements file which can be in version control and made available.

wxPython and basemap are a bit annoying, because they are tucked away not in the main PyPI/conda repos.

pip list:

[pmagpy_requirements.txt](https://github.com/PmagPy/PmagPy/files/2160865/pmagpy_requirements.txt)

Can be installed with:

    pip install -r pmagpy_requirements.txt


conda list:

[pmagpy_env.txt](https://github.com/PmagPy/PmagPy/files/2160879/pmagpy_env.txt)

The conda file can be used to create a new environment with all of the listed packages (doesn't include wxPython):

    conda create --name <env> --file pmagpy_env.txt

**Comment by njarboe** [comment]
I just did a full conda and python package update:
conda update -n root conda
conda update --all
and that solved the problem.

Is the pip list for if you are not using the conda install? Or is it a list of everything that is not in conda? I thought you meant the latter and thus tried your pip command. I got this error:
kamacite:pmagpy njarboe$ pip install -r pmagpy_requirements.txt
Collecting alabaster==0.7.10 (from -r pmagpy_requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/2e/c3/9b7dcd8548cf2c00531763ba154e524af575e8f36701bacfe5bcadc67440/alabaster-0.7.10-py2.py3-none-any.whl
Collecting anaconda-client==1.6.9 (from -r pmagpy_requirements.txt (line 2))
  Could not find a version that satisfies the requirement anaconda-client==1.6.9 (from -r pmagpy_requirements.txt (line 2)) (from versions: 1.1.1, 1.2.2)
No matching distribution found for anaconda-client==1.6.9 (from -r pmagpy_requirements.txt (line 2))

So I'm guessing that the pip list is when you don't have conda installed but then when would one update the wxPython stuff?

**Comment by moonshoes87** [comment]
The conda list seems to include everything except for wxPython and scripttest.

The pip list includes everything (whether installed by conda or pip), but doesn't specify where to get it -- so I assume it will just try to get everything from PyPI, which won't work.  

So, I think the best approach is probably to include the conda environment file, which can then be duplicated by a user as a new environment:

    conda create --name <env> --file pmagpy_env.txt

or just installed into the current environment:

    conda install --file pmagpy_env.txt

I'll also add some lines about what needs to be installed with pip to the top of the file.

I will test and see if this also works on Windows.

**Comment by moonshoes87** [comment]
I will need to make a separate environment file for Windows.

**Comment by moonshoes87** [comment]
Unfortunately I can only generate an environment file for 32 bit Windows, so that probably won't be useful to most people.  The pmagpy_env file I've generated should be directly useable by all Anaconda/OS X users, and others should be able to at least check version numbers in the file.  I can also generate a more readable format that can't be directly installed by anyone.

**Comment by moonshoes87** [comment]
So, there is now a requirements file that should work to install all pmagpy dependencies (except wx and scripttest): https://github.com/PmagPy/PmagPy/blob/master/pmagpy_env_osx.txt

and a general, more readable file you can use to check version requirements: https://github.com/PmagPy/PmagPy/blob/master/pmagpy_dependencies.txt

Unfortunately I got nothing but errors when I tried generating an equivalent for Linux, but @njarboe you should now be able to at least check what version of a package is expected to work.  We'll just have to remember to keep it updated.  I'm going to close this issue, and new issues can be raised elsewhere.
