### ISSUE TITLE
matplotlib backend troubles on Ubuntu

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#350]
https://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined

**Comment by Caoimhinmg** [comment]
@moonshoes87 does this show up in Demag or Thellier GUI both pick the WxAgg backend at the start so I haven't had any issues. After all the user has already had to install wx and it makes everything look a little more consistent. If this is cropping up in Pmag or MagIC GUI you could just steal the code setting backed from the top of Demag or Thellier GUI. If it's a command line problem isn't there a way to set matplotlib backend for the library in __init__.py?

**Comment by moonshoes87** [comment]
This is an issue a user is having with running Ubuntu on a VM on windows.  She runs into it in curie.py.  I believe she is experiencing a problem specific to Windows + the virtual machine.  Normally, curie.py is able to correctly set the matplotlib backend as TKAgg (as most of the command line plotting programs do).  It needs to be set in both curie.py and programs/ \_\_init\_\_.py as as it has to run correctly with it is installed with pip (in which case \_\_init\_\_.py is run first) or developer installed (in which case \_\_init\_\_.py is not run).

This currently works on all platforms that I have access to (OS X, Windows VM, Linux VM), so I think the problem is specific to the Windows/Linux VM interaction on this user's computer.

**Comment by Caoimhinmg** [comment]
[This doc](https://matplotlib.org/users/customizing.html#customizing-matplotlib) on customizing matplotlib may be helpful, seems you can put a matplotlibrc file in the working directory and it will alter the plotting backend and style automatically. This maybe with a call to use in __init__could ensure all users are getting the same backend so user experience and error reports are more consistent.

**Comment by ltauxe** [comment]
the problem that the student was having was completely solved by using the ipmag version of curie.  so maybe we can close this issue.

**Comment by ltauxe** [comment]
apparently not.

**Comment by moonshoes87** [comment]
@Caoimhinmg, the problem with using .matplotlibrc is that different backends are required for different plotting programs, so it isn't helpful to globally set a backend in a directory.  This is generally solved in PmagPy in two ways:  each program that uses matplotlib calls matplotlib.use at the top of the file (takes priority in the developer install), and programs/\_\_init\_\_.py sets the backend to TKAgg unless it finds the program name in the list of WXAgg-requiring programs in programs/program_envs.py (takes priority with the pip install, since \_\_init\_\_.py is run before the specific program code).  

All that to say, I don't think there is a matplotlib backend issue generally at this point, and the student's issue was very specific to her OS + VM combination.
