### ISSUE TITLE
Add/to or create an images table while calling make_magic_plots

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#352]

**Comment by moonshoes87** [comment]
@njarboe, this is done and seems to be working.  I made a modified program new_make_magic_plots.py that will create image records and combine them with an existing images table if one is available.  Otherwise, it will create a new images table.  I have tested on 10 or so contributions and everything seems to work as expected, but we will probably find some more errors running it on the server.   If you can run it without replacing the existing plots, that might be best!

**Comment by njarboe** [comment]
Plots have been running. Should be done this evening or tomorrow.

**Comment by njarboe** [comment]
Found a bug in my code and needed to restart. I'll let you know when it's done.

**Comment by moonshoes87** [comment]
Sounds good — I will expect to work on any errors found on Monday.

**Comment by njarboe** [comment]
The plots are done and the log is at http://34.236.167.37/plots/batchPlotsLog.txt 

I saw only 4 Traceback errors. You can see the other files created in the plots/$MAGICID directories.

**Comment by moonshoes87** [comment]
@ltauxe, you could check my fix for dayplot_magic in commit https://github.com/PmagPy/PmagPy/commit/bf0ab2936d38433733c816ad1c5dd2ee2023979c.

I was getting an error with contribution [14743](https://earthref.org/MagIC/14743) where the Bc list had no data and caused an error.  I just did the simplest possible fix but maybe some deeper logic should be used/fixed.

**Comment by moonshoes87** [comment]
@njarboe, I fixed the two issues I found in the log.  Today is my last day of work for a while -- feel free to use the new_make_magic_plots if you want as it seems to be working!  I may also be available for small fixes here and there.

**Comment by ltauxe** [comment]
it seems to work as advertised.  
lisa

**Comment by moonshoes87** [comment]
@njarboe, are you using new_make_magic_plots.py currently on the server?

**Comment by moonshoes87** [comment]
Once #602 is solved, I will rename new_make_magic_plots to make_magic_plots and get rid of the old make_magic_plots.

**Comment by moonshoes87** [comment]
I've renamed new_make_magic_plots --> make_magic_plots and removed the old version.

**Comment by njarboe** [comment]
Changed server programs to use make_magic_plots again.
