### ISSUE TITLE
zeq_magic bug with plotting best fit line

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#354]
I'm running into a bug with zeq_magic with the McMurdo dataset.  When I get to plotting this specimen:

<img width="616" alt="screen shot 2018-05-21 at 1 00 37 pm" src="https://user-images.githubusercontent.com/1836578/40327232-06c9748c-5cf7-11e8-8739-49d221c9d3dc.png">

zeq_magic.py fails.

Is `meas_step_max == 0.18` a mistake in the specimens table?  Or should rows like this simply be ignored for plotting?

You can replicate the error from the data_files/3_0/McMurdo directory:

     McMurdo zeq_magic.py -spc mc217a1

Error output:

    Traceback (most recent call last):
      File "/Users/nebula/Python/PmagPy/programs/zeq_magic.py", line 560, in <module>
        main()
      File "/Users/nebula/Python/PmagPy/programs/zeq_magic.py", line 390, in main
    start, end = tr.index(beg_pcas[ind]), tr.index(end_pcas[ind])  # getting the starting and ending     points
    ValueError: 0.18 is not in list

@ltauxe ?

@njarboe, you will also run into this error eventually with working through make_magic_plots.py, so hopefully I can clear it up.

**Comment by moonshoes87** [comment]
Ok.  I will implement the fix that zeq_magic.py will skip a specimen interpretation row if it has invalid bounds, so that records like this don’t break zeq_magic/make_magic_plots.  What do you want to do about handling this in Demag GUI?

**Comment by ltauxe** [comment]
this fixed the problem in zeq_magic.py   
    meas_data = meas_data[meas_data['method_codes'].str.contains(
        'AN|ARM|LP-TRM|LP-PI-ARM') == False]  # strip out unwanted experiments
but apparently not yet in demag_gui.py   
and an ARM data point is  is being included.
