### ISSUE TITLE
improve best fit line drawing in PmagGUI

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#357]
Following this suggestion from Jeff Gee:

> It might be useful to trim the best fit lines to the sample data in both projections. It looks like this is currently just being done for whatever component is on the X-axis.

The best-fit lines are currently trimmed to the extent of the data in the x-direction, but not in the y-direction which can sometimes cause issues where the line extends past the data (particularly for poor fits where the line is near vertical in the chosen projection).

**Comment by moonshoes87** [comment]
@Swanson-Hysell & @Caoimhinmg, I am closing this as another stale issue.  Feel free to reopen if someone wants to work on this.
