### ISSUE TITLE
implement zoom-out functionality for users in PmagGUI

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#358]
Following this comment from Jeff Gee

> I discovered that you can zoom in on the graph but then I wasn’t able to figure out how to unzoom without switching to a new specimen and then reloading the data/graph.

I follow this same method to unzoom (go to the next sample then come back) which is non-ideal. I think that @Caoimhinmg had implemented something where a tertiary mouse click (he was using a 3 button mouse) would do zoom-out. Perhaps we can think of another way to implement zoom-out.

**Comment by Swanson-Hysell** [comment]
Per your question @Caoimhinmg, having it be reset to original view functionality rather than zoom-out functionality seems like a good solution.

**Comment by moonshoes87** [comment]
This doesn't seem crucial -- I am closing this issue unless someone thinks it needs to be re-prioritized.
