### ISSUE TITLE
fix command line plotting programs for Windows

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#361]
Here’s more documentation about interactive mode: https://matplotlib.org/faq/usage_faq.html#what-is-interactive-mode

Below is the minimal code I used to debug pmagplotlib.  There are command line switches for -t (use TKagg), -i (use plt.ion), and -p (print an input() call at the end of the plotting).

Basically, it only works to have an interactive plot AND access to the command line (for save/quit/continue):  on OSX, with TKinter backend, with plt.ion, and with an “input()” call to prevent the program from just instantly quitting.  

On Windows, with tkinter plt.ion and input(), the plot isn’t actually filled in and is “not responding”.  If I take out plt.ion, it works, but is “blocking”.  As far as I can tell from the docs, this is exactly how matplotlib is supposed to work.

    import matplotlib
    import sys
    if "-t" in sys.argv:
        matplotlib.use("TKAgg")
    from matplotlib import pyplot as plt

    if "-i" in sys.argv:
        plt.ion()
        print('not blocking')
    else:
        print('blocking')

    plt.figure(1)
    plt.plot([1,2,3])
    plt.draw()
    plt.show()
    #plt.ioff()

    if "-p" in sys.argv:
        ans = input('hi')

**Comment by moonshoes87** [comment]
I'm going to go through all of the Windows plotting programs individually on the command line.

**Comment by ltauxe** [comment]
using plt.show() makes the command line programs break in the notebooks.

**Comment by ltauxe** [comment]
no - cartopy is just super slow.  i thought it was hung up, but not.  it works fine.
