### ISSUE TITLE
notebook vs commandline

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#362]
I'm trying to work on the _PmagPy* notebooks.  My plan was to make a notebook in parallel with the cookbook along the lines of what  Nick Swanson-Hysell started.  I ran into a weird problem with the notebook _PmagPy.ipynb  which used to work fine, but now has this bug:  

!ani_depthplot.py -h
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/ani_depthplot.py", line 3
    from __future__ import print_function
SyntaxError: future feature print_function is not defined

but this only happens in the notebook but not on the command line.  and i don't seem to have ani_depthplot_anaconda in my PmagPy version.  

I think it has to do with this line: 
#!/usr/bin/env pythonw

but of course the program doesn't work without it...

**Comment by moonshoes87** [comment]
I'll check this today

**Comment by moonshoes87** [comment]
This doesn't occur for me, whether in the notebook or out of the notebook.  

One thing to try is:

    conda install future

Also, we don't really need the line that is throwing the error:

    from __future__ import print_function

anymore.  That line was to maintain Python 2 compatibility, which we are not really supporting on the main PmagPy branch.  I've pulled that line out, and I'm pushing the change.  Let me know if the problem persists.
