### ISSUE TITLE
put aniso_magic into ipmag

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#363]

**Comment by moonshoes87** [comment]
should function without a sites table

**Comment by ltauxe** [comment]
still doesn't  - at least not in _PmagPy_nb.ipynb

**Comment by moonshoes87** [comment]
sorry, that was just a note for what I need to do :)  It doesn't work yet.

**Comment by ltauxe** [comment]
The offending file was data_files/aniso_magic/sed_specimens.txt  
and here is the command and error (from within the _PmagPy_nb  notebook:
ipmag.aniso_magic(infile='sed_specimens.txt',ivec=1,dir_path='../aniso_magic',crd='g')
-W- Couldn't read in samples data
-I- Make sure you've provided the correct file name
-W- Couldn't read in samples data
-I- Make sure you've provided the correct file name

it shouldn't be looking for a sample file if we are just using all the data, not just one site.

**Comment by moonshoes87** [comment]
Great, I should be able  to fix it with that information.

**Comment by moonshoes87** [comment]
The plotting by site issue was caused by having the wrong default for isite.  However, once I fixed that I got into the *real* mess, which is different than I was expecting.

What we want for ipmag.aniso_magic is to take in some arguments, quietly create few plots, and then return them.  However, pmagplotlib is very much written to produce plots interactively with matplotlib.  The code is full of calls to plt.show, etc., and pmagplotlib never actually returns Figure objects, it just shows or saves them.  This is a huge mess for the notebooks (or the GUIs, for that matter).  matplotlib has an object-oriented API that for creating plots without all the interactive display logic, but pmagplotlib would need to be re-written.

ipmag.ani_depthplot and ipmag.core_depthplot work in a more object-oriented way, but that's because I re-wrote them to go in the GUIs, and they don't really use pmagplotlib.  We're going to run into problems with most of the rest of the plotting programs, though.

We could consider rewriting pmagplotlib anyway, so that it would be useable for web PmagPy.  On the other hand, if we're rewriting we might want to consider other tools that could provide more interactivity online, like plotly.  

@ltauxe, what do you think?

**Comment by ltauxe** [comment]
right. instead of re-writing pmagplotlib, i was just thinking of doing stuff in ipmag along the lines of what Nick S-H started.  i’m working through them in _PmagPy_nb and I’ll just do what i can without you until i get stuck.  
lisa

**Comment by moonshoes87** [comment]
Yeah, I suspect that the plotting programs will pretty much all be problematic, and everything else should be relatively easy.  I'm going to finish getting the plotting programs working for Windows, for now.

**Comment by ltauxe** [comment]
i put it in ipmag as ipmag.aniso_magic_nb.  it seems to work well
