### ISSUE TITLE
ipmag.core_depthplot

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#366]
doesn't work for data_model 3 at all.  i put a nice version that does some of what core_depthplot does into the PmagPy_nb Jupyter notebook.  this would work as a start.  i would just move core_depthplot to core_depthplot2 and stop trying to serve both - just making a clean break to data_model 3, with pandas in ipmag would be better (easier) and faster too probably.

**Comment by moonshoes87** [comment]
Lisa, you can see an example of core_depthplot working for data model 3 in pmagpy_tests/test_ipmag.py:

    def test_core_depthplot_data_model3(self):
        path = os.path.join(WD, 'data_files', 'core_depthplot')
        program_ran, plot_name = ipmag.core_depthplot(input_dir_path=path,
                                                      spc_file='specimens.txt',
                                                      age_file='ages.txt',
                                                      meth='AF', step=15,
                                                      fmt='png', pltInc=False,
                                                      logit=True, pltTime=True,
                                                      timescale='gts12',
                                                      amin=0, amax=3, data_model_num=3)
        self.assertTrue(program_ran)
        self.assertEqual(plot_name, 'DSDP Site 522_m:_LT-AF-Z_core-depthplot.png')

There is also a working example for the command line in _PmagPy.ipynb:

    !core_depthplot.py -DM 3 -fsa ./../core_depthplot/samples.txt -LP AF 15 \
    -f ./../core_depthplot/measurements.txt -log \
    -d 50 150 -ts gts12 23 34 -D -fmt png -sav -DM 3

I believe I did the translation to 3.0, but only had the one dataset to test with.  So it works for that dataset, but may be buggy with other datasets.  I think we've previously discussed that a rewrite might be better anyway, though.  Let me know if you want me to work on this in some way.

**Comment by moonshoes87** [comment]
The core_depthplot tests worked as of commit 27421650 try to make ani_depthplot window buttons show up on Windows, #364

    pythonw -m unittest pmagpy_tests.test_ipmag.TestCoreDepthplot

They are now broken with the last few commits.  ipmag.core_depthplot is also called in Pmag GUI, so that may not be working anymore either with these changes.  Let's figure out how to attack this!

**Comment by moonshoes87** [comment]
@ltauxe, can you send me the data files that were failing for you?

**Comment by ltauxe** [comment]
the data model 3 ones in data_files/core_depthplot  
lisa

**Comment by moonshoes87** [comment]
The data model 3 files in core_depthplot work, at least the way I have been calling them.

See the example in _PmagPy.ipynb:

!core_depthplot.py -DM 3 -fsa ./../core_depthplot/samples.txt -LP AF 15 \
    -f ./../core_depthplot/measurements.txt -log \
    -d 50 150 -ts gts12 23 34 -D -fmt png -sav -DM 3 -ID ./../core_depthplot


Also, there are working examples in pmagpy_tests/test_ipmag.py with ipmag.core_depthplot.  

You can run those with:

    pythonw -m unittest -v pmagpy_tests.test_ipmag.TestCoreDepthplot  

that will run tests for core_depthplot in MagIC 2.5 and MagIC 3.0.

So there must be something more specific that you were trying that wasn’t working.  If you can reproduce the command that failed, I should be able to test it, or implement a warning message of some kind.  I did some fixes to make ipmag.core_depthplot run more natively in MagIC 3.0, but those examples did consistently work before as well.
