### ISSUE TITLE
new notebook version of aniso_magic (called aniso_magic_nb)

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#369]
I still need to implement plotting by location and by site.  
Also, this one does not save the averages to the MagIC files.  I think that should be done
as a separate action - not in the plotting program.  it just gets messy - thoughts?

**Comment by moonshoes87** [comment]
I definitely prefer segregating the functionality of plotting from the functionality of updating MagIC tables.  That way, even if the plotting needs to be done in two different ways for notebooks vs command line programs, at least the calculations can be done exactly the same.

**Comment by ltauxe** [comment]
I think i figured out how to add the by site/sample whatever functionality - see example in _PmagPy_nb.ipynb  with dmag_magic 
it seems to work ok for that application and if we like it, i can just copy that for others...

**Comment by moonshoes87** [comment]
That looks good.  If we want to abstract that out to work in all cases, we'll probably need some more checking for columns names or try/except blocks (I keep finding missing columns in various contributions).

**Comment by ltauxe** [comment]
It now plots by site.
