### ISSUE TITLE
pandas 0.23.1 munches output files

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#371]
pandas 0.23.1 partially overwrites output in the to_csv function.  This results in incomplete file output when writing out MagIC tables.  Specifically, the 

Solution: install 0.23.0.

    pip install pandas==0.23.0

or

    conda install pandas=0.23.0

pandas 0.23.2 should have the fix for this issue, and should be released around the end of June.

https://github.com/pandas-dev/pandas/issues/21471

**Comment by ltauxe** [comment]
jeez

**Comment by moonshoes87** [comment]
I've put a workaround in, but should revert it once pandas latest version is fixed.

**Comment by moonshoes87** [comment]
i will leave this issue open in the meantime as a reminder.

**Comment by moonshoes87** [comment]
I'm just going to leave this workaround in -- it doesn't create any problems anyway and insures proper behavior.
