### ISSUE TITLE
comparing direction in aniso_magic

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#378]
@ltauxe, I'm working on making sure aniso_magic works awesomely.  I'm running into trouble with the "compare direction" element.

                      Input: Vi D I to  compare  eigenvector Vi with direction D/I
                             where Vi=1: principal
                                   Vi=2: major
                                   Vi=3: minor
                                   D= declination of comparison direction
                                   I= inclination of comparison direction

No matter what input I give, I get index errors later.

As far as I understand the code, vec will always be an integer:

         vdi = input("Vi D I: ").split()
         vec = int(vdi[0])-1

but later on, in plotANIS, the code is looking for vec to be iterable:

        cart = pmag.dir2cart([v[vec][0], v[vec][1], 1.])

Can you clarify for me?  We should fix the input message to explain more clearly the desired format for Vi D I!

**Comment by ltauxe** [comment]
no vec is a float - it is the direction (dec, inc) of the comparison direction. I’ll take a look.

**Comment by moonshoes87** [comment]
the notebook example in aniso_magic no longer works:

<img width="1173" alt="screen shot 2018-07-02 at 1 40 42 pm" src="https://user-images.githubusercontent.com/1836578/42185401-99351020-7dfd-11e8-9147-c4e7126fba3e.png">

**Comment by moonshoes87** [comment]
it worked as of: abcece2

broken at:  7f18001a9f836ce5efeedaaca5ed477c605133a9

**Comment by moonshoes87** [comment]
@ltauxe, vec will always be an int because of the call to `vec = int(vdi[0]) - 1`.

But I think I finally understand the input message.  The user is choosing principal, major, or minor component with 1, 2, or 3, and then the dec and inc.  Perhaps this is obvious to everybody else, but I got totally stuck.  Maybe we could just add an example line with valid input for vdi at the end of the input string?

                      Input: Vi D I to  compare  eigenvector Vi with direction D/I
                             where Vi=1: principal
                                   Vi=2: major
                                   Vi=3: minor
                                   D= declination of comparison direction
                                   I= inclination of comparison direction
                             e.g.:     1 15 77
