### ISSUE TITLE
download_magic.py

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#386]
This doesn't work with any files downloaded from the MagIC database these days - nor does the version called by pmag_gui.   here is our favorite, the Lawrence et al McMurdo contribution.  

[magic_contribution_16436.txt](https://github.com/PmagPy/PmagPy/files/2178171/magic_contribution_16436.txt)

I get this error: 

skipping....
WARNING:  problem in file with line: 
McMurdo	mc229	DSC_0196D.JPG	Outcrop	MC229 sample detail	McMurdo Volcanics: paleomagnetic sampling :Fang Ridge	2006-12-27T00:00:00Z	Hubert StaudigeThis study

for all the lines.  why?

**Comment by moonshoes87** [comment]
I’ll check on this.

**Comment by moonshoes87** [comment]
It seems to work on all of our old MagIC files, including 3.0 files.  So perhaps there has been some change to the formatting?  I will look more in depth today if I can.

**Comment by ltauxe** [comment]
it does work on some downloaded files, but not this one (and maybe some others).  
lisa

**Comment by moonshoes87** [comment]
Looks like there is an extra tab on the front of the file.  

Another problem is that the measurements rows come without extra tabs, so they are the “wrong” length.  

Solutions:  I can strip away the leading tab if one is present.  And, I can pad the short rows with the appropriate number of empty strings.  Does that seem ok?

I’m not sure why this issue is coming up now and not earlier.  Perhaps the MagIC format changed, and tabs are no longer on the ends of rows if there is no more text?

**Comment by ltauxe** [comment]
yeah why don’t we do that - i didn’t know there was a terminal tab at the end of these MagIC files and should MagIC fix all these errors when it processes the data for download?  
lisa

**Comment by moonshoes87** [comment]
I’m not sure.  What download_magic expects is output formatted like this:

col1 col2 col3
val1\t\t

instead of 

col1 col2 col3
val1

with no tabs at the end of the row.  It’s not really a big deal, as long as we’re expecting it.

**Comment by moonshoes87** [comment]
@ltauxe, I put in a fix, you can have a look and see if it resolves everything as expected.

**Comment by rminnett** [comment]
Ah, yes, that's possible that the measurement rows are being written without trailing tabs. I'm not sure if we ever defined the "correct" behavior for MagIC text files with empty columns at the end, but it's probably good that PmagPy can handle both cases (with and without trailing tabs). It's also possible that other tables could be written this way if only some of the rows have values in the last column, but I think that scenario is less likely than with measurements.

**Comment by moonshoes87** [comment]
That makes sense.  I have fixed it so that errors should be thrown only if the number of values in a row is greater than the number of headers.
