### ISSUE TITLE
Problem with plot_title when running make_magic_plots.py --> polemap_magic.py

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#390]
Pulled from master a few hours ago.  Got the following error with this file:
[magic_contribution_12003.txt](https://github.com/PmagPy/PmagPy/files/2181821/magic_contribution_12003.txt)

magic@ip-172-31-53-34:~/batchPlots/12003$ make_magic_plots.py 
propagation successful

working on:  Arqueros Formation
-I- writing locations records to /home/magic/batchPlots/12003/tmp_locations.txt
-I- 2 records written to locations file

working on:  Elquinos Formation
-I- writing locations records to /home/magic/batchPlots/12003/tmp_locations.txt
-I- 5 records written to locations file

working on:  Quebrada Marquesa Formation
-I- writing locations records to /home/magic/batchPlots/12003/tmp_locations.txt
-I- 3 records written to locations file

working on:  Vinita Formation
-I- writing locations records to /home/magic/batchPlots/12003/tmp_locations.txt
-I- 3 records written to locations file
working on pole map
polemap_magic.py -sav -fmt png
Traceback (most recent call last):
  File "/home/magic/git/PmagPy/programs//polemap_magic.py", line 250, in <module>
    main()
  File "/home/magic/git/PmagPy/programs//polemap_magic.py", line 235, in main
    FIG = pmagplotlib.addBorders(FIG, titles, black, purple)
  File "/home/magic/git/PmagPy/pmagpy/pmagplotlib.py", line 2738, in addBorders
    plot_title = titles[key]
KeyError: 'map'

**Comment by moonshoes87** [comment]
I can't reproduce this error locally.  I'll try to see if I can figure out any additional context, and maybe look on my Linux VM.

**Comment by moonshoes87** [comment]
Oh, I need to test things with the IS_SERVER flag set to True.
