### ISSUE TITLE
Higher level parameters not given in plot names

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#391]
I'm not sure if this should be fixed at this point or is a work in progress, but for putting the plots onto the website Rupert needs the Location, Site and Sample names in the plot name. For this contribution 
[magic_contribution_16462.txt](https://github.com/PmagPy/PmagPy/files/2194053/magic_contribution_16462.txt)
we get files names like:
LO:__SI:__SA:__SP:_0SC2105_CO:_g_TY:_demag_.png
LO:__SI:__SA:__SP:_0SC2105_CO:_g_TY:_eqarea_.png
LO:__SI:__SA:__SP:_0SC2105_CO:_g_TY:_zijd_.png

Specimens show up but nothing else.

**Comment by moonshoes87** [comment]
@njarboe, this is not something I've been working on, but I can go about fixing now.  zeq_magic.py should now be producing file names as expected, and I'll also check the others.  

What should we do in a case like polemap_magic, where multiple locations are plotted in one figure? It currently looks like this:

    'LO:_' + locations + '_POLE_map.' + fmt

but that probably won't work well.  Any ideas on how to handle this?

**Comment by moonshoes87** [comment]
Other question: in all cases, will we need the full hierarchy, from location down, in order to use the figure?

**Comment by ltauxe** [comment]
colon delimited list of locations?

**Comment by ltauxe** [comment]
it would seem so but that will be awkward and should only happen within make_magic_plots and not in all the sub programs.  It is really annoying to have some of these programs break because of a lack of full hierarchy.  
lisa

**Comment by moonshoes87** [comment]
@ltauxe, definitely -- I will set it up so it won't break anything.  For the most part, this code will only be run when isServer is set to True.  And even on the server, it won't break if the full hierarchy is missing, it will just produce incomplete plot names.  Propagating all of the names down will slow the program down a bit, but again, it will only be run when isServer is set to True.

**Comment by moonshoes87** [comment]
Regarding the list of location names: colons aren't permitted in filenames in Windows, but should be ok in Linux.  @njarboe, are we assuming that the relevant server for MagIC will always be Linux?  

Another issue is that occasionally a contribution will have a lot of locations, and then sometimes a too-long filename is created.  This occurred with one of the contributions I was testing recently, so I added some code into polemap_magic.py to truncate super long lists of locations.

**Comment by njarboe** [comment]
It's unlikely we would move to a Windows OS for the MagIC plot server, so the colons should be fine.

**Comment by moonshoes87** [comment]
Right, and the whole filenames are already full of colons.  I forgot about that.  

I'm checking through the rest of the plotting programs and should be done soon!

**Comment by moonshoes87** [comment]
For programs like dayplot_magic.py, where all specimens are being plotted, what should the naming convention look like?  Currently, it looks like this: `LO:_McMurdo_SI:__SA:__SP:__TY:_day_.svg`.  Is that satisfactory?

**Comment by moonshoes87** [comment]
@njarboe, aside from the above question, the naming convention should be fixed.  Let me know what other issues you find in make_magic_plots.py.

**Comment by njarboe** [comment]
I've run through most of the MagIC Files with your first changes here. Filenames are much improved. Thanks. There aren't any errors thrown at this point. I'll rerun them to get your most recent improvements. Then I'll take a close look at those plots that don't seem to be working and let you know if there are data files that should be plotting but aren't and open those as new issues.

**Comment by njarboe** [comment]
If the pole map is plotting the poles for all the locations in the contribution, it would be nice to have 'MC:_' + MagicContributionNumber + '_POLE_map.' + fmt  This plot would be shown at the contribution level.

I'm not sure how it currently is expected to work, but it would also be nice to have the plots of the pole for each location, if available, by itself to display at the location level. In that case 'LO:_' + location + '_POLE_map.' + fmt  would be good.

**Comment by njarboe** [comment]
I think leaving out levels that are not expected to exist is cleaner for humans to read but the other is more explicit to what is going on. Since it will just be machine read or looked at by developers I would say keep the LO:_McMurdo_SI:__SA:__SP:__TY:_day_.png format.

**Comment by njarboe** [comment]
@moonshoes87 Running through all the data files again. I'll spot check a few more and then I think we should be ready to put them on the live site. Thanks.
