### ISSUE TITLE
demag_gui criteria

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#396]
This program is stuck in data model 2.5 as far as the acceptance criteria go.  instead of "ACCEPT" the criteria should be DE-SPEC, DE-SAMP, etc.

**Comment by ltauxe** [comment]
Also, it puts in an illegal column:  dir_n_specimens
AND doesn't seem to do the site averaging including lines and planes. or i did it wrong!

**Comment by moonshoes87** [comment]
I'm not sure how the DE-SPEC, DE-SAMP criteria are supposed to work.  I can try to work this out from parallels with Thellier GUI, but this might be a better job for you, @Caoimhinmg, if you have time?

@ltauxe, dir_n_specimens is legal at the locations, sites, or samples level.  Is my validation code malfunctioning, or is dir_n_specimens being added to a different table?

**Comment by ltauxe** [comment]
I think i did it wrong. it seems to be working now.
