### ISSUE TITLE
update MsT conversion  to MagIC 3

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#399]
@ltauxe, the MsT conversion script outputs a column called "measurement_magnitude" which is uncalibrated.  There is no equivalent to this in MagIC 3 -- any thoughts about where we should put this in the new data model?

@rminnett, do you have any suggestions?

**Comment by moonshoes87** [comment]
@ltauxe, I also think that MsT_magic is mishandling the first measurement record.

It warns:  `... skipping repeated temperature step`

even though it is the first record, and then method_codes for that initial lines is assigned as "".  If the first line is NRM, should the first method code be just "LT-NO"?

**Comment by ltauxe** [comment]
we should have an uncalibrated option for magnetization.  These will never be absolutely calibrated.  can we add a column to MagIC data model 3?  or use magn_moment with an appropriate method code?  [that would be a bit sloppy].  How about magn?  which would have arbitrary units]

**Comment by ltauxe** [comment]
well you are catching a lot of bad things.  thanks!
lisa

**Comment by moonshoes87** [comment]
I have fixed what I can, but we still need to decide what to do with the uncalibrated magnetization.  I am using "magn_moment" in 3.0 at present, but that is wrong.  @ltauxe, @rminnet, @njarboe, any updates on how we want to handle this in the data model?

**Comment by njarboe** [comment]
I think that magn_raw  and magn_arbitrary aren't quite right if it is really just uncalibrated. Better would be magn_uncalibrated, but that is a bit long. How about magn_uncal? Too cryptic? I will add that to the data model and then change it if we decide on something else.

@ltauxe Do you have a paper/reference that uses this type of measurement so I can get a clear understanding of how it is used? Thanks.

**Comment by njarboe** [comment]
I have now added the magn_uncal to the measurement group. Not adding it to the specimen level unless needed/requested to keep things simpler. @ltauxe If you know people/papers that would need to use this column at the specimen level, I would be happy to add it, but if not maybe wait?

New column info:
  |   |   | Group | Table | Column Name | Display Name | Type | Unit | Description | Notes | Examples | URLs | Required Method Codes | Alternate Units | Validation Rules | Previous Columns | Joining Notes (and cases when joins don't need to result in separate rows) | JSON 

56 |   |   | Magnetization | measurements | magn_uncal | Magnetization Uncalibrated | Number | Dimensionless | Uncalibrated magnitude measurement |   | '1.90','8',786.89' |   |   |   |   | {'table':'magic_measurements','column':'measurement_magnitude'} |   |   | ,'magn_uncal':{'label':'Magnetization Uncalibrated','group':'Magnetization','position':56,'type':'Number','unit':'Dimensionless','description':'Uncalibrated magnitude measurement','examples':['1.90','8',786.89'],'previous_columns':[{'table':'magic_measurements','column':'measurement_magnitude'}]}

**Comment by rminnett** [comment]
@njarboe Thanks! Do you want me to update the JSON file, deploy a new version of the app, and add the column to the Elasticsearch mappings? Without that, updating the spreadsheet alone wouldn't allow a contribution with that column to be uploaded and the column isn't visible on the data model page.

**Comment by njarboe** [comment]
@rminnett If it not much trouble. We can change it later if Lisa wants to and Lori can test out her new code. I can add a better description, notes, and other minor details after I have a better idea of how it is used.

**Comment by rminnett** [comment]
I fixed a missing quote in the examples list, added magn_uncal to the JSON file with a slightly different description to match the other columns, updated the app, and added the column to the Elasticsearch mappings:

![image](https://user-images.githubusercontent.com/1182698/43794333-ca3ff47c-9a32-11e8-9a22-33fc06a7b552.png)

**Comment by moonshoes87** [comment]
Thanks @rminnett and @njarboe !
