### ISSUE TITLE
delete ipmagplotlib?

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#40]
Now that the backend issue is resolved by @moonshoes87 (I think?), should ipmagplotlib be deleted from the repository so that we are solely using pmagplotlib?

**Comment by ltauxe** [comment]
I think that would be great.  and it would also be nice if we could move back to a unified pmag.py module as well - is that a possibility?  
lisa

**Comment by Swanson-Hysell** [comment]
When Lori and I were discussing ways to reorganize the directory structure, I brought up this pmag.py and ipmag.py merge possibility. Lori's perspective (which she convinced me of at the time) is that it makes sense to keep them separate with pmag.py containing the functions that mostly do a single thing and ipmag.py containing functions that bring pmag.py functions together to do more of a work flow (e.g. do a bootstrap reversal test and have options to save the associated output). In this way, the ipmag.py functions are similar to the command line programs that are built on top of pmag.py functions, but are built to be used without sys.argv calls, etc. The current split between the modules isn't entirely consistent with this design conception, but it largely is. Worth talking about more moving forward...

@moonshoes87 are we good to delete ipmagplotlib?

**Comment by moonshoes87** [comment]
Yes, let’s delete it.  Thanks!

**Comment by Swanson-Hysell** [comment]
I deleted it and I think I have removed the import statements to the module and changed back to pmagplotlib where necessary although some still could be lurking.
