### ISSUE TITLE
demag_gui should read many types of intensity

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#401]
right now, demag_gui expects only magn_moment, but other types are allowed in the data model. it should find the most appropriate one, e.g., using nb.get_intensity_meth

**Comment by moonshoes87** [comment]
I can implement this, but will probably be busy with other things for the next few days.  @Caoimhinmg, let me know if you want to do it, otherwise I will put it on my docket.

**Comment by moonshoes87** [comment]
This should work now -- it will prioritize magn_moment if available in the table and populated with data.  @ltauxe or @Caoimhinmg, feel free to check this out and let me know if you see any problems.
