### ISSUE TITLE
fix formatting/image issues in make_magic_plots for server

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#412]
contribution id should be included in plots
fix formatting issues
title should be displayed in plot not filename
Ultimately, we should have an images table (image name can be simple, just 1.png, 2.png)

**Comment by moonshoes87** [comment]
I've fixed that issue and also merged the error_logging branch into master, so you can use master now on the server.

**Comment by njarboe** [comment]
@moonshoes87  I'm already running master on the server as per previous instruction. Thanks for the reminder and the update.

**Comment by njarboe** [comment]
That fixed it. Thanks.

**Comment by njarboe** [comment]
If it is easy to do instead of the title "all locations" put the actual number of locations plotted. For example "MagIC contribution 12038 all locations(1)" or "MagIC contribution 12038 all locations(15)" , if that is not to complicated. That will help people because they will already know the number of locations that they expect and seeing the value will either make them more confident things are working or give a clue that something is wrong. 

It would be even more useful if you do the same with sites if it is a location pole or direction plot. I'll keep an eye out for one of those plots.

**Comment by moonshoes87** [comment]
This is relatively straightforward.  However, see for example the resulting plot for the McMurdo data:

![mc _13436_ty _pole_map](https://user-images.githubusercontent.com/1836578/47464276-91c14580-d79d-11e8-8487-5610d5be4ffc.png)


There is only one location (McMurdo), but 4 different location rows resulting in 4 different points being plotted.  So, do we actually want the title to reflect how many data points there are, or how many distinctly named locations?

Also, this brings to my attention a bug with polemap_magic.  Since the 4 location rows don't have unique names, the individual plots that are created for each row have the same name and thus keep overwrtting each other.  

Maybe it's time to really upgrade make\_magic\_plots to generate an image table...

**Comment by njarboe** [comment]
Looks nice. A few more suggested changes. 

Change the title to "Pole(4) plot of MagIC_13426, all locations(1)"
This gives a lot of info to people. If they are going to use it in a paper or slide show, they will likely change it, but scientists like to have compact data descriptions like that.

Clean up and change the URL at the bottom to point to the contribution directly. So in this case: https://earthref.org/MagIC/13463

**Comment by ltauxe** [comment]
there should not  be four different poles for this - at most there should be two (one normal and one reverse and maybe one grand mean). and they should all be very close to the north pole so i don’t know what those other poles are (the one in greanland and the one at the equator).  

lisa

**Comment by njarboe** [comment]
@lisa Looking at the location table on the website I see that there are five rows, all with the same name.
One row is just meta data like Outcrop, one is a Normal Pole, one Reversed Pole, one a Grand Mean Pole, and then a row for the Average V[A]DM. We would want only those three (and if we could color code R,N,Combined, that would be even better)

Not sure how one decides on which ones to plot but only 3 have the DE-VGP method code.

This is sure a mess with rows not having all the required fields filled out. We really need to combine rows and get all the meta data correct. I have an issue on the MagIC site:https://github.com/earthref/MagIC/issues/374
where I am listing these problems so we can hopefully fix them efficiently in the future.

**Comment by moonshoes87** [comment]
I am very confused as to why there are 4 points.  It appears that there are 3 lats/lons that are given to plot_magmap:

    lats [84.6, -79.9, 83.1] lons [214.5, 2.7, 197.5]

And that's it.  So why do we have this doubled up point?

I made a simple example that shows the problem:

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

lons = [214.5, 2.7, 197.5]
lats = [84.6, -79.9, 83.1]

ax = plt.axes(projection=ccrs.Orthographic(
    central_longitude=0,
    central_latitude=90))
# plot lat/lon points                                                                                                         
ax.plot(lons, lats, 'ro',
        transform=ccrs.Geodetic())
# plot north pole for reference                                                                                               
ax.plot([0], [90], 'b^',
        transform=ccrs.Geodetic())
# add coastlines for reference                                                                                                
ax.coastlines(resolution='50m')
ax.set_global()

plt.show()
```

Which results in this plot:

![figure_1](https://user-images.githubusercontent.com/1836578/48090089-dea01580-e1ba-11e8-96bf-ed68c26c205d.png)


@ltauxe, @Swanson-Hysell, you have more experience with cartopy than I do, so perhaps you have more insight?  It appears that problems occur mainly when there is a latitude that is close to or below the equator, but instead of just not showing that point it does all kinds of weird unpredictable things.

For example, if I change the latitudes to `[10, 10, 10]` while keeping longitudes as `[214.5, 2.7, 197.5]`, I get this plot:

![figure_1](https://user-images.githubusercontent.com/1836578/48089966-8c5ef480-e1ba-11e8-897c-32f0e0b48b12.png)

Which has 11 points or something??  I guess this is probably just a cartopy bug and I should submit it to them.

**Comment by moonshoes87** [comment]
@njarboe, the full title that you suggested doesn't fit with our current formatting, but I've tweaked that.  

We currently only plot poles with result_type == 'a' (if result type is available) and where pole_lat/pole_lon are both not null.  So in this case we are effectively selecting the pole, reverse pole, and the grand mean.  The McMurdo data have the method codes filled in as well, so plotting all points with the DE-VGP method code would work as well.  I don't necessarily think that would be more robust.

As far as the idea of color-coding the poles, as far as I can tell there is no easy way to do that.  The only place the type of pole is noted is in result_name.  We could color code by location, though, so each of the 1-3 poles for a location would have the same color/symbol.  

So, assuming we can get the cartopy bug fixed, how does this look: 

![mc _13436_ty _pole_map](https://user-images.githubusercontent.com/1836578/48091797-959e9000-e1bf-11e8-9c1a-7c8b8a017ff4.png)

**Comment by moonshoes87** [comment]
Regarding the cartopy bug, I may have found a clue.  When I upgrade to cartopy 0.16.1 (dev), I get this warning:

```
/Users/nebula/anaconda3/lib/python3.6/site-packages/cartopy/crs.py:1476: UserWarning: The Orthographic projection in Proj between 5.0.0 and 5.1.0 incorrectly transforms points. Use this projection with caution.
```

And, at any rate, I've opened this issue on Github

https://github.com/SciTools/cartopy/issues/1172

**Comment by Swanson-Hysell** [comment]
I don't reproduce the issue with my install of cartopy 0.16.0 where your example looks like this:

<img width="438" alt="screen shot 2018-11-06 at 10 46 57 pm" src="https://user-images.githubusercontent.com/4332322/48109659-5f402f80-e216-11e8-8c1d-107139a8d81c.png">

Note that there should only be two points shown in that example since one is in the Southern Hemisphere.

**Comment by moonshoes87** [comment]
@Swanson-Hysell, what version of pyproj do you have? 

    pyproj                    1.9.5.1          py36h833a5d7_1

**Comment by Swanson-Hysell** [comment]
I looks like I am behind you (and should stay that way):

```
proj4                     4.9.3                h470a237_8    conda-forge
```

**Comment by njarboe** [comment]
@moonshoes87 
That title will work. But the purple line on the left is a bit strange.  Also if you would change the MAGIC text in the URL on the bottom to "MagIC". We like that case as it is sort of a branding for us.

**Comment by moonshoes87** [comment]
@njarboe, I have no idea where that purple line came from!  I'll try to get rid of it.  And will fix MAGIC --> MagIC.

**Comment by moonshoes87** [comment]
@njarboe, I have done a bunch of fixes for polemap_magic on the server.  Tell me if there is anything that still doesn't look right.  

Also, once you have similar feedback for the other generated plots, let me know, and I will work on those fixes.

**Comment by njarboe** [comment]
@moonshoes87. Opened another issue #472 with some problems with the plotting. It includes the error and standard log from running most of the contributions we have. Not sure if I should close that one and move the info over here.

I'm out for Thanksgiving week and will take another look at the plots on my return.

**Comment by moonshoes87** [comment]
This has been done to a large extent -- at this point specific requests can be opened in new issues.
