### ISSUE TITLE
problems with freshly downloaded controlled vocabularies json 

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#413]
Trying to update the data model, but something is wrong with the new json I downloaded for controlled vocabulary:

    import pandas as pd
    # no problem 
    pd.io.json.read_json('/Users/***/Python/PmagPy/pmagpy/data_model/controlled_vocabularies_February_6_2017.json')
    # fails    
    pd.io.json.read_json('/Users/***/Python/PmagPy/pmagpy/data_model/controlled_vocabularies_August_9_2018.json')

Both pass validations at jsonlint.com.  Sigh.

**Comment by moonshoes87** [comment]
Well, this makes no sense.  I just pulled out the new json in a few chunks and pasted it into a different file.  And now it works.

**Comment by moonshoes87** [comment]
@rminnett, I'm not sure if this is a concern for you, but it might be relevant for others trying to use the controlled vocabularies/suggested vocabularies json.

Neither file could be parsed by pandas, although jsonlint said they were both valid.  All I had to do to make each file work was to copy and paste its contents into a new json file, which initially had me very confused.

The diff between the working file and the failing file:

    1c1
    < {
    ---
    > ﻿{

The problems turns out to be the initial character \ufeff.

 https://stackoverflow.com/questions/17912307/u-ufeff-in-python-string

I can solve this by specifying the encoding 'utf-8-sig', but I wonder if others could run into this issue and be similarly confused?

**Comment by rminnett** [comment]
Thanks! I wonder if one of the javascript packages changed to produce a JSON string with a leading BOM? I expected it to be UTF-8 encoded, but without the BOM. I'll look into it.
