### ISSUE TITLE
hysteresis_magic.py backfield IRM option failing

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#414]
the backfield IRM option is broken.

**Comment by moonshoes87** [comment]
@ltauxe -- sorry if we've talked about this before (I'm guessing we have).  Looking back in git history, I'm not sure when/if this functionality was working/existed.  Maybe you can help point me in the right direction?

**Comment by Swanson-Hysell** [comment]
Closing for now given the goal of such features being in feature rockmag.py functions
