### ISSUE TITLE
ldeo_magic.py

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#415]
doesn't seem to work at all.

**Comment by moonshoes87** [comment]
@ltauxe, for each conversion script there is a working example in _PmagPy-cli.ipynb and one in pmagpy_tests/test_imports3.py.  (At least, they work in the sense that they run and create output files.)  Let me know more specifically what you are trying that isn't working, and I'll fix it!

**Comment by ltauxe** [comment]
It generates an output file, but the method codes are all wrong so neither demag_gui nor zeq_magic work properly.  they just plot the first point.  
maybe it is because there seems to be an AF step before the thermal, but that never bothered sio_magic….    
lisa

**Comment by ltauxe** [comment]
oh i got it... the codelist can't be blank - must be set to "AF" or something.  on the command line that is -LP AF.  I fixed both notebooks.  I'll add a doc string to make that more clear.

**Comment by moonshoes87** [comment]
great — the docstrings are totally minimal and definitely need more TLC.  Also, should codelist be set to “AF” as the default in ldeo(), instead of default “"?

**Comment by ltauxe** [comment]
I added a bunch of instructions to ldeo_magic and sio_magic.  the rest have at least something although meant for command line and not the convert_2_magic function....

**Comment by ltauxe** [comment]
AHHH my bad - codelist has to be set to something, e.g., ‘AF’.
