### ISSUE TITLE
thellier_gui.py should not require treat_ac_field

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#417]
should not be looking for treat_ac_field.  even if required by the data model it is not required by this program.

**Comment by moonshoes87** [comment]
Is thellier_magic generating an error message, or is something else going wrong?  Could you send the the relevant data file and specific command you were trying?

**Comment by moonshoes87** [comment]
I was looking in thellier_magic, not thellier_gui.  I'll check this out!

**Comment by ltauxe** [comment]
i used  livdb_magic.py to create these files:  

they crash both thellier_gui and thellier_magic because of missing treat_ac_field,  which is required by MagIC but not necessary for this program.  also livdb_magic doesn’t make a sequence column.  both of these errors must be caused somewhere in measurements_methods3 but i haven’t had time to figure it out. 
lisa

**Comment by moonshoes87** [comment]
@ltauxe, I think when you try to attach files to the Github issues via email nothing happens.  You can email me directly or attach 'em on the Github issue page.  If you send me the livdb file, I will check this out.

**Comment by moonshoes87** [comment]
I've found a file that is missing treat_ac_field and crashes Thellier GUI.  I will see about fixes.

**Comment by moonshoes87** [comment]
@ltauxe, I've attempted a fix.  I definitely need you to double-check this one, though.  In both Thellier GUI and thellier\_magic, treat_ac_field is ONLY expected if the method code LT-AF-Z is used.  I added logic to prevent it from crashing, but I need you to check if this is legit.

**Comment by moonshoes87** [comment]
@ltauxe, same for my thellier_magic fix.
