### ISSUE TITLE
refactor plotting programs

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#424]
Goals:

1.  Each plotting program must work on the command line, in a notebook, and in tests.
2. Each command line program should have main() function that is only for the command line logic, and calls an ipmag function that does the calculation.
3. Each program should return a list of saved files.
4. Each program should be able to take a contribution/pandas dataframe argument instead of reading in a data file.

**Comment by moonshoes87** [comment]
Note to self:  I will need to go back and fix PmagPy-cli.ipynb when this is done, but I don't want to do it in a branch as that will just lead to chaos and pain.

**Comment by moonshoes87** [comment]
These programs should all have an option to only plot the first n plots....

**Comment by moonshoes87** [comment]
Next task:  go through alphabetically using PmagPy-cli and make sure that each plotting routine works in all 3 desired ways (command line interactive, save plots, and in notebooks).

**Comment by moonshoes87** [comment]
ani_depthplot -- DONE
aniso_magic -- probably can just refactor to use aniso_magic_nb

**Comment by ltauxe** [comment]
can we recombine aniso_magic to use aniso_magic_nb?  and then get rid of aniso_magic_nb? 
lisa

**Comment by moonshoes87** [comment]
@ltauxe -- yes, I'm going to try to do that on Monday :)

**Comment by moonshoes87** [comment]
@ltauxe, I know you have a few things on your plate, but could you check out my implementation of aniso_magic_nb into aniso_magic.py?  You will need to call it with the -new flag.  Let me know what, if any, changes are needed.

**Comment by moonshoes87** [comment]
Goals:

1. Each plotting program must work on the command line, in a notebook, and in tests.  
2. Each program should return a list of saved files. 
3. Each program should be able to take a contribution/pandas dataframe argument instead of reading in a data file.  

- Plots:
    - [ani_depthplot](#ani_depthplot) : DONE (except for item 3)
    - [aniso_magic](#aniso_magic) : DONE (but have not yet removed -new flag or renamed to ipmag.aniso_magic, pending @ltauxe's check, and item 3) 
    - [biplot_magic](#biplot_magic) : plots different columns against each other in MagIC formatted data files
    - [chi_magic](#chi_magic) : plots magnetic susceptibility data in MagIC format as function of field, frequency or temperature
    - [common_mean](#common_mean) : graphical approach to testing two sets of directions for common mean using bootstrap
    - [core_depthplot](#core_depthplot) : plots MagIC formatted data 
    - [curie](#curie) : makes plots of Curie Temperature data and provides estimates for Tc
    - [dayplot_magic](#dayplot_magic) : makes Day et al. (1977) and other plots with hysteresis statistics
    - [dmag_magic](#dmag_magic) : plots remanence against demagnetization step for MagIC formatted files
    - [eqarea](#eqarea) and [eqarea_magic](#eqarea_magic) : makes equal area projections for directions
    - [eqarea_ell](#eqarea_ell) : makes equal area projections for directions with specified confidence ellipses
    - [find_ei](#find_ei) : finds the inclination unflattening factor that unsquishes directions to match TK03 distribution
    - [fishqq](#fishqq): makes a Quantile-Quantile plot for directions against uniform and exponential distributions
    - [foldtest](#foldtest) & [foldtest_magic](#foldtest_magic) : finds  tilt correction that maximizes concentration of directions, with bootstrap confidence bounds.          
    - [forc_diagram](#forc_diagram): plots FORC diagrams for both conventional and irregular FORCs
    - [hysteresis_magic](#hysteresis_magic) : makes plots of hysteresis data (not FORCs). 
    - [irm_unmix](#irm_unmix) : analyzes IRM acquisition data in terms of coercivity distributions
    - [irmaq_magic](#irm_magic) : plots IRM acquistion data
    - [lnp_magic](#lnp_magic) : plots lines and planes for site level data and calculates best fit mean and alpha_95
    - [lowes](#lowes) : makes a plot of the Lowe's spectrum for a geomagnetic field model
    - [lowrie](#lowrie) and [lowrie_magic](#lowrie_magic) : makes plots of Lowrie's (1990) 3D-IRM demagnetization experiments
    - [plot_cdf](#plot_cdf) and [plot_2cdfs](#plot_2cdfs) : makes a cumulative distribution plot of data
    - [plotdi_a](#plotdi_a) : makes equal are plots of directions and their $\alpha_{95}$s
    - [plot_geomagia](#plot_geomagia) : makes plots from files downloaded from the  geomagia website
    - [plot_magic_keys](#plot_magic_keys) : plots data from MagIC formatted data files
    - [qqplot](#qqplot) : makes a Quantile-Quantile plot for data against a normal distribution
    - [qqunf](#qqunf) : makes a Quantile-Quantile plot for data against a uniform distribution
    - [revtest](#revtest) & [revtest_magic](#revtest_magic) : performs a bootstrap reversals test
    - [thellier_magic](#thellier_magic) : makes plots of thellier-thellier data. 
    - [watsons_v](#watsons_v) : makes a graph for Watson's V test for common mean
    - [zeq](#zeq) and [zeq_magic](#zeq_magic) : makes quicky zijderveld plots for measurement data

- Maps: 
    - [cont_rot](#cont_rot) : makes plots of continents after rotation to specified coordinate system
    - [plot_mag_map](#plot_mag_map) : makes a color contour plot of geomagnetic field models
    - [plot_map_pts](#plot_map_pts) : plots points on maps
    - [polemap_magic](#polemap_magic) : reads in MagIC formatted file with paleomagnetic poles and plots them
    - [vgpmap_magic](#vgpmap_magic) : reads in MagIC formatted file with virtual geomagnetic poles and plots them

**Comment by moonshoes87** [comment]
We're done with this for now.
