### ISSUE TITLE
convert.tdt() not handling additivity checks correctly

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#425]
**What command was run:**
in the _PmagPy_nb notebook:  
convert.tdt('../measurement_import/tdt_magic/')

**What happened:**
All files successfully created, but method_codes are not correct resulting in bizarre thellier_gui plots (see attached).  

**What I expected to happen:**
The problem seems to be in correctly identifying the treatment steps labeled XXX.4 in the file.  These are "additivity checks".  They are being given the code LT-PTRM-I but aren't that.  We need a new method code for this:  LT-PTRM-ADD.   This step is necessary for calculating the statistic dac.  This appears to be an option in thellier_gui, but I have no idea how we were calculating this without correctly identifying the XXX.4 steps as additivity checks. 

**Data file(s):**
PmagPy/data_files/measurement_import/tdt_magic/Krasa_MGH1.tdt

**Screenshot(s):**

![screen shot 2018-08-21 at 3 48 04 pm](https://user-images.githubusercontent.com/174861/44433256-6aaa8580-a55a-11e8-81d9-0be6e0ab930e.png)

**PmagPy version:**

**Comment by njarboe** [comment]
@moonshoes87 I will add a LT-PTRM-ADD, if that is what is needed. @ltauxe Can you give me a description for that method code?

**Comment by ltauxe** [comment]
I think the correct code that thellier_gui is looking for  is LT-PTRM-AC (or LT-PMRM-AC).  Apparently this is not in the method code list (?).    it needs to be added in the conversion script and the list.  The description would be "PTRM additivity check step”.   the reference would be the Leonhardt paper.

**Comment by ltauxe** [comment]
now the conversion script is behaving properly, but thellier_gui is not.
