### ISSUE TITLE
Method codes in mini_magic

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#432]
@ltauxe, can you take a look at the first few lines of convert_2_magic.mini?  I don't think the method codes were ever handled correctly here, and I'm not sure what the intention was exactly.  I moved the parsing of method codes from mini\_magic.py to convert_2_magic.mini and made a few guesses, but I don't know what the method code for Thermal demag actually ought to be.

**Comment by ltauxe** [comment]
deprecated the offending file.
