### ISSUE TITLE
add cookbook example for irm_unmix.py

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#435]
I tested this contribution by @botaoxiongyong and it works well.   I think we should add it to the PmagPy distribution - BUT, there are some dependencies and subtleties about the installation.  Lori, how do you think we should go about it. is there a straightforward way to add this without complicating the PmagPy install process?

**Comment by moonshoes87** [comment]
See the [PR](https://github.com/PmagPy/PmagPy/pull/436)

**Comment by moonshoes87** [comment]
example is added to PmagPy.ipynb -- interactive program doesn't work for PmagPy-cli.ipynb.
