### ISSUE TITLE
deprecate iodp_dscr_magic

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#440]
iodp\_dscr\_magic and iodp\_jr6\_magic examples are missing from PmagPy.ipynb

**Comment by ltauxe** [comment]
let's depricate iodp_dscr_magic and i added the iodp_jr6_example data.

**Comment by moonshoes87** [comment]
Just to confirm — i will remove iodp_dscr_magic from Pmag GUI, PmagPy-cli.ipynb, and remove iodp_dscr_magic from programs?

**Comment by ltauxe** [comment]
can you just move iodp_dscr_magic to the deprecated folder?  All of those IODP programs will be updated when I go out to sea with the new system.  
lisa

**Comment by moonshoes87** [comment]
I definitely can move it, but then it won’t be available by default for Pmag GUI and the notebooks.  If you want people to still have easy access to it, we should leave it where it is and update when you’re at sea.  Let me know which you prefer!

**Comment by ltauxe** [comment]
this should disappear from the Notebook and pmag_gui anyway - it is hopelessly out of date.  
lisa

**Comment by moonshoes87** [comment]
Great, I will do it!

**Comment by moonshoes87** [comment]
should iodp_srm_magic be deprecated as well?

**Comment by ltauxe** [comment]
yeah i think so.  these are all hopelessly out of date.  i will rewrite the whole thing when i go out on the ship. 
lisa

**Comment by moonshoes87** [comment]
So, iodp_jr6_magic, iodp_samples_magic should be removed as well?

**Comment by moonshoes87** [comment]
Update: we're leaving these all in place, they will just be updated when Lisa is at sea.
