### ISSUE TITLE
Problems in Binder

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#445]
**PmagPy.ipynb**

irm_unmix fails because of 

    ImportError: libGL.so.1: cannot open shared object file: No such file or directory

probably need Pyqt5

**PmagPy-cli.ipynb**

Lots of programs:

    _tkinter.TclError: no display name and no $DISPLAY environment variable

I don't think this happened before....

    ModuleNotFoundError: No module named 'wx'

**Comment by moonshoes87** [comment]
https://github.com/conda-forge/pygridgen-feedstock/issues/10

**Comment by ltauxe** [comment]
that is reasonable.

**Comment by moonshoes87** [comment]
Great.  Everything is now working in the vanilla PmagPy Binder, and we can still move forward with providing specific workflow demos.
