### ISSUE TITLE
Anaconda default install is now Python 3.7

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#446]
Anaconda default install is now Python 3.7.

I have done a fresh OSX pip install. Anaconda default is 3.7 but pmag_gui and both demag_gui and thellier_gui work at first glance. @moonshoes87  Do you expect and issues with moving to 3.7?

**Comment by moonshoes87** [comment]
That is good to know. I will set up the test environment to run python 3.7, which should help expose possible errors. I will also try upgrading.  There may not be a version of wxpython for python 3.7 on Linux, so I will make sure to note that in the Linux install.

**Comment by ltauxe** [comment]
everything of mine still works with 3.7 except basemap.  ideas?  
lisa

**Comment by moonshoes87** [comment]
Is this a new Basemap issue, or just the same problem that Basemap needs to be used in a conda env?  If it is the same old problem, I recommend just creating a conda env.

The alternative is that you could *try* downloading this version of Basemap if you really want to use it in your base env with Python 3.7.  I think this is before the breaking change:  https://anaconda.org/conda-forge/basemap/1.1.0/download/osx-64/basemap-1.1.0-py36h50ae964_6.tar.bz2

You should be able to install and then `conda install basemap-1.1.0-py36h50ae964_6.tar.bz2`.

**Comment by moonshoes87** [comment]
I got tests passing in the 3.7 environment, so aside from Basemap troubles, I would say we are currently supporting 3.6 and 3.7.

@njarboe, in your fresh install, do you get matplotlib 3.0 or matplotlib 2.*?  There are some issues with matplotlib 3.0.0 and setting the backend correctly.

**Comment by njarboe** [comment]
@moonshoes87 Sorry I did not see your question earlier. Just saw that you closed it. The fresh install had matplotlib 2.2.3.
