### ISSUE TITLE
Use cartopy instead of Basemap for the Demag GUI vgp viewer

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#449]

**Comment by Swanson-Hysell** [comment]
https://github.com/PmagPy/PmagPy/issues/292#issuecomment-425591772

**Comment by Caoimhinmg** [comment]
@Swanson-Hysell I can take a look at it this weekend if y'all want. Sorry I've been so out of commission, but I've been meaning to add a map projection option to that dialog for a long time and I need to learn Cartopy anyway. I'll also see if I can work on some of the lingering Demag GUI issues a bit.

**Comment by Swanson-Hysell** [comment]
If you can that would be great. The new ipmag functions using cartopy could be a helpful guide. And there is now a function in ipmag that plot dp/dm that it could make sense to use for plotting site-level means.

**Comment by ltauxe** [comment]
check out the PmagPy notebook and pmagplotlib.plot_map for help on cartopy implementation.

**Comment by Caoimhinmg** [comment]
@Swanson-Hysell and @ltauxe, sounds good I'll take a look this weekend. There is also plenty of screen room on that dialog maybe I'll add a radio button for dp/dm vs. a95 so you can switch between that shouldn't be too hard.
