### ISSUE TITLE
standalones won't compile (again) for OSX

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#450]
Pyinstaller requires brew python not Anaconda Python, but there are some new issues.

To make cartopy work:

- pip install cython
- brew install proj
- pip install cartopy

wxPython is also a problem.  I'm working on it.

**Comment by moonshoes87** [comment]
Mostly working, but Thellier GUI plot paleointensity curve with show map gives this error:

    Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3991.

Fixed by:

    pip install geos --upgrade

**Comment by moonshoes87** [comment]
To make the executables with Pyinstaller, I can't use Anaconda Python but must install python with brew/pip instead.  Unfortunately, cartopy isn't cooperating.  @Swanson-Hysell, @ltauxe, did you encounter any error messages like this while you were working with cartopy?

    plot_magmap.py -el B

    ...
    Unknown exception thrown
    Geometry must be a Point or LineString
    Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3991.
    Abort trap: 6

**Comment by moonshoes87** [comment]
Tried:

    pip install Pillow

which means I can now `import geos` without errors.  But problems persist.

**Comment by moonshoes87** [comment]
Cartopy killing the kernel in Jupyter:  https://github.com/SciTools/cartopy/issues/738

Trouble installing cartopy:  https://github.com/SciTools/cartopy/issues/823

**Comment by moonshoes87** [comment]
Here's what I've done to get brew Python up and running (sort of) with cartopy:

`brew install python`
`pip3 install pandas numpy scipy matplotlib future`

There are issues with installing geos, shapely, and cartopy together.  https://stackoverflow.com/questions/11294556/missing-libgeos-c-so-on-osx

Installing with pip, geos version == 0.2.0.  Installing with brew, I can get 3.7.0 and geos lives here:

    /usr/local/Cellar/geos/3.7.0/lib/libgeos-3.7.0.dylib

I am trying following these instructions to install geos and all of its dependencies:  https://stackoverflow.com/questions/11294556/missing-libgeos-c-so-on-osx

Then, once all dependencies are installed, `pip3 install cython`, `pip3 install cartopy`.

(Possibly needed:  `pip3 install pillow`.)

The above fixed some of the environment issues I was having, but plot_magmap still exits with a BusError.

Tried installing geos with brew and pointing cartopy and shapely to geos:  https://github.com/Toblerity/Shapely

but so far this doesn't help either.

**Comment by ltauxe** [comment]
we can just take the cartopy stuff out of the GUIs - they really are not that important….   
lisa

**Comment by moonshoes87** [comment]
@ltauxe, maybe I just take map plotting out for the executables only.  Also, this makes me appreciate how reasonably smoothly things go with Anaconda!  Brew-installed Python is just all over the place.

**Comment by Swanson-Hysell** [comment]
I had the same thought about being grateful for conda as I saw this issue progress. I am ok with the map plotting not being in the executables. It is just a minor add-on functionality in demag_gui at present.

**Comment by moonshoes87** [comment]
Ok, in this case I believe I have solved everything else to make the executables run.  I will see about blocking the cartopy functionality in a way that causes the least amount of confusion/frustration.

**Comment by moonshoes87** [comment]
Wow, leaving out cartopy/basemap slashes the size of the executables -- they are down to 87 MB each!

**Comment by moonshoes87** [comment]
@ltauxe or @njarboe, if either of you have a chance to just download Pmag GUI and open it, it would be nice to have a little assurance that it works on another machine.  https://github.com/PmagPy/PmagPy-Standalone-OSX/releases/tag/4.2.1

**Comment by Swanson-Hysell** [comment]
The newest Pmag GUI executable is working for me!
