### ISSUE TITLE
Demag GUI overwriting intensity

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#454]
demag\_gui.py is overwriting intensity records during the Save MagIC tables step.  It looks like  meas_step_min/meas_step_max/method_codes are the affected columns.  

@Caoimhinmg or @Swanson-Hysell, do either of you want to work on this?  If not, I am happy to get into it, I'm  just less familiar with this code.  

[measurements.txt](https://github.com/PmagPy/PmagPy/files/2497127/measurements.txt)
[specimens.txt](https://github.com/PmagPy/PmagPy/files/2497128/specimens.txt)

**Comment by moonshoes87** [comment]
Whoops, I named the fix incorrectly, but here it is:

5de16068c168774250451b4acf62a37759e3d793

**Comment by Caoimhinmg** [comment]
@moonshoes87, at a glance it looks okay, though I think on line 6750 that should be a ~ not a - sign. I'll try to test the code in a few days or this weekend.

I think it is a great idea to add some kind of concatenation logic to MagicDataFrame.merge_dfs. The original idea when I made that function was to abstract a way to correctly preserve data in the old mdf while at the same time replacing it with new data from another mdf that way it could theoretically apply in any case where you want to update your data files after analysis. Not sure I ever managed to get it to work perfectly though. I suppose it should split the data into directional and non-directional rows...maybe with a keyword argument then merge them at the end.

**Comment by moonshoes87** [comment]
Thanks, @Caoimhinmg. It '-' and '~' seem to work the same on a boolean Series, but I think '~' is the accepted convention.  

Let me know when you've had a chance to test it :)

**Comment by moonshoes87** [comment]
I assume this is working correctly, so I am closing the issue.
