### ISSUE TITLE
Review/debug import scripts in Pmag GUI

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#455]
Go through all of the import scripts in Pmag GUI from start to finish.  There will be bugs.

**Comment by moonshoes87** [comment]
@ltauxe, I am running through all of the import types in Pmag GUI and fixing bugs.  I'm wondering, what do you want me to do when everything *works*, but what is coming out looks a bit weird, i.e. the MIT example:

![7325b71_zij](https://user-images.githubusercontent.com/1836578/47394843-3af23800-d6d9-11e8-9496-52540a36d373.png)

**Comment by Swanson-Hysell** [comment]
I plotted that data up in another plotting program. It is a really weak low-coercivity poorly behaved sample. The weirdness is in the data not the code.

**Comment by moonshoes87** [comment]
Thanks, good to know!
