### ISSUE TITLE
jr6_jr6 example files corrupted

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#456]
It looks like Roi's files are still corrupted.  The example in PmagPy.ipynb isn't working (again?).  @ltauxe , did you fix these?  If so, something in the code is re-corrupting them, I guess.  We should figure out what that is.

**Comment by ltauxe** [comment]
well that is weird.  it works fine on mine.  here is the file.  try overwriting yours with this one….  
lisa

**Comment by ltauxe** [comment]
I can't attach the files so sent by email.

**Comment by moonshoes87** [comment]
Turns out the problem was just with string matching -- the notebook was trying to read in a sites file as if it was a jr6 measurements file.  I will just update PmagPy.ipynb and it will be fine.
