### ISSUE TITLE
"Export result tables" in Pmag GUI was never upgraded to 3.0

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#459]
@ltauxe, do we want to upgrade ipmag.pmag_results_extract to 3.0?  It is called in Pmag GUI, but is still stuck in 2.5.  Is generating a table like that still useful for people writing papers, etc.?

**Comment by ltauxe** [comment]
in this case we would just pick out columns from the site table, split them into intensities and directions and spit out two tables.  i guess this is still useful.  I’ll take a look.
lisa

**Comment by moonshoes87** [comment]
@ltauxe, this looks good.  I added ipmag.extract_sites back into Pmag GUI and added some tests.

Should we add the criteria functionality back in?  Also, some of the column spacing seems off in the LaTeX output.  Should we try to make it line up more precisely?

**Comment by ltauxe** [comment]
Funny thing I noticed - if you typeset it twice it is fine

**Comment by ltauxe** [comment]
And yes I’ll do specimens, criteria and locTion averaged

**Comment by moonshoes87** [comment]
Great, I’ll put them into Pmag GUI when ready.

**Comment by moonshoes87** [comment]
@ltauxe, I've tested all 3 functions and implemented them into Pmag GUI.  I'll leave this issue open until you add the extract_locations function as well that you had mentioned?

**Comment by ltauxe** [comment]
I think we skip extract_locations unless there is a demand from the community.
