### ISSUE TITLE
Pmag GUI step 3: Added location should be available in drop down menus

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#460]
A location added during Pmag GUI step 3 should be available in the drop-down-menu in the sites table, but it appears not to be.

**Comment by yanyongg** [comment]
There is an error when importing my 2G binary datafiles using Pmag_gui.py. The error is not always occurred when importing data. Is there anything wrong with the name of my dadafiles as shown below?
![1](https://user-images.githubusercontent.com/38656591/48658109-1f2f4700-ea77-11e8-9c2c-22f851a3d2ca.png)
![2](https://user-images.githubusercontent.com/38656591/48658111-22c2ce00-ea77-11e8-953a-1a43b55e2b3f.png)
![3](https://user-images.githubusercontent.com/38656591/48658126-484fd780-ea77-11e8-9996-d9df5cea0434.png)

**Comment by moonshoes87** [comment]
@yanyongg, thanks for reporting this bug.  I am not sure what is causing this problem.  Could you zip your data files and attach them to this issue?  Or, if you prefer to keep them private, you can email them to me at ljonestrask@ucsd.edu.  Thanks!
