### ISSUE TITLE
central_longitude breaks map for make_mollweide_map and make_robinson_map

### ISSUE THREAD

**Issue by yuempark** [PmagPy/PmagPy#464]
**What command was run:**
```
map_ax = ipmag.make_mollweide_map(figsize=(8,8), central_longitude=110, land_color='bisque')

for i in range(len(NP_compiled.index)):
    ipmag.plot_pole(map_ax,
                    NP_compiled['lon'][i],NP_compiled['lat'][i],NP_compiled['a95'][i],
                    color=colors[i], edgecolor=colors[i])
```

**What happened:**
If any central_longitude other than 0 is used, the map does not plot correctly:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/13757095/47609830-5623b700-d9fb-11e8-9bae-2b88d1d6bf4f.png">

However, make_orthographic_map works as expected.

I could look into why this error is occurring/how to fix it, but it would have to be a little later.

**Comment by moonshoes87** [comment]
@yuempark, it looks like this is cartopy bug which will be fixed in the next release (0.17.0), hooray!

In the meantime, you can use the development version of cartopy:  

    pip install git+git://github.com/SciTools/cartopy.git

**Comment by ltauxe** [comment]
this is a cartopy bug - i’ve been trying to figure out how to fix it for months now.  I think we must be patient. 
lisa

**Comment by moonshoes87** [comment]
@ltauxe, It is fixed in the latest version of cartopy, which will be released soon (or can be downloaded from GitHub now).

**Comment by ltauxe** [comment]
halleluja

**Comment by yuempark** [comment]
great! thanks for the heads up.

**Comment by moonshoes87** [comment]
@yuempark, could you send me the data you were trying to plot?  I am missing the NP_compiled variable.  I thought this issue was solved but it just cropped up again in a different place.  It looks like it might depend not just on the central_longitude but also on the specific points you are trying to plot.

**Comment by yuempark** [comment]
@moonshoes87 - NP_compiled is a pandas dataframe. The relevant columns are:

```
lat,lon,a95
9.3,165.9,4.3
13.2,155.2,5.3
47.6,46.7,5.6
51.6,90.5,14.43537321997599
13.5,91.0,10.892658077806354
45.1,130.4,19.0
```

**Comment by moonshoes87** [comment]
@yuempark, ok, great.  This seems to work as expected with the latest version of cartopy, so I am closing this issue!
