### ISSUE TITLE
print user warnings for demag_gui fits when there are multiple measurements with same treatment step

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#47]
Make it so that this warning is given when needed (it already is, but needs to provide more information):
"There are multiple 'good' XXX steps. The first one will be used for fit XX."

Make it so that this warning is given when needed:
"Within Fit XX, there are multiple good measurements at the XXX step. Both measurements are included in the fit."

**Comment by Caoimhinmg** [comment]
Put in lots of warnings and made sure that it also reports the bound that it is altering upper or lower, alterations to included measurements should be apparent now.

**Comment by Swanson-Hysell** [comment]
"Within fit XX for specimen XXX-XX, there are multiple good measurements at the XXX step. Both measurements are included in the fit."

**Comment by Caoimhinmg** [comment]
Done
