### ISSUE TITLE
polemap_magic.py problems

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#471]
@ltauxe, should we drop_duplicates in polemap_magic?

For example, I have contribution 12622 which has two rows with identical location names and pole_lat/pole_lon.  The only difference in the rows is dir_tilt_correction.  If we are plotting all, can we just drop the redundant records?

**Comment by moonshoes87** [comment]
www.earthref.org/MagIC/12622

**Comment by ltauxe** [comment]
we want the dir_tilt_correction to be 100 if available, then 0, then nothing.  if the pole positions are identical, yes they can be dropped. 
lisa

**Comment by moonshoes87** [comment]
Ok, I will drop_duplicates.

@ltauxe, the current default behavior is to plot all rows without regard to dir_tilt_correction unless `-crd` is specified.  Do you want me to change to prioritizing 100 --> 0 --> blank?

One more minor thing -- if reverse poles are included in the pole count, we get plot titles for the server like "1 location, 3 poles" where only 2 poles are visible.  I prefer to ignore negative latitudes in the count, so it says "1 location, 2 poles" instead.  Do we want to do something with reverse poles other than just ignore them?  @njarboe, thoughts for the server?

**Comment by ltauxe** [comment]
yes - it makes no sense to plot different coordinate systems on the same map.  
for the reverse poles, I would take the antipode (abs lat and lon+180) and use a different symbol (like white with black edges).  then all the poles show up in one hemisphere.  
lisa

**Comment by moonshoes87** [comment]
@ltauxe, we don't want to plot any poles with `result_type == 'i'`?  That is the current behavior for polemap_magic, which excludes a lot of rows.  

I'm wondering if these contributions like 12003, which has only 'individual' location results, are a result of people using result_type differently/incorrectly?  And we might still want to plot some of these on the server?  https://earthref.org/MagIC/12003  Let me know if this behavior would be worth modifying.

**Comment by njarboe** [comment]
@ltauxe @moonshoes87 
For poles I think the result_type should always be "a" for average. A single site pole is VGP but what we mean by pole is a decent number of site poles that can be average to get the GAD pole direction at a specific small time-window. 

result_type has always been a bit of a confusing label for me. A site direction is labeled with an "i" even though it is an average of many sample directions. Do you have a good description @ltauxe that I could put in the data model. Seems like we can ignore it for now as it is used incorrectly quite often and I don't see the case where it is useful.

We have: Individual (i), average (a), model (m) or stacked (s) data

but i can be and average and how does stack differ from average?

I'd like to fill in some examples in the data model and maybe some notes describing when to use each of these (model seems clear, but do we put model data in MagIC at all?)

Thanks for the plotting update Lori, I'll do another run of the plots this afternoon.

**Comment by ltauxe** [comment]
yeah.  resuit_type has been poorly understood and populated incorrectly by many many contributions - it is basically meaningless.  the only results in the location table SHOULD be averages of a bunch of sites (paleomagnetic poles and opposed to virtual poles) but probably a lot of contributions are wrong.  
lisa

**Comment by moonshoes87** [comment]
Ok, at this point every problem that has been raised for polemap_magic has been squared away, so I am closing this issue.
