### ISSUE TITLE
would it be interesting to add field model of CALS10k.2

### ISSUE THREAD

**Issue by botaoxiongyong** [PmagPy/PmagPy#477]
Recently I rewrite a python interface for the model CALS10k.2, which originally in FORTRAN.

Now the model can run directly in python, also in Jupyter Notebook. One can calculate the global field at specific time, and for the whole time range at specific location.

A Notebook example is here [CALS10k_example.ipynb](https://github.com/botaoxiongyong/pyMagModel/blob/master/CALS10k2/CALS10k_example.ipynb)

I am not sure whether this is useful or interesting for you. Should I make a pull request?

**Comment by ltauxe** [comment]
Cals10k.2 is already in igrf.py - along with a bunch of other models. see
the example in PmagPy.ipynb

Thanks for this

On Wed, Dec 5, 2018 at 6:51 AM Jiabo <notifications@github.com> wrote:

> Recently I rewrite a python interface for the model CALS10k.2, which
originally in FORTRAN.

Now the model can run directly in python, also in Jupyter Notebook. One can
calculate the global field at specific time, and for the whole time range
at specific location.

A Notebook example is here CALS10k_example.
<https://github.com/botaoxiongyong/pyMagModel/blob/master/CALS10k2/CALS10k_example.ipynb>

I am not sure whether this is useful or interesting for you. Should I make
a pull request?

**Comment by botaoxiongyong** [comment]
good, I should check this first then.

**Comment by botaoxiongyong** [comment]
Nevertheless, you may check the different ways of calculating coefs. [CALS10kcoefs.py](https://github.com/botaoxiongyong/pyMagModel/blob/master/CALS10k2/CALS10kcoefs.py) and [pmagpy/cals10k.py](https://github.com/PmagPy/PmagPy/blob/master/pmagpy/cals10k.py)

**Comment by ltauxe** [comment]
yes - i do it the same for all the models, but i think the smoothing between the different models is not quite right in pmag.doigrf()   I’ll take a look at how you are doing it.  thanks! 
lisa
