### ISSUE TITLE
thellier_magic issues with contribution 13238

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#483]
**What command was run:**

Contribution 13238
`thellier_magic.py -f measurements.txt -fsp specimens.txt -sav -fmt png`

**What happened:**

```
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 100, in <module>
    main()
  File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 91, in main
    spec, "all", save_plots, fmt)
  File "/Users/nebula/Python/PmagPy/pmagpy/ipmag.py", line 10086, in thellier_magic
    AZD, araiblock, zijdblock, this_specimen, units[-1])  # make the plots
IndexError: string index out of range
```

This is the code in ipmag.thellier_magic that is failing:
```
zijdblock, units = pmag.find_dmag_rec(
                this_specimen, spec_df, version=3)
            zed = pmagplotlib.plot_arai_zij(
                AZD, araiblock, zijdblock, this_specimen, units[-1])  # make the plots          
```
No units are found in find_dmag_rec().  

Method codes used in this measurement table:

```
['LT-NO', 'LP-T-I', 'LP-PI-TRM', 'LP-PI-II', 'LP-PI-ALT']
['LT-T-I', 'LP-PI-TRM', 'LP-PI-II', 'LP-PI-ALT']
```

However, units are only assigned in pmag.find_dmag_rec() if LT-AF-Z, LT-T-Z, or LT-M-Z are found.  So the datablock is returned, but no units are.  This leads to problems when pmagplotlib.plot_arai_zij is called.

@ltauxe, any idea how to handle this?

**Data file(s):**

[magic_contribution_13238.txt](https://github.com/PmagPy/PmagPy/files/2658799/magic_contribution_13238.txt)

**Comment by ltauxe** [comment]
if no units are found, the data are “dimensionless”.  can we assign units to “” in that case and put in a special case in plot_arai_zij.  
lisa

**Comment by moonshoes87** [comment]
I put in some default behaviors to avoid everything breaking in this situation.  However, I discovered why this seems to be happening, and it might be a problem in the livdb file:

There is only 1 measurement for specimen ATPIPV22-10B:

```
Elliot Hurst    This study  33.53   25.37   ATPIPV22-10B:LP-PI-TRM:LP-PI-BT-IZZ\
I:LP-PI-ALT-PTRM JR6 old:oven    8.823e-06   273.0   ATPIPV22-10B:LP-PI-TRM:LP-\
PI-BT-IZZI:LP-PI-ALT-PTRM_0   LT-NO:LP-PI-TRM:LP-PI-BT-IZZI:LP-PI-ALT-PTRM    g\
   377 ATPIPV22-10B    u   9999:99:99:99:99        0.0 0   90  0   273.0
```

And in the original data file:

```
ATPIPV22-10B,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,TH-PI-IZZI+,Elliot Hurst\
,JR6 old,oven,5mT AFD done before each measurement,20130828,DBRem2New_20130911,\
11.15,2500
0,0,0,6.645400E+003,4.404250E+003,3.779850E+003,27.88,0,0,90,99/99/9999,99:99,,\
 0,Z, 0, 0, 1, 0, 0, 0, 0
END
```

So now that I've fixed the plots to "work", they are still kind of stupid, i.e.:

![atpipv22-10b_arai](https://user-images.githubusercontent.com/1836578/49758049-ce280280-fc72-11e8-998d-9793428ffe8e.png)

Should something different be done with this measurement in the conversion script, or is this all just fine?

**Comment by moonshoes87** [comment]
I think livdb is Ron's code originally.  I did a little bit of surgery in there to get it into convert_2_magic, but it's mainly his.  I don't really know what should happen to measurements like that.  I guess they should be left in?

**Comment by moonshoes87** [comment]
Lori to do:  Change thellier_magic to only plot if you have at least 3 points.

Lisa to do:  Figure out why the livdb conversion isn't working awesomely:  /data_files/convert_2_magic/livdb_magic/TH_IZZI+/
