### ISSUE TITLE
pmag.domean is not setting mpars['specimen_dang'] for calculation type DE-BFL-A

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#484]
In pmag.domean:

`  if calculation_type == 'DE-BFL-A':`

should 'specimen_dang' ('dir_dang') be assigned?  Currently it is not, which is causing errors in zeq_magic.py with certain contributions.  Or, at least, can mpars['specimen_dang'] be assigned to ""?

**What command was run:**

`zeq_magic.py -sav -fmt png -crd s`

**What happened:**

```
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/programs/zeq_magic.py", line 588, in <module>
    main()
  File "/Users/nebula/Python/PmagPy/programs/zeq_magic.py", line 493, in main
    mpars['specimen_dang'])
KeyError: 'specimen_dang'
```

@ltauxe?

**Data file(s):**

[magic_contribution_13631.txt](https://github.com/PmagPy/PmagPy/files/2658849/magic_contribution_13631.txt)

**Comment by ltauxe** [comment]
no as it by definition is anchored to the origin so DANG would always be zero (and meaningless).  you could assign it to “” or 0.  
lisa
