### ISSUE TITLE
demag_gui cookbook instructions need updating

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#493]
demag_gui cookbook instructions need updating. They refer to pmag tables that are gone in data model 3.0 among other things that are possibly out of date.

**Comment by moonshoes87** [comment]
I will work on this!

**Comment by moonshoes87** [comment]
I've made updates for MagIC 3.0 accuracy and clarity in the Demag GUI install instructions.  Those are now up.  @njarboe, if you wanted to have a look, that would be great.
