### ISSUE TITLE
Current Tauxe 2004 data file on MagIC does not load into demag_gui

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#494]
This files used to upload into demag_gui, so the bug is probably in the program and not the data file. On the most recent developer pull when I run pmag_gui.py, unpack this file just downloaded from MagIC:
[magic_contribution_16533.txt](https://github.com/PmagPy/PmagPy/files/2707709/magic_contribution_16533.txt)
 and then try to run demag_gui, I get this error:

pmag_gui.py
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
objc[64204]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa3bcbcd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x117eddcd8). One of the two will be used. Which one is undefined.
-I- Read in any available data from working directory
-I- Using cached data model
-I- Read in any available data from working directory
-I- running python script:
 download_magic.py -f magic_contribution_16533.txt -WD /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004 -ID /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004 -DM 3
working on:  'contribution'
1  records written to file  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/contribution.txt
contribution  data put in  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/contribution.txt
working on:  'locations'
3  records written to file  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/locations.txt
locations  data put in  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/locations.txt
working on:  'sites'
52  records written to file  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/sites.txt
sites  data put in  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/sites.txt
working on:  'samples'
271  records written to file  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/samples.txt
samples  data put in  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/samples.txt
working on:  'specimens'
225  records written to file  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/specimens.txt
specimens  data put in  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/specimens.txt
working on:  'measurements'
3072  records written to file  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/measurements.txt
measurements  data put in  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/measurements.txt
working on:  'criteria'
20  records written to file  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/criteria.txt
criteria  data put in  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/criteria.txt
working on:  'ages'
20  records written to file  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/ages.txt
ages  data put in  /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004/ages.txt
-I- running python script:
 demag_gui.py -WD /Users/njarboe/Dropbox/MagIC/testing/Tauxe2004
data model: 3.0
-I- Using magn_moment for intensity
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/pmag_gui.py", line 501, in on_btn_demag_gui
    evt_quit=DemagGuiExitEvent)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 244, in __init__
    self.Data, self.Data_hierarchy = self.get_data()
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 4159, in get_data
    Data[s]['measurement_names'].append(rec['measurement'])
KeyError: 'measurement'

**Comment by njarboe** [comment]
Looks good. Thanks.

**Comment by moonshoes87** [comment]
I need to do a bit more to make sure all edge cases are covered, and re-release, but I can’t do that until I have WiFi again! Should be December 29 or 30 at the latest.
