### ISSUE TITLE
Problem with eqarea_magic.py

### ISSUE THREAD

**Issue by jbowles100** [PmagPy/PmagPy#497]
Lines 105-107 (first three below) were already there.  Get error that "do_plot called before defined".  So added next two lines.

    if save_plots:
        do_plot = True
        verbose = False
    else:                       #### ADDED LINE
        do_plot = False   #### ADDED LINE

**Comment by moonshoes87** [comment]
@jbowles100, I believe this is fixed.  If you have a developer install, you should be able to pull and test it out.  If you installed with pip, let me know and I will make a new release so you can check it.  Thanks!

**Comment by jbowles100** [comment]
Hi Lori,

I was wondering when this change might be reflected in the pip release?

Thanks,

Julie

**Comment by moonshoes87** [comment]
Hi Julie,

I just pushed up the new release now (4.2.19).  We usually make releases about once a month, but I can usually do one ASAP if it is needed, so feel free to ask!

thanks,
Lori

**Comment by jbowles100** [comment]
Thank you!!

**Comment by jbowles100** [comment]
Hi again, Lori.  Thanks for pushing this through.  We had a chance to test this out in class today, and the result seems to be that it works fine on the Mac (developer or pip install), but not on Windows machines (all with pip install).  Since I’m working off a developer version on a Mac, it’s a bit hard for me to track down the source of the problems on a PC.

Cheers,

Julie

**Comment by moonshoes87** [comment]
Thanks @jbowles100 -- I will try this on my Windows virtual machine and see what I can find.  I don't always test everything on Windows, so those bug reports are especially helpful!

**Comment by moonshoes87** [comment]
@jbowles, when I investigated it seemed like the problem was related to trying to save plots on Windows, and the program sometimes running very slowly.  I believe I have fixed that (on master).  Was there any other issue that your students were encountering on Windows?  If not, I will go ahead and make a new release with the fix.  If so, could you send me more details about what else was going wrong?  Thanks!

**Comment by moonshoes87** [comment]
We've made a release or two since this fix, so I'm closing this issue.  @jbowles100, please let me know if I've missed something!
