### ISSUE TITLE
Some plotting format problems

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#501]
I'm working on the plot server again in prep for Rupert setting up the linking to the live site. I'm going to focus on problems with data files that pass the current more extensive validation so there should be less problems with missing data causing errors.

For Magic file 
[magic_contribution_16502.txt](https://github.com/PmagPy/PmagPy/files/2770989/magic_contribution_16502.txt)
I get these plotting problems:
The main title obscures the specimen name
http://34.236.167.37/plots/16502/SP:_cr405g1-CZb_TY:_arai_.png
![](http://34.236.167.37/plots/16502/SP:_cr405g1-CZb_TY:_arai_.png)

For this plot:
[http://34.236.167.37/plots/16502/LO:_Costa%20Rica_SI:_cr405_SA:_cr405g_SP:_cr405g1-CZb_CO:_g_TY:_eqarea_.png](url)

![](http://34.236.167.37/plots/16502/LO:_Costa%20Rica_SI:_cr405_SA:_cr405g_SP:_cr405g1-CZb_CO:_g_TY:_eqarea_.png)

Is it hard to add the MagIC Id onto the web address? That would be nice. I think we talked about this before, but not sure of the resolution. You can also drop the http:// at this point. The date would be more compact and still unambiguous if you use the format yyyy-mm-dd, time. 

So 2019-01-17, 8:03:24 PM                                           earthref.org/MagIC/16502

If you can add if the equal area plot is a of a location, site, or specimen that would be very useful. Not sure the best way to do that. Maybe by adding to the main Title. "Location Equal Area Plot" might be more flexible than next to the location name.

Zijderveld Plot title also obscures the specimen name. Seems there is an extra blank line that could be removed.
[http://34.236.167.37/plots/16502/SP:_cr405g1-CZb_TY:_zijd_.png](url)

![](http://34.236.167.37/plots/16502/SP:_cr405g1-CZb_TY:_zijd_.png)

Please excuse me if I have repeated any issues. It has been awhile since I was working on these. It is now the top priority for Rupert at MagIC so hopefully we will have plots back into MagIC soon.

I did not see a good label for this issue, so I picked "Bug - Does not Affect Features" as a stand in.

**Comment by moonshoes87** [comment]
With my new fixes:

![fixed_arai_](https://user-images.githubusercontent.com/1836578/51634846-1d1bb580-1f0a-11e9-999e-f8225dad2017.png)

![fixed_zijd](https://user-images.githubusercontent.com/1836578/51634893-3f153800-1f0a-11e9-81fd-f165430ce4c9.png)

I *think* I have fixed everything in this issue.  Please open a new issue for what comes next, or reopen this if these fixes don't look right.
