### ISSUE TITLE
Maximum recursion depth environment error (pandas 0.24.0)

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#503]
Weird problems are happening with maximum recursion depth errors.  I think this might have to do with the version of pandas, but when I try to downgrade pandas, I get other strange errors:  https://github.com/ContinuumIO/anaconda-issues/issues/10557

See eqarea_magic.py examples in PmagPy-cli.ipynb.  Possibly matplotlib figures need to be closed that aren't getting closed?  But why did this just start causing problems when it didn't before?

**Comment by moonshoes87** [comment]
Two fixes, one permanent and one temporary:

- downgrade pandas to 0.23.4 (0.24.0 causes things to break).  
- use plt.close() in pmagplotlib.save_plots

**Comment by moonshoes87** [comment]
To do: 
- update Cookbook instructions to specify pandas version.
- revisit this problem in a few weeks, see if the pandas bug has been fixed

**Comment by moonshoes87** [comment]
Looks like pandas 0.24.1 has the fix -- I will verify this more thoroughly and then re-update the Cookbook.

**Comment by moonshoes87** [comment]
ani_depthplot.py still has problems with 0.24.1.

**Comment by moonshoes87** [comment]
Raised an issue for this:  https://github.com/pandas-dev/pandas/issues/25196

For now will keep Cookbook instructions, travis CI environment, and environment.yml pointing to 0.23.4.

**Comment by jschendel** [comment]
The related pandas issue has been fixed in the latest release:
```python
In [1]: import pandas as pd; pd.__version__
Out[1]: '0.24.2'

In [2]: df = pd.DataFrame([[0, 0], [0, 0]])

In [3]: df.apply(dict)
Out[3]:
0    {0: 0, 1: 0}
1    {0: 0, 1: 0}
dtype: object
```
