### ISSUE TITLE
Saving data from demag_gui issues

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#505]
@moonshoes87, when saving the data to magic tables, in the dialogue box the default age box is out of date. There is now longer and er_ages.txt file. It is now just ages.txt. Also the age of the site should also be able to be determined using the age columns in the sites table. Age tables will rarely be filled out for all of the sites and often for none so this option should be the default one. When selecting to use a default age the user should also be presented with the option of filling out a box for the age(age) and age one sigma(age_sigma) in addition to the older bound(age_high) and younger bound(age_low) columns already shown. A note about ages should be added:

"All sites must have an age associated with them. Either the age must be given or both the age_high and age_low should be used. In special cases all three could be used. If the uncertainty of an age is known, enter it in the age_sigma box with the one sigma value (not a two sigma value that is often reported)."
![screen shot 2019-01-29 at 11 41 22 pm](https://user-images.githubusercontent.com/1278789/51966890-afe4b480-2422-11e9-971f-d1b9480421ad.png)

Not sure how the order of the Age units in the drop down are determined, but it would be better if the order was:
Years BP
Years AD (+/-)
Years Cal BP
Years Cal AD (+/-)
ka
Ma
Ga

"Ka" in the list should be "ka".

**Comment by moonshoes87** [comment]
How does this look cosmetically?  I haven't made it actually *work* yet ;) 

<img width="956" alt="screen shot 2019-01-30 at 3 32 26 pm" src="https://user-images.githubusercontent.com/1836578/52019953-59b85580-24a4-11e9-83be-110c27d15620.png">

**Comment by njarboe** [comment]
I guess we don't need to display the computer column names. It is a bit confusing to have both and if we do we should have it everywhere for consistency.  How about just "younger bound", "older bound", "age", "age one sigma"? It would be nice if the labels were closer to the boxes but I imagine that is a gui setting you don't control. With the shorter names maybe you can fit them all on one line. That would be good. Order:
age      age one sigma     younger bound       older bound     units

Rephrasing the Note taking the above into consideration and trying to make things a bit clearer:

Note: All sites must have an age associated with them. Either the age or both the younger and older bounds must be given. If the age is given, younger and/or older bounds can be added for special cases. If the uncertainty of an age is known, enter it in the "age one sigma" box. Remember that many age uncertainties are published as two sigma. If that is the case, just divide the two sigma value by 2.

**Comment by moonshoes87** [comment]
Ok.  What do you think of having those values saved into the sites table instead of the ages table?  I think this makes more sense with the data model, as these would likely be inferred ages if they are being entered in this way rather than individually by site.

**Comment by njarboe** [comment]
That makes sense. No reason to make an age table if the person does not need it. We have had many ideas of how the age table should work over the years, but currently it is when you want to give more information about an age. Like it is from another paper, or which chron its in or to make it clear the age was done in this paper, etc.

I'm not sure how it works right now, but not having the age box show up if no ages are missing would be less confusing for people. No reason for them to have to figure out our complicated age system if the ages are already there for everything.

**Comment by ltauxe** [comment]
i agree

**Comment by njarboe** [comment]
Yes. Not requiring ages when just doing analysis is much better. Many times you won't even have an age till later. 

As Lisa said, when exporting the data to create a MagIC file for upload is the time to check for the required ages. Then it would be nice to do the complicated rules check for ages as being slow is not an issue.

**Comment by moonshoes87** [comment]
Ok, then are we comfortable with just including the option to add ages at this step, but allowing users to skip it?  

Without implementing a check, I have no way of deciding whether or not the ages box should be provided in the MagIC results table Dialog.

**Comment by ltauxe** [comment]
Yes that is good - it can also be done (and probably should be) in Pmag GUI
step 2.
So does this have to be in two places?

**Comment by moonshoes87** [comment]
Ages can be added in Pmag GUI step 3 (individually or en masse).  Not everyone uses that step, though.  I don't think it's too cumbersome having it in both places, and some people use Demag GUI more or less by itself, so allowing the input of ages there may be useful to them.  

@ltauxe, let me know if you want me to take the add ages dialog out of Demag GUI.  

@njarboe, if you can re-test this workflow on the demag_gui branch, that would be great.  If it's working well, I will merge it all back into master.

**Comment by Swanson-Hysell** [comment]
We like to be able use demag_gui as a one stop shop for generating MagIC contributions such that being able to add required metadata such as ages is important when exporting data within demag_gui.

**Comment by moonshoes87** [comment]
This makes sense.  @Swanson-Hysell, are you able to look over the changes I've made and let me know what you think?  As it was previously, the "use default age" checkbox wasn't actually hooked up to anything, so the whole operation should be more functional now.

**Comment by njarboe** [comment]
I am testing on the demag_gui branch with this file:
[magic_contribution_16566MOD.txt](https://github.com/PmagPy/PmagPy/files/2838941/magic_contribution_16566MOD.txt)
I removed the age, age_sigma, and age_unit from first site (E28) in the sites table. The validation passes with this omission. You said in general the validator just checks that the columns are there and not if they are all filled out, but I thought you were going to do the slow check when exporting for magic on the ages in the sites table.
![screen shot 2019-02-06 at 5 17 18 pm](https://user-images.githubusercontent.com/1278789/52384703-6c4a0600-2a33-11e9-91b3-f134dc899c0a.png)
I'll test out removing the columns completely from the sites table and see if that gets me the age dialogue box to pop up.

**Comment by njarboe** [comment]
Would suggest the text:
"If a sites age is not defined in the sites or ages table, please provide it here"
Even better would be, since this does not appear when the ages are all there (I think), 
list the missing sites by name and let the user fill out the age for each one;
"The sites below do not have an age defined in the sites or ages tables. All sites must have an age assigned to them. Please enter the ages for the sites below."

Not sure if this would be the best interface if the person has lots of sites that will have the same age info.

Otherwise works well.

**Comment by njarboe** [comment]
Not sure where the age unit list comes from, but the MagIC controlled Vocab "Age Units" has the correct "ka" value not "Ka".

![screen shot 2019-02-06 at 5 50 21 pm](https://user-images.githubusercontent.com/1278789/52386212-dd8cb780-2a39-11e9-8499-3b6326cc23b1.png)

**Comment by njarboe** [comment]
Fixed and pushed the Ka to ka problem.

**Comment by moonshoes87** [comment]
@njarboe -- the text looks good.  I though we discussed not doing a check on whether ages are provided (it may be a bit slow to do so thoroughly with large contributions).  I could still implement one, but that logic is not currently in place.  

In any case, I will merge into master and remove this branch.

**Comment by njarboe** [comment]
Ok. Seems fine. After a bit of thinking about it, I will change the text to make it clear that if you got your data file from a MagIC download it should already have ages for everything, and this box can be ignored. Otherwise people who are using a file that has all the ages will have to try and understand all the age details when in the end it does not matter to them.

**Comment by njarboe** [comment]
I changed the text some. (Edit: table is now tables)
![screen shot 2019-02-07 at 4 10 41 pm](https://user-images.githubusercontent.com/1278789/52451269-248ab380-2af3-11e9-9606-daa9890139ae.png)
It would be nice if the words sites and ages were links to popups of the sites and ages tables so people could look at them if they wanted to. A low priority issue that I will add shortly.

I don't think we need the warning when a person does not fill out the ages(unless you add the slow check and we know that they need to fill them out). If they did not fill out the ages section and still have missing ages, that will be caught by the MagIC validation system on uploading.
![screen shot 2019-02-07 at 4 09 24 pm](https://user-images.githubusercontent.com/1278789/52451455-ed68d200-2af3-11e9-82f3-fa7fb1560f2b.png)

If you would remove that warning, that would be great.

**Comment by njarboe** [comment]
@moonshoes87, Going over the workflow again I think the default behavior should be to not have to do anything if all the ages are present. I started to try and fix the check box logic but decided you could do a much faster and less buggy job.

If you could change the top text in the age box to: 
"If the data is from a validated file downloaded from the MagIC database, it will have ages for all sites and you can safely ignore this box.\nOtherwise, if a site's age is not defined in the sites or ages tables, please check the add ages box and provide the age information here."

then change the check box to read "add ages" and fix the logic in the code so that makes sense, that would be great.

**Comment by moonshoes87** [comment]
Ok, this makes sense.  I will add it.

**Comment by moonshoes87** [comment]
@njarboe, have a look.  I made the ages box toggle open/closed depending on whether "add ages" is checked or unchecked.  I also changed the top text to just say "you can add site ages here", because otherwise the dialog started to look very verbose.  I changed the checkbox to "add ages" as you suggested, and updated the logic.

**Comment by njarboe** [comment]
@moonshoes87 The ages box toggle is nice. This looks good. I'm closing this issue. I still don't really understand how all the different specimen orientation boxes work, but I can look into that later.
