### ISSUE TITLE
Validation tool states that the dir_nrm_origin and dir_polarity columns in the samples table are required when they should not be 

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#506]
Validation tool states that the dir_nrm_origin and dir_polarity columns in the samples table are required when they should not be.

![screen shot 2019-01-30 at 12 26 54 am](https://user-images.githubusercontent.com/1278789/51968126-099aae00-2426-11e9-9e94-d02fe7c18bfa.png)

These may have been changed recently to not required.

**Comment by moonshoes87** [comment]
@rminnet, the "update_day" in the data model .json doesn't appear have changed with these latest minor changes.  The cached version I have PmagPy and the latest downloaded from Earthref both say "updated_day": "2018:10:30", however they do contain differences.  

What is your standard for updating that field?

**Comment by moonshoes87** [comment]
@njarboe, in the samples table dir_nrm_origin is: requiredIfGroup("Direction").  It is the same for dir_polarity (in the samples table only).  So I believe this validation is being executed correctly.  Perhaps that should be changed?

**Comment by njarboe** [comment]
This is one of the cases where we want people to be able to leave it blank and then we fill in the default. That is probably not going to get done for awhile. In the mean time I can quickly add "" and/or " " to the vocabulary list for these required controlled vocab columns. @rminnett @moonshoes87 Will that work or should I add " " instead/in addition?

Here are the controlled vocab where I am adding "" and " ". 
@moonshoes87 Let me know if you only need "" or " " and I'll remove the other one.
I'll add this as an issue for MagIC fix. 

List with default value
Data Corrections: Not required? No default
Data Qualities: "g" 
Measurement Types: "u"
Rock Magnetic Test Codes: Not required? No default
NRM Origins: "p"

**Comment by moonshoes87** [comment]
The PmagPy validations do *not* check for whether or not a required column is actually filled in, just for whether it is present or absent.  So, adding "" or " " would not be relevant for PmagPy purposes.

**Comment by njarboe** [comment]
Ok. We need to complete to validation checks so that this type of data does not make it into the database. My confusion now cleared up.
