### ISSUE TITLE
Would prefer rounded output when exporting float values

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#511]
It would be nice if we could keep the data from being expanded and changed due to the conversion into the float format. So in this file:
[magic_contribution_16534.txt](https://github.com/PmagPy/PmagPy/files/2838862/magic_contribution_16534.txt)
The treat_dc_field on measurement 5 is 0.00003
Then I upload it to PmagyPy and export the data and it gets converted to:
0.0000299999999999999
[Sept-Iles_06.Feb.2019.txt](https://github.com/PmagPy/PmagPy/files/2838876/Sept-Iles_06.Feb.2019.txt)

And then that value will get saved and displayed in the database. If you can round this back to 0.00003 and output that value that would be great.

I think the str() function figures out how to do that intelligently. 

From StackExchange:
>>> a = 2.111111
>>> a
2.1111110000000002
>>> str(a)
'2.111111'

**Comment by moonshoes87** [comment]
Hmmm, yeah, that makes sense.  I'll work on that.  It seems to me that I this should happen just before upload -- we don't want to lose precision before that, right?

**Comment by moonshoes87** [comment]
@njarboe, can we decide specifically how many decimals of precision are desired?  `str()` seems to keep up to 15:

```
print(str(1.18000000000000003))
1.18
print(str(1.1800000000000003))
1.1800000000000004
```

Seems like that might still be too many digits.  str.format()  would allow us to control this more precisely.

**Comment by moonshoes87** [comment]
I implemented this with keeping 5 digits after the decimal point.  I can change that to any number of digits -- but it will be best if we can choose one number for all columns, vs trying to do it on a column by column basis.

**Comment by njarboe** [comment]
I think str() does the right thing and rounds when it looks like there is a number that has been changed due to str to float to str conversion. So basically it rounds when the last digit in the precision is off a bit up to where the number of digits would be even. Just use the str() output and that should do what we want.

**Comment by moonshoes87** [comment]
str.format() will do the same (rounding the float, not truncating), but it will allow us to control where the rounding happens. Looking through Lisa's code in pmag.py, floats are usually rounded to somewhere between 3 and 7 digits after the decimal point.  Because we are now using pandas, in many cases floats are being left super long.  I think rounding to 7 digits after the decimal is still pretty conservative but will prevent annoying values that str() would allow, like 1.1800000000000004.  @ltauxe, do you have any opinion on this?

**Comment by njarboe** [comment]
If someone puts in 1.18000000004 on purpose we should keep it. Rounding to some number of digits is not the right procedure if we can avoid that. If a value is put in by the user as .000045675 we would like to keep it. I don't think you quite grok what I am hoping to achieve. If the string in the MagIC file is .000045675 and then the str to float to str conversion creates .00004567499999999998 or something like that, what we would like is to use .000045675 as our ascii output. Is that what str() does? That would make sense. We want to keep exactly what was in the ascii in the MagIC file, if possible.

On calculated values it would be best if we could keep one additional significant digit, but that might be a pain to figure out. Some basic logic can be used for some fields. Anything in degrees, just keeping to one decimal is fine, for other data, we would have to go through them and think a bit about it. dir_r, for instance, should be kept to at least 5 decimal places and maybe more.

**Comment by moonshoes87** [comment]
No,  there is no way to recover the original string value.  `str.format()` and `str()` both use the same method of rounding floats, the only difference is that in the case of `str.format()` we can choose how many digits to round to (whereas `str()` defaults to something like 15) .  As far as I am aware, once we've converted a string to a float there is no way to recover the "true" string value again, we can only make choices about how much precision to try to keep.  You can see a little more about this issue [here](https://stackoverflow.com/questions/1317558/converting-a-float-to-a-string-without-rounding-it).

15 digits after the decimal point may be a correct and reasonable default (using less precision for specific columns most likely belongs within the function that is actually creating the values).  My point is just that we *have* to choose an amount of precision -- there is no way to get back to the original string.

**Comment by njarboe** [comment]
Hello Lori. Do you have time to Skype for a moment to clear up this issue for me? I still believe that a simple print(x) command will do what I hope it should do. It is smart about knowing how numbers are stored in base 2 64 bit format and what are the rounding problems are. Here is a sequence of output that show what I mean. We should not have to set the precision but maybe the code is doing something that creates the 4.34349999999999999999 values that we have to decided what to round to. 

>>> x = 13.949999999999999999
>>> print(x)
13.95
>>> x = 13.94999999999999999
>>> print(x)
13.95
>>> x = 13.9499999999999999
>>> print(x)
13.95
>>> x = 13.949999999999999
>>> print(x)
13.95
>>> x = 13.94999999999999
>>> print(x)
13.94999999999999
>>> x = 13.949999999999998
>>> print(x)
13.949999999999998
>>> x = 13.949999999999996
>>> print(x)
13.949999999999996
>>> x = 13.949999999999994
>>> print(x)
13.949999999999994
>>> x = 13.949999999999992
>>> print(x)
13.949999999999992
>>> x = 13.949999999999991
>>> print(x)
13.94999999999999
>>> x = 13.949999999990001
>>> print(x)
13.94999999999
>>> x = 13.949999990000001
>>> print(x)
13.94999999
>>> x = 13.949990000000001
>>> print(x)
13.949990000000001
>>> x = 13.949989999999999
>>> print(x)
13.94999

When it looks like the number is super long due to base 2 to base 10 conversion inexactness then print rounds to the right place. See the last two in particular. In the first one you might think it should round off to 13.94999 but it doesn't because the base 2 to base 10 conversion problem would not create the number 13.949990000000001 while print(x) for x = 13.949989999999999 rounds to 13.94999 because 13.949989999999999 is what 13.94999 looks like with the conversion problem.

str(x) seems to do the same as print(x)
>>> x = 13.949989999999999
>>> str(x)
'13.94999'
>>> x = 13.949990000000001
>>> str(x)
'13.949990000000001'

**Comment by moonshoes87** [comment]
Yes, it seems probably that having 16 digits after the decimal is pretty good at dealing with base 2 float  conversion issues.  `"{:16f}".format(x)` is the same as `str(x)` (except for trailing 0's, which can be removed), and we can't keep more precision than that anyway.

Also note that it isn't `str()` or `print()` that is doing the rounding in your examples, it is just happening in the assignment itself:

```
>>> x = 13.949989999999999
>>> x
13.94999
```

There isn't a way to guarantee that all digits are kept in the initial `str` to `float` conversion (which happens when pandas reads the data in from a file):

```
>>> >>> x = 13.94999000000000009
>>> x
13.94999
```

When it comes down to it, it seems perfectly reasonable to do this conversion with `str()`, but there is no way to turn a string into a float and back without potentially losing digits.  

(And if you still want to Skype, I could do that tomorrow before or after MagIC).

**Comment by njarboe** [comment]
I'm glad you agree that str() with probably work well for this. I think it has been well engineered for dealing with this problem. Let's try that and see if the long unwanted ascii values disappear. If that doesn't clear up the problem, a video conference might be a quick way to clear up the problem.

**Comment by njarboe** [comment]
So I downloaded this file from the database:
[magic_contribution_16591.txt](https://github.com/PmagPy/PmagPy/files/2853997/magic_contribution_16591.txt)
loaded into demag gui, made some fits, and exported as MagIC files and got this data file:
[Eastern-Sheep-Creek_Sheep-Creek_Valmy-Contact-Sheep-Creek_11.Feb.2019.txt](https://github.com/PmagPy/PmagPy/files/2854010/Eastern-Sheep-Creek_Sheep-Creek_Valmy-Contact-Sheep-Creek_11.Feb.2019.txt)

The dec, inc, etc that came from the file don't have the long number problem, but some new calculated values do. Maybe those aren't being printed out with the str() command.
Screen Shot 2019-02-11 at 7.25.50 PM

**Comment by moonshoes87** [comment]
Yes, this will happen when we generate floats.  We can use string formatting directly in the code, as is done in many places in the code with generated values, i.e.:

     ResRec['vgp_lat'] = '%7.1f' % (plat)

In the above example, the intensity will be stored as an exponent with up to 7 digits before decimal point and 1 after.  We can also use rounding and/or truncating from the `math` package, but again, that would need to be implemented on a case by case basis where the value is first generated, if you want to be conservative with numbers that have been entered by the user.  I don't think there is any other way to handle this, since you don't want to risk losing precision entered by the user.  By the time we get to upload, there isn't any way to distinguish between user-entered and pmagpy-generated floats.  

We *could* decide how much precision to keep for each column, and apply formatting on a column by column basis.  But again, this can remove user-entered precision, which I understand has its downsides.
  
For what it's worth, there is a python package called [`decimal`](https://docs.python.org/3.7/library/decimal.html) for storing decimal values precisely (as opposed to the Python builtin float type, which is not precise).

**Comment by njarboe** [comment]
You mean vgp_lat not intensity right?

At least the str->float->str conversion problems seem to be gone. Those were the most annoying. I think we can pass on this problem for now unless implementing the below is easy. That would work, I think,  for any data in MagIC and we don't have to set arbitrary precision limits on our data that other might want.

We could implement a function that looks at the string representation of a number when printing out the MagIC tables and if there are 5 9's or 0's in the last 6 digits of a number, the number is rounded to where the 9's or 0's start . That would solve the problem in a simple way that would not effect any measurement I know of in paleomagnetism. 

So 2.444000001 -> 2.444
2.44400001 -> 2.44400001
3.657729999999997 -> 3.65773

This could all be done with string manipulation and not very hard I think.
Two cases 0 or 9's
For 0 case look for "00000" in string
If not found print the whole number
  If found search after the "00000" and make sure the rest of the number consists of "0" except the last one can be anything.
    If true then truncate the string before the first "0" where "00000" was found
    If false print the full number

For 9's do the same thing but instead of truncating before the first 9, round up by adding 1 to the number before "99999". Fortunately the number will never be a 9 so you don't have to worry about changing two numbers.
 
I'm not sure if that would make things super slow, but the data coming out of pmag_gui should not be very big and I think this would work.

What do you think? It would be great as a scientist to get this right.

Thanks

**Comment by moonshoes87** [comment]
I will play with this -- might not be horribly slow with pandas/regex.

> Fortunately the number will never be a 9 so you don't have to worry about changing two numbers.

We could see values like this, though, right?

3.9999999

But that just adds one additional check.

**Comment by njarboe** [comment]
That is true. 

Hopefully there are not too many additional edge cases that will make it very complicated/slow :).

**Comment by moonshoes87** [comment]
I can't think of any other edge cases.  I'll have a look.

**Comment by moonshoes87** [comment]
@njarboe, could you give this a test?

**Comment by moonshoes87** [comment]
I'm fixing two small bugs in this code, but it now seems to be working.  

I added a fix for values that end like this: `0.053979999999999986` to be caught and changed to `0.05398`.

**Comment by njarboe** [comment]
I'll do another upload-download-PmagPy cycle today and will check this out. 

BTW where is this code so rupert or I could look at it/use it if we need to?

**Comment by moonshoes87** [comment]
It is a MagicDataFrame method in pmagpy/contribution_builder.py, part of `all_to_str`.  

See this [commit](ace8ed3a7c9ef9b469d71ad1afa89f3c29689579)

**Comment by njarboe** [comment]
Uploaded the Bogue2017 data into PmagPy, added some fits, and exported the MagIC file. None of these rounding problems showed up. This is great. Thanks.
