### ISSUE TITLE
Jarboe's plots don't have the new color scheme

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#512]
@moonshoes87 
I don't seem to be running with the code that produces Lisa's changes with the new color scheme. If you would comment with an image of a correct plot and a datafile that you used to produce it, that will help me figure out what is wrong. I'll then rerun all the plots. Thanks.

**Comment by ltauxe** [comment]
is it possible that the code you are using calls plot_map_basemap instead of plot_map?  in pmagplotlib.py?  I didn’t change the basemap colors…   
lisa

**Comment by njarboe** [comment]
@ltauxe 
Could you put a datafile that is plotting correctly and an image of what the plot looks like in a comment that would be quite helpful?  I am not sure what datafile will create the plot(s) and what the new plot(s) should look like. Debugging otherwise is a bit like looking for something in the dark.

**Comment by ltauxe** [comment]
the working examples are in PmagPy.ipynb and PmagPy-cli.ipynb

lisa

**Comment by moonshoes87** [comment]
@njarboe, in data_files/3_0/McMurdo:

    polemap_magic.py -sav -fmt png -rev gv 40 

produces this plot:

![mcmurdo_pole_map_t](https://user-images.githubusercontent.com/1836578/52687127-66f22d00-2f05-11e9-8d72-d1650a488c2f.png)

(That is the command that is called within make_magic_plots.py).

This is the commit that has those changes: 1247e92a91d70819c0905b46c9776d566326a90c

One other thought -- any chance that you have a pip install of pmagpy-cli, and so even though you have pulled from master, the pip version of polemap_magic.py is being called instead?  You should be able to verify if this is the case by running `which polemap_magic.py`.

**Comment by moonshoes87** [comment]
And here's the figure I get with the same polemap_magic.py command, after checkout out the commit before Lisa's changes:

    git checkout 1247e92^
    polemap_magic.py -sav -fmt png -rev gv 40

![mcmurdo_pole_map_t](https://user-images.githubusercontent.com/1836578/52687501-1976bf80-2f07-11e9-9905-b0619caba2d5.png)

**Comment by njarboe** [comment]
The plots are now working fine. More comment to follow.

**Comment by njarboe** [comment]
The plotting feature was put up on the live site before I did any testing so when they were put up it was a bit of a scramble to try and fix a lot of problems quickly. I did not re-run all of the plots every time there was a change in the plotting code as that was happening every few hours. The server takes 8-10 hours to run them all. Running the server when it was making new plots and serving up the plots from the same machine really slowed down the live site.

We have now fixed that problem and the plot files are hosted elsewhere. The amount of changes to the plotting code has slowed down, so this lag between changes and the new plots showing up should be much less. Running the plot server doesn't slow down the website so just starting the 8 hr job anytime is fine. I'll try to keep on top of any plotting changes and remake them right away, but if you would like to see something change on a particular contribution on the live site more quickly, send me an email and I can run make_magic_plots on that single contribution by hand. Any new contribution will have make_magic_plots run right away and if that has something wrong, let me know an I will update pmagpy on the plot server.

**Comment by njarboe** [comment]
I started the plots running again at around 4:30pm so they should finish up tonight. 

These three are quite large and are done separately:
magic_contribution_16274.txt  magic_contribution_16438.txt  magic_contribution_16508.txt
I'l run those in the morning.
