### ISSUE TITLE
Zijderveld Green Line is Plotting Outside of the Axes

### ISSUE THREAD

**Issue by rminnett** [PmagPy/PmagPy#513]
**What command was run:**

https://earthref.org/MagIC/13613 and clicked on plots thumbnail

(https://earthref.org/MagIC/16533 is another example)

**What happened:**

Zijderveld plots (e.g. 4th plot) are plotting the green line outside of the axes:

![image](https://user-images.githubusercontent.com/1182698/52731887-b40ce800-2f73-11e9-9d7d-62244996a65f.png)

**What I expected to happen:**

To be able to see the header and footer like the 8th plot, which is a Zijderveld plot without the green line:

![image](https://user-images.githubusercontent.com/1182698/52731939-d6066a80-2f73-11e9-872f-54a1d90f764f.png)

**PmagPy version:**

Latest on PmagPy Server (plots made on 2/13/2019)

**Comment by njarboe** [comment]
I don't know of any fits that display correctly. I don't see any fits in the earthref.org/MagIC/16502 Santos & Tauxe 2018 data set and earthref.org/MagIC/16533 Tauxe 2004 has some fits but they have the same problem. I'll try downloading the SantosTauxe 2018 and adding some fits later this afternoon, although it is unlikely that will work. 

I have been using Bogue 2017 to debug the upload->download->PmagPy->add fit ->Export to MagIC textfile-> upload to MagIC loop, but it is still a work in progress. Lori and I have been spending quite a bit of time the last couple of weeks working out many problems and we are getting pretty close, I hope.

**Comment by njarboe** [comment]
@moonshoes87 @ltauxe If anyone knows of a data set that displays fits correctly that is in MagIC or I can upload to MagIC, that would help with the debugging. Data from the Swanson-Hysell group with fits are also not plotting correctly. earthref.org/MagIC/16403 

earthref.org/MagIC/11883 has not plots made

**Comment by ltauxe** [comment]
this one works perfectly well:  magic_contribution_16533.txt

so does this one:  https://earthref.org/MagIC/13613

![lp1001a1_g_zijd](https://user-images.githubusercontent.com/174861/52735390-621c9000-2f7c-11e9-9928-7055456ec48a.png)


the santos and tauxe example is for a bunch of unoriented samples so there are no fits to plot.  

so I cannot reproduce your problem.  I downloaded both of these and ran first download_magic.py then make_magic_plots.py   Also zeq_magic itself does not have this problem.

**Comment by Swanson-Hysell** [comment]
The fits look good within demag_gui for the Fairchild et al. 2016 contribution (https://earthref.org/MagIC/16403) you referenced:

<img width="642" alt="screen shot 2019-02-13 at 10 49 45 am" src="https://user-images.githubusercontent.com/4332322/52735778-2fbf6280-2f7d-11e9-8276-4d7c6f2a4347.png">

**Comment by njarboe** [comment]
Ok. I'll check those out and hopefully get the correct plots up on the website shortly.

**Comment by njarboe** [comment]
@moonshoes87 I'm checking out FairchildET2016 from the Nick S-H comment.
[magic_contribution_16403.txt](https://github.com/PmagPy/PmagPy/files/2862133/magic_contribution_16403.txt)

It looks OK on the non-server version( although it would be nice to add second fits at some point):
![screen shot 2019-02-13 at 12 26 37 pm](https://user-images.githubusercontent.com/1278789/52742236-2e496680-2f8c-11e9-96d4-3c38ffa169e1.png)

but the server version has a problem.
![onserver-lo__slate islands_si__dei2_sa__dei2-3_sp__dei2-3a_co__g_ty__zijd_](https://user-images.githubusercontent.com/1278789/52742414-8718ff00-2f8c-11e9-990c-1535f4c8188d.png)

I pulled from master in the last 15min. 

@moonshoes87 Do you have a plot sever environment set up? I could help you setup access to the pmag server, that that would probably take 15-20 minutes to do.

**Comment by moonshoes87** [comment]
@njarboe, I don't have an environment set up.  I've just been downloading files and setting pmagplotlib.isServer to True.  Let me have a look at this locally first, and if I can reproduce the problem then we can think about server access later.

**Comment by moonshoes87** [comment]
I can reproduce the problem.  I don't know how to fix it yet.  A quick "solution" would be not calling pmagplotlib.add_borders for this type of figure, in which case we will have the non-server type of plot that lacks header and footer.  If we want to re-run plots ASAP and have them look reasonable, this is my suggestion.  Spacing things is always a pain and a solution could come quickly or slowly.

**Comment by ltauxe** [comment]
why does the header and footer mess with the green line?

**Comment by moonshoes87** [comment]
> why does the header and footer mess with the green line?

That's the question.  I'm pretty confused.  It seems like adding border_ax (plt.Axes object) messes up the whole plot, for some reason, although it doesn't cause any problems in the other types of plots.

**Comment by moonshoes87** [comment]
It looks like the axis is getting weirdly reset and maybe even flipped.  The border_ax axes is supposed to just overlay the existing plot axis, but it doesn't seem to do that.  I added a bunch of x,y coordinate points to the plot (in the areas where they are readable), and they don't make a lot of sense.

So the earthref panel is getting put at .09999, .03, which should be basically the bottom left, but for some reason is about a third of the way up.  The title panel is likewise shifted way up, so it doesn't even make the frame.  It looks like x values are basically correct, while y values have gotten way off.

![lo _slate islands_si _pi15_sa _pi15-10_sp _pi15-10a_ty _zijd_](https://user-images.githubusercontent.com/1836578/52753109-4def8780-2faa-11e9-93ec-5f273a1180db.png)

@ltauxe, maybe your matplotlib skills are more advanced than mine?

**Comment by ltauxe** [comment]
I cannot reproduce this at all!  it doesn’t do it on my computer.  we can try to debug on thursday on your computer.  i guess it is only when we add the header and footer?  
lisa

**Comment by ltauxe** [comment]
right.  weird.  
lisa

**Comment by moonshoes87** [comment]
It looks like only zijderveld plots with a best fit line have problems.  So, Zijderveld plots produced by zeq_magic for contribution 16432 are totally fine.

**Comment by moonshoes87** [comment]
It only happens when `pmagplotlib.plot_dir` is called.

**Comment by moonshoes87** [comment]
I believe I found the solution.  `pmagplotlib.add_borders` (which draws the header/footer for plots on the server) can only be called AFTER every other plotting command runs.  In zeq_magic.py, `pmagplotlib.plot_dir` was being called after `pmagplotlib.add_borders` if specimen interpretations were available.  That's a big sigh of relief.  Knowing that, we can move forward with adding interpretations into ipmag.zeq_magic and then replacing the code in zeq_magic with ipmag.zeq_magic.

**Comment by moonshoes87** [comment]
@njarboe, looking at the initial examples it looks like the plots were re-run without best fit lines?  I can no longer find examples on MagIC of the pathological plots. I'm not sure where this change was made or if it is on master, but now might be a good time to re-run plots again, especially if we can put up a quick solution (either in the data or in the contribution_builder.py code) for #519.

**Comment by moonshoes87** [comment]
![lo _slate islands_si _pi15_sa _pi15-10_sp _pi15-10a_ty _zijd_](https://user-images.githubusercontent.com/1836578/52980522-53c0e080-338f-11e9-9d72-52387c3d85b0.png)

**Comment by ltauxe** [comment]
hurray

**Comment by njarboe** [comment]
Will be re-running shortly
