### ISSUE TITLE
Anisotropy Plots Are Missing the Header and Footer

### ISSUE THREAD

**Issue by rminnett** [PmagPy/PmagPy#514]
**What command was run:**

https://earthref.org/MagIC/16436 and clicked on plots thumbnail

**What happened:**

The anisotropy plots (e.g. the first two plots) are missing the header and footer:

![image](https://user-images.githubusercontent.com/1182698/52732642-90e33800-2f75-11e9-8180-31233111166e.png)

**What I expected to happen:**

To see the header and footer like the equal area plots:

![image](https://user-images.githubusercontent.com/1182698/52732693-ab1d1600-2f75-11e9-9a81-1d9c35074197.png)

**PmagPy version:**

Latest on PmagPy Server (plots made on 2/13/2019)

**Comment by rminnett** [comment]
So do histogram plots (e.g. https://earthref.org/MagIC/16433):

![image](https://user-images.githubusercontent.com/1182698/52733882-b756a280-2f78-11e9-8ad8-bc68fad2a9c5.png)

**Comment by moonshoes87** [comment]
Working on this.  Small data integrity note:  the contributions table lacks the id column in this download.

Here's a first pass at some fixes.  There are some inconsistencies with how the program is set up to format these -- i.e., the tcdf plot doesn't have a secondary label, and the other two have 'bootstrap' and McMurdo respectively.  

![lo _mcmurdo_si __sa __sp __co _s_ty _aniso-conf_](https://user-images.githubusercontent.com/1836578/52739268-61d4c280-2f85-11e9-972c-6d5f53d95a5c.png)
![lo _mcmurdo_si __sa __sp __co _s_ty _aniso-data_](https://user-images.githubusercontent.com/1836578/52739269-626d5900-2f85-11e9-94e6-b1b505afaca5.png)
![lo _mcmurdo_si __sa __sp __co _s_ty _aniso-tcdf_](https://user-images.githubusercontent.com/1836578/52739270-626d5900-2f85-11e9-8320-99538f74d105.png)

How do we want to actually title these plots?  What else should be changed/added?

**Comment by moonshoes87** [comment]
https://earthref.org/MagIC/16433 is also missing contribution.id.  Additional weirdness -- the names are not consistent between table levels, so there is not a full hierarchy from measurements -> locations.  

Also, I noticed on MagIC there are only 3 plots for this contribution, but when I run it locally, I get additional hundreds of plots.

**Comment by njarboe** [comment]
@rminnett The lack of contribution IDs is a problem for magic_geomagia.py also. I have added the issue to https://github.com/earthref/MagIC/issues/374 but maybe should have its own?

**Comment by moonshoes87** [comment]
First attempt with histplot, MagIC borders added:

![lo __ty _intensities_histogram _](https://user-images.githubusercontent.com/1836578/52741608-9d25c000-2f8a-11e9-91c2-80a7446f0582.png)

How should this plot be titled?  Also, is it a problem that it is a different size/shape from most of the other plots?

**Comment by rminnett** [comment]
Maybe "Intensity Histogram" might be a bit more clear (although "Intensity" is in the x axis label)? It would be nice if the area under the histograms was colored in (light grey?) to make it more clear where most of the data are. I'll let @njarboe and @ltauxe decide about plot titles for the other types above.

**Comment by rminnett** [comment]
> @rminnett The lack of contribution IDs is a problem for magic_geomagia.py also. I have added the issue to [earthref/MagIC#374](https://github.com/earthref/MagIC/issues/374) but maybe should have its own?

We have an old issue for this (https://github.com/earthref/MagIC/issues/291), so I elevated it back to P1 and I'll check for and insert the contribution.id field and upload to S3

**Comment by rminnett** [comment]
@moonshoes87 the aspect ratio isn't critical, although as close to square as possible is better, as long as the axes bounding box is consistent relative to the final figure for each plot type to make creating nice thumbnails possible (#518).

**Comment by njarboe** [comment]
@rminnett Are you going to make changes to the contribution files and keep the same magic id. It is pretty nice that all files named magic_contribution_16544.txt are always the same and one does not need to consider if one is working with the most updated version of a data file. I have data files in many areas and having to download a new copy from the website each time to make sure it is not an old one would be a pain. Maybe this one time is OK, but I would prefer a different route. 

Maybe magic_contribution_16544-2.txt for the second version of a contribution although of course we already have a versioning system in place.

**Comment by njarboe** [comment]
@moonshoes87 @Lisa 
I think it would also be nice to have an easy way to know how many for something is in each bin. I like having the frequency axis but maybe you could put a number axis on the other side. Lots of plots are like this and would be pretty neat.

**Comment by njarboe** [comment]
This might not be the best contribution to use to comment on other plot features as the id and hierarchy are missing. A (sub)title with the location:site:sample/specimen displayed is needed but maybe that already happens when the data is not corrupt.

**Comment by moonshoes87** [comment]
@rminnett, that's good to know.  I am hesitant to mess with the aspect ratios as @ltauxe set them up, however it is very easy to change them if we agree that the visual representation of the data isn't undermined.  

![lo __ty _intensities_histogram _](https://user-images.githubusercontent.com/1836578/52747773-83d84000-2f99-11e9-97af-ed0a2f24b3be.png)

**Comment by moonshoes87** [comment]
> @moonshoes87 @lisa
> I think it would also be nice to have an easy way to know how many for something is in each bin. I like having the frequency axis but maybe you could put a number axis on the other side. Lots of plots are like this and would be pretty neat.

I'll try adding this as well.

**Comment by ltauxe** [comment]
i can re-do the histogram plots with square plots, and even a kernel density curve (which is nicer than a histogram anyway).

**Comment by moonshoes87** [comment]
@njarboe, adding a second y axis is turning out to be a bit tricky.  I will return to this as it is lower priority than some of our other issues.

**Comment by njarboe** [comment]
@moonshoes87 Ok. Save for later.

**Comment by ltauxe** [comment]
I think the anisotropy plots are completely meaningless for this study as they are all unoriented and the data were for correcting the paleointensity measurements.  is there some way to suppress making silly plots?  maybe all equal area projections should be in either geographic or stratigraphic coordinates  for a start?   - this goes for equal area projections  or directions for nything other than the specimen level for unoriented specimens (like many paleointensity studies)

**Comment by ltauxe** [comment]
regarding the histogram plot, making a second y-axis on the right with the numbers is pretty easy (twinx command).  I'll give it a go

**Comment by moonshoes87** [comment]
I tried twinx, but couldn’t get the units right.  Good luck!

**Comment by ltauxe** [comment]
It is plt.twiny().  One could be normalized (density set to True) and one not normalized. 

   but histplot.py already has the option to plot things that are not normalized (the -N option).  Should I take out the option and just do it both ways for everybody?

**Comment by ltauxe** [comment]
it’s twiny sorry I can have a look, but we already have a -N option for un-normalized plots.  should i change it so that it plots both ways always?  

lisa

**Comment by ltauxe** [comment]
actually - it WAS twinx (not sure why), but anyway, i added an option to plot both to histplot.py (-twin) and changed make_magic_plots.py to do it that way.
