### ISSUE TITLE
Create MagIC Plots With a Higher Resolution

### ISSUE THREAD

**Issue by rminnett** [PmagPy/PmagPy#515]
Plots are currently on the order of 400px square. For submission-ready plots and viewing on high pixel density monitors, I think at least 600 dpi (although Nature recommends 1200 dpi for line drawings: https://www.nature.com/authors/policies/image.html) is better. For a 3" square 600 dpi figure in a journal or about a 6" square region of a 4k 15" screen, that's at least 1800px square.

**Comment by ltauxe** [comment]
This little plots aren't supposed to be for publication really - they are intended as a quick look.  can you download the plots anyway?  I can make them at higher resolution no prob, but I'm not sure that is what we intended...  I would download the data, make nicer plots for publicationwith the GUIs or in the notebooks.. No?

**Comment by rminnett** [comment]
We can certainly add a download button (they are downloadable now if you right click and choose Save As or open in a new tab and Save). Yes, I suppose vector plots are better for publication anyway, but higher resolution won't take up much more space (most of the content is a solid color and compresses well). We could try making high resolution .png and .svg plots from make_magic_plots and see which is better on the website.

**Comment by ltauxe** [comment]
it would have to be added as an option for each of the individual plotting programs. can do, but not highest priority right now. 
lisa

**Comment by moonshoes87** [comment]
I think this might be simple.  It may not catch all cases, but I believe that most plotting programs will call plot_init.  See the above commit. @njarboe and @rminnett, could you test this out and see if it is what you want?   Looking at it in Preview, I'm not sure if this is actually producing "bigger" plots as well, but I assume it is relatively simple for you to resize as needed.

**Comment by ltauxe** [comment]
or it is in the savefig command - like setting the dpi to 300 or something.

**Comment by moonshoes87** [comment]
It looks like it works either way:

High resolution:
![lo _slate islands_si _pi15_sa _pi15-10_sp _pi15-10a_ty _zijd_](https://user-images.githubusercontent.com/1836578/53059760-dff50580-346c-11e9-932d-1a8b9ae4cd79.png)

Low resolution:
![lo _slate islands_si _pi15_sa _pi15-10_sp _pi15-10a_ty _zijd_](https://user-images.githubusercontent.com/1836578/53059782-f9964d00-346c-11e9-9184-54d3ba662f3b.png)

High resolution the other way:
![lo _slate islands_si _pi15_sa _pi15-10_sp _pi15-10a_ty _zijd_](https://user-images.githubusercontent.com/1836578/53059834-2d717280-346d-11e9-86f7-2dba9bf94a91.png)

**Comment by moonshoes87** [comment]
@rminnett, let me know how those look.

**Comment by rminnett** [comment]
@moonshoes87, yep, those look much better (either way is fine, they both make 4400x4800 px images in this case). If you can, I would make them a quarter of that size (2200x2400 px in that case).

The green trend line looks much better on these plots now, but it looks like the grey header and footer borders are gone now. However, I think they actually look a bit better like this (@njarboe, do you agree?) - can you make all of the plots not have the grey header and footer borders?

@njarboe and @moonshoes87, if making the thumbnail versions #518 is too tricky in PmagPy or with ImageMagick on the PmagPy server, can you keep making low resolution versions like the one you have above (440x480 px in that case) and calling them "LO: ... TY:_eqarea_.thumb.png" for now and I'll try to crop them in the browser? Having small images will still help them load faster until you click on them.

**Comment by rminnett** [comment]
Actually, just 3x the size in each dimension would be better (1320x1440 in that case). I can see that some of the latest plots on MagIC are already over 4k pixels in each dimension and taking a little while to load from S3 (and probably taking up unnecessary space there).

**Comment by moonshoes87** [comment]
I haven't been able to look into the question of making thumbnails yet.  It looks like it may be quite easy to do with the `pillow` module, so I can try that.

As far as sizing plots is concerned, with our plotting library (matplotlib) I have two things to play with: dpi and plot size.  However, it appears that setting the dpi higher results in plot that is larger by default.  What I have done so far is just increase the dpi (from 80 to 800, so there is a lot of room in between).  @rminnett, I am a little confused about what you are looking for right now -- could you clarify?

And I just added the gray line back in, but I can take it out again.  That change will apply to all plots for the server.

**Comment by rminnett** [comment]
If you keep the figure size the same and set the dpi to 240 (3x what you were doing instead of 10x), I think that should make clear plots that aren't too big to store 100k+ of them on S3 nor too big to transfer. If you can make dpi=80 ones as well with ".thumb.png" file names that will help keep the plots quick on the website (they can be replaced with cropped ones later).

**Comment by moonshoes87** [comment]
I don't have a way of keeping the figure size the same but changing the dpi.  When I changed the dpi using matplotlib, the figure size changed as well. I'm not sure if there is a way around this...  I am not very experienced in editing images this way.   I will go ahead and try setting the dpi to 300, and look into changing dpi without changing figure size.

Thumbnails are easy to do using `pillow`.  I can leave that as a separate program (currently in programs/thumbnails.py), or I can call that functionality within make_magic_plots.py.

**Comment by njarboe** [comment]
It will be very easy create a thumbnail image from the highres one on the server with ImageMagick. I'll get that installed and get that working. @rminnett What size do you want for the thumbnail? 100x100?

**Comment by rminnett** [comment]
Max dimension = 300px, please (#518).

**Comment by njarboe** [comment]
@moonshoes87 If you can have make_magic_plots make the thumbnails, that would be best. That way making them a bit different will be easy while shrinking bit ones with imagemagick won't do that. When that's working I'll test it out and re-run the plots.

**Comment by moonshoes87** [comment]
Ok, I'm closing this issue -- @rminnett, if the 240 dpi images are not satisfactory, please feel free to reopen.

**Comment by moonshoes87** [comment]
I will continue to update the thumbnails issue #518
