### ISSUE TITLE
earthref.org/MagIC/11883 has data to measurement level but no plots are being made

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#516]
earthref.org/MagIC/11883 has data to measurement level but no plots are being made. Need to run make_magic_plots on this data to see if it is a data or make_magic_plots problem.

**Comment by ltauxe** [comment]
This works absolutely fine for me.  
download_magic.py -f magic_contribution_11883.tx
then 
make_magic_plots.py  

worked a treat..  e.g.:  

![cm1-1a_g_zijd](https://user-images.githubusercontent.com/174861/52750798-154bb000-2fa2-11e9-98c7-ca53abf05a98.png)

**Comment by ltauxe** [comment]
but the aged range for this is listed as 0-1.092 Ga.  I think all the data are from 1.092Ga.

**Comment by moonshoes87** [comment]
Running locally and with isServer set to True, I also get lots of plots.

**Comment by moonshoes87** [comment]
@njarboe, let me know if there is something else you want me to do with this issue -- for now I can't seem to reproduce your problem.  Is it possible you linked to the wrong contribution?

**Comment by njarboe** [comment]
I left this issue so that I would not forget to check out what the problem was with the data file. I had not run make_magic_plots on the data so I was wondering why the plots were not show up on the server. Found out there are a few data files that I thought were from the 2.5 data model that actually was from 3.0. This is one of them. I will re-run the plots shortly to get the other fixes run and to get those contribution plots made and on the live site.
