### ISSUE TITLE
Some Data Labels on MagIC Plots are Illegible

### ISSUE THREAD

**Issue by rminnett** [PmagPy/PmagPy#517]
For example in :

https://earthref.org/MagIC/16418:
![image](https://user-images.githubusercontent.com/1182698/52737907-53d17280-2f82-11e9-9e11-d37b9d08e873.png)

https://earthref.org/MagIC/16415:
![image](https://user-images.githubusercontent.com/1182698/52738309-39e45f80-2f83-11e9-97ff-341506b518fb.png)

https://earthref.org/MagIC/14510:
![image](https://user-images.githubusercontent.com/1182698/52738857-719fd700-2f84-11e9-9225-bd057da3ebbc.png)

Perhaps adjusting the axis limits so the data use the full axes (the upper right quadrant in the first case) and only labeling five data points (at roughly 0%, 25%, 50%, 75%, 100% through the data)? The marker colors could also indicate the order of the points between labels by progressing through a sequential color map.

Higher resolution plots (#515) would allow a smaller font to still be legible. Or maybe making the marker size smaller and moving the label away from the marker a bit might help.

**Comment by ltauxe** [comment]
The weird demagnetization plot happens if the method codes are incorrect.  this must have been a complicated experiment and the data were improperly labeled or zeq_magic wasn't designed to cope with it.  As for the zijderveld diagrams, this is a 'feature" of having a lot of closely spaced demag steps and zeq_magic will plot them this way.  we can't anticipate every single contingency.

**Comment by rminnett** [comment]
Yes, I agree, this isn't critical, just an iterative step towards a more "publication-ready" ideal that we're pursuing, but feel free to ignore this issue if it's determined to not be worth changing.

If the axis limits on the Zijderveld plots above (e.g. if the x axis on the second one was -25 to 0, or whatever the min/max x data are) it would make the individual points more clear (or just fewer labels and/or a colormap on the markers).

Here's another Demag plot, too, if that helps (https://earthref.org/MagIC/16418):

![image](https://user-images.githubusercontent.com/1182698/52758288-944de200-2fbc-11e9-9049-91261d72949c.png)

**Comment by ltauxe** [comment]
let’s just park this problem for now as each case would be different.  
lisa
