### ISSUE TITLE
Create 300px MagIC Plot Thumbnails

### ISSUE THREAD

**Issue by rminnett** [PmagPy/PmagPy#518]
I used to do this with ImageMagick by cropping to the axes boundaries (based on the plot type), resizing so the larger of the two dimensions is 100px:

Plot:
![image](https://user-images.githubusercontent.com/1182698/52740987-3522aa00-2f89-11e9-8a23-b5001cf47f9e.png)

Cropping Boundary (this only worked well if the axes boundaries were in the same place for each plot type):
![image](https://user-images.githubusercontent.com/1182698/52741109-6ef3b080-2f89-11e9-92e8-9508eaeb6426.png)

Cropped Plot:
![image](https://user-images.githubusercontent.com/1182698/52741132-7ca93600-2f89-11e9-8c76-5a4ac32a2fd3.png)

Resized Plot to 100px (by 77px in this case):
![image](https://user-images.githubusercontent.com/1182698/52741272-d578ce80-2f89-11e9-8b23-cc198e5a5cdd.png)

**Comment by rminnett** [comment]
Actually, if you start with a larger image and can resize and crop within the axes to 300px instead of 100px, that would look better on higher density screens,

**Comment by moonshoes87** [comment]
Thumbnails are very easy to make.  No cropping yet, but I added a simple program called thumbnails.py that will make thumbnails for every image in a directory.  I should be able to add cropping based on image type.  For now:

![lo _chile_ty _vgp_map thumb](https://user-images.githubusercontent.com/1836578/53121275-b8ec1180-3508-11e9-992d-806c9f31afca.png)
![lo _chile_ty _vgp_map](https://user-images.githubusercontent.com/1836578/53121281-bdb0c580-3508-11e9-9c71-bd21b059344f.png)

**Comment by rminnett** [comment]
Great, thanks, can you make them 300px thumbnails (see above comment) when you have a chance?

**Comment by moonshoes87** [comment]
Using all of these python modules, changing the number of pixels changes the size -- this seems to be the way of resizing.

This is the cropped thumbnail for an equal area plot, using 300 px by 300 px:

![lo _chile_si _10cl14_sa __sp __co _t_ty _eqarea_ cropped_thumb](https://user-images.githubusercontent.com/1836578/53132950-4a1db100-3526-11e9-8687-36a08ddfe803.png)

If I use 100 px x 100 px size with 300 x 300 dpi resolution, I get this:
![lo _chile_si _10cl14_sa __sp __co _t_ty _eqarea_ cropped_thumb](https://user-images.githubusercontent.com/1836578/53133087-c617f900-3526-11e9-80f2-eb661e57cde7.png)

Is the second image what you are looking for?

**Comment by moonshoes87** [comment]
Also, do they need to be cropped exactly square?  I.e., see the vgp map example, which is very rectangular:

![lo _chile_ty _vgp_map thumb](https://user-images.githubusercontent.com/1836578/53133590-8225f380-3528-11e9-8f13-5294f73da74a.png)

**Comment by rminnett** [comment]
That first equal area thumbnail looks great! No, just as long as the larger of the two dimensions is 300px, I can center it with a white background.

**Comment by moonshoes87** [comment]
This is the current cropping for most if not all plot types. There may be some sneaky outliers.


![lo _mcmurdo_si __sa __sp __co _s_ty _aniso_conf_ thumb](https://user-images.githubusercontent.com/1836578/53197563-514cc980-35cf-11e9-9a70-bf35d0a43c49.png)
![lo _mcmurdo_si __sa __sp __co _s_ty _aniso_data_ thumb](https://user-images.githubusercontent.com/1836578/53197666-7ccfb400-35cf-11e9-9044-39212daca3ca.png)
![lo _mcmurdo_si _mc01_sa __sp __co _g_ty _eqarea_ thumb](https://user-images.githubusercontent.com/1836578/53197669-7d684a80-35cf-11e9-919b-e27947ab9ca0.png)
![lo _mcmurdo_si _mc01_sa _mc01a_sp _mc01a_co _g_ty _demag_ thumb](https://user-images.githubusercontent.com/1836578/53197986-37f84d00-35d0-11e9-975d-7fbebdd7f858.png)

![lo _mcmurdo_si _mc01_sa _mc01d_sp _mc01d_co _g_ty _zijd_ thumb](https://user-images.githubusercontent.com/1836578/53198564-89eda280-35d1-11e9-8066-078d803271d4.png)


![lo _mcmurdo_si _mc217a_sa _mc217a_sp _mc217a2-1_ty _hyst_ thumb](https://user-images.githubusercontent.com/1836578/53198496-662a5c80-35d1-11e9-8f5d-bd1b24dfe13d.png)
![lo _mcmurdo_ty _intensities_histogram _ thumb](https://user-images.githubusercontent.com/1836578/53198705-ea7cdf80-35d1-11e9-9e19-c4c4c614d83d.png)

![lo _mcmurdo_ty _pole_map_t_1 thumb](https://user-images.githubusercontent.com/1836578/53197674-7e00e100-35cf-11e9-9533-05024b76d180.png)
![lo _mcmurdo_ty _vgp_map thumb](https://user-images.githubusercontent.com/1836578/53197675-7e00e100-35cf-11e9-95ce-a19ec438e106.png)
![mc _13436_ty _pole_map_t thumb](https://user-images.githubusercontent.com/1836578/53197676-7e00e100-35cf-11e9-8a31-eaf248f51779.png)

**Comment by moonshoes87** [comment]
Unfortunately I have no good way of guarding against these smaller equal area plots, which won't be as nicely cropped:

![lo _mcmurdo_si _mc01_sa _mc01f_sp _mc01f_co _g_ty _eqarea_ thumb](https://user-images.githubusercontent.com/1836578/53201464-f28c4d80-35d8-11e9-9dce-28eaa3f6fcc7.png)
:  
![sp _mc01d_ty _eqarea_ thumb](https://user-images.githubusercontent.com/1836578/53201379-b822b080-35d8-11e9-9fa7-cbfe08e9ede1.png)

They aren't marked as differently sized from other equal area plots.  I'll see if I can fix it, but for now those thumbnails will just be a little awkward.

**Comment by njarboe** [comment]
I would say all of those are good enough for just a thumbnail. Except the histogram. It would be nice to have the solid line on the bottom, otherwise it looks a bit weird. Not a big deal if it is to much of a pain to fix.

**Comment by njarboe** [comment]
Just pulled from master and I'm going to start redoing all of the plots shortly to get the new thumbnails and other improvements.

**Comment by moonshoes87** [comment]
@njarboe, it looks a little weird to me with just the bottom line:

![lo _mcmurdo_ty _intensities_histogram _ thumb](https://user-images.githubusercontent.com/1836578/53264860-946f7100-3691-11e9-9e41-1155cca14a41.png)

I think maybe all 4 bounding lines instead?

![lo _mcmurdo_ty _intensities_histogram _ thumb](https://user-images.githubusercontent.com/1836578/53265127-4dce4680-3692-11e9-9960-b0e7422b6132.png)

**Comment by moonshoes87** [comment]
Two more things.  @rminnett, I changed the type of the anisotropy plots from aniso-conf/aniso-data to aniso_conf and aniso_data.  This is more consistent with our general naming scheme.  Let me know if this messes anything up for you.

Also, there may be plot types that I haven't caught, in which case there will be some plots for which thumbnails are not not cropped.  These failures will be logged in a file called thumbnail_errors.txt in each directory.

**Comment by ltauxe** [comment]
yes you need all the axes and also the axis labels.
lisa

**Comment by moonshoes87** [comment]
@ltauxe -- this is just for the clickable thumbnails.  The full plots will be un-cropped.  Is that what you are thinking?

**Comment by moonshoes87** [comment]
This looks pretty good on the website.  I'm closing this issue.  @njarboe, please let me know if you discover any missing thumbnail types.  If anyone else has other thoughts, feel free to reopen.
