### ISSUE TITLE
Bogue2018 with one location produces no equal area plot

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#519]
This magic file has one Location and sites but nothing lower. No plot is produced but expected one equal area plot of directions
[magic_contribution_16592.txt](https://github.com/PmagPy/PmagPy/files/2870641/magic_contribution_16592.txt)
Maybe their is a problem with the data but it passes validation and has directions, so I think an equal area plot of the sites should be produced.

While this similar file with two locations produces two plots.
[magic_contribution_16587.txt](https://github.com/PmagPy/PmagPy/files/2870649/magic_contribution_16587.txt)

The first one without plots is on the MagIC homepage as a recent contribution. It displays a "No plots" image, so it would be nice get this fixed quickly.

**Comment by moonshoes87** [comment]
eqarea_magic is being called appropriately, but it only plots records that contain "This study" in the citations column.  "This study" is not included in any of the rows in this sites table:

    10.1029/2018GC007748:10.1029/JB089iB12p10341

Should this be fixed in the contribution, or relaxed in the contribution_builder module?

**Comment by ltauxe** [comment]
this is a hold-over from the old data model.  we can ignore this.

**Comment by njarboe** [comment]
Yea. Go ahead and plot them. We now allow using the doi of the contribution in the citation table instead of "This study"

**Comment by moonshoes87** [comment]
@njarboe and @ltauxe -- just confirming, I will remove this filter entirely, so all rows will be plotted regardless of citation.  If that is incorrect, let me know.

**Comment by njarboe** [comment]
Works. Great. Plot now on website.
