### ISSUE TITLE
refactor zeq_magic

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#520]
This will requires working out some details with the interactivity, and adding plotting of interpretations to ipmag.zeq_magic.

**Comment by moonshoes87** [comment]
@ltauxe, I've made a lot of progress on this.  I'm running into a confusing thing in the McMurdo dataset, though.

The problem is that there are two non-unique measurement names in this block, both `mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI4`.  This leads to a pandas error:

`ValueError: cannot reindex from a duplicate axis`

Here is the section of the measurements file for specimen mc15a:

```
                     experiment    ...    treatment
measurement name                                                                      ...             
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI2   mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          373
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI4   mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          423
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI6   mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          473
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI9   mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          523
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI11  mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          573
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI14  mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          623
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI16  mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          673
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI19  mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          723
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI21  mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          773
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI24  mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          798
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI26  mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          823
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI1   mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          843
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI4   mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          853
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI6   mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI    ...          863

[14 rows x 63 columns]
```

This is in violation of the data model description of measurements.measurement as a unique identifier.  Any thoughts about how this should be handled in zeq_magic?

**Comment by moonshoes87** [comment]
Here's the whole section before it got trimmed down (only including methods and treatment columns):

```
spec_df                                           treatment                                       method_codes
measurement name                                                                                      
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI1        273            LT-NO:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-ZI
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI2        373  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI3        373  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI4        423  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI5        423  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI6        473  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI7        373        LT-PTRM-I:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-ZI
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI8        473  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI9        523  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI10       523  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI11       573  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI12       473        LT-PTRM-I:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-ZI
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI13       573  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI14       623  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI15       623  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI16       673  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI17       573        LT-PTRM-I:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-ZI
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI18       673  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI19       723  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI20       723  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI21       773  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI22       673        LT-PTRM-I:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-ZI
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI23       773  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI24       798  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI25       798  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI26       823  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI27       773        LT-PTRM-I:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-ZI
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI28       823  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI1        843  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI2        773        LT-PTRM-I:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-ZI
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI3        843  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI4        853  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI5        853  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI6        863  LT-T-Z:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI7        823        LT-PTRM-I:LP-PI-TRM:LP-PI-ALT-PTRM:LP-PI-ZI
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI8        863  LT-T-I:LP-PI-TRM-ZI:LP-PI-TRM:LP-PI-ALT-PTRM:L...
mc15a-LP-AN-ARM1                               0.18                                  LT-AF-Z:LP-AN-ARM
mc15a-LP-AN-ARM2                               0.18                                  LT-AF-I:LP-AN-ARM
mc15a-LP-AN-ARM3                               0.18                                  LT-AF-Z:LP-AN-ARM
mc15a-LP-AN-ARM4                               0.18                                  LT-AF-I:LP-AN-ARM
mc15a-LP-AN-ARM5                               0.18                                  LT-AF-Z:LP-AN-ARM
mc15a-LP-AN-ARM6                               0.18                                  LT-AF-I:LP-AN-ARM
mc15a-LP-AN-ARM7                               0.18                                  LT-AF-Z:LP-AN-ARM
mc15a-LP-AN-ARM8                               0.18                                  LT-AF-I:LP-AN-ARM
mc15a-LP-AN-ARM9                               0.18                                  LT-AF-Z:LP-AN-ARM
mc15a-LP-AN-ARM10                              0.18                                  LT-AF-I:LP-AN-ARM
mc15a-LP-AN-ARM11                              0.18                                  LT-AF-Z:LP-AN-ARM
mc15a-LP-AN-ARM12                              0.18                                  LT-AF-I:LP-AN-ARM
mc15a-LP-AN-ARM13                              0.18                                  LT-AF-Z:LP-AN-ARM
mc15a-LP-AN-ARM14                              0.18                                  LT-AF-I:LP-AN-ARM
mc15a-LP-AN-ARM15                              0.18                                  LT-AF-Z:LP-AN-ARM
mc15a-LP-AN-ARM16                              0.18                                  LT-AF-I:LP-AN-ARM
mc15a-LP-AN-ARM17                              0.18                                  LT-AF-Z:LP-AN-ARM
mc15a-LP-AN-ARM18                              0.18                                  LT-AF-I:LP-AN-ARM
```

The reason that the two `mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI4` rows cause problems and the other duplicates don't is because we try to select all rows without the method codes `LT-PTRM`, and that is the only place we end up with duplication in our result.

**Comment by moonshoes87** [comment]
I've found a way around the above error -- but still, we should think about why this happened at all since it is in violation of the data model.

I've found another discrepancy between ipmag.zeq_magic and zeq_magic.py.  

You can now call `zeq_magic.py` with the -new switch to use the not-yet-complete ipmag code.  You can run this in a notebook.

New way:
```
!zeq_magic.py -WD data_files/3_0/McMurdo -spc mc01a -fmt png -new
Image('mc01a_eqarea.png')
```
old way:
```
!zeq_magic.py -WD data_files/3_0/McMurdo -spc mc01a -fmt png
Image('mc01a_eqarea.png')
```
with the ipmag code, it doesn't make a plot.  With the old zeq_magic code, it does.  This seems to be because of a line in ipmag.zeq_magic that gets rid of ptrm steps:

            spec_df_th = spec_df_th[spec_df.method_codes.str.contains(
                'LT-PTRM') == False]  # get rid of some pTRM steps    

@ltauxe, perhaps you could look at this specimen and decide which behavior, old or new, is correct?

**Comment by moonshoes87** [comment]
@ltauxe, let me know if you are able to look at this before you go to sea!

**Comment by ltauxe** [comment]
yes i will get to it.  but not today :) 
lisa

**Comment by ltauxe** [comment]
well - i don't know why that would ever be in there as you shouldn't have both LT-T-Z and LT-PTRM in the same method code string.   but the real puzzle is why the syntax doesn't work - it tries to filter out all records with LT-PTRM in the method code, but seems to filter out ALL the records, whether that string is present or not!  that leaves an empty dataframe which of course blows up the whole project.  this doesn't happen in demag_gui.  

if you try to  print out the series spec_df_th['method_codes'], you get the whole dataframe so somehow with the dataframe was read in, it is being corrupted in a way that I have seen before but never understood.   you get the expected behavior using the pd.read_csv() syntax,  but the Empty DataFrame problem persists!  

I'm just commenting out the LT-PTRM removal step.

**Comment by ltauxe** [comment]
the next step should be to add the interpretations for the AF data from the specimens.txt file - that doesn't work but the TH data does seem to work properly.  (compare results for mc01f in old and new):
old:  zeq_magic.py  -crd g -fsp specimens.txt -spc mc01f -fmt png
![mc01f_g_eqarea](https://user-images.githubusercontent.com/174861/54056999-8ac42e00-41a6-11e9-9b9b-cb30b3c4dfb0.png)
![mc01f_g_zijd](https://user-images.githubusercontent.com/174861/54057001-8ac42e00-41a6-11e9-964b-b1a51d13b6ce.png)

and new:  
![mc01f_eqarea](https://user-images.githubusercontent.com/174861/54057084-ca8b1580-41a6-11e9-8c3e-3459633997e1.png)
![mc01f_zijd](https://user-images.githubusercontent.com/174861/54057085-cb23ac00-41a6-11e9-8870-d06629d23e2d.png)

**Comment by ltauxe** [comment]
Another problem is that the -new option does not do the geographic coordinate system transformation as the old one did (see difference in plots).

**Comment by ltauxe** [comment]
so summary of issues for zeq_magic.py -new:
1) doesn't do -crd switch correctly (no geographic coordinates)
2) doesn't put on the interpretations for the AF data - only the thermal data.  
3) mystery about why the filtering by LT-PTRM method code fails (not urgent - just a puzzle)

**Comment by moonshoes87** [comment]
Thanks @ltauxe.  I will work on 1 & 2 today or Monday.

**Comment by moonshoes87** [comment]
Ok, so -crd was indeed never implemented into ipmag.zeq_magic.  In order to make this work, we will need to use a sample file which has azimuth and dip.  This will take a little re-working.

**Comment by ltauxe** [comment]
the McMurdo one does have a sample table with all the stuff in it.  
lisa

**Comment by moonshoes87** [comment]
I got that part working for the most part, still need to test tilt–corrected coordinates a bit more:

![mc01f_zijd](https://user-images.githubusercontent.com/1836578/54063144-86583f00-41bf-11e9-8780-c85bc2e9cd74.png)

I will verify that -crd t works too and then make sure we get all interpretations on Monday.

**Comment by moonshoes87** [comment]
Tilt corrected coordinates now seem to work as well as geographic.

**Comment by moonshoes87** [comment]
The problem with AF interpretations being skipped is caused by some code that creates the a hybrid column called `treatment`.

```
    if 'treat_ac_field' in meas_df.columns:
        meas_df['treatment'] = meas_df['treat_ac_field'].where(
            cond=meas_df['treat_ac_field'].astype(bool), other=meas_df['treat_temp'])
    else:
        meas_df['treatment'] = meas_df['treat_temp']
```

This sometimes means that treatments look like `[273, 0.1, 0.18, 0.2, ....]`.  Whereas, `meas_step_min` will have values like `[0, 0.1, 0.18, 0.2, ...]`.  0 values were ignored (since 0 as a boolean is False).  

This line of code then caused the immediate problem:

```
                        try:
                            # getting the starting and ending points                                                                                                                            
                            start, end = treatments.index(beg_pcas[ind]), treatments.index(end_pcas[ind])
                            mpars = pmag.domean(
                                datablock, start, end, calculation_type)
                        except ValueError as ex:
                            mpars['specimen_direction_type'] = "Error"
```

This was causing a `ValueError` which resulted in the interpretation being ignored.  

I have made a workaround which should eliminate this problem.

**Comment by moonshoes87** [comment]
@ltauxe, I believe I have resolved problems 1 & 2.  

There is one more thing that I am noticing, which is that ARM measurements are also causing some trouble.  

See `zeq_magic.py -crd g -fsp specimens.txt -spc mc15a -fmt png -new`.

```
-W- Specimen mc15a record contains invalid start/stop bounds:
meas_step_min    673
meas_step_max    823
Name: mc15a, dtype: object

    Measurement records:
                                         treat_ac_field  treat_temp
measurement name                                                   
mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI1              0         273
mc15a-LP-AN-ARM1                                   0.18         273
mc15a-LP-AN-ARM3                                   0.18         273
mc15a-LP-AN-ARM5                                   0.18         273
mc15a-LP-AN-ARM7                                   0.18         273
mc15a-LP-AN-ARM9                                   0.18         273
mc15a-LP-AN-ARM11                                  0.18         273
mc15a-LP-AN-ARM13                                  0.18         273
mc15a-LP-AN-ARM15                                  0.18         273
mc15a-LP-AN-ARM17                                  0.18         273

    Data will be plotted without interpretations
```
![mc15a_demag](https://user-images.githubusercontent.com/1836578/54152352-47fa9400-43fa-11e9-9b0d-2e6f8afabc2c.png)
![mc15a_eqarea](https://user-images.githubusercontent.com/1836578/54152353-47fa9400-43fa-11e9-8168-343bb17ef4f3.png)
![mc15a_zijd](https://user-images.githubusercontent.com/1836578/54152355-47fa9400-43fa-11e9-91a6-aae2e21518f4.png)


Is this being handled correctly?  I think it must be getting the meas_step_max/meas_step_min that belongs to this experiment: mc15a-LP-PI-TRM-LP-PI-ALT-PTRM-LP-PI-ZI.  Let me know what you think!

**Comment by moonshoes87** [comment]
@ltauxe, I believe I've also fixed problem 3 (filtering by LT-PTRM).  The answer is that the filtering *was* working correctly, but it was catching LP-ALT-PTRM (which does indeed contain the substring LT-PTRM).  I have fixed it by using a regular expression match instead of just a string match:

previously:

```
cond = spec_df.method_codes.str.contains( 'LT-PTRM') == False]
```

Fixed:
```
cond = spec_df.method_codes.str.contains('\ALT-PTRM|[\s:]LT-PTRM')
```

pythex.org is a great place to play with regular expressions, and happily pandas can deal with regex easily.  The above regular expression matches if LT-PTRM is at the beginning of the string OR is prefaced by ':' or ' ', and not otherwise.

I believe we can now replace zeq_magic.py with the new zeq_magic.py, if all this looks ok to you, @ltauxe .

**Comment by ltauxe** [comment]
clever.  hmmm.  
lisa

**Comment by ltauxe** [comment]
oh dear.  these must also be filtered out (like the LT-PTRM ones).

**Comment by moonshoes87** [comment]
I got the wrong code -- LP-PI-ALT-PTRM is the one that is also being caught.  Are you sure you want to exclude that?  I thought that was the behavior that caused you to comment out that entire section.  See specimens mc01a and mc01b for some examples of specimens that will then end up with no plots.

<img width="738" alt="Screen Shot 2019-03-11 at 8 42 52 PM" src="https://user-images.githubusercontent.com/1836578/54173242-66827e80-443e-11e9-961b-a4e83078dce7.png">

Or is mc01a a thellier experiment that shouldn't have been included in the first place?  It is being included due to this line:

        spec_df_th = spec_df[spec_df.method_codes.str.contains(
            'LT-T-Z')]  # zero field thermal demag steps

**Comment by moonshoes87** [comment]
Oh wait, you're saying the ARM ones need to be filtered out?

**Comment by ltauxe** [comment]
yes - same as the LT-PTRM.

**Comment by ltauxe** [comment]
the only  exception would if someone wanted to AF demagnetize an initial ARM - pretty rare and not what zeq_magic is typically used for.

**Comment by ltauxe** [comment]
no bbecause it is “LP” or lab protocol, describinh the whole set of data for the experiment.  we do NOT want to filter it out.  on the specific PTRM step (LT-PTRM).  
lisa

**Comment by moonshoes87** [comment]
ok, done.
