### ISSUE TITLE
upload_magic is converting integers to floats and then upload fails in MagIC

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#525]
**What command was run:**

upload_magic.py 

**What happened:**
the upload file was created as expected, but then the validation failed in MagIC.  upload_magic had taken inserted 'nan' values into the sites table where the site was blank and converted dir_n_measurements integer values to floats in the specimens
![screen shot 2019-03-05 at 12 09 59 pm](https://user-images.githubusercontent.com/174861/53834355-9f52bd00-3f3f-11e9-964d-2535bf965ef8.png)
<img width="829" alt="screen shot 2019-03-05 at 12 10 16 pm" src="https://user-images.githubusercontent.com/174861/53834380-abd71580-3f3f-11e9-8358-ff37129ed079.png">

 table.  These caused errors in the validation step.  

**What I expected to happen:**
I expected upload_magic to not change these values

**Data file(s):**

[sites.txt](https://github.com/PmagPy/PmagPy/files/2932640/sites.txt)
[specimens.txt](https://github.com/PmagPy/PmagPy/files/2932641/specimens.txt)

[U1456A_U1456C_U1456D_05.Mar.2019_1.txt](https://github.com/PmagPy/PmagPy/files/2932649/U1456A_U1456C_U1456D_05.Mar.2019_1.txt)

**Screenshot(s):**
<img width="829" alt="screen shot 2019-03-05 at 12 10 16 pm" src="https://user-images.githubusercontent.com/174861/53834389-b1346000-3f3f-11e9-9ec7-ffc9ef0fe27f.png">
![screen shot 2019-03-05 at 12 09 59 pm](https://user-images.githubusercontent.com/174861/53834398-b4c7e700-3f3f-11e9-9685-fc4a0c6b576b.png)

**PmagPy version:**

**Comment by moonshoes87** [comment]
@rminnett, I will see about fixing on the PmagPy side.  However, it seems to me that a value like 8.0 should not fail validation as an integer.  Do you agree?

**Comment by ltauxe** [comment]
I agree completely.  but we should also fix it in PmagPy.
lisa

**Comment by moonshoes87** [comment]
@ltauxe, agreed.  I'm working on that now.

**Comment by moonshoes87** [comment]
@ltauxe, feel free to check my solution and close this issue.

**Comment by ltauxe** [comment]
yes - this works!  thanks.

**Comment by rminnett** [comment]
> @rminnett, I will see about fixing on the PmagPy side. However, it seems to me that a value like 8.0 should not fail validation as an integer. Do you agree?

Sure, the validation is only intended to verify that the entered data match the intent of the data model. I created https://github.com/earthref/MagIC/issues/440 to track this.

**Comment by njarboe** [comment]
I was hoping that having 8.0 fail the integer check would not be a problem. We might have caught some data integrity problems that way, but it is not a big deal either way.

**Comment by moonshoes87** [comment]
@njarboe, we have fixed it on the PmagPy side (if someone uses upload_magic/Pmag GUI), so that part is done. However, I can imagine it being an annoyance for others as well.
