### ISSUE TITLE
demag gui not saving MagIC tables as expected

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#526]
**What command was run:**

demag_gui.py

**What happened:**
Tried to save MagIC tables and got an error:
ltauxe:~/Dropbox/4Rashida/Oriented_Analysis$ demag_gui.py -WD .
-I- You are in log mode.
    You can check your log output in "demag_gui.log"
    If you prefer verbose output to your Terminal/Command prompt, run "demag_gui.py -v"
Traceback (most recent call last):
  File "/Users/ltauxe/PmagPy/programs/demag_gui.py", line 6861, in on_menu_make_MagIC_results_tables
    self.On_close_MagIC_dialog(dia)
  File "/Users/ltauxe/PmagPy/programs/demag_gui.py", line 5365, in On_close_MagIC_dialog
    sites = sorted(list(spec_df['site'].drop_duplicates()))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

**What I expected to happen:**

demag_gui to save the MagIC tables

**Data file(s):**

[measurements.txt](https://github.com/PmagPy/PmagPy/files/2933882/measurements.txt)
[samples.txt](https://github.com/PmagPy/PmagPy/files/2933883/samples.txt)
[sites.txt](https://github.com/PmagPy/PmagPy/files/2933884/sites.txt)
[specimens.txt](https://github.com/PmagPy/PmagPy/files/2933885/specimens.txt)

**Screenshot(s):**

**PmagPy version:**

**Comment by moonshoes87** [comment]
@ltauxe, I'll work on this next.

**Comment by moonshoes87** [comment]
@ltauxe, this seems to be a simple issue that is fixed by ignoring blank values (it seems to happen in these files with specimens that have more than one row).  With the above fix, it all worked for me.  Let me know if you have any more trouble with this.

**Comment by ltauxe** [comment]
bless you.  this works great now.
