### ISSUE TITLE
Large lakes need outlines on pole plots

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#528]
I just pulled from master. I wanted to run the plots again with the various improvements added recently, but now I see these big lakes in Western North America on the pole plots. Is this a known issue in Cartopy that we are just accepting at the moment? The last version of the plots I made did not have this problem.

from contribution 16545:
[magic_contribution_16454.txt](https://github.com/PmagPy/PmagPy/files/2954145/magic_contribution_16454.txt)
![LO__P941_TY__POLE_map](https://user-images.githubusercontent.com/1278789/54157080-d411b900-4404-11e9-9556-deefa27c7b00.png)

http://34.236.167.37/files/tmp/LO:_P941_TY:_POLE_map.png

**Comment by Swanson-Hysell** [comment]
Which lakes are a problem here? The Great Lakes and northern Canada lakes (e.g. Slave) all look good as does the Great Salt Lake.

**Comment by moonshoes87** [comment]
I believe Lisa did change the default resolution for server plots, which may have changed the appearance of the map somewhat.

**Comment by Swanson-Hysell** [comment]
While the resolution may have changed, I don't think there is anything wrong with the outlines and their  position.

**Comment by Swanson-Hysell** [comment]
@njarboe Do you think that we shouldn't be including lakes?

**Comment by njarboe** [comment]
@Swanson-Hysell, I think the cartoonish look of the lakes was throwing me off, along with the lack of black outlines. The lakes are good, if there is a way to add black outlines. Otherwise probably leave them off would be my preference. Hard to tell exactly without seeing the differences side-by-side.

**Comment by ltauxe** [comment]
the lakes are real - we can color them the same as the continents if you like so you would see them. 
lisa

**Comment by ltauxe** [comment]
sure we can add black outlines - i’ll look into it.

**Comment by moonshoes87** [comment]
@ltauxe and @njarboe, is it still a priority to add outlines to the lakes?

**Comment by Swanson-Hysell** [comment]
I think it is right to close this issue. I will note that the default in ipmag is no lakes:
<img width="768" alt="Screen Shot 2020-02-14 at 3 23 45 PM" src="https://user-images.githubusercontent.com/4332322/74575998-ff1e5a00-4f3d-11ea-96c8-d3bd2c69ed36.png">
