### ISSUE TITLE
MagIC ID number missing on sever plots

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#529]
The plot used in #528 should have the MagIC id on the web address in the right bottom corner. So earthref.org/MagIC/16454 should be there.

**Comment by moonshoes87** [comment]
Id is missing from the contribution table, so I think this is actually a data quality issue belonging in: https://github.com/earthref/MagIC/issues/391

**Comment by njarboe** [comment]
Ok. I see it on other plots.
