### ISSUE TITLE
find_EI.py not returning correct values for example data

### ISSUE THREAD

**Issue by cthissen** [PmagPy/PmagPy#53]
Running the test data
`find_EI.py -f find_EI_example.dat`
returns 
```
Io Inc  I_lower, I_upper, Elon, E_lower, E_upper 
38.9  =>     58.8 _     0.0 ^    67.0:  1.4679 _ 0.0000 ^ 1.7189

```
when it should return something like this
```
Io Inc  I_lower, I_upper, Elon, E_lower, E_upper
38.9  =>     58.8 _    48.4 ^    67.0:  1.4679 _ 1.2912 ^ 1.7337

```
For some reason, both E_lower and I_lower are zero. I get the expected results with pmag-3.3.2, but not the current version.

**Comment by Swanson-Hysell** [comment]
Thanks for reporting this bug. It should now been fixed. A variable was renamed when adding the option of site-level (rather than study-level) correction a couple days ago.
