### ISSUE TITLE
refactor aniso_magic

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#531]
Need to get approval, remove -new flag, and implement Contribution argument.

**Comment by ltauxe** [comment]
ipmag.aniso_plots() does not work like ipmag.aniso_plots_nb() and it should.  can we just rename  ipmag.aniso_plot_nb() to be ipmag.aniso_plots()  when we remove the -new flag.

**Comment by ltauxe** [comment]
the -v option does not work as expected - it should give plots with a bunch of dots (like in PmagPy.ipynb example for aniso_magic_nb.  this gives the confidence ellipses instead.  and i don't see how to get the eigenvalue cdf plots...

**Comment by moonshoes87** [comment]
Yes, I am going to remove ipmag.aniso_magic and rename ipmag.aniso_magic_nb once it is fully working correctly with your seal of approval!  I can check the -v option.  eigenvalue cdf plots should be created when both iboot and ivec are True.  

I wonder if there is something wrong in how I am processing of the command line arguments?  I'm hoping you can help clarify the desired behavior for me.  Maybe I have some incorrect defaults in the command line version.  See the following two examples:

Comparing the second example for aniso_magic_nb in PmagPy.ipynb

```
ipmag.aniso_magic_nb(infile='sed_specimens.txt',dir_path='data_files/aniso_magic',
       iboot=1,ihext=0,ivec=1,Dir=[0,90],vec=3,ipar=1, save_plot=True) # parametric bootstrap and compare V3 with vertical
```

output:

![_g_aniso-conf](https://user-images.githubusercontent.com/1836578/54466017-2c192a00-473b-11e9-8cdc-a1558d74e5cd.png)
![_g_aniso-data](https://user-images.githubusercontent.com/1836578/54466018-2c192a00-473b-11e9-9a13-0245019ef363.png)
![_g_aniso-tcdf](https://user-images.githubusercontent.com/1836578/54466019-2c192a00-473b-11e9-9d7d-c7c807c87789.png)
![_g_aniso-cdf_0](https://user-images.githubusercontent.com/1836578/54466022-2facb100-473b-11e9-88c5-14073179883f.png)
![_g_aniso-cdf_1](https://user-images.githubusercontent.com/1836578/54466023-2facb100-473b-11e9-9ab3-a0cd751ae70b.png)
![_g_aniso-cdf_2](https://user-images.githubusercontent.com/1836578/54466024-2facb100-473b-11e9-8901-8c4c562cbd5c.png)


and

`!aniso_magic.py -WD . -ID data_files/aniso_magic -v -d 3 0 90 -new -par -f sed_specimens.txt -sav`

Output of the second command:

![_g_aniso-conf](https://user-images.githubusercontent.com/1836578/54465908-b90fb380-473a-11e9-9e22-06b3b2f0c5b5.png)
![_g_aniso-data](https://user-images.githubusercontent.com/1836578/54465909-b90fb380-473a-11e9-90d8-24ebceca02e5.png)
![_g_aniso-tcdf](https://user-images.githubusercontent.com/1836578/54465910-b90fb380-473a-11e9-8c72-bac3991977f0.png)
![_g_aniso-cdf_0](https://user-images.githubusercontent.com/1836578/54465915-bd3bd100-473a-11e9-9601-da86a205c848.png)
![_g_aniso-cdf_1](https://user-images.githubusercontent.com/1836578/54465916-bd3bd100-473a-11e9-9995-3d70c7749127.png)
![_g_aniso-cdf_2](https://user-images.githubusercontent.com/1836578/54465917-bdd46780-473a-11e9-9eb9-cea9679542a2.png)

**Comment by ltauxe** [comment]
-v should set ivec=1 and vec=3 (eigenvalues cdfs).   i think we are close.  
lisa

**Comment by moonshoes87** [comment]
The last three plots are only created if a value is given for `Dir`.  Otherwise, the `vec` argument is never used.  if the `-v ` flag is used, should we pass in a default value for `Dir` as well?

in plot_aniso:
```
                # do cartesian coordinates of selected eigenvectori [using vec] vs Dir
                if len(Dir) > 0:
                    V = [row[vec-1] for row in BVs]
                    X = pmag.dir2cart(V)
                    comp_X = pmag.dir2cart(Dir)
                    for i in range(3):
                        xs = np.sort(np.array([row[i] for row in X]))
                        pmagplotlib.plot_cdf(
                            fignum+i+3, xs, "", colors[i], "")  # plot the CDF                               
                        figs['cdf_' + str(i)] = fignum + i + 3
                        # minimum 95% conf bound                                                             
                        plt.axvline(xs[int(0.025*len(xs))],
                                    color=colors[vec-1], linestyle=styles[i])
                        # max 95% conf bound                                                                 
                        plt.axvline(xs[int(0.975*len(xs))],
                                    color=colors[vec-1], linestyle=styles[i])
                        # put on the comparison direction                                                    
                        plt.axvline(
                            comp_X[0][i], color='lightgreen', linewidth=3)
```

**Comment by ltauxe** [comment]
no that is correct.  the last three are comparing the bootrapped eigenvectors with a known direction.  
lisa

**Comment by moonshoes87** [comment]
Gotcha.  I think I fixed it.  Give it another try?
