### ISSUE TITLE
refactor biplot_magic

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#532]
Each plotting program must work on the command line, in a notebook, and in tests.
Each command line program should have main() function that is only for the command line logic, and calls an ipmag function that does the calculation.
Each program should return a list of saved files.
Each program should be able to take a contribution/pandas dataframe argument instead of reading in a data file.

**Comment by ltauxe** [comment]
perhaps we should deprecate biplot_magic altogether?   
lisa

**Comment by moonshoes87** [comment]
We could -- your call.  I'm realizing that I should focus first on the programs that are used in make_magic_plots and Pmag GUI, though.  Let me know what you think about biplot_magic.

**Comment by ltauxe** [comment]
hmmm. i guess we better fix it then.  i have an example in PmagPy.ipynb that we could use to make an ipmag version

**Comment by ltauxe** [comment]
so we don't have biplot_magic in make_magic_plots - should we?

**Comment by moonshoes87** [comment]
If you want to -- I was meaning that I will work on other programs that are in make_magic_plots first, then consider returning to the other plotting programs.

**Comment by ltauxe** [comment]
yes good plan.  if i get to biplot_magic, i’ll do it, and we can add it to make_magic_plots.py.    but it is lower priority than others.  
lisa
