### ISSUE TITLE
Title on pole plot for server should state the number of poles more clearly

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#535]
Title on pole plot for server should state the number of poles more clearly. For 13689 we have "0 pole 1 reversed pole"  Note that this should say reversed not reverse as per our controlled vocab for magnetic polarities.

What we would like is "0 normal and 1 reversed pole". Or in this case just "1 reversed pole" 
![Screen Shot 2019-03-12 at 1 18 54 PM](https://user-images.githubusercontent.com/1278789/54233529-5912d600-44ca-11e9-913e-148332303323.png)

**Comment by moonshoes87** [comment]
How do these look?  I tried using commas, but they don't show up for some reason (probably based on spacing, which I don't want to break).  I could add different punctuation, like '-' or ':'.  Let me know what you think.

![MC:_13436_TY:_POLE_map_t](https://user-images.githubusercontent.com/1836578/54306399-83c26480-4586-11e9-8be9-8f9efb896480.png)
![MC:_13436_TY:_POLE_map_t_with_both](https://user-images.githubusercontent.com/1836578/54306444-8f159000-4586-11e9-9eca-9152fdca7d63.png)
![MC:_13689_TY:_POLE_map_g](https://user-images.githubusercontent.com/1836578/54306470-9b99e880-4586-11e9-82d2-96792d195ba1.png)

**Comment by njarboe** [comment]
These are good. First one seems to have an extra space between normal and pole.

**Comment by njarboe** [comment]
Will re-run plots shortly.

**Comment by moonshoes87** [comment]
Great, if you can pull my latest changes, that would be great!

**Comment by njarboe** [comment]
Ok. Pulled and re-running. 

The plot log now updates while the plots are being made:http://34.236.167.37/plots/batchPlotLog.txt

And you can see all the files and plots in the MagIC ID number directory in http://34.236.167.37/plots
