### ISSUE TITLE
upload_magic.py

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#536]
**What command was run:**

upload_magic.py

**What happened:**

it inserted nan for blank data in core_depth and composite_depth keys

**What I expected to happen:**

i expected these blanks to stay blank!

**Data file(s):**

**Screenshot(s):**

**PmagPy version:**

**Comment by moonshoes87** [comment]
@ltauxe, could you send me or post the data files?

**Comment by moonshoes87** [comment]
@ltauxe, this should be fixed now, let me know if it doesn't work as expected for you.
