### ISSUE TITLE
Problem: "KeyError: 'treat_tmp'" in newly contributed data file

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#537]
Problem "KeyError: 'treat_tmp'" in magic_contribution_16609.txt
[magic_contribution_16609.txt](https://github.com/PmagPy/PmagPy/files/2962132/magic_contribution_16609.txt)
ran on server pulled this morning on master.
![Screen Shot 2019-03-13 at 8 12 45 AM](https://user-images.githubusercontent.com/1278789/54290756-c9703480-4568-11e9-9d36-18798caaa231.png)

Possible data model validation mismatch?

**Comment by moonshoes87** [comment]
@njarboe, we just did an overhaul of zeq_magic -- refactored so that the same code is used in zeq_magic and ipmag.zeq_magic, which means a big reduction in redundancy and improved consistency.  However, in the meantime, I expect to find some problems.  Thanks for sending them along :)

**Comment by moonshoes87** [comment]
@njarboe, interestingly, this contribution actually failed to run in the old zeq_magic, too.  It is a pretty odd measurements file -- only two measurements, both of which are labeled bad.  In any case, I believe I fixed the code so it won't barf on this kind of thing in the future.  If you don't mind giving it another try, that would be great.

**Comment by njarboe** [comment]
@moonshoes87 Looks good.
