### ISSUE TITLE
Demag GUI tests require interaction to run

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#54]
The new Demag GUI tests seem to require interaction to run.  When I run them, I get stuck with screens like this: 
![screen shot 2016-03-08 at 3 14 11 pm](https://cloud.githubusercontent.com/assets/1836578/13619930/cb6df532-e540-11e5-83dd-7a1d75f94678.png)

and then I have to click through for the testing to continue.  This won't work for automated testing (Travis CI), and it isn't ideal for running through all PmagPy tests in a batch.

Is this the behavior that other people get, as well?  Or is it a local problem?

**Comment by Swanson-Hysell** [comment]
Interesting... @Caoimhinmg it would make sense to pull these tests requiring interaction out of the main test suite. Perhaps they could live somewhere else.

**Comment by Caoimhinmg** [comment]
Sorry, working on removing the interaction requirement I was hoping they wouldn't run when you ran the other tests as I didn't add the demag_tests to the __init__ file in the tests directory. If it's causing a problem with the other tests I'll move it while I finish development.

**Comment by moonshoes87** [comment]
Yeah, testing wxPython is kind of a pain.  There might be some useful information in this post, but it might not be anything you don't already know: http://wiki.wxpython.org/Unit%20Testing%20with%20wxPython

The way I typically run the tests is with: "python -m unittest discover".  This means that the unittest module will find anything that calls unittest.main():

    if __name__ == '__main__':
        unittest.main()

We can instruct unittest to skip certain tests: https://docs.python.org/2/library/unittest.html#skipping-tests-and-expected-failures .  For example, the code below can be applied at the class or the test-case level, and will skip everything in that class/test case.

    @unittest.skip("Reason for skipping")
    class()....

There is also "@unittest.skipIf", so there might be some kind of conditional logic that we could apply.  

I'll just add the skip line for the time being.

**Comment by Swanson-Hysell** [comment]
This workaround is fine for the moment.
