### ISSUE TITLE
Log from the latest run of the plots with various errors.

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#540]
@moonshoes87 The log from the last plot run can be found at:http://34.236.167.37/files/batchLog.txt

This run was started about a day and a half ago with the latest master version. The first Traceback was the one I posted as an issue but wanted you to have access to the whole file, if that would be helpful for debugging the new plotting changes. Let me know if there are other things I can do to help with that or when a good time to re-run the plots would be.

**Comment by moonshoes87** [comment]
Thanks, @njarboe.  I'll work my way through until I start seeing mostly repeat issues, and then let you know.

**Comment by moonshoes87** [comment]
11846 is missing 'sample' column in samples table (reported in https://github.com/earthref/MagIC/issues/391).  Should I make a fix for this in PmagPy, so that it doesn't throw an error?  Seems like this is a pretty minimal standard that should be upheld in all contributions.

**Comment by njarboe** [comment]
No. Next time I run all the plots I can bypass the contributions in earthref/MagIC#391 until the data in those are fixed so you don't keep seeing them.

**Comment by moonshoes87** [comment]
Great, that will be helpful.

**Comment by ltauxe** [comment]
you might as well put in a trap so PmagPy doesn’t croak over this, but perhaps should warn the user that this is a required column (except for synthetics - perhaps this is a synthetic?) 
lisa

**Comment by moonshoes87** [comment]
@ltauxe, I've added a fix of sorts for this.  PmagPy won't build a MagicDataFrame for a samples table (etc.) if it doesn't have a sample column -- it will treat that the same way it would treat an empty file.  This means nothing should crash.

**Comment by ltauxe** [comment]
ok.  that allows folks to use the GUIs but they will have to fix the table prior to uploading.

**Comment by moonshoes87** [comment]
Yes, and make_magic_plots will still be able to create other plots that don't require that table.  yay!

**Comment by moonshoes87** [comment]
@njarboe, could you point me towards the current latest log?

**Comment by njarboe** [comment]
http://34.236.167.37/plots/batchPlotLog.txt

These were done on the 21st March. Do you want me to re-run?

I'm still figuring out why the thumbnails are not cropped right on the server.

**Comment by moonshoes87** [comment]
No, that should be ok -- I haven't worked much since then, I've had a crazy ear infection.  Let me know if I can help with the thumbnail issue.  When running locally, I get the incorrectly cropped thumbnails if I comment out `-new` from the aniso_magic command, and the correctly cropped thumbnails if I leave `-new`.  I wonder if you could somehow be calling an out-of-date version of make_magic_plots.py, perhaps installed via pip or something like that?

**Comment by ltauxe** [comment]
so i’m just about ready to start working with the aniso_magic script.  are we still using the -new syntax?  that seems a bit awkward.
lisa

**Comment by moonshoes87** [comment]
@ltauxe -- I will drop the -new for aniso_magic as soon as you approve it :)  I believe I addressed your last concerns with the new aniso_magic, but if you can confirm that it works as expected I will make that change.  

I already dropped -new for zeq_magic, we are just diving into the future.

**Comment by ltauxe** [comment]
ok - i’ll check it with new JR data today or tomorrow.  
lisa

**Comment by njarboe** [comment]
Closing this issue with #546 open with the new plot run.
