### ISSUE TITLE
demag_gui fails with developer installation

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#545]
**What command was run:**
I installed PmagPy following the OSX developer instructions in the cookbook on the JOIDES Resolution.  The path is set correctly in .bashrc.  All programs seem to function normally, EXCEPT the GUIs.  I ran:  demag_gui.py from within the data_files/3_0/McMurdo directory

**What happened:**

a bunch of errors 

**What I expected to happen:**

I expected it to run as it does on my own computer

**Data file(s):**
data_files/3_0/McMurdo

**Screenshot(s):**

**PmagPy version:**
pmagpy-4.2.21

**Comment by moonshoes87** [comment]
@ltauxe, could you attach the errors to this issue?

**Comment by ltauxe** [comment]
this is related to the criteria.txt problem and has now been fixed (i think).
