### ISSUE TITLE
Plots with some errors from run for March 26th, 2019

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#546]
@moonshoes87 The latest run is finished and the log is at http://34.236.167.37/plots/batchPlotsLog.txt

There are some "Traceback" errors involving zeq_magic.py and "None" values.

The previously "bad data" labeled files should not have been run.

**Comment by moonshoes87** [comment]
@njarboe, I believe I've fixed everything revealed by this run, except for issue #553 which will require feedback from Lisa, and the contributions with bad data.  Please go ahead and re-run!

**Comment by njarboe** [comment]
@moonshoes87 Re-running. I'll let you know when it is finished and the log location. The new bad contributions you added to the list should not be run now.
