### ISSUE TITLE
thellier_magic.py problem making deremag plots with teslas as units

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#553]
**What command was run:**

```
download_magic.py -f magic_contribution_16501.txt
thellier_magic.py -sav -fmt png -fsp specimens.txt -f measurements.txt -spc SW01-01A-1_sun
```

**What happened:**

```
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 109, in <module>
    main()
  File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 100, in main
    spec, n_specs, save_plots, fmt, interactive)
  File "/Users/nebula/Python/PmagPy/pmagpy/ipmag.py", line 10699, in thellier_magic
    zed = make_plots(this_specimen, thel_data, cnt)
  File "/Users/nebula/Python/PmagPy/pmagpy/ipmag.py", line 10645, in make_plots
    AZD, araiblock, zijdblock, this_specimen, unit_string)  # make the plots
  File "/Users/nebula/Python/PmagPy/pmagpy/pmagplotlib.py", line 1288, in plot_arai_zij
    plot_np(ZED['deremag'], araiblock, s, units)
  File "/Users/nebula/Python/PmagPy/pmagpy/pmagplotlib.py", line 1218, in plot_np
    plt.text(X[-1] - delta, Y[-1] + delta,
IndexError: list index out of range
```

**What I expected to happen:**

Plots created, or fail gracefully.

**Data file(s):**

[magic_contribution_16501.txt](https://github.com/PmagPy/PmagPy/files/3035853/magic_contribution_16501.txt)

Units are 'T', which isn't an option in pmagplotlib.plot_np:

If I change the code in plot_np to treat teslas like joules or blank:    
```
 for rec in first_Z:
        if units == "K":
            if rec[0] != 0:
                X.append(rec[0] - 273.)
            else:
                X.append(rec[0])
	if (units == "J") or (not units) or (units == "T"):  # added 'T' here
            X.append(rec[0])
```

then everything runs and produces these plots:

![SP:_SW01-01A-1_sun_TY:_deremag_](https://user-images.githubusercontent.com/1836578/55435371-8fce9000-554e-11e9-8c78-627d0f6a3df5.png)
![SP:_SW01-01A-1_sun_TY:_eqarea_](https://user-images.githubusercontent.com/1836578/55435372-8fce9000-554e-11e9-81a1-8273158ad86b.png)
![SP:_SW01-01A-1_sun_TY:_zijd_](https://user-images.githubusercontent.com/1836578/55435373-90672680-554e-11e9-978c-04cd1979ca3d.png)
![SP:_SW01-01A-1_sun_TY:_arai_](https://user-images.githubusercontent.com/1836578/55435375-90672680-554e-11e9-908a-a8d4d3663930.png)

@ltauxe, I'm wondering if the method codes are just wrong in this contribution, or what.  Is my hack-y fix useful, or should I make a useful error message instead?

With this specimen, it also looks like in pmag.sortarai, the resulting araiblock is missing ptrm_checks, ptrm_tails, and zptrm_checks, but I'm not sure if this is relevant or not.  

```
araiblock ([[273, 1.81, 45.51, 3.590448e-05, 1], [273.0, 1.81, 45.51, 3.590448e-05, 1], [273.0, 1.81, 45.51, 3.590448e-05, 1]], [[273, 0.0, 0.0, 0.0, 1], [273.0, 151.05903825924304, -10.913418701074121, 5.2651869672693324e-05, 1], [273.0, 151.05903825924304, -10.913418701074121, 5.2651869672693324e-05, 1]], 
[], [], [], 
[[0.0, array([42.88251484])], [0.0, array([42.88251484])]])
```

**Comment by moonshoes87** [comment]
@ltauxe, I added in this fix - feel free to weigh in if this is a bad idea for some reason.

**Comment by ltauxe** [comment]
indeed - these data are not thellier data and have the wrong method codes assigned to them.  according to the paper, there are some actual thellier data, but the contribution is a mess with different experiments and wrong method codes.

**Comment by moonshoes87** [comment]
Bummer.  Do you think there is something else we should do in PmagPy to provide a better error message?  And should we leave the fix that I did to allow teslas (otherwise some plotting will fail on the server)?

**Comment by moonshoes87** [comment]
I am closing this as it seems to be an edge case with bad data.
