### ISSUE TITLE
April 3rd, 2019 round of all plots

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#555]
@moonshoes87, with the 4 "large" files included this time the plotting took about 24hr. The 134MB log file is at:
http://34.236.167.37/plots/batchPlotsLog.txt

About 6 Traceback errors.

**Comment by moonshoes87** [comment]
It looks like at least one of the very large contributions (https://earthref.org/MagIC/16277), fails with a `MemoryError` during the `download_magic.py` command.  Thus, no plots at all are created.  This doesn't happen for me locally -- I am able to run download_magic.py and at least start make_magic_plots.py.  Perhaps there is a way to either allocate more memory on the server, or to pre-run download_magic in a different environment on these very large files?

**Comment by moonshoes87** [comment]
@njarboe, In the plot log, I am seeing errors with contribution 16508.  But that just seems to be an older version of https://earthref.org/MagIC/16619.  Is there a reason that the older version should be getting run?

**Comment by njarboe** [comment]
@moonshoes87 I had a directory full of current files on the plot server some time back from which I run the plots off of. I have added new files but did not remove this one. I have removed it now. Sometime soon I can switch over to downloading the current files from s3 directly, now that that system is in place.
