### ISSUE TITLE
Plots run from April 15th 2019

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#559]
The plots have finished and I see only one Traceback error this time. The log is at:
http://34.236.167.37/plots/batchPlotsLog.txt

**Comment by moonshoes87** [comment]
Looks like the only traceback error is related to https://earthref.org/MagIC/16497, which is already in https://github.com/earthref/MagIC/issues/391 for having bad values in controlled vocabularies.  

So this is good progress!  Can you check for which contributions end up with errors.txt files?  That could also reveal problems either in PmagPy or with data integrity.  Should just require `find . -name errors.txt` from the plots directory.

**Comment by njarboe** [comment]
@moonshoes87, added 16497 to the skip list. 

All the files created during making the plots can be found in: http://34.236.167.37/plots/$MAGICID/
Here is the errors.txt list:
./13742/errors.txt
./16279/errors.txt
./16277/errors.txt
./16426/errors.txt
./15444/errors.txt
./16335/errors.txt
./15349/errors.txt
./15897/errors.txt
./13727/errors.txt
./16240/errors.txt
./16619/errors.txt
./16450/errors.txt
./16308/errors.txt
./16501/errors.txt
./16238/errors.txt
./16291/errors.txt
./16497/errors.txt
./16515/errors.txt
./15283/errors.txt
./13709/errors.txt
./14359/errors.txt
./16334/errors.txt
./15890/errors.txt
./16452/errors.txt
./16358/errors.txt
./11943/errors.txt
./14868/errors.txt
./12450/errors.txt
./16609/errors.txt
./16263/errors.txt
./16273/errors.txt
./16505/errors.txt
./11881/errors.txt
./15221/errors.txt
./14614/errors.txt
./15840/errors.txt
./16416/errors.txt
./11189/errors.txt
./16458/errors.txt
./16269/errors.txt
./14575/errors.txt
./16421/errors.txt
./11883/errors.txt
./16353/errors.txt
./11821/errors.txt
./16301/errors.txt
./14809/errors.txt
./15435/errors.txt
./16508/errors.txt
./16280/errors.txt
./16460/errors.txt
./16305/errors.txt
./12638/errors.txt
./16496/errors.txt
./16258/errors.txt
./16237/errors.txt
./16233/errors.txt
./14891/errors.txt
./16410/errors.txt
./15551/errors.txt
./11906/errors.txt
./13538/errors.txt
./16624/errors.txt
./16411/errors.txt
./16529/errors.txt
./16313/errors.txt
./15803/errors.txt
./15040/errors.txt
./14384/errors.txt
./16457/errors.txt
./16626/errors.txt
./15461/errors.txt
./15085/errors.txt
./16015/errors.txt
./11773/errors.txt
./11929/errors.txt
./11846/errors.txt
./13969/errors.txt
./16618/errors.txt
./16623/errors.txt

**Comment by moonshoes87** [comment]
Thanks, @njarboe!  I've added some notes to the MagIC data integrity issue https://github.com/earthref/MagIC/issues/391.  Otherwise, there don't seem to be any obvious problems left for me to fix here.

Once I get through some more of the refactoring in make_magic_plots.py, we can run again.  Or, if you or @rminnett notice any plot issues in what is displayed on the server, point me in that direction.
