### ISSUE TITLE
PmagPy.ipynb is slow

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#562]
**What command was run:**

Opened the PmagPy.ipynb notebook and it was slow to load.

**What happened:**

It is bit difficult to use the notebook given how long it takes to load and how long it takes to respond to things like resizing the window. This has been an issue for a while and I presume I am not the only one who has experienced it.

**What I expected to happen:**

The notebook is a fantastic reference and teaching tool. If it is slow and lagging it might be off-putting to users. Perhaps we could split it into multiple notebooks such: *calculations*, *plots*, *working with MagIC* to try prevent this issue. Or perhaps it is better to leave as is.

**PmagPy version:**
4.2.24

**Comment by ltauxe** [comment]
i do think we should break it up into separate notebooks for the different topics.  we can link from one to another so there is no reason that they have to all be in one.  i’ll take a stab at this, unless you want to Nick?  
lisa

**Comment by Swanson-Hysell** [comment]
I can tackle it given that it was my suggestion.

I will plan to split into these notebooks:

- PmagPy_introduction
- PmagPy_calculations
- PmagPy_plots
- PmagPy_MagIC

**Comment by moonshoes87** [comment]
@Swanson-Hysell, I agree that this will help make that notebook more useable.  We will need to decide how we want to handle the pmagpy.github.io pages and the binder hosted pages, as well as updating the markdown links to those resources within the notebooks.  For now, those links and pages will continue to be correct and functional, but we will want to update those documentation pages eventually.  

Perhaps I can work on updating the static html and binders once you're done, @Swanson-Hysell?

**Comment by Swanson-Hysell** [comment]
Yes. I realized that the static html would be an issue when going through. Jupyter notebooks can link to each other so I am making sure that each one links to the other one. And we can keep the -cli notebook the same, I think?

I am still working on a few improvements for the PmagPy_plots_analysis.ipynb notebook.

I am bumping into a few issues that I will document as I try to run this notebook.

**Comment by Swanson-Hysell** [comment]
I have now created these notebooks:

PmagPy_introduction.ipynb
PmagPy_calculations.ipynb
PmagPy_MagIC.ipynb
PmagPy_plots_analysis.ipynb (I raised separate issues for two things that came up when trying to run this notebook)

That are more manageable. I left the previous PmagPy.ipynb in there for the moment, but if @ltauxe and @moonshoes87 are happy with these we could delete that notebook since these contain everything that was in those (would be good to do that soon so that we aren't needing to keep things updated in different places).

**Comment by moonshoes87** [comment]
Yes, I think PmagPy-cli.ipynb can be left as is.  

So, the steps for me to do to update the documentation:

- Create static html pages for the 4 new notebooks (including adding a somewhat different intro paragraph, that doesn't mention 'how to run this notebook')
- Re-do the Cookbook links to point at the new static html
- Re-do the PmagPy-cli links to point at the new static html
- Look at the Binder situation and decide how we want to handle it

I could use input on one question.  I had set up the links between PmagPy-cli and PmagPy to go to the static html, not to a notebook.  In other words, if you're in the ani_depthplot section in PmagPy, and you want to see documentation on the command line version, you get linked like this:  [\[command_line_version\]](http://pmagpy.github.io/PmagPy-cli.html#ani_depthplot.py), which sends you to the static html section on ani_depthplot.py.  The nice thing is that this link works whether you are looking at static html, or running a notebook server locally, or in a Binder.  I don't want to create a maintenance hassle, but maybe I should customize those links for static html vs local notebook using grep/sed to replace the local links with static ones.

Thoughts?

**Comment by moonshoes87** [comment]
Should be pretty easy to do the links -- just query replace:

http://pmagpy.github.io/PmagPy-cli.html#  with PmagPy-cli.ipynb#  or vice versa.   Plus a couple more times for the other notebooks.  

@Swanson-Hysell, let me know when you are done in the notebooks and I will get to work on links and static html.

**Comment by Swanson-Hysell** [comment]
I am done with the notebooks for now. So go for it.

One thought is that it is a bit confusing that the table of contents list is the name of the command line programs rather than the functions. This approach has the advantage of the notebooks being the same as the PmagPy-cli in names. One option would be to insert the names of the relevant ipmag/pmag function in the description in the table of contents as well?

**Comment by moonshoes87** [comment]
Great, I will work on that.

Regarding the table of contents, are you meaning the table of contents in the Cookbook, or in the notebooks?  In many cases, the names are the same if the functionality is the same (i.e., I renamed ipmag.dayplot to ipmag.dayplot_magic to follow this convention).  Could you give me an example of what adding the ipmag/pmag function name could look like?  I would be happy to make them more clear!

**Comment by Swanson-Hysell** [comment]
I am referring to the notebook list of functions/functionality.

For example, polemap_magic is the command line program, but in the notebook what is used is ipmag.plot_pole. (**Please don't rename ipmag.plot_vgp!**). Another example is revtest being ipmag.reversal_test_bootstrap (again, I don't think renaming the ipmag function here is wise given backward compatibility issues and the fact that the function name is pretty informative). The result is that the list of functions that is the contents has different naming conventions than if it were not being tied to the command line programs. 

The reality is that if we were seeking to

**Comment by moonshoes87** [comment]
Yes, I won't rename any of those things!  How do you think the contents list could be updated to reflect those differences better?

Something like this?  Or is that awkward?

    - [polemap_magic/plot_pole](#polemap_magic) : reads in MagIC formatted file with paleomagnetic poles and plots them

Also, I'm questioning my initial impulse to link the notebooks directly.  For example, if you go from ani_depthplot.py in PmagPy-cli to the ani_depthplot section in PmagPy_plots_analysis, then try to run that cell, you will just get errors.  This could be more frustrating and confusing to notebook newcomers who don't know that they need to scroll up to the first cell and run it.  Perhaps it is better to simply stay linked to the static html?  

<img width="1098" alt="Screen Shot 2019-04-24 at 3 20 02 PM" src="https://user-images.githubusercontent.com/1836578/56697767-7aa7d580-66a4-11e9-9e11-c4dd1b0cc0f0.png">

**Comment by moonshoes87** [comment]
I've fully updated the static documentation to use the new notebooks.  I'm leaving http://pmagpy.github.io/PmagPy.html (the full PmagPy.ipynb) in place for now.  All the links between notebooks should work in the static html.  

The notebooks also link to each other locally in their introductory paragraphs, i.e.:

<img width="1030" alt="Screen Shot 2019-05-05 at 2 09 25 PM" src="https://user-images.githubusercontent.com/1836578/57200322-6e8f0400-6f3f-11e9-8388-1b80e22a82b1.png">

So if you are running the notebooks locally, you can switch between them very efficiently.  The other links that come later in the notebooks that go to a *different* notebook will go to the static html.  I.e, the command line link below goes to the static html:

<img width="1038" alt="Screen Shot 2019-05-05 at 2 11 11 PM" src="https://user-images.githubusercontent.com/1836578/57200350-b6159000-6f3f-11e9-9fc6-28a8d0bd63f3.png">

As I said in the previous comment, it's awkward to link to the middle of a different notebook because it won't actually run correctly without first running the initial cells.  

I think everything looks pretty good and is much more efficient to load :)

**Comment by moonshoes87** [comment]
The Cookbook links have been updated.  I'm not going to redo the Binder demo for now.
