### ISSUE TITLE
Missing demag_gui help file

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#57]
The help PDF for Demag GUI appears to be missing.  Either the "Help --> Usage & Tips" option should be taken out of the menu, or we should put demag_gui_doc.pdf back in.  

I noticed this because I'm trying to make sure all image files etc. are available in the pmagpy-cli edition of the GUIs.

**Comment by Swanson-Hysell** [comment]
The information that was in this file was moved to the cookbook. Perhaps choosing this option in the dropdown menu could link to that part of the Earthref hosted cookbook?

**Comment by moonshoes87** [comment]
That sounds like a good solution.  Do you want to implement this or should I?

**Comment by Swanson-Hysell** [comment]
If you could go ahead and do it that would be great.
