### ISSUE TITLE
No module named demag_interpretation_editor error in demag_gui

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#58]
Recent changes to demag_gui are resulting in this fatal error:

```
Traceback (most recent call last):
  File "/Users/Laurentia/PmagPy/programs/pmag_gui.py", line 332, in on_run_demag_gui
    import demag_gui
  File "/Users/Laurentia/PmagPy/programs/demag_gui.py", line 73, in <module>
    from dialogs.demag_interpretation_editor import InterpretationEditorFrame
ImportError: No module named demag_interpretation_editor
```

**Comment by moonshoes87** [comment]
The solution may be adding to the dialogs __init__.py file.  I'm going to play with this.

**Comment by moonshoes87** [comment]
Could you try some diagnostic tests for me?

1.  In a non PmagPy directory, try `import dialogs` in the Python interpreter and see what you get.
2.  See if installing this version of pmagpy fixes your problem (from test site not main site):  pip install -i https://testpypi.python.org/pypi pmagpy --upgrade

I actually can't reproduce your error, but I think some things may be getting cached weirdly or something like that -- I should probably set some virtual environments.

**Comment by Swanson-Hysell** [comment]
I'm am simply running the GUI out of the repo (which is an option I think we should still support) rather doing a pip install. Given the framework issue with Anaconda (which I haven't been able to take the time to look into) and the fact that I want to be using the Anaconda distribution given how nice of a package manager it is, I haven't been using the pip installed version of PmagPy.

I can ```import dialogs``` (since the PmagPy folder is in my path) but after doing so there don't appear to be any functions available from the module. I think this is an init.py issue as you say since the submodules need to be loaded using the init.py no?

**Comment by moonshoes87** [comment]
I agree, everything should be able to run from the repo.  I'm still a little perplexed that I couldn't reproduce your error, but oh well.  

I add the \_\_init\_\_.py file.  Let me know if that fixes the problem!

**Comment by Swanson-Hysell** [comment]
That does it. Thanks!
