### ISSUE TITLE
Remove MagIC data model 2 options from Pmag GUI

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#583]
@ltauxe, should I just rip all of the MagIC data model 2 support out of Pmag GUI?  We really don't want anyone using data model 2 anymore, right?  It doesn't really make sense to update, for example, the new IODP conversions to be able to output magic data model 2 (#580).  Let me know if you're ok with me taking data model 2 out of Pmag GUI (I won't touch Thellier/Demag GUI in this process).

**Comment by ltauxe** [comment]
Yes, let’s clean house. Another thing: I do need to verify that all files
downloaded from LIMS, including old ones, can be converted with the new
conversion scripts too

**Comment by moonshoes87** [comment]
It looks like magic_grid2 is still used in Pmag GUI (data model 3).  I might want to switch that to use magic_grid3 eventually, but otherwise, none of the MagIC 2 dialogs are left.

**Comment by moonshoes87** [comment]
This is done and seems to be fine.
