### ISSUE TITLE
bug in command line versions

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#585]
**What command was run:**

di_vgp.py -f tmp.txt

**What happened:**

Traceback (most recent call last):
  File "/Users/ltauxe/PmagPy/programs/di_vgp.py", line 94, in <module>
    main()
  File "/Users/ltauxe/PmagPy/programs/di_vgp.py", line 87, in main
    output = pmag.dia_vgp(data)
  File "/Users/ltauxe/PmagPy/pmagpy/pmag.py", line 1175, in dia_vgp
    (decs, dips, a95s, slats, slongs) = list(zip(*largs))
TypeError: zip argument #1 must support iteration

And there are probably more programs with this problem.  

**What I expected to happen:**

that it would spit out the vgp

**Data file(s):**

[tmp.txt](https://github.com/PmagPy/PmagPy/files/3279385/tmp.txt)

**Screenshot(s):**

**PmagPy version:**

**Comment by moonshoes87** [comment]
The PmagPy-cli.ipynb example still seems to work:

    di_vgp.py -f data_files/di_vgp/di_vgp_example.dat

It looks like the problem is with having a single line of data in tmp.txt.  

I believe I fixed that, but I found another issue if you have multiple lines with 5 values each (a95s included).  

```
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/programs/di_vgp.py", line 97, in <module>
    main()
  File "/Users/nebula/Python/PmagPy/programs/di_vgp.py", line 81, in main
    output = pmag.dia_vgp(inlist)
UnboundLocalError: local variable 'inlist' referenced before assignment
```

Looks like you just need to set `inlist` in this code if `data.shape[1]==5`:

```
    if len(data.shape)>1: # 2-D array                                                                                    
            N=data.shape[0]
            if data.shape[1]==4:   # only dec,inc,sitelat, site long -no alpha95                                         
                data=data.transpose()
                inlist=numpy.array([data[0],data[1],numpy.zeros(N),data[2],data[3]]).transpose()
```

I am not sure how the 5 values should be ordered...

**Comment by ltauxe** [comment]
with the alpha95 after the dec inc and before the lat lon

**Comment by moonshoes87** [comment]
@ltauxe, this seems to work correctly.  Reopen this issue if you need to!
