### ISSUE TITLE
Bug for plot_poles and plot_poles_colorbar

### ISSUE THREAD

**Issue by hl04445567** [PmagPy/PmagPy#588]
When I tried to use plot_poles and plot_poles_colorbar recently, it keeps reporting that 

UnboundLocalError: local variable 'cy' referenced before assignment

**Comment by Swanson-Hysell** [comment]
Can you please provide example code where you get this error?

In this simple example, no such error arises:

```
import pmagpy.ipmag as ipmag
map_axis = ipmag.make_mollweide_map(central_longitude=200,figsize=(10,10))
ipmag.plot_pole(map_axis,218,-24,11,color='red')
```

<img width="646" alt="Screen Shot 2019-06-20 at 10 04 18 AM" src="https://user-images.githubusercontent.com/4332322/59867377-e88a1980-9342-11e9-8607-1883d7485a60.png">

**Comment by hl04445567** [comment]
At a closer look, it turns out that there are two entries of my pole list lack A95s, which caused the problem.

Sorry about this. Thanks for the prompt reply.

**Comment by Swanson-Hysell** [comment]
All good. Definitely feel free to report bugs as you run into them!
