### ISSUE TITLE
trouble in zeq_magic

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#593]
**What command was run:**
from the PmagPy_plot_analysis notebook:

dir_path='data_files/zeq_magic/'
ipmag.zeq_magic(input_dir_path=dir_path, save_plots=False)

**What happened:**

contribution_builder threw a KeyError:  'derived_value'  on line 10575 in ipmag.py

I think this is because there is only a measurements.txt file and no higher level files.  This should not happen as zeq_magic was intended as a quick and dirty look - you shouldn't need all the higher level files!  I tried to fix this but got lost in contribution_builder.  Help!

**Comment by moonshoes87** [comment]
I believe this is because of a change in the online data model.  @ltauxe, try running this command with the internet turned off (or with pmag_env/set_env.py OFFLINE = True).

**Comment by moonshoes87** [comment]
Setting `OFFLINE = True`, should be a temporary fix, I will push up a full fix later today or tomorrow.

**Comment by ltauxe** [comment]
All fixed!  Thanks Lori - you’re a hero!
