### ISSUE TITLE
subplots

### ISSUE THREAD

**Issue by craigmillernz** [PmagPy/PmagPy#596]
I'd like to be able to use matplotlib subplots to include multiple sub figures into one figure.  
For example ipmag.plot_net() requires a figure number which creates a new figure.  How can i imbed a plot_net plot (along with the subsequent plot_di(), as a subplot in a larger figure that contains other matplotlib objects.

**Comment by Swanson-Hysell** [comment]
This is a good request. 

You are right that it would be nice to embed stereo plots within subplots. Feel free to dig into the code and make modifications that could come in as a pull request. Alternatively, I can carve out some time to play around with it at some point — but it will be a while.

**Comment by craigmillernz** [comment]
I achieved a quick hack simply by commenting out the plt.figure and plt.clf at the start of the plot_net function. Then I can place it within my own figure or subplot.

**Comment by ltauxe** [comment]
that should work.  we can modify plot_net to ignore these commands and just plot an ax  object passed in  if desired.  
lisa

**Comment by Swanson-Hysell** [comment]
The only trick here is backward compatibility given places in the code where a figure number is passed to the function. I think that we can do this and it will work:

```
def plot_net(fignum=None):
    """
    Draws circle and tick marks for equal area projection.
    """

    if fignum != None:
        plt.figure(num=fignum,)
        plt.clf()
```
In this code, one can still use the previous code that passed fignums:

<img width="795" alt="Screen Shot 2019-11-04 at 11 45 09 AM" src="https://user-images.githubusercontent.com/4332322/68152493-9fed8a00-fef8-11e9-8249-7d001781278b.png">

But can also have it use the current axis and make subplots:

<img width="843" alt="Screen Shot 2019-11-04 at 11 44 56 AM" src="https://user-images.githubusercontent.com/4332322/68152506-aaa81f00-fef8-11e9-8e53-a6fa1397aaff.png">

**Comment by ltauxe** [comment]
yeah - this will work. thanks Nick.
lisa

**Comment by Swanson-Hysell** [comment]
The b3b56bce commit implements this change
