### ISSUE TITLE
ipmag.magic_write and ipmag.combine_magic delete the 'age' column from the sites table

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#597]
**What command was run:**
filenames=['jsites.txt','.hsites.txt']
outfile='.combined_sites.txt'
magic_table='sites'
ipmag.combine_magic(filenames,outfile=outfile,magic_table=magic_table)

**What happened:**

the resulting sites table had no 'age' column but the originals did!

**What I expected to happen:**

age is a perfectly acceptable column in the sites table. it should be removed. 

**Data file(s):**
[jsites.txt](https://github.com/PmagPy/PmagPy/files/4051398/jsites.txt)
[hsites.txt](https://github.com/PmagPy/PmagPy/files/4051399/hsites.txt)

**Screenshot(s):**

**PmagPy version:**
"pmagpy-4.2.31"

**Comment by moonshoes87** [comment]
I am back (ish), so I will work on this :)

**Comment by moonshoes87** [comment]
That doesn't happen when I run those commands -- the age column is still present as expected.  @ltauxe, any thoughts?

<img width="1143" alt="Screen Shot 2020-01-22 at 3 50 29 PM" src="https://user-images.githubusercontent.com/1836578/72944873-1e570c80-3d2f-11ea-909e-f7e86a251587.png">
