### ISSUE TITLE
can't install anaconda on OSX Catalina

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#599]

**Comment by moonshoes87** [comment]
There are two new problems created by Catalina.

1.
Catalina won't allow Anaconda to install into the root folder (which is Anaconda's old default).  The current solution, annoyingly, is to reinstall Anaconda *using the command line installer* .  The graphical installer doesn't (yet) work, but should be updated soon.  See more information from Anaconda [here](https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/).  Get the command line installer [here](https://repo.anaconda.com/archive/Anaconda3-2019.10-MacOSX-x86_64.sh).


2.  
Catalina switches to using zsh shell instead of bash by default.  I think this will only cause problems for brand new users who haven't used their Terminal before, but I'm not completely sure yet, since I haven't upgraded from an old account.  

However, the workaround is simple.  Just copy the anaconda installer code from .bash_profile to .zshrc.  See more detail in [this article](https://medium.com/@kuanhoong/setting-up-anaconda3-to-work-with-macos-catalina-zsh-shell-99898522ece1)

**Comment by moonshoes87** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/11334

**Comment by aisync** [comment]
> [ContinuumIO/anaconda-issues#11334](https://github.com/ContinuumIO/anaconda-issues/issues/11334)

^ Does command line installation resolve the referenced issue? (Not the issue w/ proper $PATH setup)

**Comment by moonshoes87** [comment]
I looked at your error on ContinuumIO/anaconda-issues#11334, and unfortunately I don't know.  I'll let you know if I figure it out.

**Comment by aisync** [comment]
Sorry, I thought that was maybe why you referenced the issue. My apologies. And thank you!
