### ISSUE TITLE
new_make_magic_plots.py fails on most current MagIC upload file

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#602]
The measurement file says software version: pmagpy-4.2.24-1 which is a bit behind our current version, so maybe that is the problem?

new_make_magic_plots.py 
-I- Using online data model
-I- Getting method codes from earthref.org
-I- Importing controlled vocabularies from https://earthref.org

working on:  Midway Atoll
-I- writing measurements records to /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16656/data/tmp_measurements.txt
-I- 2374 records written to measurements file
-I- writing specimens records to /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16656/data/tmp_specimens.txt
-I- 106 records written to specimens file
-I- writing samples records to /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16656/data/tmp_samples.txt
-I- 106 records written to samples file
-I- writing sites records to /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16656/data/tmp_sites.txt
-I- 106 records written to sites file
-I- writing locations records to /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16656/data/tmp_locations.txt
-I- 1 records written to locations file
using specimen coordinates
working on plotting measurements data
ipmag.zeq_magic(crd=s, n_plots='all', contribution=<pmagpy.contribution_builder.Contribution object at 0x10e5f9828>, image_records=True)
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/new_make_magic_plots.py", line 517, in <module>
    main()
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/new_make_magic_plots.py", line 262, in main
    contribution=con, image_records=True)
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/ipmag.py", line 10701, in zeq_magic
    ZED, interpretations = make_plots(s, cnt, meas_df, spec_container, samp_container)
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/ipmag.py", line 10616, in make_plots
    return plot_interpretations(ZED, spec_container, s, this_spec_meas_df, datablock, coord)
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/ipmag.py", line 10455, in plot_interpretations
    prior_specimen_interpretations.meas_step_min.values).tolist()
  File "/Users/njarboe/anaconda3/envs/pmagpy/lib/python3.6/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'meas_step_min'

[magic_contribution_16656.txt](https://github.com/PmagPy/PmagPy/files/4161060/magic_contribution_16656.txt)

**PmagPy version:**
Current development version

**Comment by moonshoes87** [comment]
Thanks, I will work on that asap.

**Comment by moonshoes87** [comment]
It looks like this is happening because the specimens file uses the LP-DIR-T method code but doesn't actually have any directional data.  I can put in a workaround for this, but perhaps something is wrong with this specimen file?

**Comment by moonshoes87** [comment]
If this specimen file was generated by PmagPy, maybe there is something additional that we need to fix.

**Comment by njarboe** [comment]
The measurement table has "pmagpy-4.2.24-1" as the software used, so I would think the specimens table was also from pmagpy. I have asked the contributor to find out for sure.

**Comment by njarboe** [comment]
@moonshoes87 Working is working. Will reopen if Bono get back to me and the specimens file was created by PmagPy.
