### ISSUE TITLE
Should we remove PmagPy.ipynb from the repo?

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#604]
@ltauxe @moonshoes87 @Swanson-Hysell 
Now that Nick S-H has broken up the large notebook into four parts, should we remove the large one. I don't think we need it and keeping it in sync with the other files is just extra work. What do you think?

**Comment by Swanson-Hysell** [comment]
I think removing it makes sense for the reasons that you state.

**Comment by moonshoes87** [comment]
Yes, sounds good to me.

**Comment by njarboe** [comment]
OK. Removed.
