### ISSUE TITLE
ipmag.upload_magic()

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#607]
**What command was run:**

ipmag.upload_magic(concat=True)

**What happened:**

my file passed validation, but then failed after upload to my private workspace and attempt to validate - the first time with missing columns in the site table (blank ages and no result_type, result_quality columns).  then the second time with missing result_type, result_quality and blank method_codes

**What I expected to happen:**

to pass with flying colors

**Data file(s):**

[Tel-Hazor_Tel-Megiddo_19.Feb.2020_4.txt](https://github.com/PmagPy/PmagPy/files/4228767/Tel-Hazor_Tel-Megiddo_19.Feb.2020_4.txt)

**Screenshot(s):**

**PmagPy version:**
pmagpy-4.2.34

**Comment by moonshoes87** [comment]
Lisa, when I just download and then upload this example, it doesn't give any validation errors in PmagPy, nor any errors during  Step 2. Import on MagIC.  

However, when I got to Step 3. Upload, it just spins:

<img width="1215" alt="Screen Shot 2020-02-20 at 11 33 26 AM" src="https://user-images.githubusercontent.com/1836578/74971384-dcc08c80-53d4-11ea-986c-b1dc34cf7df7.png">

@rminnett, maybe you are working on something on the server?

and @ltauxe, if you got validation warnings in PmagPy or the MagIC upload, what other steps did you take between download and upload?

**Comment by moonshoes87** [comment]
@rminnett, this is happening on Safari.

**Comment by rminnett** [comment]
Is it still stuck uploading?

**Comment by moonshoes87** [comment]
Yes, but the upload succeeded on Chrome.

**Comment by rminnett** [comment]
That's interesting - I'll see if I can reproduce the different behavior on
Safari.

**Comment by moonshoes87** [comment]
@ltauxe -- I found the validation errors.  I'll see what I can do.

**Comment by moonshoes87** [comment]
@rminnett, the issue on Safari persists.  

Also, perhaps you can lend some insight into the other validation errors I am seeing.  

<img width="881" alt="Screen Shot 2020-02-24 at 2 53 35 PM" src="https://user-images.githubusercontent.com/1836578/75198448-79f12d00-5715-11ea-9478-3ad5162084dd.png">

result_quality is not missing from the samples table overall.  Does this mean that a value for result_quality is required in each row of the samples table?  That doesn't feel completely clear to me from the description:  `Governed: this column must not be empty unless the contribution includes rows in the sites table.` + `Controlled: this column must contain a value found in the Data Qualities controlled vocabulary.` This contribution does have a sites table...

And @ltauxe, I'm wondering about this pattern in the samples table in which every other row has result_quality/result_type filled in:

<img width="220" alt="Screen Shot 2020-02-24 at 3 18 44 PM" src="https://user-images.githubusercontent.com/1836578/75199834-ffc2a780-5718-11ea-9b1c-47e1e0916ca9.png">
<img width="459" alt="Screen Shot 2020-02-24 at 3 24 49 PM" src="https://user-images.githubusercontent.com/1836578/75200168-d8b8a580-5719-11ea-8acc-71000dcc2e6f.png">

Seems like result_quality and result_type should be filled in for all rows, but instead rows described as "paleointensity mean" have result_quality and rows described as "Paleointensity;V[A]DM;hz05a, Paleointensity; V[A]DM" have result_type.  Looks like these rows are generated by Thellier GUI in `on_menu_prepare_magic_results_tables`.  We might want to add the missing values around lines 4126 and 4313.

**Comment by moonshoes87** [comment]
@ltauxe, do you want me to add result_type i and result_quality good?

**Comment by rminnett** [comment]
@moonshoes87 I updated the data model to replace the required() with suggested() for results_quality and results_type fields. I'm updating the validation interface to report suggested empty fields as warnings and I'll clarify some of the messages in the data model browser and validation report.
