### ISSUE TITLE
pmag_gui quits unexpectedly

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#610]
**What command was run:**

pmag_gui_4.2.39.2.app

**What happened:**

After step 3 (adding meta-data to various MagIC tables), pmag_gui the pmag_gui front panel just never came back. The program appeared to still be running and all the files were saved, but the application had to be re-started to continue.    This also happens with the pip and git versions. 

**What I expected to happen:**

to return to the GUI interface

**Data file(s):**

**Screenshot(s):**

**PmagPy version:**
4.2.39

**Comment by moonshoes87** [comment]
I will look — is there any error message output?  Also, could you send me the specific data file in case that is relevant?

**Comment by moonshoes87** [comment]
@ltauxe, I reproduced the problem.  I will try to fix this, but in the meantime, you can always use the menubar to force the main frame to show:  File --> Show main window:

<img width="480" alt="Screen Shot 2020-03-09 at 5 31 17 PM" src="https://user-images.githubusercontent.com/1836578/76268679-0d555280-622c-11ea-8b59-860ea3cab6d3.png">
