### ISSUE TITLE
make_magic_plots not cropping thumbnails

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#611]
Lisa's Feb 23 contribution worked, but Julie's most recent did not. I also tried it on this smaller contribution that is correct on the website, but now does not get cropped. I get this kind of output:
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-30.2_demag.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-14.2_eqarea.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-7.2_eqarea.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-36.2_zijd.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-10.2_zijd.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-27.1_demag.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-17.2_demag.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-27.1_eqarea.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-30.2_eqarea.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/CMR-12.e_demag.png
Could not crop /Users/njarboe/Dropbox/MagIC/testing/make_magic_plots/16686/data/Cape_Marsh,_Robertson_Island_CMR_CMR-36_CMR-36.2_g_eqarea.png

[magic_contribution_16686.txt](https://github.com/PmagPy/PmagPy/files/4327178/magic_contribution_16686.txt)

**Comment by moonshoes87** [comment]
It looks like make_magic_plots.py was actually reverted to its old version around a month ago (accidentally, in e561c9fbbcdbb8190073da552cbf314e0413da62).  So, I've fixed that.

Additionally, it appears that isServer was not set to True in the server environment, so that probably needs to be done as well.  

@njarboe, let me know if any issues persist.  It works locally when I un-revert the reversion and set isServer.

**Comment by njarboe** [comment]
download_magic.py was crashing when running on the server due to the large >300k number of measurements in Julie's contribution. So I tried running it locally as a quick fix, but forgot to set the isServer flag to make the plots for the website. I bumped up the plot server to a t2.small so now it can handle unpacking Julies magic file.

**Comment by njarboe** [comment]
Pulled the current version and the thumbnails are still being made when isServer is not set. Is make_magic_plots.py only for the server or should people be able to use it on their own machines.
