### ISSUE TITLE
core_depthplot.py needs to be updated to MagIC data model 3.0 and integrated into make_magic_plots.py

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#612]
It would be nice to have core plots working in PmagPy, especially now that Branden Reilly is adding data files from cores. When data from cores are uploaded and don't have any other type of plots, they leave the contribution page with an empty place.

**Comment by ltauxe** [comment]
core_depthplot is already MagIC 3 and is in ipmag.core_depthplot.  I'll see about adding it to make_magic_plots

**Comment by ltauxe** [comment]
I added a function df_depthplot to ipmag.  This plots data from MagIC tables that have depth information imported from the sites table.  I added a call to this in make_magic_plots.   This works pretty well, but make_magic_plots tries to make an equal area projection for every single measurement in the measurements table - a little annoying.
