### ISSUE TITLE
upload_magic.py states there is an error with image.txt file when online validation does not.

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#615]
upload_magic.py states there is an error with image.txt file when online validation does not. The image file looks like it should pass validation to me.

These files:
[tmp.zip](https://github.com/PmagPy/PmagPy/files/4472479/tmp.zip)

give the following output when upload_magic.py is run:
(base) kamacite:tmp njarboe$ upload_magic.py
Using default arguments for: -f, -F, -A, -WD, -ID, -Fsa, -Fsi, -cat
-I- Removing old error files from /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp: locations_errors.txt, samples_errors.txt, specimens_errors.txt, sites_errors.txt, ages_errors.txt, measurements_errors.txt, criteria_errors.txt, contribution_errors.txt, images_errors.txt
-I- Using online data model
-I- Getting method codes from earthref.org
-I- Importing controlled vocabularies from https://earthref.org
-W- Column 'core_depth' isn't in samples table, skipping it
-W- Column 'composite_depth' isn't in samples table, skipping it
-W- Invalid or missing column names, could not propagate columns
-I- images file successfully read in
-I- Validating images
-I- You are missing some required headers
-I- You need at least one header from these groups: Names
-I- appending images data to /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- 9 records written to images file
-I- images written to  /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- locations file successfully read in
-I- Validating locations
-I- No row errors found!
-I- appending locations data to /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- 1 records written to locations file
-I- locations written to  /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- measurements file successfully read in
-I- Validating measurements
-I- No row errors found!
-I- appending measurements data to /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- 88 records written to measurements file
-I- measurements written to  /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- samples file successfully read in
-I- Validating samples
-I- No row errors found!
-I- appending samples data to /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- 2 records written to samples file
-I- samples written to  /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- sites file successfully read in
-I- Validating sites
-I- No row errors found!
-I- appending sites data to /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- 2 records written to sites file
-I- sites written to  /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- specimens file successfully read in
-I- Validating specimens
-I- No row errors found!
-I- appending specimens data to /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
-I- 5 records written to specimens file
-I- specimens written to  /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/upload.txt
Finished preparing upload file: /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/Jack-Hills_13.Apr.2020.txt 
-W- These tables have errors: images
-W- validation of upload file has failed.
You can still upload /Users/njarboe/Dropbox/MagIC/people/Shah/testWeiss/Weiss2018Set2/tmp/Jack-Hills_13.Apr.2020.txt to MagIC,
but you will need to fix the above errors before your contribution can be activated.

**Comment by moonshoes87** [comment]
@njarboe, this should be working correctly now -- I'm closing this issue, please reopen if I missed something.
