### ISSUE TITLE
doigrf function in pmag_gui seems not working with 2020 dates 

### ISSUE THREAD

**Issue by ronshaar** [PmagPy/PmagPy#617]
**What command was run:**

Using the Pmag GUI, I edited a new "demag_orient.txt" file with the date "01/28/20). 
Then, using the standard routine we clicked the "Calculate Sample Orientations" button

**What happened:**

  File "/Users/ronshaar/PmagPy/dialogs/pmag_gui_dialogs.py", line 3019, in on_m_calc_orient
    output_dir_path=self.WD, append=append, data_model=3)
  File "/Users/ronshaar/PmagPy/pmagpy/ipmag.py", line 5937, in orientation_magic
    x, y, z, f = pmag.doigrf(lon, lat, 0, decimal_year)
TypeError: cannot unpack non-iterable NoneType object

BUT - if I change the date prior to 2020, for example 01/28/19, there is no error. 
**What I expected to happen:**

**Data file(s):**

[demag_orient.txt](https://github.com/PmagPy/PmagPy/files/4533457/demag_orient.txt)
[locations.txt](https://github.com/PmagPy/PmagPy/files/4533458/locations.txt)
[measurements.txt](https://github.com/PmagPy/PmagPy/files/4533459/measurements.txt)
[samples.txt](https://github.com/PmagPy/PmagPy/files/4533460/samples.txt)
[sites.txt](https://github.com/PmagPy/PmagPy/files/4533461/sites.txt)
[specimens.txt](https://github.com/PmagPy/PmagPy/files/4533462/specimens.txt)

**Screenshot(s):**

**PmagPy version:**
latest  version. problem occur both in OSX and windows.

**Comment by moonshoes87** [comment]
It looks like only dates prior to 2020 are supported.  Lisa added a warning about this in this commit: https://github.com/PmagPy/PmagPy/commit/b99cf3ce221b7ea2c5034005dd97a80c50408b4a

@ltauxe, are you expecting to add support for 2020 and later?  

In the meantime, we should make it fail a bit more gracefully.  I will work on that aspect this weekend.

**Comment by ltauxe** [comment]
yeah.  when i get a minute. until only dates to 2019.999 supported
lisa

**Comment by ltauxe** [comment]
had a minute. all fixed.  appears reliable up to 2020 at least.
