### ISSUE TITLE
How to draw ellipse for each site-mean direction using eqarea_ell.py

### ISSUE THREAD

**Issue by wilfred9110** [PmagPy/PmagPy#619]
**What command was run:**

eqarea_ell, fisher_mean, a95

**What happened:**

I cannot draw confidence ellipse for each site-mean direction in Pmagpy 4.2.46. but it can be done in the version of  3.2.11

**What I expected to happen:**
I expect to see the site-mean data in "SXB_Ds_Is.txt" be plotted with a95 shown for each site-mean direction. Also, I want to flip the reversed direction to the antipode and calculate the fisher mean direction of this dataset, then plot the mean direction with a95 (normal value).  I expect all the above shown in a common *.svg figure

**Data file(s):**

[SXB_Ds_Is.txt](https://github.com/PmagPy/PmagPy/files/4790088/SXB_Ds_Is.txt)

**Screenshot(s):**
![image](https://user-images.githubusercontent.com/48851042/84849278-87953e80-b087-11ea-90cc-40efe38e1ff8.png)

![image](https://user-images.githubusercontent.com/48851042/84849330-9f6cc280-b087-11ea-8eb9-e5438d53cb82.png)

**PmagPy version:**
4.2.46

**Comment by ltauxe** [comment]
You can do it this way:  
vectors=np.loadtxt('SXB_Ds_Is.txt')
plt.figure(1,figsize=(10,10))
ipmag.plot_net(1)
for k in range(len(vectors)):
    print (vectors[k])
    ipmag.plot_di_mean(vectors[k][0],vectors[k][1],vectors[k][2])
![fig_for_Donghai](https://user-images.githubusercontent.com/174861/84920151-a55aa780-b077-11ea-93a9-2401fe379917.png)

I guess I should re-instate eqarea_ell  through ipmag so this is easier, but this way works fine for now.
