### ISSUE TITLE
site table not generated (AttributeError: ‘DataFrame’ object has no attribute ‘reindex_axis’) 

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#625]
**What command was run:**

demag_gui.py on_menu_make_MagIC_results_tables

**What happened:**

Traceback (most recent call last):
  File “programs/demag_gui.py”, line 6929, in on_menu_make_MagIC_results_tables
  File “programs/demag_gui.py”, line 5799, in On_close_MagIC_dialog
  File “pandas/core/generic.py”, line 5130, in __getattr__
AttributeError: ‘DataFrame’ object has no attribute ‘reindex_axis’

I think the issue is related to https://github.com/dashaub/espandas/issues/2 such that it may be fixed by replacing df.reindex_axis(.......) with df.reindex(......)

**What I expected to happen:**

A site file to be generated

**PmagPy version:**

pmag_gui_4.2.50 

I need to check whether this is also happening within demag_gui.py in the PmagPy master

**Comment by ltauxe** [comment]
fixed this using df.reindex  instead of df.reindex_attribute.    It seems to work now.
