### ISSUE TITLE
pmag_gui cannot be invoked

### ISSUE THREAD

**Issue by wilfred9110** [PmagPy/PmagPy#626]
**What command was run:**
pmag_gui

**What happened:**

Nothing changed.
I have used the following commands to reinstall the Pmagpy, and other functions like sundec work well.

 pip uninstall pmagpy pmagpy-cli  
  pip install pmagpy --upgrade --no-deps --force-reinstall --no-cache-dir  
  pip install pmagpy-cli --upgrade --no-deps --force-reinstall --no-cache-dir

**What I expected to happen:**

invoke pmag_gui by inputting this command in the anaconda prompt window.

**Data file(s):**

**Screenshot(s):**
![image](https://user-images.githubusercontent.com/48851042/100916792-34b62300-3511-11eb-9c1e-413006c2e9d6.png)

**PmagPy version:**
4.2.55

the latest version of pmagpy is 4.2.56 and pmagpy-cli is 4.2.55. I forced to install the version of pmagpy to 4.2.55 to avoid bugs caused by this difference.

**Comment by wilfred9110** [comment]
![screenshot](https://user-images.githubusercontent.com/48851042/100917150-bc039680-3511-11eb-8821-f8f915bce346.png)

it seems the screenshot above was crashed.

**Comment by Swanson-Hysell** [comment]
Do you get an error message? In a terminal one would expect to see something like:
'''
command not found
'''
or 
'''
ModuleNotFoundError: No module named 'wx'
'''

Have you tried using the standalone executable programs? Given that those are compiled they are faster and can provide a work around that allows you to use pmag_gui
https://github.com/PmagPy/PmagPy-Standalone-Windows
https://github.com/PmagPy/PmagPy-Standalone-OSX

**Comment by wilfred9110** [comment]
No error message is shown.  I will try the standalone one.  thanks.

**Comment by Swanson-Hysell** [comment]
Did the standalone work for you @wilfred9110?
