### ISSUE TITLE
Trouble using pmag_gui_anaconda

### ISSUE THREAD

**Issue by sarah-potatoes** [PmagPy/PmagPy#627]
**What command was run:**
pmag_gui_anaconda 
Then I selected the directory with a MagIC text file, unpacked the MagIC file, and attempted to run Demag GUI

**What happened:**
On two different magic files (magic_contribution_17051.txt which is attached along with the unpacked txt files, and magic_contribution_17059.txt) I was able to unpack the text file, but after selecting the Demag GUI I would get a screen saying "Compiling data, please wait..." that would stay for hours until I killed the script.

In the terminal I would get similar outputs: 
 pmag_gui_anaconda 
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
-I- Read in any available data from working directory
-I- Using online data model
-I- Getting method codes from earthref.org
-I- Importing controlled vocabularies from https://earthref.org
-I- Read in any available data from working directory
-I- running python script:
 demag_gui.py -WD /Users/sarah/Research/UCSD/Easter/paper2/magic/test
data model: 3.0
-I- Using magn_moment for intensity
-I- done sorting meas data
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/programs/pmag_gui.py", line 441, in on_btn_demag_gui
    demag_gui_frame = demag_gui.Demag_GUI(self.WD, self,
  File "/opt/anaconda3/lib/python3.8/site-packages/programs/demag_gui.py", line 304, in __init__
    self.init_UI()  # build the main frame
  File "/opt/anaconda3/lib/python3.8/site-packages/programs/demag_gui.py", line 709, in init_UI
    bounds_sizer.AddMany([(self.tmin_box, 1, wx.ALIGN_TOP | wx.EXPAND | wx.BOTTOM, top_bar_2v_space),
  File "/opt/anaconda3/lib/python3.8/site-packages/wx/core.py", line 1858, in _Sizer_AddMany
    self.Add(*item)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_BOTTOM)" failed at /Users/robind/projects/bb2/dist-osx-py38/build/ext/wxWidgets/src/common/sizer.cpp(2066) in DoInsert(): Vertical alignment flags are ignored in vertical sizers

**What I expected to happen:**
I expected the demag gui to open after a few minutes

**Data file(s):**
[contribution.txt](https://github.com/PmagPy/PmagPy/files/5766835/contribution.txt)
[locations.txt](https://github.com/PmagPy/PmagPy/files/5766836/locations.txt)
[magic_contribution_17051.txt](https://github.com/PmagPy/PmagPy/files/5766837/magic_contribution_17051.txt)
[measurements.txt](https://github.com/PmagPy/PmagPy/files/5766838/measurements.txt)

**Screenshot(s):**

**PmagPy version:**
 4.2.62

**Comment by ltauxe** [comment]
I could not reproduce this problem - everything worked as expected.  I'm using Pmag_gui.py version 4.2.62.  
First, update your version to the most recent one.  Then try it again.
