### ISSUE TITLE
wx.ALIGN commands not compatible with new wxPython and need to be removed from GUIs

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#628]
The newest version of wxPython (https://pypi.org/project/wxPython/4.1.1/) does not support the wx.ALIGN commands. I went through and removed all of these from demag_GUI and the interpretation editor dialogue with this commit: https://github.com/PmagPy/PmagPy/commit/f47e7cf8c956a84dfc40aada9a61e803640213ae. All seems to work just fine with them removed.

They need to be removed from Thellier GUI as well as the wx.ALIGN results in fatal assertion errors.

**Comment by ltauxe** [comment]
I did the same for thellier_gui.  so this should be resolved.
