### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by maxingduo** [PmagPy/PmagPy#630]
**What command was run:
**# initiate figure and specify figure size
plt.figure(figsize=(5, 5))

# initiate a Basemap projection, specifying the latitude and
# longitude (lat_0 and lon_0) at which our figure is centered.
pmap = Basemap(projection='ortho',lat_0=30,lon_0=320,
               resolution='c',area_thresh=50000)

# other optional modifications to the globe figure
pmap.drawcoastlines(linewidth=0.25)
pmap.fillcontinents(color='bisque',lake_color='white',zorder=1)
pmap.drawmapboundary(fill_color='white')
pmap.drawmeridians(np.arange(0,360,30))
pmap.drawparallels(np.arange(-90,90,30))

# Here we plot a pole at 340 E longitude, 30 N latitude with an
# alpha 95 error angle of 5 degrees. Keyword arguments allow us
# to specify the label, shape, and color of this data.
ipmag.plot_pole(pmap,340,30,5,label='VGP examples',
               marker='s',color='Blue')

# We can plot multiple poles sequentially on the same globe using
# the same plot_pole function.
ipmag.plot_pole(pmap,290,-3,9,marker='s',color='Blue')

plt.legend()
# Optional save (uncomment to save the figure)
#plt.savefig('Code_output/VGP_example.pdf')
plt.show()

**What happened:**
ValueError: Axes should be an instance of GeoAxes, got <class 'matplotlib.axes._subplots.AxesSubplot'>

**What I expected to happen:**

**Data file(s):**

**Screenshot(s):**

**PmagPy version:**

**Comment by maxingduo** [comment]
the basemp no more working?

**Comment by Swanson-Hysell** [comment]
While we have sought to maintain Basemap support for PmagPy, basemap has now been deprecated in favor of Cartopy and has now reached its "end of life" (https://matplotlib.org/basemap/). I therefore recommend using cartopy (https://scitools.org.uk/cartopy/docs/latest/) which has been implemented across the PmagPy functions. Cartopy can be readily installed using the conda package manager or other python installers.

**Comment by maxingduo** [comment]
@Swanson-Hysell thanks!!I am a layman in python,I am wonderding if you help me with the program I've sent here.how to deal with it by Cartopy.

**Comment by Swanson-Hysell** [comment]
This code should work:

```
plon = 340
plat = 30
A95 = 5
map_axis = ipmag.make_orthographic_map(central_longitude=340,central_latitude=30)
ipmag.plot_pole(map_axis, plon, plat, A95, marker='s',color='blue',markersize=40)
```

<img width="990" alt="Screen Shot 2021-04-21 at 7 22 14 PM" src="https://user-images.githubusercontent.com/4332322/115646377-e397a780-a2d6-11eb-9325-2747c301aec3.png">

**Comment by maxingduo** [comment]
@Swanson-Hysell thank you very very much !
