### ISSUE TITLE
re-implementing nice validations in Pmag GUI

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#638]
**Is your feature request related to a problem? Please describe.**
validation with upload_magic

**Describe the solution you'd like**
we should implement ipmag.validate_with_public_endpoint() within upload_magic and make sure it works within pmag_gui.   

**Additional context**
Also there is a lot of error fixing instead of error checking that can be done.  e.g., insuring that all the specimens in the measurements table are in the specimens table - all samples in the specimens table are in the samples table and all sites in the samples table are in the sites table.  Given the specimen=>sample=>site convention, this should get the user pretty far.  one could query once errors are detected to clarify these conventions.

**Comment by moonshoes87** [comment]
Still need to do:

- resize bug
- highlighting on the outer buttons

**Comment by moonshoes87** [comment]
@ltauxe, I think I've got this back to working (as well as fixed some ugly bugs that maybe were there before, or maybe were created by updates to wxPython).  I'd still like to test it on a few more contributions, but it would be great if you could take a quick look at it too.
