### ISSUE TITLE
Problem with pmag.dokent() and aniso_magic.py ellipse parameters

### ISSUE THREAD

**Issue by allochthonous** [PmagPy/PmagPy#64]
When running aniso_magic.py with a bootstrap I was getting weird error ellipses that were rotated 90º from the data distribution they were meant to be representing. 

Datafile:
[WT1_anisotropy.txt](https://github.com/PmagPy/PmagPy/files/287506/WT1_anisotropy.txt)
Command:
`aniso_magic.py -f WT1_anisotropy.txt -par -crd g`
Result:
![aniso_test_data](https://cloud.githubusercontent.com/assets/9516117/15624020/6d7d31c8-244b-11e6-965a-c9dd6f6a6de1.png)
![aniso_test1](https://cloud.githubusercontent.com/assets/9516117/15624022/78e760f6-244b-11e6-8c60-eb134f7a2a9d.png)
I eventually worked out that somehow the zeta angle was being given the eta angles D,I parameters and vice-versa, which I traced back to pmag.dokent():
<img width="609" alt="dokent_code_highlighted" src="https://cloud.githubusercontent.com/assets/9516117/15624082/91eb591c-244c-11e6-9353-87ba371c731a.png">
In the first two chunks of highlighted code below there appears to be a mismatch with the third chunk: sigma1at [i][1] in an array is associated with eta and sigma2 at [i][0] with zeta, yet at 3221-3222 the zeta directions are calculated from [i][1] and eta from [i][0]. If you instead have:
`3305       sigma1=sigma1+xg[i][0]**2`
`3306       sigma2=sigma2+xg[i][1]**2`
Then you get the right result.
![aniso_test2](https://cloud.githubusercontent.com/assets/9516117/15624101/2ecc6a46-244d-11e6-9a0e-82267a856753.png)
Also: in aniso_magic.py lines 322-325, which print the bootstrap output, the zeta parameters are printed in the eta columns and vice versa.

**Comment by ltauxe** [comment]
ahh thanks for catching that!  there was an inconsistency in what was zeta and what was eta in the code (between the bootstrap for directions and for eigenvectors)  and i thought I had fixed it, but obviously messed it up.  
(i always use the -v option, so i didn’t notice it).    I will fix this shortly…..   
lisa

**Comment by ltauxe** [comment]
I think i fixed this now….  
lisa

**Comment by Swanson-Hysell** [comment]
Hey Chris,

Is everything working as it should now? If so, we will go ahead and close the issue.
