### ISSUE TITLE
when I use pmag_gui to flag a bad measurment, it will report this problem

### ISSUE THREAD

**Issue by zhaotengge** [PmagPy/PmagPy#643]
"your measurement table has non-unique measurement names. you may end up marking more than one measurement as good."

and I cant save my interpretation in magic tables

**Comment by Swanson-Hysell** [comment]
Hi @zhaotengge. Did you close the issue, because you figured out how to save your MagIC tables?

**Comment by zhaotengge** [comment]
Thank you for your letter. I solved this problem with version 3.16 of "pmag_gui".
At present, there is still a problem in data conversion。When I convert files in cit format, the image processing program（Demag Gui） of "pmag_gui" will report an error (the picture and files are in the attachment). Is there any way to deal with this situation? I'm a novice. My English is not very good. Please forgive me.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PmagPy/PmagPy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月5日(星期六) 凌晨2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PmagPy/PmagPy] when I use pmag_gui to flag a bad measurment, it will report this problem (Issue #643)





 
Hi @zhaotengge. Did you close the issue, because you figured out how to save your MagIC tables?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Swanson-Hysell** [comment]
Can you post the image on Github? I am not able to see the attachment sent via email.

**Comment by zhaotengge** [comment]
Thank you for your reply！I have submitted the question to GitHub.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PmagPy/PmagPy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 凌晨1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PmagPy/PmagPy] when I use pmag_gui to flag a bad measurment, it will report this problem (Issue #643)





 
Can you post the image on Github? I am not able to see the attachment sent via email.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
