### ISSUE TITLE
File conversion in cit format

### ISSUE THREAD

**Issue by zhaotengge** [PmagPy/PmagPy#644]
When I convert files in cit format, the image processing program（Demag Gui） of "pmag_gui" will report an error (the picture and files are in the attachment). Is there any way to deal with this situation?

we used 2G superconducting instrument。

Thank you for your help!

![error](https://user-images.githubusercontent.com/72237100/157146036-ace825a6-c2e8-4dae-9fe0-91a8fd4c1773.JPG)

[contribution.txt](https://github.com/PmagPy/PmagPy/files/8201874/contribution.txt)
[locations.txt](https://github.com/PmagPy/PmagPy/files/8201875/locations.txt)
[measurements.txt](https://github.com/PmagPy/PmagPy/files/8201876/measurements.txt)
[samples.txt](https://github.com/PmagPy/PmagPy/files/8201877/samples.txt)
[sites.txt](https://github.com/PmagPy/PmagPy/files/8201878/sites.txt)
[specimens.txt](https://github.com/PmagPy/PmagPy/files/8201879/specimens.txt)

**PmagPy version:**
4.72

**Comment by Swanson-Hysell** [comment]
The problem looks to be with the conversion to MagIC format. 

When I look at your measurements.txt table, I see that there are no values in the magn_moment column. There need to be such magnetic moment values in order for the software to work. Without those values, no analysis or plots are possible. 

If you can attach example data in the CIT format, I can see if I can get the conversion to work.

**Comment by zhaotengge** [comment]
Thank you for your help. This is my CIT file
[rapid.zip](https://github.com/PmagPy/PmagPy/files/8202603/rapid.zip)

**Comment by zhaotengge** [comment]
I have uploaded the cit file to GitHub. Thank you for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PmagPy/PmagPy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 中午11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PmagPy/PmagPy] File conversion in cit format (Issue #644)





 
The problem looks to be with the conversion to MagIC format.
 
When I look at your measurements.txt table, I see that there are no values in the magn_moment column. There need to be such magnetic moment values in order for the software to work. Without those values, no analysis or plots are possible.
 
If you can attach example data in the CIT format, I can see if I can get the conversion to work.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
