### ISSUE TITLE
lnp_magic not working with 3.0 data format

### ISSUE THREAD

**Issue by sslotznick** [PmagPy/PmagPy#647]
I was unable to get pmag.do_lnp() to work on a set of data in the 3.0 format.  I added a column for 'specimen_direction_type' but the issues seemed to relate to the "tilt_correction."   I've attached the dataset I was working with.

I also got an error when doing plot_lnp that pmagpy.pmagplotlib had no such attribute.

[LNP_issue.xls](https://github.com/PmagPy/PmagPy/files/8311415/LNP_issue.xls)
?

**Comment by ltauxe** [comment]
ok… I’ll look into it.

**Comment by ltauxe** [comment]
I fixed the issue and made a new pip release too.  But this will only work with the .txt file version - not excel, so use this one:
[specimens.txt](https://github.com/PmagPy/PmagPy/files/8327498/specimens.txt)
