### ISSUE TITLE
Inversed color using in stereonet and CDF of ipmag.reversal_test_bootstrap

### ISSUE THREAD

**Issue by Lu-Hongliang** [PmagPy/PmagPy#661]
**What command was run:**
ipmag.reversal_test_bootstrap(dec=decs,inc=incs,plot_stereo=True)

**What happened:**
In the stereonet the blue points are the normal paleomagnetic directions, while the red points are the reversed paleomagnetic directions. However, in the CDF, the red line represents the normal paleomagnetic directions, and the blue line represents the reversed paleomagnetic directions.

**What I expected to happen:**
The color used to show the normal or reversed directions should be the same in stereonet and CDFs, because when we use ipmag.reversal_test_bootstrap to generate these two figures, we have no chance to select the color we use.

**Data file(s):**

[Decs.txt](https://github.com/PmagPy/PmagPy/files/9724763/Decs.txt)

[Incs.txt](https://github.com/PmagPy/PmagPy/files/9724766/Incs.txt)

**Screenshot(s):**
![image](https://user-images.githubusercontent.com/115157308/194311990-7ab7c5f5-c9f3-422c-963d-c22b672e4394.png)

**PmagPy version:**
4.2.107

**Comment by Swanson-Hysell** [comment]
Let use know if that fix works for you!

**Comment by Lu-Hongliang** [comment]
> Let use know if that fix works for you!

Many thanks for your contribution! 

However, after downloading the latest version of pmagpy-master with the #666 fix, the CDFs of ipmag.reversal_test_bootstrap goes wrong as the picture below shows. I think your code just adds the option to choose the color, which seems will not lead to this bug, and everything seems great in your tests. So it's quite confusing to me. Can you do more tests or check on ipmag.common_mean_bootstrap()?

Many thanks for your help again!

![屏幕截图 2022-10-21 204217](https://user-images.githubusercontent.com/115157308/197198263-5d77ae81-3cf7-4643-ad2b-7de7b12316af.png)

**Comment by Lu-Hongliang** [comment]
I think this bug may not be caused by #666 fix itself, because before this fix, in the v4.2.108 pmagpy, this bug also occurs. 
![屏幕截图 2022-10-21 212533](https://user-images.githubusercontent.com/115157308/197206596-b4569b84-9100-45c7-9d3c-54a4c83a3ed5.png)


> > Let use know if that fix works for you!
> 
> Many thanks for your contribution!
> 
> However, after downloading the latest version of pmagpy-master with the #666 fix, the CDFs of ipmag.reversal_test_bootstrap goes wrong as the picture below shows. I think your code just adds the option to choose the color, which seems will not lead to this bug, and everything seems great in your tests. So it's quite confusing to me. Can you do more tests or check on ipmag.common_mean_bootstrap()?
> 
> Many thanks for your help again!
> 
> ![屏幕截图 2022-10-21 204217](https://user-images.githubusercontent.com/115157308/197198263-5d77ae81-3cf7-4643-ad2b-7de7b12316af.png)

**Comment by Swanson-Hysell** [comment]
That is an odd bug — I can look into it. As you say, it looks like a distinct issue from the color fix I made. 

Does the example using the data you provided :

`
decs = np.loadtxt('decs.txt')
incs = np.loadtxt('incs.txt')
data_di_block = ipmag.make_di_block(decs,incs)
ipmag.reversal_test_bootstrap(di_block=data_di_block,
                              plot_stereo=True)
`

work for you as it did for me?

**Comment by Lu-Hongliang** [comment]
![image](https://user-images.githubusercontent.com/115157308/197224532-ff7910cc-51cc-4811-bfa2-3aacebada549.png)
Using the data I provided also shows up with this bug.

**Comment by Swanson-Hysell** [comment]
This looks to be an issue associated with the b7f38207 commit. @ltauxe are you able to have a look at this? It looks like the b7f38207 commit you made that modified pmagplotlib.plot_cdf() had some deleterious effects.

**Comment by duserzym** [comment]
@ltauxe Hi Lisa, it seems in commit https://github.com/PmagPy/PmagPy/commit/b7f3820782fe956e0c9dae2199e9f22da79c9c6e the addition of line `plt.clf()` clears the figure after it is created; and commenting out line `sdata.sort()` results in basically a random walk figure for the cumulative distribution plots. These changes  result in the corruption of `ipmag.common_mean_boostrap` and `ipmag.reversal_test_boostrap` outputs as are shown in Hongliang's example. Could we revert this commit?

**Comment by ltauxe** [comment]
Sure - was it me?

**Comment by duserzym** [comment]
It appears to be a small commit on just `pmagplotlib.py` file a while ago. I reverted the changes. @Lu-Hongliang Could you pull the latest changes and try running `ipmag.reversal_test_bootstrap ` on your dataset again? It looks to be working on my end.

**Comment by Lu-Hongliang** [comment]
It works well now! Thank you guys~

**Comment by Swanson-Hysell** [comment]
Excellent! Thanks for raising the issue and being a part of improving PmagPy.
