### ISSUE TITLE
'ma' is not defined in ipmag.plot_distributions()

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#662]
@duserzym in this commit: https://github.com/PmagPy/PmagPy/commit/09fed3a45411d0d2d8b6985afe408825440d6337 the `plot_distributions()` function has an undefined object `ma` in this line:

`density = ma.masked_where(density <= 0.05*density.max(), density)`

Can you have a look at this?

**Comment by duserzym** [comment]
Just updated the code. This should be the numpy.ma module.

**Comment by Swanson-Hysell** [comment]
Can you commit or put in a pull request?
