### ISSUE TITLE
overlapping plots generated by make_magic_plots.py

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#667]
**What command was run:**

python make_magic_plots.py on contribution https://earthref.org/MagIC/19580

**What happened:**

A histogram was generated that overlay an intensity histogram and a pole plot.

<img width="608" alt="Screen Shot 2022-10-17 at 1 06 47 PM" src="https://user-images.githubusercontent.com/4332322/196272763-fa9f4e59-fd1e-446f-b8e7-5914eaf071fb.png">

**What I expected to happen:**

We need to update the code so that it makes both better pole plots and doesn't make plots that overlie one another like this.

**PmagPy version:**

4.2.108

**Comment by Swanson-Hysell** [comment]
This issue is related to this one in earthref/MagIC: https://github.com/earthref/MagIC/issues/568

**Comment by rminnett** [comment]
@njarboe, do you know if we actually need both /make_magic_plots.py and /programs/make_magic_plots.py in this repo?

**Comment by ltauxe** [comment]
it should be in programs - keeps the main directory cleaner.  
lisa

**Comment by rminnett** [comment]
They're identical at the moment, so I'll remove /make_magic_plots.py

**Comment by Swanson-Hysell** [comment]
I don't think they are identical as there is a March 24 commit to the one in programs b8dd06080edbb6225ec0aadfa86e109d8c8e6228 with the last commit to the one in Master being in 2020 0d37a8378ad148f6add5a52db3a504c1c6f22b43

But given that the one in programs is the most recently updated, it is the one that makes sense to move forward with so your plan makes sense.
