### ISSUE TITLE
Demag GUI test failing

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#67]
One of the Demag GUI tests is failing:

When I run:

 `python -m unittest pmagpy_tests.test_demag_gui.TestMainFrame`

I see this error:

ERROR: test_read_write_redo (pmagpy_tests.test_demag_gui.TestMainFrame)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pmagpy_tests/test_demag_gui.py", line 233, in test_read_write_redo
    self.assertFalse(self.frame.interpretation_editor_open)
AttributeError: 'Demag_GUI' object has no attribute 'interpretation_editor_open'

**Comment by Swanson-Hysell** [comment]
Thoughts on this @Caoimhinmg?

**Comment by Caoimhinmg** [comment]
Yeah forgot to update tests for demag_gui I renamed a few internal variables that I had to use for testing I can rename that quick then make sure everything works again.
