### ISSUE TITLE
No module named past

### ISSUE THREAD

**Issue by MikeVolk** [PmagPy/PmagPy#674]
I encountered the issue of missing module `past`.

Pmagpy (4.2.108)  was installed on Ubuntu 22.04 LTS with poetry  (python 3.10). 
Just importing `import pmagpy.pmag as pmag` throws the `ModuleNotFoundError: No module named 'past'` Error. 
I found an old issue where the past module is supposed to be removed. Did that happen already?

**Comment by Swanson-Hysell** [comment]
We still need to remove a few lingering dependencies on this module (using ```past.old_div```) — it lingers due to the Python 2 to Python 3 conversion a long while back.

A confusing thing about the package is that it is actually called ```future``` so you can pip or condo install ```future``` and you will then have ```past```.
