### ISSUE TITLE
View VGPs

### ISSUE THREAD

**Issue by ellennelson10** [PmagPy/PmagPy#682]
**What command was run:**

I went to tools, VGP. Pop up box showed "Missing Longitude and Latitude data for location". I clicked cancel, but the box did not close and I am now unable to type anything into the data boxes, click cancel, click okay, or click the exit button.

Force quit the application.

Was using the MagIC 2023 test data set (SS20)

**Screenshot(s):**

<img width="1440" alt="Screen Shot 2023-03-02 at 11 30 14 AM" src="https://user-images.githubusercontent.com/91563766/222532565-234fa628-cc69-4a5e-b38f-dc1d675a01c7.png">

**PmagPy version:**
4.2.109

**Comment by duserzym** [comment]
Were you using the standalone version of the gui? I don't think this window should pop up since we are not compiling the standalone softwares with `cartopy`, which is a needed package to plot poles.  The solution would be to export the directions into magic tables and plot poles with a Jupyter Notebook and PmagPy....!  @Swanson-Hysell  perhaps we should remove this function in the dropdown panel under Tools?

**Comment by Swanson-Hysell** [comment]
@Caoimhinmg Are you ok with us removing the VGP view from Pmag GUI? We are trying to simply things and not require cartopy to be bundled with the binary release of Pmag_GUI. We can create templates for VGP plotting using pmagpy in Jupyter notebooks.

**Comment by duserzym** [comment]
I am rethinking about removing this... 

If one has cartopy installed, you can use this tool and view VGPs. Below is an example. But in the standalone we do not compile with cartopy imported, the function is not usable. 
![Screenshot 2023-03-09 at 14 09 50](https://user-images.githubusercontent.com/39976081/224171654-00e5ad9f-97b6-4838-83fc-0a61f75fed78.png)

Perhaps we can leave it there but note in the release page that the view VGPs do not work for standalone apps?

**Comment by Swanson-Hysell** [comment]
The behavior that @ellennelson10 describes of having to force quit when trying to use the function in the stand alone seems non-ideal. Perhaps there is someone to have a warning pop up in the standalone rather than having the app freeze up.

**Comment by duserzym** [comment]
Ok. We can turn this function off for the standalone and leave this option available in the .py file.

**Comment by Swanson-Hysell** [comment]
We have removed this tool from the OSX release that was just published so that this error does not occur.
