### ISSUE TITLE
Demag GUI not saving plot 

### ISSUE THREAD

**Issue by gdacton** [PmagPy/PmagPy#683]
In the demag GUI, when I attempted to save a Zjiderveld plot from the "File/Save plot" pull down menu, no pdf or svg file was generated.

**Comment by Swanson-Hysell** [comment]
Thanks for reporting this bug @gdacton.  @duserzym has worked out a fix. We will get a new release compiled soon.

**Comment by Swanson-Hysell** [comment]
This issue has been fixed in the main repository and in the newest OSX release. We will recompile a new Windows release soon.
