### ISSUE TITLE
Polar VGP α-95 ellipses have artefacts

### ISSUE THREAD

**Issue by aluthfian** [PmagPy/PmagPy#692]
**What command was run:**

1. Loading the paleomagnetic inclination, declination, and $\alpha_{95}$ from the csv file using pd.read_csv
2. Calculating the VGP using `ipmag.pmag.dia_vgp`
3. Make an orthographic basemap using `ipmag.make_orthographic_map`
4. Plot the VGP iteratively using `ipmag.plot_pole_dp_dm` in a `for` loop
5. This map with the real ellipse and artefact lines is produced.

**What happened:**

<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/47322232/246295878-ce79ee18-1d33-4085-b242-fa37523f9bab.png" width="400">

**What I expected to happen:**

The same globe image as above but without choppy polygon lines near the pole.
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/47322232/246302107-e2931ecf-f565-4ee3-8f8b-520983d4ad41.png" width="400">

**Data file(s):**

N/A (closed data)

**PmagPy version:**

_pmagpy-4.2.109_

**My workaround**

To define transform in the `ipmag.plot_pole_dp_dm` function. Works with `ccrs.Geodetic()`.

```
def plot_pole_dp_dm(map_axis, plon, plat, slon, slat, dp, dm, pole_label='pole', site_label='site',
                    pole_color='k', pole_edgecolor='k', pole_marker='o',
                    site_color='r', site_edgecolor='r', site_marker='s',
                    markersize=20, legend=True, transform=ccrs.PlateCarree()):

    if not has_cartopy:
        print('-W- cartopy must be installed to run ipmag.plot_pole_dp_dm')
        return
    dp_km = dp*111.32
    dm_km = dm*111.32
    map_axis.scatter(plon, plat, marker=pole_marker,
                     color=pole_color, edgecolors=pole_edgecolor, s=markersize,
                     label=pole_label, zorder=101, transform=transform)
    map_axis.scatter(slon, slat, marker=site_marker,
                     color=site_color, edgecolors=site_edgecolor, s=markersize,
                     label=site_label, zorder=101, transform=transform)
    # the orientation of the ellipse needs to be determined using the
    # two laws of cosines for spherical triangles where the triangle is
    # A: site, B: north pole, C: paleomagnetic pole (see Fig. A.2 of Butler)

    site_lon_rad = np.deg2rad(slon)
    site_lat_rad = np.deg2rad(slat)
    c_rad = np.deg2rad(90-slat)

    pole_lon_rad = np.deg2rad(plon)
    pole_lat_rad = np.deg2rad(plat)
    a_rad = np.deg2rad(90-plat)

    B_rad = np.abs(pole_lon_rad-site_lon_rad)

    cos_b = np.cos(c_rad)*np.cos(a_rad) + np.sin(c_rad) * \
        np.sin(a_rad)*np.cos(B_rad)
    b_rad = np.arccos(cos_b)

    sin_C = (np.sin(B_rad)/np.sin(b_rad))*np.sin(c_rad)
    C_rad = np.arcsin(sin_C)

    # need to make the rotation of the ellipse go the right way
    if slon-plon > 180:
        if plon >= slon and plat >= slat:
            C_deg = -np.abs(np.rad2deg(C_rad))
        elif plon <= slon and plat >= slat:
            C_deg = np.abs(np.rad2deg(C_rad))
        elif plon >= slon and plat <= slat:
            C_deg = np.abs(np.rad2deg(C_rad))
        elif plon <= slon and plat <= slat:
            C_deg = -np.abs(np.rad2deg(C_rad))
    elif slon-plon <= 180:
        if plon >= slon and plat >= slat:
            C_deg = np.abs(np.rad2deg(C_rad))
        elif plon <= slon and plat >= slat:
            C_deg = -np.abs(np.rad2deg(C_rad))
        elif plon >= slon and plat <= slat:
            C_deg = -np.abs(np.rad2deg(C_rad))
        elif plon <= slon and plat <= slat:
            C_deg = np.abs(np.rad2deg(C_rad))

    #print(C_deg)
    ellipse(map_axis, plon, plat, dp_km, dm_km, C_deg, color=pole_color, transform=transform)

    if legend == True:
        plt.legend(loc=2)
```

**Comment by Swanson-Hysell** [comment]
Thanks for raising the issue here.

As you saw, the default for the functions is the ccrs.PlateCarree() projection. Are you having this issue with ccrs.PlateCarree(), but then not when you change it to ccrs.Geodetic() with your workaround? We were having other issues with ccrs.Geodetic() (I think associated with dateline wrapping issues) which led to relying more on ccrs.PlateCarree(), but that might come with its own issues.

Could you provide minimal working example code that leads to the issue? It could just be for one of poles (and you can adjust the values) as I realize you want to keep your data private.

**Comment by aluthfian** [comment]
Thanks @Swanson-Hysell for the reply.

Yes, kind of weird that I have the issue if I use `ipmag.orthographic` with `ccrs.PlateCarree()` projection, and the issue goes away if I use `ccrs.Geodetic()`.

**Minimum Working Example**
```
fig = plt.figure(figsize=(10,20), dpi=100)
map_axis_1 = fig.add_subplot(1,2,1,projection=ccrs.Orthographic(central_longitude=200, central_latitude=60))
#map_axis = fig.add_subplot(projection=ccrs.Robinson(central_longitude=200))
map_axis_1.coastlines()
map_axis_1.set_global()
map_axis_1.gridlines()
colour='xkcd:red'
is_legend=True
ipmag.plot_pole_dp_dm(map_axis_1, 275, 85, 145, 36, 10, 15, pole_label='not working', site_label='site',
                      pole_color=colour, pole_edgecolor=colour, pole_marker='o',
                      site_color=colour,site_edgecolor=colour, site_marker='*',
                      markersize=40, legend=is_legend)

map_axis_2 = fig.add_subplot(1,2,2,projection=ccrs.Orthographic(central_longitude=200, central_latitude=60))
map_axis_2.coastlines()
map_axis_2.set_global()
map_axis_2.gridlines()
colour='xkcd:green'
is_legend=True
ipmag.plot_pole_dp_dm(map_axis_2, 275, 85, 145, 36, 10, 15, pole_label='working well', site_label='site',
                      pole_color=colour, pole_edgecolor=colour, pole_marker='o',
                      site_color=colour,site_edgecolor=colour, site_marker='*',
                      markersize=40, legend=is_legend,transform=ccrs.Geodetic())
```

![image](https://github.com/PmagPy/PmagPy/assets/47322232/87fb12e0-b5c8-4193-a318-5cbd536e5694)

**Comment by duserzym** [comment]
This is interesting! I just looked into functions `ipmag.plot_pole` and `ipmag.plot_pole_dp_dm`. The first uses function `ipmag.equi` to generate the uncertainty circle and the second `ipmag.ellipse`. Both functions eventually generates a Polygon object which needs a transform argument. `ipmag.equi` hard codes in _`transform=ccrs.Geodetic()`_ whereas `ipmag.ellipse` defaults to _`transform=ccrs.PlateCarree()`_.  I guess we should just expose `_transform_` as a parameter in the `ipmag.plot_pole_dp_dm` function so that when issues like this happens one can toggle between the different cartopy transforms.

**Comment by Swanson-Hysell** [comment]
It seems preferable to me to hardcode in the transform that works so the user doesn't have to worry about it, but perhaps which one works will depend on nuances of the map projection in which case putting in transform as a parameter could make sense.

**Comment by Swanson-Hysell** [comment]
I think we have enabled your issue to be resolved in pmagpy through using your workaround (pull request https://github.com/PmagPy/PmagPy/pull/693). This pull request keeps `ccrs.PlateCarree()` as the default, but enables `ccrs.Geodetic()` to be used to resolve issues such as the one that arose for you.
