### ISSUE TITLE
Problem with creating fits on files that include both thermal and AF demag

### ISSUE THREAD

**Issue by oliviamoehl** [PmagPy/PmagPy#696]
**What command was run:**

I am using pmag_gui_4.2.111. I have successfully imported my data to a working directory, but am having problems with the "fits" within the Analysis and Plots portion of the software.

**What happened:**

My files all include a mix of thermal and AF demagnetization. When I try to create a fit by selecting any of my lower thermal steps (60C, 90C, 120C), the program glitches and then selecting the numerically equivalent AF step. For example, if I want to start my fit at 90C, then the program glitches and automatically starts the fit at 90mT instead. This happens both when I try to select the fit bounds on the dropdown menus and when I try to select the values from the table.

This is a problem because it is preventing me from creating any fits that start or end with my lower thermal step.

**Data file(s):**

[https://www.dropbox.com/scl/fo/wvz1bpukfdo7y24j3aa3t/h?dl=0&rlkey=q6czyvmqgati3kpb3nrlz5hjl](url)

**PmagPy version:**

4.2.111

**Comment by Caoimhinmg** [comment]
Hi @oliviamoehl, thanks for pointing out this problem. It should be fixed after the last commit. You can use the source version on the master branch to overcome this issue right now or wait until a new binary release is made for your OS.

**Comment by duserzym** [comment]
Hi @Caoimhinmg, thanks for fixing this. I added a small edit so that when determining the measurement type the "-" sign for thermal steps with temperatures below 0 will be recognized as thermal steps. The previous commit caused a new bug when selecting the liquid nitrogen steps.

**Comment by duserzym** [comment]
Hi @oliviamoehl, I have just made a new release of the software. You can find the MacOS version here: https://github.com/PmagPy/PmagPy-Standalone-OSX. Please let us know if there is any further issue.

**Comment by oliviamoehl** [comment]
Hi @Caoimhinmg and @duserzym, thanks for fixing this problem and releasing the new software!
