### ISSUE TITLE
doincfish function bug

### ISSUE THREAD

**Issue by xiaoneimeng** [PmagPy/PmagPy#697]
The doincfish function cannot be used properly due to the fact that ML_zeros = np.array(Oo[[idx_zeros]]) constructs ML_zeros as a three-dimensional array. This issue can be resolved by modifying the line to ML_zeros = np.array(Oo[idx_zeros]).
Additionally, after making the modifications and running the example file again, the calculated α95 in the output results differs from the provided results. However, the example's expected output described in the function remains the same. I am currently reviewing the specific calculations.

**PmagPy version:**
4.2.109

**Comment by Swanson-Hysell** [comment]
@ltauxe Are you able to take a look at this issue regarding `pmag.doincfish`?

**Comment by apivarunas** [comment]
See discussion in #713, @Swanson-Hysell 

I reproduced an error in the doincfish function and fixed it. I could not reproduce the change in a95. So, the function works now. I made some additional changes in that PR, as well.

**Comment by Swanson-Hysell** [comment]
Thanks for raising this issue @xiaoneimeng. We should be all good now thanks to @apivarunas and #713
