### ISSUE TITLE
Add CSD to Measurement List in Demag_Gui

### ISSUE THREAD

**Issue by sslotznick** [PmagPy/PmagPy#70]
This will be helpful for evaluation of data points determining if they are "bad" or "good" especially when repeat measurements are made.

**Comment by Swanson-Hysell** [comment]
@Caoimhinmg, we realize that this additional field will make the measurement panel too wide, but given that when it is to wide there is a scroll bar that will be fine. The name of the field in the magic_measurements.txt is measurement_csd.
