### ISSUE TITLE
light colors for point selection in demag_gui

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#73]
It would be easier to see the highlighted points if they became a lighter color rather than a darker color when selected in the z-plot, equal area and M/Mo plots.

**Comment by Caoimhinmg** [comment]
This is a bit challenging as the colors used for the z-plot eqarea and M/M0 are the brightest they can be. I Made them whiter as opposed to brighter and that seemed to work, but makes the black outline of points a little bold. For the equal area plot this is actually impossible as white is used for upper hemisphere measurement vectors, I changed upper hemisphere measurement vectors to black though now they blend a lot with lower hemisphere measurement vectors and made white the selected color. Let me know what you think, I can also make the upper and lower hemisphere selected measurement vector different colors as opposed to one color like it is now.

**Comment by Swanson-Hysell** [comment]
The z-plot and M/Mo selections look good.

The upper hemisphere points in the equal area plot have to be white (or open circles) as that is the convention. Could you do something like put a red outline around them when they are selected?
