### ISSUE TITLE
new pip release

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#74]
We haven't really established a system for determining when to make a new pip release.  So, this issue has two parts:  1.  does anyone have a reason I shouldn't go ahead and make a new release now?  2.  How should we time/coordinate new releases in general?

Regarding item two, it seems obvious that we should make sure all tests are passing, but maybe we should have other safeguards as well?

**Comment by Swanson-Hysell** [comment]
It would be great to make a new pip release now. I was just trying to get someone going on demag_gui and the version in the last pip release is very out-of-date now. Regarding #2, I don't know what other safeguards there should be other than doing what you are doing now and checking in to see if there are any reasons to hold up putting together a new release. I think Github has nice machinery for putting together a draft release that anyone can comment on. 

What is the process for getting a new release up on pip?

**Comment by Swanson-Hysell** [comment]
It would also be great to do a new release of the Pmag_GUI binary....the mac one at least.

**Comment by moonshoes87** [comment]
I’ll make a new pip release today for both pmagpy and pmagpy-cli.

Here is the process I use, which we should probably preserve somewhere other than here in this issue:

First, I increment the version number in setup.py or command_line_setup.py.  PYPI will reject a duplicate version number I forget this step.  

From the PmagPy directory, I use the following command to build a new distribution of pmagpy, upload it to PYPI, and upgrade locally:

`rm -rf build dist && python setup.py sdist bdist_wheel && twine upload dist/* && pip install pmagpy —upgrade`

If I just want to make a test release, I use a slightly different command from the PmagPy directory, which will: build a new distribution of pmagpy, upload it to the test site (will not overwrite the version people can download), and upgrade locally:

`python setup.py sdist bdist_wheel upload -r https://testpypi.python.org/pypi && pip install -i https://testpypi.python.org/pypi pmagpy —upgrade`

A few notes on the whole thing:  first of all, I haven’t found that testing the pip install locally works very well (i.e., `python setup.py install` or `python setup.py test`), because it doesn’t deal correctly with the required data files.  Whenever I’m testing a new pip distribution, I do the full process of uploading to test_PYPI instead, even though it takes a minute or so to do.  Second, I’m using twine for uploading to real PYPI but not to upload to test PYPI.  Using twine is recommended because it transfers the package data in a more secure way, but I wasn’t able to get it to work with test_PYPI when I initially set this all up (it might be easy to fix now, but it hasn’t been my priority.  Third, if we want to have more than one person making releases, I’m not exactly sure how the PYPI credentials will work.  My credentials for PYPI and test PYPI are stored in my ~/.pypirc, and I’m not sure exactly how to support more than one uploader.  Maybe I will need to make those credentials available to Lisa or whomever else we want making releases? Or maybe we can add more than one person to the account somehow?  I’m not sure.

This article has some more good information about uploading to PYPI, etc.:  https://tom-christie.github.io/articles/pypi/

**Comment by moonshoes87** [comment]
Yes, I’m going to try to get that done this week as well :)

**Comment by moonshoes87** [comment]
I've made a new pip release of pmagpy and pmagpy-cli.  If the 3 failing tests in Demag GUI are important, I can re-release when those are fixed.

**Comment by Swanson-Hysell** [comment]
@Caoimhinmg can you look at having multiple people be able to have PYPI credentials and be in touch with @moonshoes87 about it. And let's make a .md file that details this process that we put within the repo.

**Comment by Caoimhinmg** [comment]
Guess it's about time that I updated this with some new information. In response to @Swanson-Hysell, multiple people can have PyPi credentials by being marked as either an Owner or a Maintainer by the original Owner, @moonshoes87. Anyone marked as such can then follow @moonshoes87's instructions above (eventually to make it into the developers guide in #85 ) to the letter and push a new release to PyPi ([source and details](https://docs.python.org/2/distutils/packageindex.html#pypi-overview)). To move this forward I created a PyPi and PyPiTest account under the same handle as my github handle (caoimhinmg) so that we could test this when time is available, possibly after the workshop.

**Comment by moonshoes87** [comment]
Partly in response to #146:

I can go ahead and do a new pip release.  Perhaps we could re-open the discussion of how to schedule our pip releases?  For instance, it isn’t necessarily unreasonable to do a pip release whenever we add functionality or fix a bug that someone outside the PmagPy organization has asked for/reported.  It takes about 15 minutes to make a new pip release, so it *can* be done frequently.  The standalones are obviously more 

On the other hand, maybe we expect people who are reporting issues or requesting features (like Julie Bowles and her students) to be using the developer install?  

Thoughts?

**Comment by Swanson-Hysell** [comment]
It would be nice not to have to have students working off of the developer install (I think Julie is using the code in the context of a class).

Doing a new release now seems good to me.

**Comment by moonshoes87** [comment]
New release will be tomorrow -- I have a final bug to clean up before I want to release.

**Comment by moonshoes87** [comment]
I just published new releases for pmagpy and pmagpy-cli (version 3.8.8).  @jbowles100, the two bugs you reported should now be fixed in the up-to-date pip release!

**Comment by Swanson-Hysell** [comment]
:+1:
