### ISSUE TITLE
Error running PmagPy after running Install Script on Mac OS X

### ISSUE THREAD

**Issue by ihilburn** [PmagPy/PmagPy#80]
Summary:
PmagPy throws an error when I try to run the post-install test-script on Mac OS X.

How to Recreate:
1) On Mac OS X: v10.9.5 (Maverick), download .Zip file of the PmagPy GitHub repository:
https://github.com/PmagPy/PmagPy/

2) Extract all files and then open and run the file: ../PmagPy-master/install_Mac_OSX.app

3) Choose to have the files installed onto the Mac HD.  (The option to install under the the current user was grayed out. The installer said this option was not allowed).

4) Run the installer. Installs all PmagPy files under: /Users/{my username}/PmagPy/

5) At finish, the installer runs the test script: 
":~ {my username}$ eqarea.py -h" in Terminal

This command fails with the following error:
Traceback (most recent call last):
  File "/Users/lab/PmagPy/programs/eqarea.py", line 8, in <module>
    import pmagpy.pmagplotlib as pmagplotlib
ImportError: No module named pmagpy.pmagplotlib

I checked the install directory and found the relevant file:
/Users/{my username}/PmagPy/pmagpy/pmagplotlib.py

6) I tried rerunning the command prompt as super user:
":~ {my username}$ sudo eqarea.py -h"

and got the same error.

Thank you,
Isaac

**Comment by Swanson-Hysell** [comment]
The way to install PmagPy so that it is in the Python path is to use Pip install. Instructions for how to do so are found in the PmagPy cookbook here: https://earthref.org/PmagPy/cookbook/#QQ2-1-6

> **1.2.1 Installing PmagPy**

> Here we provide instructions for using pip to install PmagPy from the command line. “Pip” is a package manager that comes standard with any modern Python distribution (NB: you will have to update it to the most recent version). Pip allows you to install and uninstall pmagpy, the package with all the low-level functionality of PmagPy and pmagpy-cli which provides the PmagPy command-line-interface and has all the packages you may use to download/upload, visualize, and manipulate data.
To install using pip:

> Find and open your command line.
> Update pip: type on the command line:
> `pip install --upgrade pip`
> Install or update pmagpy: use the command:
> `pip install --upgrade pmagpy`
> Install or update pmagpy-cli, use the command:
> `pip install --upgrade pmagpy-cli` 
> To uninstall either, use the command: “pip uninstall pmagpy” or “pip uninstall pmagpy-cli”
> If you run into trouble, use pip to uninstall both pmagpy and pmagpy-cli, then try again to install first pmagpy and then pmagpy-cli

The other way to go is to add a statement such as:
`export PYTHONPATH=$PYTHONPATH:~/PmagPy` 
in your .profile or .bash_profile file that points to where PmagPy is on your local machine. Since it is in your home directory you should be able to put it into your .bash_profile as I have it above and the command line programs will then be able to find the pmagpy module.

@moonshoes87 is there a reason we still have install_Mac_OSX in the repo. Seems like it shouldn't be there now that we are doing pip.

**Comment by ihilburn** [comment]
Tried the PiP install. Got a different error - but still a broken module.

If I open Anaconda Navigator and run Jupyter, I can open any ipynb file belonging to PmagPy without issue.

So, something's off with my Python PATH variable, likely...

Isaac

Sent from my fruit-based mobile device.
And, of course, Hello to Jason Isaacs.

On Oct 18, 2016, at 3:20 PM, Nick Swanson-Hysell <notifications@github.com> wrote:

The way to install PmagPy so that it is in the Python path is to use Pip install. Instructions for how to do so are found in the PmagPy cookbook here: https://earthref.org/PmagPy/cookbook/#QQ2-1-6

1.2.1 Installing PmagPy

Here we provide instructions for using pip to install PmagPy from the command line. “Pip” is a package manager that comes standard with any modern Python distribution (NB: you will have to update it to the most recent version). Pip allows you to install and uninstall pmagpy, the package with all the low-level functionality of PmagPy and pmagpy-cli which provides the PmagPy command-line-interface and has all the packages you may use to download/upload, visualize, and manipulate data.
To install using pip:

Find and open your command line.
Update pip: type on the command line:
pip install --upgrade pip
Install or update pmagpy: use the command:
pip install --upgrade pmagpy
Install or update pmagpy-cli, use the command:
pip install --upgrade pmagpy-cli 
To uninstall either, use the command: “pip uninstall pmagpy” or “pip uninstall pmagpy-cli”
If you run into trouble, use pip to uninstall both pmagpy and pmagpy-cli, then try again to install first pmagpy and then pmagpy-cli

The other way to go is to add a statement such as:
export PYTHONPATH=$PYTHONPATH:~/PmagPy 
in your .profile or .bash_profile file that points to where PmagPy is on your local machine. Since it is in your home directory you should be able to put it into your .bash_profile as I have it above and the command line programs will then be able to find the pmagpy module.

@moonshoes87 is there a reason we still have install_Mac_OSX in the repo. Seems like it shouldn't be there now that we are doing pip.

**Comment by Swanson-Hysell** [comment]
What error are you now getting?

When you open a .ipynb file can you execute the code that looks like this?:

```
import pmagpy.ipmag as ipmag
import pmagpy.pmag as pmag
```

**Comment by Swanson-Hysell** [comment]
Note that if you are running a PmagPy program from the command line and aren't using the pip install, you need to set the path to the main folder and to the programs:

```
export PATH=~/PmagPy:./:$PATH
export PATH=~/PmagPy/programs:./:$PATH
```

**Comment by ihilburn** [comment]
Here's the import header for _PmagPy_3.0.ipynb when open in Jupyter running
under Anaconda python  v2.7:

#import pmagpy.ipmag as ipmag
import pmagpy.pmagplotlib as pmagplotlib
import pmagpy.pmag as pmag
from IPython.display import Image
import matplotlib as plt
import sys
%matplotlib inline

If I am using the PIP install, how should I open pmagpy from the command
line?

Do I use PIP?

I may be making a nube error.

Isaac

**Comment by Swanson-Hysell** [comment]
Doing the pip install should allow you to run the command line programs without doing anything special. For example, after doing the pip install you should be able to launch an IPython session at the command line (or a Jupyter notebook) and then import pmagpy modules using the syntax such as that you have above.

```
$ ipython

In [1]: import pmagpy.ipmag as ipmag

In [2]: ipmag.do_flip?
Signature: ipmag.do_flip(dec=None, inc=None, di_block=None)
Docstring:
This function returns the antipode (i.e. it flips) of directions.
```

**Comment by Swanson-Hysell** [comment]
Since these install scripts are deprecated and now removed, I am closing this issue.
