### ISSUE TITLE
Demag GUI tests crash on my machine

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#88]
Here is an example of the output I'm getting before the tests crash:

```
test_VGP_viewer (pmagpy_tests.test_demag_gui.TestDemagGUI) ... -I- can't find zeq_gui_preferences file, using defualt default
data model: 2.5
....
-E- invalid parameters cannot assign to fit test0 for specimen SI3-59.8-D - was given: {'er_specimen_name': 'SI3-59.8-D', 'specimen_comp_name': u'test0', 'specimen_dang': 0}
Could not calculate dec or inc for specimen SI3-59.8-D component test0 with bounds 7.5mT and     145.0mT in coordinate_system geographic, component not added
-E- no measurement data for specimen SI3-59.9-D in coordinate system geographic
-E- invalid parameters cannot assign to fit test0 for specimen SI3-59.9-D - was given {'er_specimen_name': 'SI3-59.9-D', 'specimen_comp_name': u'test0', 'specimen_dang': 0}
Could not calculate dec or inc for specimen SI3-59.9-D component test0 with bounds 7.5mT and 145.0mT in coordinate_system geographic, component not added
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string::erase
Abort trap: 6
```

Breaks similarly with: `test_check_sample_orientation_bad_good (pmagpy_tests.test_demag_gui.TestDemagGUI)`

and:  `test_read_write_pmag_tables (pmagpy_tests.test_demag_gui.TestDemagGUI)`

The rest of the tests run correctly.  They all have this line in common:  `self.ie_add_n_fits_to_all(n_fits)`, but I haven't done any digging.  

@Caoimhinmg ?  I've been just skipping these tests on my machine, which is fine, but this might be useful information.

**Comment by Caoimhinmg** [comment]
@moonshoes87 This is one of those completely mind boggling errors. It's some kind of low level error in a C++ library native to OSX and used by python on macs, which is why I've never noticed this. After digging on the internet I found one thread that mentioned an association with importing pylab so I removed the depreciated pylab imports from DemagIE which seems to be causing the error. I'm not sure it will fix it but right now it's my best hunch. Let me know if the error persists.

**Comment by moonshoes87** [comment]
Yeah, I hate stuff like this :\  Unfortunately, I just pulled and the error does persist.  

Is it possible that this error is affecting actual use of Demag GUI for Mac users, as well as testing?  Is there any kind of sequence I should try with Demag GUI to see if I can get it to crash under actual use conditions?

**Comment by Caoimhinmg** [comment]
Yeah, of course, the tests only simulate user input. I would suppose that if it's crashing on ie_add_n_fits_to_all which is a helper method adding n fits using the DemagIE add all function. So I'd say open DemagGUI on a dataset without a pmag_specimens file (the test uses $PmagPyDir/pmagpy_tests/examples/demag_test_data), then open the DemagIE using command+e or the tools menu, put some info into the fit name/color and bounds boxes, and finally hit the add all button. It should add a fit with all the attributes in those boxes to every specimen where those bounds and name make sense, if this doesn't crash try opening the DemagIE again while it's open as that could be happening in the tests as well it should just bring the DemagIE to the top. I'll look into this a bit more in the mean time. Thanks @moonshoes87.

**Comment by moonshoes87** [comment]
I tried out this sequence and it seems to work fine.  One slight glitch is that the ShowModal "ok" and "cancel" buttons (with issues with a particular specimen, after clicking 'add new fit to all specimens') both seem to do the same thing, or if they have a different effect it is unclear in the UI.  

Seems like this might just be a weird testing environment issue.  Let me know if you want me to try anything else.

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87 I've done more digging on this and it appears that the library in question libc++abi.dylib is possibly a part of XCode on mac so updating those libraries might help fix the problem. I can't be totally sure as I can't debug and I can't seem to find anyone with exactly this problem on the internet. If this doesn't work I'll try restructuring the tests to prevent the scenario that's causing the error from ever occurring.

**Comment by moonshoes87** [comment]
I just updated everything I could, and I still have the same error as before:

libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string::erase
Abort trap: 6


It’s your call as to how much time you want to put into this — I’m ok with just skipping these tests.  Let me know if you want me to try any other debugging steps...

**Comment by moonshoes87** [comment]
I am closing this issue, since the tests work on Linux/Windows, and the tested functionality works on OS X.
