### ISSUE TITLE
Thellier GUI boxes show up black with Anaconda....

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#89]
I'm working on making Thellier GUI Anaconda compatible.  

One display error I have is that blank wx.TextCtrls are showing up with a black background.  

![screen shot 2016-11-09 at 11 46 07 am](https://cloud.githubusercontent.com/assets/1836578/20152203/22f1ba76-a672-11e6-93c1-8cd6e20c2ee6.png)

@Caoimhinmg, @Swanson-Hysell, do I remember correctly that this is a problem you already solved in Demag GUI?

**Comment by Caoimhinmg** [comment]
@moonshoes87 I just tried to patch this issue same way it's fixed in Demag GUI, let me know if it worked. It's a simple issue of making sure the TextCtrls are set to have wx.WHITE as a background color rather than whatever the style TE_READONLY sets which can vary, the Acceptance criteria boxes don't have this issue because they were set to wx.NULLCOLOR.

**Comment by moonshoes87** [comment]
This looks good, thanks!

**Comment by moonshoes87** [comment]
Not sure what happened, but now it appears that both Thellier GUI and Demag GUI are giving the black window error with Anaconda:

Demag GUI:
![screen shot 2016-11-21 at 1 48 46 pm](https://cloud.githubusercontent.com/assets/1836578/20502067/4de29722-aff1-11e6-94a2-f73ef29b96ed.png)

Thellier GUI:

![screen shot 2016-11-21 at 1 50 57 pm](https://cloud.githubusercontent.com/assets/1836578/20502124/93f67e22-aff1-11e6-910d-c1d0cd8041e9.png)


I also get quite a few error messages like this:

    Nov 21 13:48:29  python[36037] <Warning>: void CGSUpdateManager::log() const:  31  libpython2.7.dylib                  0x00000001000a338a PyEval_EvalFrameEx + 3866


It looks like it could be a matplotlib issue:  http://stackoverflow.com/questions/37265675/odd-matplotlib-errors-warnings-when-producing-multiple-plots, but then I don't know why it would just be affecting the wxPython components.  (Or maybe this error message is unrelated to the ugly display behavior...)

**Comment by Caoimhinmg** [comment]
@moonshoes87 this is my fault I think, I forgot to set the background of the specimen and sample results boxes to white thinking that all the TextCtrls were created in one loop. Now that I've figured out the Thellier GUI UI a bit better I can set them to white. In Demag GUI at least if there is no statistic for a item I set it to wx.NullColor on purpose I can make it white instead, but I think a color change is a good idea. I could change it from wx.NullColor to wx.LightGrey which is what my null color is and it doesn't look as bad. For now I'll give that a try in Demag GUI and set the initial color for Thellier GUI white. What do you think?

**Comment by Caoimhinmg** [comment]
Here's an example of the grey color I am planning to replace wx.NullColor with, as this is the null color I get on my machine.
![thellierguigreyboxes](https://cloud.githubusercontent.com/assets/5723397/20504855/7f7e4a08-affe-11e6-9e88-2f8d96d00fdf.png)

**Comment by moonshoes87** [comment]
Looks good
