### ISSUE TITLE
Renamed functions in PmagPy_notebook

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#98]
Some function names have been changed and this bit of data_files/Jupyter_notebook/PmagPy_notebook.ipynb no longer works:

![screen shot 2017-01-11 at 5 48 24 pm](https://cloud.githubusercontent.com/assets/1836578/21873854/3ad23b30-d826-11e6-92c0-a25f09820ed0.png)

I changed watson_common_mean to common_mean_watson and  bootstrap_common_mean to common_mean_bootstrap, but ipmag.flip also breaks.  Neither pmag.flip nor ipmag.do_flip seem to fix the problem.  @Swanson-Hysell, maybe you could have a look?

**Comment by Swanson-Hysell** [comment]
I think the best thing to do here would be to replace these notebooks with the ones that we developed for the PmagPy paper: https://github.com/PmagPy/2016_Tauxe-et-al_PmagPy_Notebooks

**Comment by Swanson-Hysell** [comment]
This code would work with the current version of ipmag

```
ipmag.flip(di_block=reverse_directions)
```

The code now accepts either a list of declinations and a list of inclinations, or a di_block (nested list of dec,inc)

```
def do_flip(dec=None, inc=None, di_block=None):
    """
    This function returns the antipode (i.e. it flips) of directions.

    The function can take dec and inc as seperate lists if they are of equal
    length and explicitly specified or are the first two arguments. It will then
    return a list of flipped decs and a list of flipped incs. If a di_block (a
    nested list of [dec,inc,1.0]) is specified then it is used and the function
    returns a di_block with the flipped directions.

    Parameters
    ----------
    dec: list of declinations
    inc: list of inclinations

    or

    di_block: a nested list of [dec,inc,1.0]

    A di_block can be provided instead of dec, inc lists in which case it will
    be used. Either dec, inc lists or a di_block need to passed to the function.
    """

**Comment by moonshoes87** [comment]
Great, I forgot about these notebooks.  They are more complete and in better shape than the one in the main repo.  I'm inclined to delete the old Jupyter_notebook folder and just point people to the 2016_Tauxe_et_al_PmagPy_Notebooks repo.  @ltauxe, any issue with taking the old example PmagPy notebook out of the repo?  We can keep the 2016_Tauxe_et_al_PmagPy_Notebooks separate, or we could replicate that directory and put it in with the other example PmagPy notebooks in the 'notebooks' directory.  

Either way, I will also fix the documentation in the Cookbook to be more clear on where examples can be found and how to use them.  I will also link to the notebooks in the directory structure section.

**Comment by Swanson-Hysell** [comment]
I think that pointing people towards the 2016_Tauxe_et_al_PmagPy_Notebooks repo makes sense so that we don't need to do maintenance in two places.

**Comment by moonshoes87** [comment]
That does make sense.  My only concern is that we have example notebooks in several different places.  Currently, several are in PmagPy/notebooks, one is in data_files/, and two are in 2016_Tauxe_et_al_PmagPy_Notebooks.  I will at least consolidate the ones that are in the PmagPy repo, but I am still concerned that this may be a little confusing.

**Comment by ltauxe** [comment]
there is also the notebook in the data_files directory, which runs all the examples as in the cookbook.  
lisa

**Comment by moonshoes87** [comment]
Lisa, for the moment I am consolidating by moving _PmagPy.ipynb from data_files into the notebooks directory.  I'm making sure that all of the scripts still point to the correct data file.  Let me know if you have a better idea!
